export const questions = [
  {
    id: 1.1,
    name: 'gps',
    question: 'อุปกรณ์ GPS+เครื่องรูดบัตรขับขี่',
    howto: 'สายตา / เสียง / ดูไฟที่กล่องและฟังเสียงเตือน',
    accept: 'แสดงผลปกติเมื่อเปิดสวิทช์กุญแจ มีเสียงเตือนให้รูดบัตรขับขี่',
  },
  {
    id: 1.2,
    name: 'licenseplate',
    question: 'แผ่นป้ายทะเบียน และ ภาษีประจำปี',
    howto: 'สายตา',
    accept: 'สะอาด มองเห็นได้ชัดเจน ไม่หมดอายุ',
  },
  {
    id: 1.3,
    name: 'insurance',
    question: 'เอกสารประกันภัยประจำรถ',
    howto: 'สายตา',
    accept: 'สภาพสมบูรณ์ ไม่ขาด ไม่หมดอายุ',
  },
  {
    id: 1.4,
    name: 'engine',
    question: 'ระบบเครื่องยนต์/ระบบส่งกำลัง',
    howto: 'ฟังเสียงเครื่องยนต์ ',
    accept: 'ไม่มีเสียงดังผิดปกติของเครื่องยนต์ทั้งหมด',
  },
  {
    id: 1.5,
    name: 'meter',
    question: 'มาตรวัด ไฟเตือนหน้าปัด',
    howto: 'ตรวจสอบมาตรวัด',
    accept: 'ไม่มีไฟแจ้งเตือนที่แผงหน้าปัด',
  },
  {
    id: 1.6,
    name: 'handbrake',
    question: 'เบรคมือ / เท้าใช้งานได้ดี',
    howto: 'เหยียบเบรกเท้า / ยกเบรกมือฟังเสียง',
    accept:
      'เบรกเหยียบแล้วไม่ค้าง ไม่จม ยกเบรกแล้วแป้นเบรกคืนกลับมาตามปกติ / เบรกมือมีเสียงเมื่อทำงาน',
  },
  {
    id: 1.7,
    name: 'safetyBelt',
    question: 'เข็มขัดนิรภัยล๊อกได้สนิท',
    howto: 'ทดสอบดึงกระชาก',
    accept: 'สายเข็มขัดล็อคเมื่อถูกกระชาก',
  },
  {
    id: 1.8,
    name: 'whipper',
    question: 'ที่ปัดน้ำฝนซ้าย / ขวา และน้ำฉีดกระจก',
    howto: 'เปิดที่ปัดน้ำฝน',
    accept: 'ที่ปัดน้ำฝนทำงานปกติ มีน้ำฉีดกระจก',
  },
  {
    id: 1.9,
    name: 'horn',
    question: 'สัญญาณแตร',
    howto: 'กดสัญญาณแตร',
    accept: 'แตรมีเสียงเมื่อกด / ไม่ใช้แตรลม',
  },
  {
    id: 1.1,
    name: 'sideMirror',
    question: 'กระจกหน้าหน้าต่าง / มองข้าง',
    howto: 'มองกระจกโดยรอบ',
    accept: 'กระจกใสไม่มีคราบสกปรก ม่านบังแดดหรือสติกเตอร์บดบังทรรศนวิสัย',
  },
  {
    id: 1.11,
    name: 'oil',
    question: 'ระดับน้ำมันเชื้อเพลิง / ระดับแก๊สในถัง',
    howto: 'ตรวจสอบไฟเตือนน้ำมันและเกจวัดน้ำมัน/แก๊ส',
    accept: 'เกจน้ำมัน/แก๊ส ใช้งานได้ และระดับที่เพียงพอ ',
  },
  {
    id: 1.12,
    name: 'firstAid',
    question: 'ชุดปฐมพยาบาลในการห้ามเลือดและถุงมืออนามัย',
    howto: 'ตรวจสอบจำนวนและวันหมดอายุ',
    accept: 'ยาและอุปกรณ์ปฐมพยาบาลไม่หมดอายุ มีครบเพียงพอต่อการปฐมพยาบาล',
  },
  {
    id: 1.13,
    name: 'light',
    question:
      'ไฟหลัก / เลี้ยวหน้า / หลัง / ส่องทะเบียน / ไฟราวข้าง/ ไฟเบรค / ไฟฉุกเฉิน',
    howto: 'เปิดไฟทั้งหมด',
    accept: 'ไฟติดสว่างมองเห็นได้ชัดเจนทุกดวง',
  },
  {
    id: 1.14,
    name: 'harness',
    question: 'มี Safety Belt ขึ้นที่สูงหลังถัง *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบสภาพ',
    accept: 'สภาพสมบูรณ์พร้อมใช้งาน มี Safety Belt อย่างน้อย 1 สาย ',
  },
  {
    id: 2.1,
    name: 'backSilent',
    question: 'มีสัญญาณไฟและเสียงขณะถอยหลัง',
    howto: 'ใส่เกียร์ถอย',
    accept:
      'ไฟถอยติด สว่างชัดเจน / มีเสียงสัญญานเตือนถอยหลังดังขณะใส่เกียร์ถอย',
  },
  {
    id: 2.2,
    name: 'wheel',
    question: 'ล้อ ลมยาง และ สภาพยาง',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'ดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง ร่องยางลึกไม่น้อยกว่า 2 มม./ มีน๊อตล้อครบ',
  },
  {
    id: 2.3,
    name: 'tire',
    question: 'มียางอะไหล่/มีขอนรองล้อ 2 อัน (รถพ่วง 4 อัน)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'มียางอะไหล่ / มีขอนรองล้อมีขนาดอย่างน้อย 6 นิ้ว สภาพสมบูรณ์',
  },
  {
    id: 2.4,
    name: 'fireExtinguisher',
    question: 'ถังดับเพลิง (15 Lbs.)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'เกจวัดแรงดันอยู่ในช่องสีเขียว สภาพถังพร้อมใช้งาน',
  },
  {
    id: 2.5,
    name: 'cone',
    question: 'กรวยจราจร หรือ ป้ายสะท้อนแสง 2 อัน',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่สกปรก แถบสะท้อนแสงสามารถมองเห็นได้',
  },
  {
    id: 2.6,
    name: 'airBrake',
    question: 'เช็คหม้อลมเบรก',
    howto: 'ตรวจสอบด้วยสายตา และดึงสลัก',
    accept: 'ดึงสลักเพื่อเดรนน้ำออกจากหม้อพักลมสำรอง',
  },
  {
    id: 2.7,
    name: 'hose',
    question: 'ท่อยางเป่าปูน และเข็มขัดรัดต่อสายต่างๆ *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'ท่อเป่าปูนไม่แตก ฉีกขาด พับหักงอ / เข็มขัดรัดท่อตามจุดต่อต้องมีอย่างน้อย 3 เส้น ห้ามต่อสายเกิน 1 จุด',
  },
  {
    id: 2.8,
    name: 'lip',
    question: 'สภาพลูกยางโดนัท/ฝาครอบปลายท่อจุดร้อยซีล *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา / ทดลองดึงฝาครอบ',
    accept:
      'ไม่ฉีกขาด เปื่อยยุ่ย ยางไม่แข็งกรอบ / ฝาครอบท่อไม่ชำรุดและมีรูร้อยซีล / ไม่สามารถเปิดหรือถอดฝาครอบได้เมื่อร้อยซึลแล้ว',
  },
  {
    id: 2.9,
    name: 'campLock',
    question:
      'สภาพก้ามปูที่ใช้ล๊อคท่อเป่าปูน ต้องล็อคได้แน่นหนา *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา / ทดลองโยก',
    accept:
      'สลักก้ามปูปากยึดไม่อ้า พินล็อคอยู่ในสภาพดี ไม่หลวมคลอนจนเกินไป เกลียวเร่งอยู่ในสภาพดี เชือกอุปกรณ์รัดกล้ามปูไม่เปื่อย ขาดรุ่ย',
  },
  {
    id: 2.1,
    name: 'connector',
    question: 'สลักยึดและ รอยต่อระหว่างตัวแม่-ลูก *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'สลักยึดไม่สึก ไม่หลวมคลอน',
  },
  {
    id: 2.11,
    name: 'shell',
    question: 'สภาพภายนอกถังปูน *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'สภาพถังปูนอยู่ในสภาพดี ไม่บุบ สึกกร่อน ร้าวหรือรั่ว',
  },
  {
    id: 2.12,
    name: 'gauge',
    question: 'การทำงานของเกจ์วัดแรงดัน(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'กระจก หน้าปัดเกจวัดไม่เรือนราง อ่านค่าได้ ',
  },
  {
    id: 2.13,
    name: 'butterfly',
    question: 'การทำงานของวาล์วปีกผีเสื้อ(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'วาล์วระบายแรงดันพร้อมใช้งาน ไม่คด บิด งอ ระบายลมได้ดี ไม่มีสิ่งกีดขวาง อุดตัน รูระบายลม',
  },
  {
    id: 2.14,
    name: 'release',
    question: 'การทำงานของเซฟตี้วาล์ว(ครั้งล่าสุด)*(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'วาล์วระบายแรงดันพร้อมใช้งาน ไม่คด บิด งอ ระบายลมได้ดี ไม่มีสิ่งกีดขวาง อุดตัน รูระบายลม สปริงไม่ล้า อยู่ในสภาพพร้อมใช้งาน',
  },
  {
    id: 2.15,
    name: 'ladder',
    question: 'บันได และราวกันตก*(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา / โยกบันได ราวกันตกขึ้น',
    accept: 'อยู่ในสภาพแข็งแรง ไม่ผุ กร่อน อุปกรณ์ล็อคแข็งแรง',
  },
  {
    id: 2.16,
    name: 'valve',
    question: 'การทำงานของวาล์วหลังถัง(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'วาล์วระบายแรงดันพร้อมใช้งาน ไม่คด บิด งอ ระบายลมได้ดี ไม่มีสิ่งกีดขวาง อุดตัน รูระบายลม',
  },
  {
    id: 2.17,
    name: 'sealHole',
    question: 'จุดร้อยซีลหลังถัง *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'มีรูคล้องซีลที่ฝาหลังถัง  รูไม่อุดตันหรือชำรุด',
  },
  {
    id: 2.18,
    name: 'seal',
    question: 'ซีลยางฝาถังหลังถัง *(เฉพาะรถปูนผงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'ไม่ฉีกขาด เปื่อยยุ่ย ยางไม่แข็งกรอบ / ไม่มีร่อง รู ที่ลมรั่วออกมาได้',
  },
  {
    id: 2.19,
    name: 'clean',
    question: 'สภาพความสะอาดของกระบะบรรทุก *(เฉพาะรถปูนถุงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'สะอาด ไม่มีสิ่งปนเปื้อน กระบะรถไม่ผุกร่อน ไม่เปียก ไม่มีสิ่งที่อาจทำให้ถุงปูนแตกได้',
  },
  {
    id: 2.2,
    name: 'strap',
    question: 'ผ้าใบและสายรัด *(เฉพาะรถปูนถุงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'ผ้าใบสะอาด ไม่เปียก ขาด ที่ส่งผลต่อสินค้าได้ /สายรัดผ้าใบมีความแข็งแรงไม่ขาดหลุดรุ่ย ที่อาจทำให้เกิดอุบัติเหตุขณะดึงสายรัด',
  },
  {
    id: 2.21,
    name: 'bolt',
    question: 'สลักยึดและ รอยต่อระหว่างตัวแม่-ลูก *(เฉพาะรถปูนถุงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'สลักยึดไม่สึก ไม่หลวมคลอน',
  },
  {
    id: 2.22,
    name: 'tailgate',
    question: 'ตัวล๊อคฝาท้ายกระบะ/ปากนกแก้ว *(เฉพาะรถปูนถุงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ทำงานได้ปกติ ล็อดฝาท้ายได้แน่นหนา',
  },
  {
    id: 2.23,
    name: 'pin',
    question:
      'ก้ามปูที่ล๊อค(Pinที่ยึดตามข้อแน่นหนาล็อคได้สนิท) *(เฉพาะรถปูนถุงเท่านั้น)',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่สึก ไม่หลวมคลอน',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'gps', label: '1.1 อุปกรณ์ GPS+เครื่องรูดบัตรขับขี่' },
  { field: 'gpsR', label: '' },
  { field: 'gpsP', label: '' },
  { field: 'gpsA', label: 'Respond to defect' },
  { field: 'gpsF', label: '' },
  { field: 'licenseplate', label: '1.2 แผ่นป้ายทะเบียน และ ภาษีประจำปี' },
  { field: 'licenseplateR', label: '' },
  { field: 'licenseplateP', label: '' },
  { field: 'licenseplateA', label: 'Respond to defect' },
  { field: 'licenseplateF', label: '' },
  { field: 'insurance', label: '1.3 เอกสารประกันภัยประจำรถ' },
  { field: 'insuranceR', label: '' },
  { field: 'insuranceP', label: '' },
  { field: 'insuranceA', label: 'Respond to defect' },
  { field: 'insuranceF', label: '' },
  { field: 'engine', label: '1.4 ระบบเครื่องยนต์/ระบบส่งกำลัง' },
  { field: 'engineR', label: '' },
  { field: 'engineP', label: '' },
  { field: 'engineA', label: 'Respond to defect' },
  { field: 'engineF', label: '' },
  { field: 'meter', label: '1.5 มาตรวัด ไฟเตือนหน้าปัด' },
  { field: 'meterR', label: '' },
  { field: 'meterP', label: '' },
  { field: 'meterA', label: 'Respond to defect' },
  { field: 'meterF', label: '' },
  { field: 'handbrake', label: '1.6 เบรคมือ / เท้าใช้งานได้ดี' },
  { field: 'handbrakeR', label: '' },
  { field: 'handbrakeP', label: '' },
  { field: 'handbrakeA', label: 'Respond to defect' },
  { field: 'handbrakeF', label: '' },
  { field: 'safetyBelt', label: '1.7 เข็มขัดนิรภัยล๊อกได้สนิท' },
  { field: 'safetyBeltR', label: '' },
  { field: 'safetyBeltP', label: '' },
  { field: 'safetyBeltA', label: 'Respond to defect' },
  { field: 'safetyBeltF', label: '' },
  { field: 'whipper', label: '1.8 ที่ปัดน้ำฝนซ้าย / ขวา และน้ำฉีดกระจก' },
  { field: 'whipperR', label: '' },
  { field: 'whipperP', label: '' },
  { field: 'whipperA', label: 'Respond to defect' },
  { field: 'whipperF', label: '' },
  { field: 'horn', label: '1.9 สัญญาณแตร' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'sideMirror', label: '1.10 กระจกหน้าหน้าต่าง / มองข้าง' },
  { field: 'sideMirrorR', label: '' },
  { field: 'sideMirrorP', label: '' },
  { field: 'sideMirrorA', label: 'Respond to defect' },
  { field: 'sideMirrorF', label: '' },
  { field: 'oil', label: '1.11 ระดับน้ำมันเชื้อเพลิง / ระดับแก๊สในถัง' },
  { field: 'oilR', label: '' },
  { field: 'oilP', label: '' },
  { field: 'oilA', label: 'Respond to defect' },
  { field: 'oilF', label: '' },
  {
    field: 'firstAid',
    label: '1.12 ชุดปฐมพยาบาลในการห้ามเลือดและถุงมืออนามัย',
  },
  { field: 'firstAidR', label: '' },
  { field: 'firstAidP', label: '' },
  { field: 'firstAidA', label: 'Respond to defect' },
  { field: 'firstAidF', label: '' },
  {
    field: 'light',
    label:
      '1.13 ไฟหลัก / เลี้ยวหน้า / หลัง / ส่องทะเบียน / ไฟราวข้าง/ ไฟเบรค / ไฟฉุกเฉิน',
  },
  { field: 'lightR', label: '' },
  { field: 'lightP', label: '' },
  { field: 'lightA', label: 'Respond to defect' },
  { field: 'lightF', label: '' },
  {
    field: 'harness',
    label: '1.14 มี Safety Belt ขึ้นที่สูงหลังถัง *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'harnessR', label: '' },
  { field: 'harnessP', label: '' },
  { field: 'harnessA', label: 'Respond to defect' },
  { field: 'harnessF', label: '' },
  { field: 'backSilent', label: '2.1 มีสัญญาณไฟและเสียงขณะถอยหลัง' },
  { field: 'backSilentR', label: '' },
  { field: 'backSilentP', label: '' },
  { field: 'backSilentA', label: 'Respond to defect' },
  { field: 'backSilentF', label: '' },
  { field: 'wheel', label: '2.2 ล้อ ลมยาง และ สภาพยาง' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'tire', label: '2.3 มียางอะไหล่/มีขอนรองล้อ 2 อัน (รถพ่วง 4 อัน)' },
  { field: 'tireR', label: '' },
  { field: 'tireP', label: '' },
  { field: 'tireA', label: 'Respond to defect' },
  { field: 'tireF', label: '' },
  { field: 'fireExtinguisher', label: '2.4 ถังดับเพลิง (15 Lbs.)' },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  { field: 'cone', label: '2.5 กรวยจราจร หรือ ป้ายสะท้อนแสง 2 อัน' },
  { field: 'coneR', label: '' },
  { field: 'coneP', label: '' },
  { field: 'coneA', label: 'Respond to defect' },
  { field: 'coneF', label: '' },
  { field: 'airBrake', label: '2.6 เช็คหม้อลมเบรก' },
  { field: 'airBrakeR', label: '' },
  { field: 'airBrakeP', label: '' },
  { field: 'airBrakeA', label: 'Respond to defect' },
  { field: 'airBrakeF', label: '' },
  {
    field: 'hose',
    label: '2.7 ท่อยางเป่าปูน และเข็มขัดรัดต่อสายต่างๆ *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'hoseR', label: '' },
  { field: 'hoseP', label: '' },
  { field: 'hoseA', label: 'Respond to defect' },
  { field: 'hoseF', label: '' },
  {
    field: 'lip',
    label:
      '2.8 สภาพลูกยางโดนัท/ฝาครอบปลายท่อจุดร้อยซีล *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'lipR', label: '' },
  { field: 'lipP', label: '' },
  { field: 'lipA', label: 'Respond to defect' },
  { field: 'lipF', label: '' },
  {
    field: 'campLock',
    label:
      '2.9 สภาพก้ามปูที่ใช้ล๊อคท่อเป่าปูน ต้องล็อคได้แน่นหนา *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'campLockR', label: '' },
  { field: 'campLockP', label: '' },
  { field: 'campLockA', label: 'Respond to defect' },
  { field: 'campLockF', label: '' },
  {
    field: 'connector',
    label: '2.10 สลักยึดและ รอยต่อระหว่างตัวแม่-ลูก *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'connectorR', label: '' },
  { field: 'connectorP', label: '' },
  { field: 'connectorA', label: 'Respond to defect' },
  { field: 'connectorF', label: '' },
  { field: 'shell', label: '2.11 สภาพภายนอกถังปูน *(เฉพาะรถปูนผงเท่านั้น)' },
  { field: 'shellR', label: '' },
  { field: 'shellP', label: '' },
  { field: 'shellA', label: 'Respond to defect' },
  { field: 'shellF', label: '' },
  {
    field: 'gauge',
    label: '2.12 การทำงานของเกจ์วัดแรงดัน(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'Respond to defect' },
  { field: 'gaugeF', label: '' },
  {
    field: 'butterfly',
    label:
      '2.13 การทำงานของวาล์วปีกผีเสื้อ(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'butterflyR', label: '' },
  { field: 'butterflyP', label: '' },
  { field: 'butterflyA', label: 'Respond to defect' },
  { field: 'butterflyF', label: '' },
  {
    field: 'release',
    label: '2.14 การทำงานของเซฟตี้วาล์ว(ครั้งล่าสุด)*(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'releaseR', label: '' },
  { field: 'releaseP', label: '' },
  { field: 'releaseA', label: 'Respond to defect' },
  { field: 'releaseF', label: '' },
  { field: 'ladder', label: '2.15 บันได และราวกันตก*(เฉพาะรถปูนผงเท่านั้น)' },
  { field: 'ladderR', label: '' },
  { field: 'ladderP', label: '' },
  { field: 'ladderA', label: 'Respond to defect' },
  { field: 'ladderF', label: '' },
  {
    field: 'valve',
    label: '2.16 การทำงานของวาล์วหลังถัง(ครั้งล่าสุด) *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'valveR', label: '' },
  { field: 'valveP', label: '' },
  { field: 'valveA', label: 'Respond to defect' },
  { field: 'valveF', label: '' },
  {
    field: 'sealHole',
    label: '2.17 จุดร้อยซีลหลังถัง *(เฉพาะรถปูนผงเท่านั้น)',
  },
  { field: 'sealHoleR', label: '' },
  { field: 'sealHoleP', label: '' },
  { field: 'sealHoleA', label: 'Respond to defect' },
  { field: 'sealHoleF', label: '' },
  { field: 'seal', label: '2.18 ซีลยางฝาถังหลังถัง *(เฉพาะรถปูนผงเท่านั้น)' },
  { field: 'sealR', label: '' },
  { field: 'sealP', label: '' },
  { field: 'sealA', label: 'Respond to defect' },
  { field: 'sealF', label: '' },
  {
    field: 'clean',
    label: '2.19 สภาพความสะอาดของกระบะบรรทุก *(เฉพาะรถปูนถุงเท่านั้น)',
  },
  { field: 'cleanR', label: '' },
  { field: 'cleanP', label: '' },
  { field: 'cleanA', label: 'Respond to defect' },
  { field: 'cleanF', label: '' },
  { field: 'strap', label: '2.20 ผ้าใบและสายรัด *(เฉพาะรถปูนถุงเท่านั้น)' },
  { field: 'strapR', label: '' },
  { field: 'strapP', label: '' },
  { field: 'strapA', label: 'Respond to defect' },
  { field: 'strapF', label: '' },
  {
    field: 'bolt',
    label: '2.21 สลักยึดและ รอยต่อระหว่างตัวแม่-ลูก *(เฉพาะรถปูนถุงเท่านั้น)',
  },
  { field: 'boltR', label: '' },
  { field: 'boltP', label: '' },
  { field: 'boltA', label: 'Respond to defect' },
  { field: 'boltF', label: '' },
  {
    field: 'tailgate',
    label: '2.22 ตัวล๊อคฝาท้ายกระบะ/ปากนกแก้ว *(เฉพาะรถปูนถุงเท่านั้น)',
  },
  { field: 'tailgateR', label: '' },
  { field: 'tailgateP', label: '' },
  { field: 'tailgateA', label: 'Respond to defect' },
  { field: 'tailgateF', label: '' },
  {
    field: 'pin',
    label:
      '2.23 ก้ามปูที่ล๊อค(Pinที่ยึดตามข้อแน่นหนาล็อคได้สนิท) *(เฉพาะรถปูนถุงเท่านั้น)',
  },
  { field: 'pinR', label: '' },
  { field: 'pinP', label: '' },
  { field: 'pinA', label: 'Respond to defect' },
  { field: 'pinF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
