export const questions = [
  {
    id: 1,
    name: 'weldingMachineCondition',
    question:
      'Máy hàn có chắc chắn về mặt vật lý khi đang hoạt động không? / Is the welding machine physically sound and in working condition?',
    howto: 'Kiểm tra tổng thể tình trạng bề ngoài của máy hàn để phát hiện các hư hỏng rõ ràng và đảm bảo máy hoạt động bình thường.',
    accept: 'Máy hàn chắc chắn về mặt vật lý và trong tình trạng hoạt động tốt.',
  },
  {
    id: 2,
    name: 'switchesCondition',
    question:
      'Các công tắc có bị hư hỏng và được cách điện đúng cách không? / Are switches free from damage and properly insulated?',
    howto: 'Kiểm tra tất cả các công tắc trên máy hàn để phát hiện hư hỏng và đảm bảo cách điện được thực hiện đúng cách.',
    accept: 'Các công tắc không bị hư hỏng và được cách điện đúng cách.',
  },
  {
    id: 3,
    name: 'weldingLeadConnection',
    question:
      'Kết nối dây hàn có được siết chặt đúng cách bằng ổ cắm/vấu nối không? / Are welding and return lead connections properly tight by means of socket/lugs?',
    howto: 'Kiểm tra độ chặt của các kết nối dây hàn và dây trở về, đảm bảo được kết nối chắc chắn qua ổ cắm hoặc vấu nối.',
    accept: 'Kết nối dây hàn và dây trở về được siết chặt đúng cách.',
  },
  {
    id: 4,
    name: 'weldingLeadCondition',
    question:
      'Dây hàn và kìm hàn có bị hư hỏng không (ví dụ: bị cắt, hở, quá nhiều mối nối)? / Are welding and return leads free from damage (e.g. cut, open, too many joints)?',
    howto: 'Kiểm tra toàn bộ chiều dài của dây hàn và kìm hàn để phát hiện các hư hỏng như bị cắt, hở mạch, hoặc có quá nhiều mối nối.',
    accept: 'Dây hàn và kìm hàn không bị hư hỏng, không có vết cắt, hở mạch hay quá nhiều mối nối.',
  },
  {
    id: 5,
    name: 'weldingHolderCondition',
    question:
      'Kìm hàn có trong tình trạng tốt không có tiếp xúc kim loại không mong muốn không? / Is the welding holder in good condition without any unwanted metal contact?',
    howto: 'Kiểm tra kìm hàn để đảm bảo trong tình trạng tốt và không có tiếp xúc kim loại không mong muốn có thể gây chập điện.',
    accept: 'Kìm hàn trong tình trạng tốt, không có tiếp xúc kim loại không mong muốn.',
  },
  {
    id: 6,
    name: 'earthingHolderCondition',
    question:
      'Giá đỡ nối đất có trong tình trạng tốt và không bị gỉ không? / Is the earthing holder in good condition and free from rust?',
    howto: 'Kiểm tra giá đỡ nối đất để đảm bảo không bị gỉ sét và trong tình trạng hoạt động tốt.',
    accept: 'Giá đỡ nối đất trong tình trạng tốt và không bị gỉ.',
  },
  {
    id: 7,
    name: 'weldingMachineGrounding',
    question:
      'Máy hàn có được nối đất đúng cách không? / Is the welding machine properly grounded?',
    howto: 'Kiểm tra hệ thống nối đất của máy hàn để đảm bảo an toàn điện và tuân thủ các quy định an toàn.',
    accept: 'Máy hàn được nối đất đúng cách theo quy định an toàn.',
  },
  {
    id: 8,
    name: 'fireExtinguisherAvailable',
    question:
      'Có chuẩn bị bình chữa cháy phù hợp tại nơi làm việc không? / Is suitable fire extinguisher available at work place?',
    howto: 'Kiểm tra sự có mặt và tình trạng của bình chữa cháy phù hợp cho công việc hàn tại khu vực làm việc.',
    accept: 'Bình chữa cháy phù hợp được chuẩn bị sẵn sàng tại nơi làm việc.',
  },
  {
    id: 9,
    name: 'fireRetardantMaterial',
    question:
      'Có chuẩn bị vật liệu chống cháy tại nơi làm việc không? / Is fire retardant material available at work place?',
    howto: 'Kiểm tra sự có mặt của các vật liệu chống cháy để bảo vệ khu vực xung quanh khỏi tia lửa hàn.',
    accept: 'Vật liệu chống cháy được chuẩn bị tại nơi làm việc.',
  },
  {
    id: 10,
    name: 'weldingBoothWorkstation',
    question:
      'Có cung cấp màn che lửa hoặc trạm làm việc phù hợp khi cần thiết không? / Is welding booth or proper work station provided whenever required?',
    howto: 'Kiểm tra sự có mặt của màn che lửa hàn hoặc trạm làm việc được thiết lập phù hợp để bảo vệ người lao động và khu vực xung quanh.',
    accept: 'Màn che lửa hàn hoặc trạm làm việc phù hợp được cung cấp khi cần thiết.',
  },
  {
    id: 11,
    name: 'competentWelder',
    question:
      'Công việc hàn có được thực hiện bởi người có kinh nghiệm và có năng lực không? / Is welding work carried out by experienced and competent person?',
    howto: 'Xác minh rằng người thực hiện công việc hàn có kinh nghiệm, được đào tạo và có chứng chỉ phù hợp.',
    accept: 'Công việc hàn được thực hiện bởi người có kinh nghiệm và có năng lực.',
  },
  {
    id: 12,
    name: 'cableConditionIndustrialPlug',
    question:
      'Tất cả cáp có bị hư hỏng và luôn sử dụng phích cắm công nghiệp để kết nối nguồn điện không? / Are all cables damage free and always use industrial plug to take power connection?',
    howto: 'Kiểm tra tình trạng của tất cả các cáp điện và đảm bảo sử dụng phích cắm công nghiệp phù hợp cho kết nối nguồn điện.',
    accept: 'Tất cả cáp không bị hư hỏng và sử dụng phích cắm công nghiệp để kết nối nguồn điện.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'weldingMachineCondition', label: '1. Máy hàn có chắc chắn về mặt vật lý khi đang hoạt động không? / Is the welding machine physically sound and in working condition?'},
  { field: 'weldingMachineConditionR', label: '' },
  { field: 'weldingMachineConditionP', label: '' },
  { field: 'weldingMachineConditionA', label: '' },
  { field: 'weldingMachineConditionF', label: '' },
  { field: 'switchesCondition', label: '2. Các công tắc có bị hư hỏng và được cách điện đúng cách không? / Are switches free from damage and properly insulated?'},
  { field: 'switchesConditionR', label: '' },
  { field: 'switchesConditionP', label: '' },
  { field: 'switchesConditionA', label: '' },
  { field: 'switchesConditionF', label: '' },
  { field: 'weldingLeadConnection', label: '3. Kết nối dây hàn có được siết chặt đúng cách bằng ổ cắm/vấu nối không? / Are welding and return lead connections properly tight by means of socket/lugs?'},
  { field: 'weldingLeadConnectionR', label: '' },
  { field: 'weldingLeadConnectionP', label: '' },
  { field: 'weldingLeadConnectionA', label: '' },
  { field: 'weldingLeadConnectionF', label: '' },
  { field: 'weldingLeadCondition', label: '4. Dây hàn và kìm hàn có bị hư hỏng không (ví dụ: bị cắt, hở, quá nhiều mối nối)? / Are welding and return leads free from damage (e.g. cut, open, too many joints)?'},
  { field: 'weldingLeadConditionR', label: '' },
  { field: 'weldingLeadConditionP', label: '' },
  { field: 'weldingLeadConditionA', label: '' },
  { field: 'weldingLeadConditionF', label: '' },
  { field: 'weldingHolderCondition', label: '5. Kìm hàn có trong tình trạng tốt không có tiếp xúc kim loại không mong muốn không? / Is the welding holder in good condition without any unwanted metal contact?'},
  { field: 'weldingHolderConditionR', label: '' },
  { field: 'weldingHolderConditionP', label: '' },
  { field: 'weldingHolderConditionA', label: '' },
  { field: 'weldingHolderConditionF', label: '' },
  { field: 'earthingHolderCondition', label: '6. Giá đỡ nối đất có trong tình trạng tốt và không bị gỉ không? / Is the earthing holder in good condition and free from rust?'},
  { field: 'earthingHolderConditionR', label: '' },
  { field: 'earthingHolderConditionP', label: '' },
  { field: 'earthingHolderConditionA', label: '' },
  { field: 'earthingHolderConditionF', label: '' },
  { field: 'weldingMachineGrounding', label: '7. Máy hàn có được nối đất đúng cách không? / Is the welding machine properly grounded?'},
  { field: 'weldingMachineGroundingR', label: '' },
  { field: 'weldingMachineGroundingP', label: '' },
  { field: 'weldingMachineGroundingA', label: '' },
  { field: 'weldingMachineGroundingF', label: '' },
  { field: 'fireExtinguisherAvailable', label: '8. Có chuẩn bị bình chữa cháy phù hợp tại nơi làm việc không? / Is suitable fire extinguisher available at work place?'},
  { field: 'fireExtinguisherAvailableR', label: '' },
  { field: 'fireExtinguisherAvailableP', label: '' },
  { field: 'fireExtinguisherAvailableA', label: '' },
  { field: 'fireExtinguisherAvailableF', label: '' },
  { field: 'fireRetardantMaterial', label: '9. Có chuẩn bị vật liệu chống cháy tại nơi làm việc không? / Is fire retardant material available at work place?'},
  { field: 'fireRetardantMaterialR', label: '' },
  { field: 'fireRetardantMaterialP', label: '' },
  { field: 'fireRetardantMaterialA', label: '' },
  { field: 'fireRetardantMaterialF', label: '' },
  { field: 'weldingBoothWorkstation', label: '10. Có cung cấp màn che lửa hoặc trạm làm việc phù hợp khi cần thiết không? / Is welding booth or proper work station provided whenever required?'},
  { field: 'weldingBoothWorkstationR', label: '' },
  { field: 'weldingBoothWorkstationP', label: '' },
  { field: 'weldingBoothWorkstationA', label: '' },
  { field: 'weldingBoothWorkstationF', label: '' },
  { field: 'competentWelder', label: '11. Công việc hàn có được thực hiện bởi người có kinh nghiệm và có năng lực không? / Is welding work carried out by experienced and competent person?'},
  { field: 'competentWelderR', label: '' },
  { field: 'competentWelderP', label: '' },
  { field: 'competentWelderA', label: '' },
  { field: 'competentWelderF', label: '' },
  { field: 'cableConditionIndustrialPlug', label: '12. Tất cả cáp có bị hư hỏng và luôn sử dụng phích cắm công nghiệp để kết nối nguồn điện không? / Are all cables damage free and always use industrial plug to take power connection?'},
  { field: 'cableConditionIndustrialPlugR', label: '' },
  { field: 'cableConditionIndustrialPlugP', label: '' },
  { field: 'cableConditionIndustrialPlugA', label: '' },
  { field: 'cableConditionIndustrialPlugF', label: '' },
  { field: 'tag', label: 'Tag' },
  { field: 'collection', label: 'Type of Equipment' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
