export const questions = [
  {
    id: 1,
    name: "wheel",
    question: "កង់ កង់សាកួរមិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងការបង្វិលកង់",
    accept: "កង់ស្ថានភាពល្អ ក្រឡានៅស្អាត និងប៊ូឡុងខ្ចៅតឹងណែនល្អ",
  },
  {
    id: 2,
    name: "hydraulic",
    question: "គ្រឿងបង្គុំបូមទាំងអស់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងការប្រើប្រាស់",
    accept: "គ្រឿងបង្គុំបូមដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត",
  },
  {
    id: 3,
    name: "air",
    question: "ប្រពន្ធ័ខ្យល់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងភាពដំណើរការរបស់ប្រព័ន្ធខ្យល់",
    accept: "ប្រពន្ធ័ខ្យល់ដំណើរការបានត្រឹមត្រូវ",
  },
  {
    id: 4,
    name: "seat",
    question: "ខ្សែក្រវ៉ាត់ និងចំណាំងផ្លាតខ្សែក្រវ៉ាត់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាពខ្សែក្រវ៉ាត់ និងចំណាំង",
    accept: "ខ្សែក្រវ៉ាត់ដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត",
  },
  {
    id: 5,
    name: "mirror",
    question: "កញ្ចក់ឆ្លុះទាំងអស់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាពកញ្ចក់ និងភាពច្បាស់",
    accept: "កញ្ចក់ស្ថានភាពល្អ គ្មានការបាក់ ឬស្នាមប៉ះ",
  },
  {
    id: 6,
    name: "handbrake",
    question: "ហ្រ្វាំងដៃ ហ្រ្វាំងជើង និងហ្គាមិនធម្មតា",
    howto: "តេស្តជាន់ហ្រ្វាំងមុនបើកបរ",
    accept: "ហ្វ្រាំងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត",
  },
  {
    id: 7,
    name: "steering",
    question: "ចង្កូតមិនធម្មតា",
    howto: "តេស្តបួងចង្កូត ឆ្វេង-ស្តាំង២ជុំ",
    accept: "ចង្កូតដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត",
  },
  {
    id: 8,
    name: "wire",
    question: "ខ្សែកាបទាំងអស់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងភាពខ្សែកាប",
    accept: "ខ្សែកាបស្ថានភាពល្អ គ្មានការខូចខាត",
  },
  {
    id: 9,
    name: "reeving",
    question: "ក្បាលដុំស្ទូច ទំពួកស្ទូច សន្ទះសុវត្ថិភាពរបស់ទំពក់មិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងភាពដំណើរការនៃទំពួក",
    accept: "ទំពួកស្ថានភាពល្អ និងដំណើរការបានត្រឹមត្រូវ",
  },
  {
    id: 10,
    name: "wedge",
    question: "ក្រាប់ស្វាយ ក្រចាប់កាបមិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងការប្រើប្រាស់",
    accept: "ក្រចាប់កាបស្ថានភាពល្អ គ្មានការខូចខាត",
  },
  {
    id: 11,
    name: "light",
    question: "អំពូលទាំងអស់មិនធម្មតា",
    howto: "ពិនិត្យការដំណើរការរបស់អំពូល",
    accept: "អំពូលដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត",
  },
  {
    id: 12,
    name: "horn",
    question: "ស៊ីផ្លេមិនធម្មតា",
    howto: "តេស្តសំលេងស៊ីផ្លេ",
    accept: "ស៊ីផ្លេដំណើរការរលូន និងលឺច្បាស់",
  },
  {
    id: 13,
    name: "chart",
    question: "តារាងស្ទូចបន្ទុក និងជើងទប់លំនឹងក្រេនមិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាពនិងភាពដំណើរការរបស់តារាងស្ទូច",
    accept: "តារាងស្ថានភាពល្អ និងអាចប្រើប្រាស់បានត្រឹមត្រូវ",
  },
  {
    id: 14,
    name: "corne",
    question: "ដុំកោនសុវត្ថិភាព និងរបាំងការពារពេលស្ទូចមិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាពនិងការការពារចំពោះដុំកោន",
    accept: "ដុំកោនស្ថានភាពល្អ គ្មានការខូចខាត",
  },
  {
    id: 15,
    name: "extinguisher",
    question: "បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា",
    howto: "ពិនិត្យស្ថានភាព និងការដំណើរការ",
    accept: "បំពង់ដំណើរការបានត្រឹមត្រូវ",
  },
  {
    id: 16,
    name: "reversing",
    question: "សឺរ៉ែនថយក្រោយមិនធម្មតា",
    howto: "តេស្តស្ថានភាព និងសម្លេងសឺរ៉ែន",
    accept: "សឺរ៉ែនដំណើរការត្រឹមត្រូវ និងលឺច្បាស់",
  },
];

export const detailFields = [
  { field: "id", label: "អត្តលេខ - ID" },
  { field: "date", label: "កាលបរិច្ឆេទ - Date" },
  { field: "inspector", label: "អ្នកត្រួតពិនិត្យ - Inspector" },
  { field: "responder", label: "អ្នកឆ្លើយតប - Responder" },
  { field: "wheel", label: "1. កង់ កង់សាកួរមិនធម្មតា" },
  { field: "wheelR", label: "" },
  { field: "wheelP", label: "" },
  { field: "wheelA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "wheelF", label: "" },
  { field: "hydraulic", label: "2. គ្រឿងបង្គុំបូមទាំងអស់មិនធម្មតា" },
  { field: "hydraulicR", label: "" },
  { field: "hydraulicP", label: "" },
  { field: "hydraulicA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "hydraulicF", label: "" },
  { field: "air", label: "3. ប្រពន្ធ័ខ្យល់មិនធម្មតា" },
  { field: "airR", label: "" },
  { field: "airP", label: "" },
  { field: "airA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "airF", label: "" },
  {
    field: "seat",
    label: "4. ខ្សែក្រវ៉ាត់ និងចំណាំងផ្លាតខ្សែក្រវ៉ាត់មិនធម្មតា",
  },
  { field: "seatR", label: "" },
  { field: "seatP", label: "" },
  { field: "seatA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "seatF", label: "" },
  { field: "mirror", label: "5. កញ្ចក់ឆ្លុះទាំងអស់មិនធម្មតា" },
  { field: "mirrorR", label: "" },
  { field: "mirrorP", label: "" },
  { field: "mirrorA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "mirrorF", label: "" },
  { field: "handbrake", label: "6. ហ្រ្វាំងដៃ ហ្រ្វាំងជើង និងហ្គាមិនធម្មតា" },
  { field: "handbrakeR", label: "" },
  { field: "handbrakeP", label: "" },
  { field: "handbrakeA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "handbrakeF", label: "" },
  { field: "steering", label: "7. ចង្កូតមិនធម្មតា" },
  { field: "steeringR", label: "" },
  { field: "steeringP", label: "" },
  { field: "steeringA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "steeringF", label: "" },
  { field: "wire", label: "8. ខ្សែកាបទាំងអស់មិនធម្មតា" },
  { field: "wireR", label: "" },
  { field: "wireP", label: "" },
  { field: "wireA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "wireF", label: "" },
  {
    field: "reeving",
    label: "9. ក្បាលដុំស្ទូច ទំពួកស្ទូច សន្ទះសុវត្ថិភាពរបស់ទំពក់មិនធម្មតា",
  },
  { field: "reevingR", label: "" },
  { field: "reevingP", label: "" },
  { field: "reevingA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "reevingF", label: "" },
  { field: "wedge", label: "10. ក្រាប់ស្វាយ ក្រចាប់កាបមិនធម្មតា" },
  { field: "wedgeR", label: "" },
  { field: "wedgeP", label: "" },
  { field: "wedgeA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "wedgeF", label: "" },
  { field: "light", label: "11. អំពូលទាំងអស់មិនធម្មតា" },
  { field: "lightR", label: "" },
  { field: "lightP", label: "" },
  { field: "lightA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "lightF", label: "" },
  { field: "horn", label: "12. ស៊ីផ្លេមិនធម្មតា" },
  { field: "hornR", label: "" },
  { field: "hornP", label: "" },
  { field: "hornA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "hornF", label: "" },
  {
    field: "chart",
    label: "13. តារាងស្ទូចបន្ទុក និងជើងទប់លំនឹងក្រេនមិនធម្មតា",
  },
  { field: "chartR", label: "" },
  { field: "chartP", label: "" },
  { field: "chartA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "chartF", label: "" },
  {
    field: "corne",
    label: "14. ដុំកោនសុវត្ថិភាព និងរបាំងការពារពេលស្ទូចមិនធម្មតា",
  },
  { field: "corneR", label: "" },
  { field: "corneP", label: "" },
  { field: "corneA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "corneF", label: "" },
  { field: "extinguisher", label: "15. បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា" },
  { field: "extinguisherR", label: "" },
  { field: "extinguisherP", label: "" },
  { field: "extinguisherA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "extinguisherF", label: "" },
  { field: "reversing", label: "16. សឺរ៉ែនថយក្រោយមិនធម្មតា" },
  { field: "reversingR", label: "" },
  { field: "reversingP", label: "" },
  { field: "reversingA", label: "ឆ្លើយតបដល់កំហុស - Respond to defect" },
  { field: "reversingF", label: "" },
  { field: "remark", label: "មតិយោបល់ - Remark" },
  { field: "lat", label: "" },
  { field: "url", label: "" },
];
