export const questions = [
  {
    id: 1,
    name: 'fireHoseTube',
    question: 'តួទុយោអគ្គិភ័យ',
    howto: 'ភ្នែក',
    accept: 'គ្មានដាច់រលាត់ថ្នាំ និង​​​​ មិនមានប្រេះស្រាំ',
  },
  {
    id: 2,
    name: 'waterValveCheck',
    question: 'វ៉ាល់សន្ទះបិទបើកទឹក',
    howto: 'ភ្នែក, ដៃ',
    accept: 'ត្រួតពិនិត្យមើលវ៉ាល់បិទបើកធ្វើការធម្មតា',
  },
  {
    id: 3,
    name: 'hoseRackNozzle',
    question: 'ក្បាលទុយោបាញ់របស់ fire hose rack',
    howto: 'ភ្នែក, ដៃ',
    accept: 'លក្ខណៈគ្មានប្រេះស្រាំ',
  },
  {
    id: 4,
    name: 'fireHoseRackCondition',
    question: 'ទុយោពន្លត់របស់ fire hose rack',
    howto: 'ភ្នែក, ដៃ',
    accept: 'លក្ខណៈគ្មានដាច់រហែក និង ទុយោរៀបតាមលំដាប់លំដោយ',
  },
  {
    id: 5,
    name: 'fireReelNozzle',
    question: 'ក្បាលទុយោបាញ់របស់ fire reel',
    howto: 'ភ្នែក, ដៃ',
    accept: 'លក្ខណៈគ្មានប្រេះស្រាំ',
  },
  {
    id: 6,
    name: 'fireHoseReelCondition',
    question: 'ទុយោពន្លត់របស់ fire hose reel',
    howto: 'ភ្នែក, ដៃ',
    accept: 'លក្ខណៈគ្មានដាច់រហែក និង សភាពស្អាតល្អ',
  },
  {
    id: 7,
    name: 'fireHoseBox',
    question: 'ប្រអប់ទុយោអគ្គិភ័យ',
    howto: 'ភ្នែក, ដៃ',
    accept: 'បិទជិត និង មិនមានខូចទ្រង់ទ្រាយ',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'fireHoseTube', label: '1. តួទុយោអគ្គិភ័យ - Pipe Condition' },
  { field: 'fireHoseTubeR', label: '' },
  { field: 'fireHoseTubeP', label: '' },
  { field: 'fireHoseTubeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'fireHoseTubeF', label: '' },
  { field: 'waterValveCheck', label: '2. វ៉ាល់សន្ទះបិទបើកទឹក - Water Valve' },
  { field: 'waterValveCheckR', label: '' },
  { field: 'waterValveCheckP', label: '' },
  { field: 'waterValveCheckA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'waterValveCheckF', label: '' },
  {
    field: 'hoseRackNozzle',
    label: '3. ក្បាលទុយោបាញ់របស់ fire hose rack - Nozzle Condition',
  },
  { field: 'hoseRackNozzleR', label: '' },
  { field: 'hoseRackNozzleP', label: '' },
  { field: 'hoseRackNozzleA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hoseRackNozzleF', label: '' },
  {
    field: 'fireHoseRackCondition',
    label: '4. ទុយោពន្លត់របស់ fire hose rack - Hose Condition',
  },
  { field: 'fireHoseRackConditionR', label: '' },
  { field: 'fireHoseRackConditionP', label: '' },
  {
    field: 'fireHoseRackConditionA',
    label: 'ឆ្លើយតបដល់កំហុស - Respond to defect',
  },
  { field: 'fireHoseRackConditionF', label: '' },
  {
    field: 'fireReelNozzle',
    label: '5. ក្បាលទុយោបាញ់របស់ fire reel - Nozzle Condition',
  },
  { field: 'fireReelNozzleR', label: '' },
  { field: 'fireReelNozzleP', label: '' },
  { field: 'fireReelNozzleA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'fireReelNozzleF', label: '' },
  {
    field: 'fireHoseReelCondition',
    label: '6. ទុយោពន្លត់របស់ fire hose reel - Hose Reel Condition',
  },
  { field: 'fireHoseReelConditionR', label: '' },
  { field: 'fireHoseReelConditionP', label: '' },
  {
    field: 'fireHoseReelConditionA',
    label: 'ឆ្លើយតបដល់កំហុស - Respond to defect',
  },
  { field: 'fireHoseReelConditionF', label: '' },
  { field: 'fireHoseBox', label: '7. ប្រអប់ទុយោអគ្គិភ័យ - Hose Box Condition' },
  { field: 'fireHoseBoxR', label: '' },
  { field: 'fireHoseBoxP', label: '' },
  { field: 'fireHoseBoxA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'fireHoseBoxF', label: '' },
  { field: 'remark', label: 'ាម់មុទរនានីអាវា - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
