export const questions = [
  {
    id: 1,
    name: 'cleanlinessCondition',
    question:
      'Vệ sinh dầu, mỡ, quá nhiều bụi đóng bám? / Is it clean from oil, grease, and excessive dust buildup?',
    howto: 'Kiểm tra bề mặt thang để phát hiện sự tích tụ dầu, mỡ và bụi bẩn quá mức.',
    accept: 'Thang sạch sẽ, không có dầu, mỡ hay bụi tích tụ quá mức.',
  },
  {
    id: 2,
    name: 'fasteningTightness',
    question:
      'Bậc thang, đinh ốc, con tán, vít, bu lông, hoặc các bộ phận kim loại khác có bị lỏng lẻo không? / Are steps, screws, rivets, bolts, or other metal parts loose?',
    howto: 'Kiểm tra độ chặt của các bu lông, vít, đinh tán và các bộ phận kim loại bằng cách thử vặn bằng tay.',
    accept: 'Tất cả bậc thang, đinh ốc, con tán, vít, bu lông và các bộ phận kim loại khác được siết chặt, không thể vặn bằng tay.',
  },
  {
    id: 3,
    name: 'structuralIntegrity',
    question:
      'Thanh đứng, giằng, bậc thang có bị nứt nẻ, thủng, cắt hoặc bể không? / Are rails, braces, or steps cracked, punctured, cut, or broken?',
    howto: 'Kiểm tra tổng thể cấu trúc thang để phát hiện các vết nứt, lỗ thủng, vết cắt hoặc gãy.',
    accept: 'Thanh đứng, giằng và bậc thang không có vết nứt, thủng, cắt hoặc gãy.',
  },
  {
    id: 4,
    name: 'stepSurfaceWear',
    question:
      'Bậc thang, mặt phủ bậc thang có bị mòn không? / Are ladder steps or step surfaces worn?',
    howto: 'Kiểm tra tình trạng mòn của bậc thang và mặt phủ bậc thang.',
    accept: 'Bậc thang và mặt phủ bậc thang không bị mòn.',
  },
  {
    id: 5,
    name: 'debrisOnLadder',
    question:
      'Có mảnh vụn trên thanh đứng, bậc thang không? / Are there debris on rails or steps?',
    howto: 'Kiểm tra sự hiện diện của mảnh vụn hoặc vật cản trên thanh đứng và bậc thang.',
    accept: 'Không có mảnh vụn trên thanh đứng và bậc thang.',
  },
  {
    id: 6,
    name: 'antiSlipCondition',
    question:
      'Để chống trượt có bị hư, mòn không? / Are anti-slip features damaged or worn?',
    howto: 'Kiểm tra tình trạng của các tính năng chống trượt trên thang.',
    accept: 'Các tính năng chống trượt không bị hư hỏng hoặc mòn.',
  },
  {
    id: 7,
    name: 'fiberglassCondition',
    question:
      'Sợi thủy tinh trong thang (loại bằng sợi thủy tinh) có nứt và nhô ra ngoài không? / Are fiberglass fibers in the ladder cracked and protruding?',
    howto: 'Kiểm tra thang sợi thủy tinh để phát hiện các vết nứt và sợi nhô ra ngoài.',
    accept: 'Sợi thủy tinh không bị nứt và không có sợi nhô ra ngoài.',
  },
  {
    id: 8,
    name: 'wearCorrosionOxidation',
    question:
      'Có mòn, rỉ, oxy hóa và quá mòn không, đặc biệt là đối với mặt phủ bậc thang? / Is there wear, rust, oxidation, and excessive wear, especially on step surfaces?',
    howto: 'Kiểm tra dấu hiệu mòn, rỉ sét, oxy hóa và mài mòn quá mức, đặc biệt chú ý đến mặt phủ bậc thang.',
    accept: 'Không có dấu hiệu mòn, rỉ sét, oxy hóa hoặc mài mòn quá mức.',
  },
  {
    id: 9,
    name: 'identificationLabels',
    question:
      'Có mất nhãn nhận dạng không? / Are identification labels missing?',
    howto: 'Kiểm tra sự hiện diện của các nhãn nhận dạng và thông tin kỹ thuật trên thang.',
    accept: 'Các nhãn nhận dạng còn nguyên và rõ ràng.',
  },
  {
    id: 10,
    name: 'ropesChainsCables',
    question:
      'Dây, xích, dây thừng có bị hư hại không? / Are ropes, chains, or cables damaged?',
    howto: 'Kiểm tra tình trạng của dây thừng, xích và cáp để phát hiện hư hỏng.',
    accept: 'Dây thừng, xích và cáp không bị hư hỏng.',
  },
  {
    id: 11,
    name: 'climbingDevices',
    question:
      'Dụng cụ leo có bị lỗi không, bao gồm thanh trượt, dây thừng bị hư hoặc lỏng lẻo? / Are climbing devices faulty, including damaged or loose slide rails and ropes?',
    howto: 'Kiểm tra các dụng cụ leo, thanh trượt và dây thừng để phát hiện lỗi hoặc tình trạng lỏng lẻo.',
    accept: 'Dụng cụ leo, thanh trượt và dây thừng hoạt động bình thường và được siết chặt.',
  },
  {
    id: 12,
    name: 'safetyCageCondition',
    question:
      'Lồng bảo vệ có bị móp méo hoặc hư hại không? / Is the safety cage dented or damaged?',
    howto: 'Kiểm tra tình trạng của lồng bảo vệ để phát hiện móp méo hoặc hư hỏng.',
    accept: 'Lồng bảo vệ không bị móp méo hoặc hư hỏng.',
  },
  {
    id: 13,
    name: 'cageBoltsRivets',
    question:
      'Lồng bảo vệ, bu lông và đầu đinh tán có bị mòn không? / Are safety cage, bolts, and rivet heads worn?',
    howto: 'Kiểm tra tình trạng mòn của lồng bảo vệ, bu lông và đầu đinh tán.',
    accept: 'Lồng bảo vệ, bu lông và đầu đinh tán không bị mòn.',
  },
  {
    id: 14,
    name: 'handrailsPlatforms',
    question:
      'Tay vịn và bệ trên sản có bị hư hoặc mòn không? / Are handrails and platforms damaged or worn?',
    howto: 'Kiểm tra tình trạng của tay vịn và bệ đỡ để phát hiện hư hỏng hoặc mòn.',
    accept: 'Tay vịn và bệ trên sản không bị hư hỏng hoặc mòn.',
  },
  {
    id: 15,
    name: 'extensionLocks',
    question:
      'Chốt duỗi có bị lỏng, bẻ hoặc bị mất không? / Are extension locks loose, bent, or missing?',
    howto: 'Kiểm tra tình trạng của các chốt duỗi thang để phát hiện lỏng lẻo, bị bẻ cong hoặc mất.',
    accept: 'Chốt duỗi còn nguyên, không bị lỏng lẻo hoặc bẻ cong.',
  },
  {
    id: 16,
    name: 'lockingMechanism',
    question:
      'Chốt khóa có bị hỏng, không vào khớp khi thang được kéo duỗi ra không? / Are locking mechanisms broken or not engaging when ladder is extended?',
    howto: 'Kiểm tra hoạt động của cơ chế khóa khi duỗi thang ra.',
    accept: 'Chốt khóa hoạt động bình thường và vào khớp chắc chắn khi thang được duỗi ra.',
  },
  {
    id: 17,
    name: 'lubricationMaintenance',
    question:
      'Có tra dầu mỡ các bộ phận làm việc không? / Are working parts properly lubricated?',
    howto: 'Kiểm tra việc bôi trơn các bộ phận chuyển động và hoạt động của thang.',
    accept: 'Các bộ phận làm việc được tra dầu mỡ phù hợp.',
  },
  {
    id: 18,
    name: 'padsGrooves',
    question:
      'Đệm lót có bị mất, hư hỏng các đệm lót hoặc rãnh trượt không? / Are pads missing, damaged, or are sliding grooves damaged?',
    howto: 'Kiểm tra tình trạng của đệm lót và rãnh trượt để phát hiện mất mát hoặc hư hỏng.',
    accept: 'Đệm lót còn nguyên và rãnh trượt không bị hư hỏng.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'cleanlinessCondition', label: '1. Vệ sinh dầu, mỡ, quá nhiều bụi đóng bám? / Is it clean from oil, grease, and excessive dust buildup?'},
  { field: 'cleanlinessConditionR', label: '' },
  { field: 'cleanlinessConditionP', label: '' },
  { field: 'cleanlinessConditionA', label: '' },
  { field: 'cleanlinessConditionF', label: '' },
  { field: 'fasteningTightness', label: '2. Bậc thang, đinh ốc, con tán, vít, bu lông, hoặc các bộ phận kim loại khác có bị lỏng lẻo không? / Are steps, screws, rivets, bolts, or other metal parts loose?'},
  { field: 'fasteningTightnessR', label: '' },
  { field: 'fasteningTightnessP', label: '' },
  { field: 'fasteningTightnessA', label: '' },
  { field: 'fasteningTightnessF', label: '' },
  { field: 'structuralIntegrity', label: '3. Thanh đứng, giằng, bậc thang có bị nứt nẻ, thủng, cắt hoặc bể không? / Are rails, braces, or steps cracked, punctured, cut, or broken?'},
  { field: 'structuralIntegrityR', label: '' },
  { field: 'structuralIntegrityP', label: '' },
  { field: 'structuralIntegrityA', label: '' },
  { field: 'structuralIntegrityF', label: '' },
  { field: 'stepSurfaceWear', label: '4. Bậc thang, mặt phủ bậc thang có bị mòn không? / Are ladder steps or step surfaces worn?'},
  { field: 'stepSurfaceWearR', label: '' },
  { field: 'stepSurfaceWearP', label: '' },
  { field: 'stepSurfaceWearA', label: '' },
  { field: 'stepSurfaceWearF', label: '' },
  { field: 'debrisOnLadder', label: '5. Có mảnh vụn trên thanh đứng, bậc thang không? / Are there debris on rails or steps?'},
  { field: 'debrisOnLadderR', label: '' },
  { field: 'debrisOnLadderP', label: '' },
  { field: 'debrisOnLadderA', label: '' },
  { field: 'debrisOnLadderF', label: '' },
  { field: 'antiSlipCondition', label: '6. Để chống trượt có bị hư, mòn không? / Are anti-slip features damaged or worn?'},
  { field: 'antiSlipConditionR', label: '' },
  { field: 'antiSlipConditionP', label: '' },
  { field: 'antiSlipConditionA', label: '' },
  { field: 'antiSlipConditionF', label: '' },
  { field: 'fiberglassCondition', label: '7. Sợi thủy tinh trong thang (loại bằng sợi thủy tinh) có nứt và nhô ra ngoài không? / Are fiberglass fibers in the ladder cracked and protruding?'},
  { field: 'fiberglassConditionR', label: '' },
  { field: 'fiberglassConditionP', label: '' },
  { field: 'fiberglassConditionA', label: '' },
  { field: 'fiberglassConditionF', label: '' },
  { field: 'wearCorrosionOxidation', label: '8. Có mòn, rỉ, oxy hóa và quá mòn không, đặc biệt là đối với mặt phủ bậc thang? / Is there wear, rust, oxidation, and excessive wear, especially on step surfaces?'},
  { field: 'wearCorrosionOxidationR', label: '' },
  { field: 'wearCorrosionOxidationP', label: '' },
  { field: 'wearCorrosionOxidationA', label: '' },
  { field: 'wearCorrosionOxidationF', label: '' },
  { field: 'identificationLabels', label: '9. Có mất nhãn nhận dạng không? / Are identification labels missing?'},
  { field: 'identificationLabelsR', label: '' },
  { field: 'identificationLabelsP', label: '' },
  { field: 'identificationLabelsA', label: '' },
  { field: 'identificationLabelsF', label: '' },
  { field: 'ropesChainsCables', label: '10. Dây, xích, dây thừng có bị hư hại không? / Are ropes, chains, or cables damaged?'},
  { field: 'ropesChainsCablesR', label: '' },
  { field: 'ropesChainsCablesP', label: '' },
  { field: 'ropesChainsCablesA', label: '' },
  { field: 'ropesChainsCablesF', label: '' },
  { field: 'climbingDevices', label: '11. Dụng cụ leo có bị lỗi không, bao gồm thanh trượt, dây thừng bị hư hoặc lỏng lẻo? / Are climbing devices faulty, including damaged or loose slide rails and ropes?'},
  { field: 'climbingDevicesR', label: '' },
  { field: 'climbingDevicesP', label: '' },
  { field: 'climbingDevicesA', label: '' },
  { field: 'climbingDevicesF', label: '' },
  { field: 'safetyCageCondition', label: '12. Lồng bảo vệ có bị móp méo hoặc hư hại không? / Is the safety cage dented or damaged?'},
  { field: 'safetyCageConditionR', label: '' },
  { field: 'safetyCageConditionP', label: '' },
  { field: 'safetyCageConditionA', label: '' },
  { field: 'safetyCageConditionF', label: '' },
  { field: 'cageBoltsRivets', label: '13. Lồng bảo vệ, bu lông và đầu đinh tán có bị mòn không? / Are safety cage, bolts, and rivet heads worn?'},
  { field: 'cageBoltsRivetsR', label: '' },
  { field: 'cageBoltsRivetsP', label: '' },
  { field: 'cageBoltsRivetsA', label: '' },
  { field: 'cageBoltsRivetsF', label: '' },
  { field: 'handrailsPlatforms', label: '14. Tay vịn và bệ trên sản có bị hư hoặc mòn không? / Are handrails and platforms damaged or worn?'},
  { field: 'handrailsPlatformsR', label: '' },
  { field: 'handrailsPlatformsP', label: '' },
  { field: 'handrailsPlatformsA', label: '' },
  { field: 'handrailsPlatformsF', label: '' },
  { field: 'extensionLocks', label: '15. Chốt duỗi có bị lỏng, bẻ hoặc bị mất không? / Are extension locks loose, bent, or missing?'},
  { field: 'extensionLocksR', label: '' },
  { field: 'extensionLocksP', label: '' },
  { field: 'extensionLocksA', label: '' },
  { field: 'extensionLocksF', label: '' },
  { field: 'lockingMechanism', label: '16. Chốt khóa có bị hỏng, không vào khớp khi thang được kéo duỗi ra không? / Are locking mechanisms broken or not engaging when ladder is extended?'},
  { field: 'lockingMechanismR', label: '' },
  { field: 'lockingMechanismP', label: '' },
  { field: 'lockingMechanismA', label: '' },
  { field: 'lockingMechanismF', label: '' },
  { field: 'lubricationMaintenance', label: '17. Có tra dầu mỡ các bộ phận làm việc không? / Are working parts properly lubricated?'},
  { field: 'lubricationMaintenanceR', label: '' },
  { field: 'lubricationMaintenanceP', label: '' },
  { field: 'lubricationMaintenanceA', label: '' },
  { field: 'lubricationMaintenanceF', label: '' },
  { field: 'padsGrooves', label: '18. Đệm lót có bị mất, hư hỏng các đệm lót hoặc rãnh trượt không? / Are pads missing, damaged, or are sliding grooves damaged?'},
  { field: 'padsGroovesR', label: '' },
  { field: 'padsGroovesP', label: '' },
  { field: 'padsGroovesA', label: '' },
  { field: 'padsGroovesF', label: '' },
  { field: 'tag', label: 'Tag' },
  { field: 'collection', label: 'Type of Equipment' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
