export const questions = [
  {
    id: 1,
    name: 'wiper',
    question: 'ใบปัดน้ำฝน',
    howto: 'สายตา',
    accept: 'ไม่เสื่อมสภาพ มีน้ำฉีดกระจก',
  },
  {
    id: 2,
    name: 'cone',
    question: 'กรวยจราจร',
    howto: 'สายตา',
    accept: 'สะอาด สะท้อนแสงได้ จำนวนครบถ้วน',
  },
  {
    id: 3.1,
    name: 'sideGuardL',
    question: 'การ์ดด้านข้างซ้าย',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 3.2,
    name: 'sideGuardR',
    question: 'การ์ดด้านข้างขวา',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 4,
    name: 'waterReverse',
    question: 'ถังน้ำสำรอง',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่รั่วซึม',
  },
  {
    id: 5,
    name: 'drum',
    question: 'สภาพโม่',
    howto: 'สายตา',
    accept: 'สะอาด สีไม่ซีด โลโก้อยู่ในสภาพดี',
  },
  {
    id: 6,
    name: 'hydrolic',
    question: 'ปั๊มขับโม่',
    howto: 'สายตา',
    accept: 'ทำงานปกติ',
  },
  {
    id: 7,
    name: 'guardShaft',
    question: 'ฝาครอบเพลา',
    howto: 'สายตา',
    accept: 'มีการ์ดครอบคลุมจุดหมุน',
  },
  {
    id: 8,
    name: 'valve',
    question: 'วาล์วน้ำ',
    howto: 'สายตา',
    accept: 'ไม่รั่วซึม',
  },
  {
    id: 9.1,
    name: 'blade',
    question: 'ใบกวน',
    howto: 'สายตา',
    accept: 'ไม่ล้ม',
  },
  {
    id: 9.2,
    name: 'bladeTear',
    question: 'ใบกวนไม่มีรอยฉีกขาด',
    howto: 'สายตา',
    accept: 'ไม่มีรอยฉีกขาด',
  },
  {
    id: 10,
    name: 'ladder',
    question: 'บันได',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม',
  },
  {
    id: 11,
    name: 'chain',
    question: 'ราว/โซ่กันตก',
    howto: 'สายตา',
    accept: 'แข็งแรง จำนวนครบถ้วน',
  },
  {
    id: 12,
    name: 'chute2',
    question: 'ราง2 ล็อคแน่น',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 13,
    name: 'chute3',
    question: 'ราง3 ล็อคแน่น',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 14,
    name: 'pvcChuteW',
    question: 'ราง PVC',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 15,
    name: 'atena',
    question: 'เสาวัดความสูง',
    howto: 'สายตา',
    accept: 'ตั้งตรง มีความสูงตามที่กำหนด',
  },
  {
    id: 16,
    name: 'chuteHandle',
    question: 'โกร่ง-หูจับราง',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
];

export const detailFields = [
  { field: 'date', label: 'วันที่ Date' },
  { field: 'inspector', label: 'ผู้ตรวจ Inspector' },
  { field: 'inspectionBy', label: 'ตรวจสอบโดย' },
  { field: 'inspectionType', label: 'Inspection Type' },
  { field: 'steering', label: '1.พวงมาลัย *' },
  { field: 'steeringR', label: '' },
  { field: 'horn', label: '2.แตร*' },
  { field: 'hornR', label: '' },
  { field: 'gear', label: '3.เกียร์*' },
  { field: 'gearR', label: '' },
  { field: 'footBrake', label: '4.เบรคเท้า**' },
  { field: 'footBrakeR', label: '' },
  { field: 'handBrake', label: '5.เบรคมือ*' },
  { field: 'handBrakeR', label: '' },
  { field: 'belt', label: '6.เข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'door', label: '7.ประตู' },
  { field: 'doorR', label: '' },
  { field: 'mirror', label: '8.กระจก' },
  { field: 'mirrorR', label: '' },
  { field: 'lamp', label: '9.ไฟหน้าใหม่**' },
  { field: 'lampR', label: '' },
  { field: 'turnLight', label: '10.ไฟเลี้ยว**' },
  { field: 'turnLightR', label: '' },
  { field: 'nut', label: '11.น๊อตล้อ**' },
  { field: 'nutR', label: '' },
  { field: 'frontWheelL', label: '12.ล้อหน้า **ซ้าย' },
  { field: 'frontWheelLR', label: '' },
  { field: 'frontWheelR', label: '12.ล้อหน้า **ขวา' },
  { field: 'frontWheelRR', label: '' },
  { field: 'lub', label: '13.น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม' },
  { field: 'lubR', label: '' },
  { field: 'brakeOil', label: '14.น้ำมันเบรคเพียงพอ/ไม่รั่วซึม' },
  { field: 'brakeOilR', label: '' },
  { field: 'backSound', label: '15.สัญญาณเสียงถอย' },
  { field: 'backSoundR', label: '' },
  { field: 'backLight', label: '16.สัญญาณไฟถอย' },
  { field: 'backLightR', label: '' },
  { field: 'rearLampL', label: '17.ไฟท้าย **ซ้าย' },
  { field: 'rearLampLR', label: '' },
  { field: 'rearLampR', label: '17.ไฟท้าย **ขวา' },
  { field: 'rearLampRR', label: '' },
  { field: 'rearWheelL', label: '18.ล้อหลัง **ซ้าย' },
  { field: 'rearWheelLR', label: '' },
  { field: 'rearWheelR', label: '18.ล้อหลัง **ขวา' },
  { field: 'rearWheelRR', label: '' },
  { field: 'extinguisher', label: '19.ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'pvcChuteD', label: '20.ราง PVC' },
  { field: 'pvcChuteDR', label: '' },
  { field: 'wiper', label: '1.ใบปัดน้ำฝน' },
  { field: 'wiperR', label: '' },
  { field: 'cone', label: '2.กรวยจราจร' },
  { field: 'coneR', label: '' },
  { field: 'sideGuardL', label: '3.การ์ดด้านข้างซ้าย' },
  { field: 'sideGuardLR', label: '' },
  { field: 'sideGuardR', label: '3.การ์ดด้านข้างขวา' },
  { field: 'sideGuardRR', label: '' },
  { field: 'waterReverse', label: '4.ถังน้ำสำรอง' },
  { field: 'waterReverseR', label: '' },
  { field: 'drum', label: '5.สภาพโม่' },
  { field: 'drumR', label: '' },
  { field: 'hydrolic', label: '6.ปั๊มขับโม่' },
  { field: 'hydrolicR', label: '' },
  { field: 'guardShaft', label: '7.ฝาครอบเพลา' },
  { field: 'guardShaftR', label: '' },
  { field: 'valve', label: '8.วาล์วน้ำไม่รั่วซึม' },
  { field: 'valveR', label: '' },
  { field: 'blade', label: '9.ใบกวนไม่ล้ม' },
  { field: 'bladeR', label: '' },
  { field: 'bladeTear', label: '9.ใบกวนไม่มีรอยฉีกขาด' },
  { field: 'bladeTearR', label: '' },
  { field: 'ladder', label: '10.บันได' },
  { field: 'ladderR', label: '' },
  { field: 'chain', label: '11.ราว/โซ่กันตก' },
  { field: 'chainR', label: '' },
  { field: 'chute2', label: '12.ราง2 ล็อคแน่น' },
  { field: 'chute2R', label: '' },
  { field: 'chute3', label: '13.ราง3 ล็อคแน่น' },
  { field: 'chute3R', label: '' },
  { field: 'pvcChuteW', label: '14.ราง PVC' },
  { field: 'pvcChuteWR', label: '' },
  { field: 'atena', label: '15.เสาวัดความสูง' },
  { field: 'atenaR', label: '' },
  { field: 'chuteHandle', label: '16.โกร่ง-หูจับราง' },
  { field: 'chuteHandleR', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
