export const questions = [
  {
    id: 1,
    name: 'physicalCondition',
    question:
      'Physical condition of Fire Extinguisher* (অগ্নি নির্বাপক যন্ত্রের অবস্থা)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: 'সিলিন্ডার ক্ষতএবং ক্ষয় মুক্ত।',
  },
  {
    id: 2,
    name: 'pressureGuage',
    question: 'Pressure Gauge condition* (প্রেসার গেজেরঅবস্থা)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: ' প্রেসার  গেজঠিক আছে এবং সঠিকমান প্রদর্শন করে।',
  },
  {
    id: 3,
    name: 'safetyPin',
    question: 'Safety Pin* (সেফটি পিন)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: ' সেফটিপিন সঠিক এবং কার্যকরঅবস্থায় আছে।',
  },
  {
    id: 4,
    name: 'label',
    question: 'Labeling/ Class (লেবেল/ক্লাস)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept:
      ' অগ্নিনির্বাপক যন্ত্রের ধরন (A, B, C, D, K, AB, CO2, Foam etc.) উল্লেখ করা আছে।',
  },
  {
    id: 5,
    name: 'weight',
    question: 'Gross Weight (মোট ওজন)',
    howto: 'উত্তোলন পরীক্ষা',
    accept: 'পাউডারসহ অগ্নি নির্বাপক যন্ত্রের ভর সঠিক আছে।',
  },
  {
    id: 6,
    name: 'mounting',
    question: 'Mounting (নির্ধারিত স্থানেএবং নির্দিষ্ট উচ্চতায় ঝুলানো)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept:
      'অগ্নি নির্বাপক যন্ত্র নির্ধারিত স্থানেএবং নির্দিষ্ট উচ্চতায় ঝুলানো আছে।',
  },
  {
    id: 7,
    name: 'accessibility',
    question: 'Accessibility (প্রবেশযোগ্যতা)',
    howto: 'বাহ্যিকপরিদর্শন',
    accept: 'অগ্নিনির্বাপক যন্ত্রটি বাধাহীন পৌঁছানো যায় এবং সহজেদেখা যায়।',
  },
  {
    id: 8,
    name: 'usingGuidelines',
    question: 'Usage Guideline (ব্যবহারের নির্দেশিকা)',
    howto: ' বাহ্যিক পরিদর্শন',
    accept:
      'অগ্নিনির্বাপক যন্ত্রটি ব্যবহারের নির্দেশিকা (P.A.S.S) সিলিন্ডারের গায়ে দেওয়া আছে।',
  },
  {
    id: 9,
    name: 'expirationDate',
    question: 'Expiration Date (মেয়াদশেষ হওয়ার তারিখ)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: 'অগ্নিনির্বাপক যন্ত্রের গাঁয়ে মেয়াদ শেষ হওয়ার তারিখদেওয়া আছে।',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'তারিখঃ - Date' },
  { field: 'inspector', label: 'পরিদর্শক - Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'physicalCondition',
    label:
      '1 Physical condition of Fire Extinguisher (অগ্নি নির্বাপক যন্ত্রের অবস্থা)',
  },
  { field: 'physicalConditionR', label: '' },
  { field: 'physicalConditionP', label: '' },
  { field: 'physicalConditionA', label: 'Respond to defect' },
  { field: 'physicalConditionF', label: '' },
  {
    field: 'pressureGuage',
    label: '2 Pressure Gauge condition (প্রেসার গেজের অবস্থা)',
  },
  { field: 'pressureGuageR', label: '' },
  { field: 'pressureGuageP', label: '' },
  { field: 'pressureGuageA', label: 'Respond to defect' },
  { field: 'pressureGuageF', label: '' },
  { field: 'safetyPin', label: '3 Safety Pin (সেফটি পিন)' },
  { field: 'safetyPinR', label: '' },
  { field: 'safetyPinP', label: '' },
  { field: 'safetyPinA', label: 'Respond to defect' },
  { field: 'safetyPinF', label: '' },
  { field: 'label', label: '4 Labeling/ Class (লেবেল/ক্লাস)' },
  { field: 'labelR', label: '' },
  { field: 'labelP', label: '' },
  { field: 'labelA', label: 'Respond to defect' },
  { field: 'labelF', label: '' },
  { field: 'weight', label: '5 Gross Weight (মোট ওজন)' },
  { field: 'weightR', label: '' },
  { field: 'weightP', label: '' },
  { field: 'weightA', label: 'Respond to defect' },
  { field: 'weightF', label: '' },
  {
    field: 'mounting',
    label: '6 Mounting (নির্ধারিত স্থানেএবং নির্দিষ্ট উচ্চতায় ঝুলানো)',
  },
  { field: 'mountingR', label: '' },
  { field: 'mountingP', label: '' },
  { field: 'mountingA', label: 'Respond to defect' },
  { field: 'mountingF', label: '' },
  { field: 'accessibility', label: '7 Accessibility (প্রবেশযোগ্যতা)' },
  { field: 'accessibilityR', label: '' },
  { field: 'accessibilityP', label: '' },
  { field: 'accessibilityA', label: 'Respond to defect' },
  { field: 'accessibilityF', label: '' },
  {
    field: 'usingGuidelines',
    label: '8 Usage Guideline (ব্যবহারের নির্দেশিকা)',
  },
  { field: 'usingGuidelinesR', label: '' },
  { field: 'usingGuidelinesP', label: '' },
  { field: 'usingGuidelinesA', label: 'Respond to defect' },
  { field: 'usingGuidelinesF', label: '' },
  {
    field: 'expirationDate',
    label: '9 Expiration Date (মেয়াদশেষ হওয়ার তারিখ)',
  },
  { field: 'expirationDateR', label: '' },
  { field: 'expirationDateP', label: '' },
  { field: 'expirationDateA', label: 'Respond to defect' },
  { field: 'expirationDateF', label: '' },
  { field: 'remark', label: 'মন্তব্য - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
