export const questions = [
  {
    id: 1,
    name: 'structuralDamage',
    question: 'Cấu trúc hư hỏng',
    howto: 'Kiểm tra cấu trúc hư hỏng do thiên tai, chế chán, xích, chọt, móc.',
    accept: 'Cấu trúc không có hư hỏng.',
  },
  {
    id: 2,
    name: 'hydraulicSystem',
    question: 'Hệ thống thủy lực',
    howto:
      'Kiểm tra giá sống tàu, kết nối, rò rỉ, kết nối, hao mòn, chiều dài trò chuyện.',
    accept: 'Hệ thống thủy lực hoạt động bình thường.',
  },
  {
    id: 3,
    name: 'wheelsTracksTires',
    question: 'Bánh xe, xích, vỏ xe',
    howto: 'Kiểm tra đai ốc vấu, áp suất, độ mòn.',
    accept: 'Bánh xe, xích, vỏ xe không có vấn đề.',
  },
  {
    id: 4,
    name: 'accessories',
    question: 'Phụ kiện',
    howto: 'Kiểm tra gàu, xô cát, chặt, bè, trục quay.',
    accept: 'Phụ kiện hoạt động bình thường.',
  },
  {
    id: 5,
    name: 'fluids',
    question: 'Chất lỏng',
    howto:
      'Kiểm tra mức dầu, dầu thủy lực, nước làm mát, nhiên liệu, ắc quy, nước rửa kính chắn gió. Việc kiểm tra nước làm mát sẽ chỉ được kiểm tra mực nước trong bình nước phụ và không cần mở mắt bình nước phụ cũng như két làm mát.',
    accept: 'Chất lỏng ở mức hợp lý.',
  },
  {
    id: 6,
    name: 'cab',
    question: 'Buồng lái',
    howto:
      'Kiểm tra người ngồi, dây an toàn, cấu trúc báo động an toàn, tuổi thọ của đồ vật, tâm trí, bình cứu hỏa, số, bom nước, tay cầm nước.',
    accept: 'Buồng lái an toàn và hoạt động tốt.',
  },
  {
    id: 7,
    name: 'loadIndicator',
    question: 'Chỉ báo khả năng tải',
    howto: 'Kiểm tra hiển thị, thay thế, vệ sinh và sử dụng.',
    accept: 'Chỉ báo khả năng tải hoạt động bình thường.',
  },
  {
    id: 8,
    name: 'brakeSystem',
    question: 'Hệ thống thắng',
    howto: 'Kiểm tra tay tháng, chân tháng.',
    accept: 'Hệ thống thắng hoạt động bình thường.',
  },
  {
    id: 9,
    name: 'controlSystem',
    question: 'Hệ thống điều khiển',
    howto:
      'Kiểm tra vô lăng, thiết bị cảnh báo, hệ thống thông minh, thiết kế thông minh, làm việc.',
    accept: 'Hệ thống điều khiển hoạt động bình thường.',
  },
  {
    id: 10,
    name: 'warnings',
    question: 'Cảnh báo',
    howto: 'Kiểm tra còi, còi báo động, chuông cảnh báo, đèn cảnh báo.',
    accept: 'Cảnh báo hoạt động bình thường.',
  },
  {
    id: 11,
    name: 'others',
    question: 'Khác',
    howto:
      'Kiểm tra đồng hồ báo thức, bảo vệ tay, bảo vệ hoa, hộp sơ cứu, búa khẩn cấp.',
    accept: 'Các mục khác không có vấn đề.',
  },
];

export const headerFields = [
  { field: 'id', label: 'Mã số thiết bị' },
  { field: 'site', label: 'Site' },
  { field: 'kind', label: 'Loại máy nâng Kind of Lifting' },
  { field: 'area', label: 'Khu vực Area' },
  { field: 'swl', label: 'Tải trọng LV an toàn (SWL) (Ton)' },
  { field: 'operateBy', label: 'Operate By' },
  {
    field: 'latestInspection',
    label: 'Ngày kiểm định gần nhất Latest Inspection 3rd Party',
  },
  {
    field: 'nextInspection',
    label: 'Ngày kiểm định lần tới next Inspection 3rd Party',
  },
  {
    field: 'installDiameter',
    label: 'Đường kính cáp tiêu chuẩn Cable diameter installing (mm)',
  },
  {
    field: 'actualDiameter',
    label: 'Đường kính cáp đo thực tế Cable diameter actual measure (mm)',
  },
  { field: 'tolerance', label: 'Độ sai lệch Tolerance (mm)' },
  { field: 'result', label: 'Kết quả Result' },
  {
    field: 'internalInspector',
    label: 'Người kiểm tra nội bộ Internal Inspector',
  },
  { field: 'remarks', label: 'Ghi chú Remarks' },
  { field: 'owner', label: 'Chủ sở hữu Owner' },
  { field: 'no', label: 'Số No' },
  { field: 'etype', label: 'Loại thiết bị Equipment Type' },
  { field: 'esite', label: 'Trang web Equipment Site' },
  { field: 'place', label: 'Địa điểm Place' },
  { field: 'location', label: 'Vị trí Location' },
  { field: 'type', label: 'Loại Type' },
  { field: 'cableDiameter', label: 'Đường kính cáp Cable Diameter' },
  { field: 'email', label: 'Responsible person' },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'structuralDamage', label: '1. Cấu trúc hư hỏng *' },
  { field: 'structuralDamageR', label: '' },
  { field: 'structuralDamageP', label: '' },
  { field: 'structuralDamageA', label: 'Respond to defect' },
  { field: 'structuralDamageF', label: '' },
  { field: 'hydraulicSystem', label: '2. Hệ thống thủy lực *' },
  { field: 'hydraulicSystemR', label: '' },
  { field: 'hydraulicSystemP', label: '' },
  { field: 'hydraulicSystemA', label: 'Respond to defect' },
  { field: 'hydraulicSystemF', label: '' },
  { field: 'wheelsTracksTires', label: '3. Bánh xe, xích, vỏ xe *' },
  { field: 'wheelsTracksTiresR', label: '' },
  { field: 'wheelsTracksTiresP', label: '' },
  { field: 'wheelsTracksTiresA', label: 'Respond to defect' },
  { field: 'wheelsTracksTiresF', label: '' },
  { field: 'accessories', label: '4. Phụ kiện *' },
  { field: 'accessoriesR', label: '' },
  { field: 'accessoriesP', label: '' },
  { field: 'accessoriesA', label: 'Respond to defect' },
  { field: 'accessoriesF', label: '' },
  { field: 'fluids', label: '5. Chất lỏng *' },
  { field: 'fluidsR', label: '' },
  { field: 'fluidsP', label: '' },
  { field: 'fluidsA', label: 'Respond to defect' },
  { field: 'fluidsF', label: '' },
  { field: 'cab', label: '6. Buồng lái *' },
  { field: 'cabR', label: '' },
  { field: 'cabP', label: '' },
  { field: 'cabA', label: 'Respond to defect' },
  { field: 'cabF', label: '' },
  { field: 'loadIndicator', label: '7. Chỉ báo khả năng tải *' },
  { field: 'loadIndicatorR', label: '' },
  { field: 'loadIndicatorP', label: '' },
  { field: 'loadIndicatorA', label: 'Respond to defect' },
  { field: 'loadIndicatorF', label: '' },
  { field: 'brakeSystem', label: '8. Hệ thống thắng *' },
  { field: 'brakeSystemR', label: '' },
  { field: 'brakeSystemP', label: '' },
  { field: 'brakeSystemA', label: 'Respond to defect' },
  { field: 'brakeSystemF', label: '' },
  { field: 'controlSystem', label: '9. Hệ thống điều khiển *' },
  { field: 'controlSystemR', label: '' },
  { field: 'controlSystemP', label: '' },
  { field: 'controlSystemA', label: 'Respond to defect' },
  { field: 'controlSystemF', label: '' },
  { field: 'warnings', label: '10. Cảnh báo *' },
  { field: 'warningsR', label: '' },
  { field: 'warningsP', label: '' },
  { field: 'warningsA', label: 'Respond to defect' },
  { field: 'warningsF', label: '' },
  { field: 'others', label: '11. Khác *' },
  { field: 'othersR', label: '' },
  { field: 'othersP', label: '' },
  { field: 'othersA', label: 'Respond to defect' },
  { field: 'othersF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
