export const questions = [
  {
    id: 1,
    name: "gps",
    question: "ระบบ GPS ใช้งานได้ปกติ",
    type: "Safety",
    score: 0,
    howto:
      "หน้าจอGPSเปิดติดทุกหน้าจอ\nหน้าจอGPSสามารถทำการกดเข้าและออกงานได้จากหน้าจอที่ของรถ",
    accept: "สภาพอุปกรณ์ใช้งานได้ปกติ",
  },
  {
    id: 2,
    name: "cameraMount",
    question: "ขาตั้งจุดยึด จอแสดงภาพและกล้องมองหน้าใช้งานได้ปกติ",
    type: "Safety",
    score: 0,
    howto:
      "ขายึดไม่แตกหักเสียหายวางอยู่จุดที่ถูกต้อง\nจอภาพและกล้องมองหน้าสามารถติดตั้งได้อยู่ในจุดที่เหมาะสมอย่างแข็งแรงมั่นคง",
    accept: "สภาพอุปกรณ์ใช้งานได้ปกติ",
  },
  {
    id: 3,
    name: "diffLock",
    question: "สวิทย์ดิ๊ฟล๊อค(DL)สภาพพร้อมใช้งาน",
    type: "Safety",
    score: 1,
    howto:
      "ต้องมีระบบดิ๊ฟล๊อค(DL)ทุกคัน\nสตาร์ตแล้วเหยีบเบรคกดสวิทย์ดิ๊ฟล๊อคแล้วสัญญาญไฟแสดงการทำงานให้ผ่าน",
    accept: "สภาพอุปกรณ์ใช้งานได้ปกติ",
  },
  {
    id: 4,
    name: "roofLights",
    question: "ไฟหลังคาสีเขียว 4 ดวง",
    type: "Safety",
    score: 1,
    howto:
      "สภาพส่องสว่างหลอดไฟได้ชัดเจนทุกดวง\nโคมไฟต้องไม่แตกหักจนเสียรูป, โคมไฟต้องสะอาดไม่มีคราบโคลนหรือคอนกรีตเกาะจนทำให้ไม่เห็นแสงไฟ สภาพเนื้อพลาสติกโคมต้องไม่ขุ่นมัว จนทำให้ไม่อาจมองเห็นแสงไฟชัดเจนทุกดวง และไม่แตกร้าว",
    accept: "สภาพอุปกรณ์ใช้งานได้ปกติ",
  },
  {
    id: 5,
    name: "wheelNuts",
    question: "น็อตล้อรถหน้าและล้อหลังครบทุกล้อ",
    type: "Safety",
    score: 1,
    howto:
      "มีน็อตล้อครบทุกล้อ\nน็อตยางหน้าต้องครบ\nยางหลังยอมรับได้แค่ขาด 1 ตัว",
    accept: "สภาพใช้งานได้ปกติ",
  },
  {
    id: 6,
    name: "fireExtinguisher",
    question:
      "ถังดับเพลิงขนาด 15 ปอนด์ 1 ลูก และกรวยยางสะท้อนแสง จำนวน 2 อัน,ไม้หมอนหนุนล้อรถ จำนวน 2 อัน",
    type: "Safety",
    score: 1,
    howto:
      "ถังดับเพลิงต้องมีสลักล๊อค/สายยางต้องไม่แตกลายงา/น้ำยาไม่ตกผนึก/เข็มอยู่ในแทบเขียว\nกรวยจราจรสูง80ซม.มีแถบสะท้อนแสง/สะอาด\nไม้หนุนล้อมีขนาดความกว้างพอดีหน้ายาง/ความสูงถึงแก้มยาง",
    accept: "สภาพได้มาตราฐาน",
  },
  {
    id: 7,
    name: "reflectiveTape",
    question: "แถบสะท้อนแสงรอบรถตามมาตราฐานและเสาวัดความสูงขนาดกับกรวยท้ายโม่",
    type: "Safety",
    score: 1,
    howto:
      "แถบสะท้อน ต้องมีทั้ง 3 ด้าน ด้านหน้า การ์ดข้าง บังโคลน\nหากการ์ดข้างมี 3 แถว ต้องติดสติกเกอร์อย่างน้อย 1 แถบขึ้นไปโดยติดที่แถบด้านบนสุด\nหากไม่ติดแถบสะท้อนแสงสามารถใช้ทับทิมติดตั้งแทนได้โดยต้องติดในรูปแบบเดียวกันกับสติกเกอร์สะท้อนแสง\nเสาวัดความสูงมีความสูงเท่ากับปลายกรวยด้านหลัง",
    accept: "สภาพได้มาตราฐานพร้อมใช้งาน / เสาจะต้องสูงเกินท้ายโม่",
  },
  {
    id: 8,
    name: "seatBelt",
    question: "เข็มขัดนิรภัยสภาพพร้อมใช้งาน",
    type: "Safety",
    score: 2,
    howto:
      "ติดตั้งเข็มขัดนิรภัยแบบล็อก 3 จุด ที่เบาะนั่งคนขับและผู้โดยสารตอนหน้า\nทดสอบการทำงานโดยกระตุกสายเข็มขัดนิรภัย 2-3 รอบแล้ว หากเข็มขัดล็อกแปลว่าทำงานได้ปกติ",
    accept: "สภาพใช้งานได้ปกติและไม่ฉีกขาด",
  },
  {
    id: 9,
    name: "tachometer",
    question: "ไมล์วัดรอบเครื่อง",
    type: "Safety",
    score: 2,
    howto: "สตาร์ตเครื่องยนต์ ตรวจสอบเข็มรอบสถานะต้องทำงานปกติ",
    accept: "เข็มไมล์แสดงรอบเครื่องได้ถูกต้องตามสถานะรอบเครื่องยนต์",
  },
  {
    id: 10,
    name: "wipers",
    question: "ปัดน้ำฝน+พร้อมน้ำฉีดล้างกระจก",
    type: "Safety",
    score: 2,
    howto:
      "มีชุดใบปัดน้ำฝนครบตามรุ่นที่กระจกหน้า และใช้ปัดและฉีดน้ำได้\nใบปัดน้ำฝนต้องใช้ได้ทั้ง 2 ข้าง ปัดได้ข้างเดียว ไม่ผ่าน\nที่ฉีดน้ำต้องใช้ได้ทั้ง 2 ข้าง",
    accept: "ใบปัดน้ำฝน ที่ปัดน้ำฝน ขนาดมาตรฐาน ตรงรุ่น ปัดน้ำสะอาด",
  },
  {
    id: 11,
    name: "steps",
    question:
      "บันใดหน้าขึ้น-ลงซ้าย-ขวา บันใดท้ายโม่ด้านขวาพร้อมคอกและอุปกรณ์กันตก",
    type: "Safety",
    score: 2,
    howto:
      "หัวเก๋งต้องมีบันไดสภาพดีทั้ง 2 ด้าน และบันไดท้ายต้องมีสภาพไม่ บิดเบี้ยว จนผิดรูป พร้อมมีอุปกรณ์กันตก",
    accept: "สามารถเหยียบได้อย่างปลอดภัยและไม่ทำให้เป็นอันตราย",
  },
  {
    id: 12,
    name: "licensePlate",
    question: "ป้ายทะเบียนหน้ารถ/หลังรถ สภาพพร้อมใช้",
    type: "Safety",
    score: 2,
    howto:
      "มีป้ายทะเบียนทั้งหน้า หลัง สภาพป้ายต้องมองเห็นสีและตัวเลขได้ชัดเจนทุกตัวอักษร\nกรณีสีซีดจากเหลือง เป็น ขาว ไม่ผ่าน\nกรณีชำรุด แต่มีหลักฐานเป็นเอกสารว่ากำลังแก้ไข ถือว่าผ่าน",
    accept: "สภาพสีป้ายถูกต้องตามที่จดทะเบียนสามารถมองเห็นเลขทะเบียนได้ชัดเจน",
  },
  {
    id: 13,
    name: "battery",
    question: "ชุดแบตเตอร์รี่สภาพสมบูรณ์ได้มาตราฐาน",
    type: "Safety",
    score: 2,
    howto:
      "แบตเตอร์รี่ต้องมีสภาพสมบูรณ์มีฝาปิดช่องน้ำกลั่นและขั้วแบตครบทุกจุด พร้อมฝาครอบแบตพลาสติกขนาดครอบคลุมแบตแตอรี่ได้ทั้งลูกเป็นอย่างน้อยที่มีตัวล็อกใช้งานได้ ไม่มีขี้เกลือบริเวณขั้วแบต\nฝาครอบเป็นพลาสติกรูปทรงอื่นได้ ให้สามารถคลุมปิดมิดชิด ไม่ใช้ผ้าใบคลุม",
    accept:
      "ฝาแบตสามารถป้องกันน้ำเข้าแบตเตอรรี่ได้อย่างดีและเป็นระเบียบเรียบร้อย",
  },
  {
    id: 14,
    name: "brakeLights",
    question:
      "สัญญานไฟเบรคหลังซ้าย-ขวา , สัญญานไฟถอยพร้อมเสียง , สัญญานไฟส่องป้าย",
    type: "Safety",
    score: 2,
    howto:
      "สภาพไฟแสงสว่างติดทุกดวง  โคมไฟต้องสะอาดและไม่หม่อง เห็นแสงไฟชัดเจนทุกดวง",
    accept: "ไฟติดชัดเจนทุกดวง",
  },
  {
    id: 15,
    name: "lockSystem",
    question: "โกร่ง-หูจับราง/รางท้ายโม่/ราง3/รางPVC 4 เมตร พร้อมระบบล็อค",
    type: "Safety",
    score: 2,
    howto:
      "ตรวจอุปกรณ์ต่าง ๆ ต้องมีครบและไม่ชำรุด\nอุปกรณ์ทุกตัวมีตัวยึดติดล็อกอย่างปลอดภัย",
    accept: "สภาพใช้งานได้ปกติ\nตัวล็อกใช้งานได้",
  },
  {
    id: 16,
    name: "rollerCovers",
    question: "ฝาคลอบโลเลอร์รับโม่ซ้าย-ขวา , ฝาคลอบเพลาปั่นโม่",
    type: "Safety",
    score: 2,
    howto:
      "ฝาคลอบโลเลอร์รับโม่ซ้าย-ขวาต้องมีครบและปิดมิชิด\nฝาคลอบเพลาปั่นโม่ต้องมีครบและปิดมิดชิด",
    accept:
      "มีการ์ดและฝาคลอบโลเลอร์และเพลาปั่นโม่ครบ\nไม่หักหรือชำรุดหรือและไม่บิดเบียว",
  },
  {
    id: 17,
    name: "mudFlaps",
    question: "ยางกันฝุ่นหลังซ้าย-ขวา สูงกว่าพื้นระหว่าง 20-30 เซนติดเมตร",
    type: "Safety",
    score: 2,
    howto:
      "ยางกันฝุ่นหน้าและด้านหลังซ้ายขวา ต้องมีและสูงจากพื้นระหว่าง 20-30 เซนติเมตรและไม่ล้นออกจากซุ้มบังโคลนรถ\nติดตั้งยางกันฝุ่นเฉพาะที่ซุ้มล้อยางคู่หน้าและซุ้มล้อยางคู่หลังสุดเท่านั้น",
    accept: "มีสภาพใช้งานได้และติดตั้งในจุดที่กำหนด",
  },
  {
    id: 18,
    name: "handBrake",
    question: "เบรกมือ",
    type: "Safety",
    score: 3,
    howto: "ทำการดึงเบรกมือแล้วเข้าเกียร์1 แล้วปล่อยต้องดับ",
    accept: "สภาพใช้งานได้ปกติและรถขนส่งไม่ไหลขณะใช้เบรกมือ",
  },
  {
    id: 19,
    name: "insurance",
    question: "ประกันภัย/พรบ./ป้ายวงกลม",
    type: "Safety",
    score: 3,
    howto:
      "เอกสารไม่หมดอายุ\nตรวจเฉพาะป้ายภาษีติดรถ ส่วน พรบ. และ ประกัน ให้ส่งตามทีหลัง",
    accept: "เอกสารป้ายภาษีต้องไม่หมดอายุ",
  },
  {
    id: 20,
    name: "windows",
    question: "กระจกบังลมหน้า กระจกประตูซ้าย-ขวา กระจกมองข้างและกระจกมองกันชน",
    type: "Safety",
    score: 3,
    howto: "สภาพกระจกไม่แตกร้าวและมองเห็นได้ชัดเจน",
    accept: "สภาพใช้งานได้ปกติและไม่แตกร้าว",
  },
  {
    id: 21,
    name: "headlights",
    question: "ไฟแสงสว่างหน้ารถซ้าย-ขวา",
    type: "Safety",
    score: 3,
    howto:
      "สภาพส่องสว่างแสงไฟได้ชัดเจนทุกดวง โคมไฟต้องไม่แตกหักจนเสียรูป\nโคมไฟต้องสะอาดไม่มีคราบโคลนหรือคอนกรีตเกาะจนทำให้ไม่เห็นแสงไฟ\nสภาพเนื้อพลาสติกโคมต้องไม่ขุ่นมัว\nมองเห็นแสงไฟชัดเจนทุกดวง และไม่แตกร้าว",
    accept: "สภาพใช้งานได้และสัญญาณไฟติดทุกดวง",
  },
  {
    id: 22,
    name: "turnSignals",
    question: "สัญญาณไฟเลี้ยว-ไฟหรี่หน้าหลังซ้าย-ขวา และไฟฉุกเฉิน",
    type: "Safety",
    score: 3,
    howto:
      "สภาพส่องสว่างแสงไฟได้ชัดเจนทุกดวง โคมไฟต้องไม่แตกหักจนเสียรูป\nโคมไฟต้องสะอาดไม่มีคราบโคลนหรือคอนกรีตเกาะจนทำให้ไม่เห็นแสงไฟ\nสภาพเนื้อพลาสติกโคมต้องไม่ขุ่นมัว\nมองเห็นแสงไฟชัดเจนทุกดวง และไม่แตกร้าว",
    accept: "สภาพใช้งานได้และสัญญาณไฟติดทุกดวง",
  },
  {
    id: 23,
    name: "brakeSystem",
    question: "ตรวจสอบระบบเบรกหลักและระบบลมทีใช้ในการเบรกต้องลดไม่เกิน 2 ปอนด์",
    type: "Safety",
    score: 3,
    howto: "ทดสอบเหยียบเบรคยาว 4 ครั้งลมต้องไม่ลดลงเกิน 2 ปอนด์",
    accept: "ระบบเบรกทำงานและรถไม่เคลื่อนตัว\nระบบลมต้องลดลงไม่เกิน2ปอนด์",
  },
  {
    id: 24,
    name: "airDrain",
    question: "ระบบระบายน้ำในถังลมต้องพร้อมใช้งาน",
    type: "Safety",
    score: 3,
    howto:
      "ทำการดึงน้ำในถังลมและทำการเดรนน้ำในถังลมให้หมด\nตรวจสอบการเดรนน้ำถังพักลมทุกถัง",
    accept: "ไม่มีน้ำในถังลม\nที่เดรนน้ำใช้งานได้ปกติ",
  },
  {
    id: 25,
    name: "lowPressureWarning",
    question: "ระบบเบรกเมื่อแรงดันลมต่ำต้องมีสัญญาญเสียงหรือสัญลักษณ์ไฟเตือน",
    type: "Safety",
    score: 3,
    howto:
      "ทำการทดสอบระบบแรงดันลมในถังลมโดยการเหยียบเบรกพร้อมดับเครื่อง\nเมื่อลมต่ำกว่า 5 ปอนด์ จะมีเสียงหรือเสียงเตือนหรือสัญลักษณ์ไฟเตือนลมต่ำ",
    accept: "มีเสียงหรือมีสัญลักษณ์ไฟเตือน",
  },
  {
    id: 26,
    name: "motorcycleGuard",
    question: "โครงเซฟการ์ดกันมอเตอร์ไซด์ , ห่วงคล้องเพลากลาง",
    type: "Safety",
    score: 3,
    howto:
      "ความสูงจากพื้นของการ์ดกันมอเตอร์ไซร์อยู่ระหว่าง50-60 ซม.\nการ์ดกันมอเตอร์ไซต์จะต้องไม่บิดเบี้ยวผิดรอบ\nมีโซ่หรือห่วงเหล็กคล้องเพลากลางแน่นหนา",
    accept:
      "สภาพการ์ดไม่บิดเบี้ยวและสูงอยู่ระหว่าง50-60 ซม.\nสภาพของโซ่หรือห่วงมีและใช้งานได้ตามปกติ",
  },
  {
    id: 27,
    name: "ppe",
    question: "อุปกรณ์ PPE ของพนักงานจัดส่ง",
    type: "Safety",
    score: 3,
    howto:
      "พนักงานสวม หมวก เสื้อฟอร์ม รองเท้าเซฟตี้ เรียบร้อย หมวกต้องใช้งานได้\nเนื้อพลาสติกยังไม่หมดอายุ/รองเท้าเซฟตี๋ไม่ฉีกขาดหรือเปื่อยยุ่ย/เสื้อแบบฟอร์มบริษัท สีไม่ซีดจนผิดจากแบบมาตรฐาน\nหากเป็นพนักงานใหม่ อนุญาติให้เป็นยูนิฟอร์มของนกที่เป็นเสื้อยืดแขนยาว ใส่เสื้อสะท้อนแสงแทนเท่านั้น",
    accept: "ชุดอุปกรณ์ PPE พนักงานจัดส่งต้องมีครบและไม่ขาดหรือซีดจากปกติ",
  },
  {
    id: 28,
    name: "frontTires",
    question:
      "ยางคู่หน้าดอกสร้อยไม่หล่อดอก ยางชุดหลังสภาพพร้อมใช้งาน ดอกยางต้องเหลือไม่น้อยกว่า 2 มม.",
    type: "Safety",
    score: 5,
    howto:
      "ตรวจร่องลึกของยางต้องไม่น้อยกว่า 2 มม.\nรอยบาดของแก้มยางไม่ลึกเกิน 2 มม.",
    accept: "ดอกยางเหลือไม่น้อยกว่า 2 มม.",
  },
  {
    id: 29,
    name: "frontNumber",
    question:
      "ติดหมายเลขหน้าสีน้ำเงินซ้าย-ขวา ขนาด หนา 2 ซม.* สูง 12.5 ซม.* กว้าง 10 ซม. หลังสีน้ำเงิน ขนาด หนา 3 ซม.* สูง 21 ซม.* กว้าง 15 ซม.",
    type: "branding",
    score: 2,
    howto:
      "มีหมายเลขรถตรงตามแบบ และติดตั้งครบทุกจุดโดยตัวอักษรจะต้องสีไม่ซีดจางมองเห็นได้ชัดเจนทุกตัวอักษร",
    accept: "ติดตั้งในจุดที่กำหนดตามแบบและต้องได้ขนาดตามมาตราฐาน",
  },
  {
    id: 30,
    name: "logo",
    question:
      "ติดโลโก้อินทรีคอนกรีตภาษาอังกฤษ ขนาด 23X50 ซม.พร้อมแถบสีแดง ที่ประตูหน้าซ้าย-ขวาขนาดกว้าง32ซม.ยาวจากหัวจรดท้าย",
    type: "branding",
    score: 5,
    howto:
      "มีโลโก้อินทรีและสติกเกอร์ด้านข้างครบถ้วนไม่ฉีกขาด\nตรงตามแบบทั้ง 2 ข้าง และสภาพสีต้องไม่ซีดจาง",
    accept: "สภาพสีต้องเป็นเนื้อสีเดียวกันและไม่ซีด",
  },
  {
    id: 31,
    name: "cabinCleanliness",
    question: "ความสะอาดในห้องโดยสารและทัศนวิสัยในการมองเห็น",
    type: "branding",
    score: 5,
    howto:
      "ไม่มีกองเศษขยะอยู่ตามพื้นหรือเบาะนั่งภายในหัวเก๋ง\nไม่มีวัสดุหรือเครื่องมือวางโดยไม่ได้ยึดติด(ยึดด้วยน็อตหรือกาว)อยู่ตามคอนแผงคอนโซลหรือจุด\nอื่นๆที่ไม่ใช่ช่องเก็บของ อันจะส่งผมให้ของกระเด็นมาขัดขวางการขับขี่\nเบาะนั่งและแผงประตูอยู่ในสภาพดีไม่ฉีกขาดหรือฟองน้ำยุบตัวจนผิดรูปส่งผลต่อการขับขี่\nห้ามติดตั้งผ้าม่านภายในหัวเก๋ง\nความเข้มของทางฟิล์มกรองแสงต้องไม่เกิน60%ของเบอร์ฟิล์มกรองแสง\nห้ามติดตั้งสติกเกอร์ใดๆ บริเวณกระจกรอบคันยกเว้นสติกเกอร์เบรนดิ้งของอินทรีเท่านั้น",
    accept:
      "สภาพเบาะและแผงประตูสมบูรณ์\nสามารถมีถังขยะภายในหัวเก๋งได้แต่ต้องทำการยึดติดมั่นคง\nสติกเกอร์ที่ติดรถต้องเป็นแบบที่อินทรีกำหนดเท่านั้น และเบอร์ฟิล์มความเข้มต้องไม่เกิน60%",
  },
  {
    id: 32,
    name: "vehicleCleanliness",
    question: "ความสะอาดรอบตัวรถโม่คอนกรีต",
    type: "branding",
    score: 7,
    howto:
      "บริเวณโดยรอบตัวรถมีการจัดเก็บอุปกรณ์ต่าง ๆ เป็นระเบียบเรียบร้อย ไม่มีการนำวัสดุต่างๆ เช่น ขวดน้ำยาฯ รองเท้า ไม้ถูพื้นอุปกรณ์ทำความสะอาด มาแนบหรือเสียบไว้ตามจุดต่างๆ ของตัวรถ\nชิ้นส่วนต่างๆ ของรถโม่ต้องไม่มีเศษคราบคอนกรีตติดฝังอยู่เกินกว่า20%ของชิ้นส่วนนั้นๆ",
    accept:
      "ไม่มีอุปกรณ์ที่ไม่เกี่ยวข้องเหน็บหรือเสียบอยู่ด้านตัวรถ\nคราบคอนกรีตฝังอยู่ที่แต่ละชิ้นส่วนไม่เกิน20%",
  },
  {
    id: 33,
    name: "mixerCondition",
    question: "คุณภาพตัวโม่และส่วนประกอบควบอื่นๆ อยู่ในสภาพดีพร้อมทำงาน",
    type: "branding",
    score: 7,
    howto:
      "โม่ต้องไม่เป็นสนิมผุกกร่อนจนอาจทำให้โม่ทะลุลูกโม่ต้องกลมตามแบบไม่บุบ บิดเบี้ยวผิดรูป\nตัวโม่ต้องทำการปั่นให้ได้ 12-14 รอบต่อนาที\nถังน้ำต้องบรรจุน้ำได้ตามขนาดของถังน้ำและไม่รั่วซึม\nคันโยกต้องสามารถบังคับโม่ได้",
    accept: "สภาพต้องอยู่ในสภาพดีไม่มีคอนกรีตรั่วออกมาด้านนอก",
  },
  {
    id: 34,
    name: "logoAndColor",
    question: "โลโก้และสีรถถูกต้องตามแบบมาตรฐานที่กำหนด",
    type: "branding",
    score: 7,
    howto:
      "ตราสัญลักษณ์อินทรีที่บริเวณลูกโม่และหัวเก๋งถูกต้องตรงตามแบบในสัญญาขนส่งทั้งขนาดและหมายเลขสีถูกต้องตามที่ี่กำหนด\nสภาพสีทั้งที่ตราสัญลักษณ์และสีพื้นจะต้องไม่ซีดจาง, หลุดร่อน, หมองคล้ำ (เช่นสีขาวเก่าจนกลายเป็นสีเหลืองหรือน้ำตาล สีแดงจนกลายเป็นสีคล้ำดำ)กลายเป็นสีเหลืองหรือน้ำตาล สีแดงจนกลายเป็นสีคล้ำดำ)",
    accept: "ตราสัญลักษณ์อินทรีถูกต้อง",
  },
  {
    id: 35,
    name: "overallColorCondition",
    question:
      "สภาพสีโดยรวมทั้งคันรถ อยู่ในสภาพดีเหมาะสมในการเป็นตัวแทนภาพลักษณ์ที่ดีของแบรนด์อินทรี",
    type: "branding",
    score: 7,
    howto:
      "สภาพสีรถโดยร่วมอยู่ในสภาพดีทั้งคันรถรวมไปถึงวัสดุอุปกรณ์รถบริเวณที่ทำสี เช่น บังโคลน รางเทคอนกรีต กรวย Hopper จะต้องไม่บุบเบี่ยวผิดรูป\nในแต่ละด้านของตัวรถ(ซ้าย ขวา หน้า หลัง) ต้องไม่มีคราบหรือรอยสนิมเกินกว่า 20% ของพื้นที่แต่ละด้าน",
    accept: "สภาพโลโก้ไม่ซีดจางและสภาพดีถูกตามแบบที่กำหนดของอินทรี",
  },
];

export const detailFields = [
  { field: "id", label: "ID" },
  { field: "date", label: "วันที่ - Date" },
  { field: "email", label: "ผู้รับผิดชอบ - Responsible person" },
  { field: "inspector", label: "ผู้ตรวจสอบ - Inspector" },
  { field: "type", label: "ประเภทการตรวจ" },
  { field: "responder", label: "Responder" },
  { field: "steering", label: "1.พวงมาลัย *" },
  { field: "steeringR", label: "" },
  { field: "steeringP", label: "" },
  { field: "steeringA", label: "Respond to defect" },
  { field: "steeringF", label: "" },
  { field: "horn", label: "2.แตร*" },
  { field: "hornR", label: "" },
  { field: "hornP", label: "" },
  { field: "hornA", label: "Respond to defect" },
  { field: "hornF", label: "" },
  { field: "gear", label: "3.เกียร์*" },
  { field: "gearR", label: "" },
  { field: "gearP", label: "" },
  { field: "gearA", label: "Respond to defect" },
  { field: "gearF", label: "" },
  { field: "footBrake", label: "4.เบรคเท้า**" },
  { field: "footBrakeR", label: "" },
  { field: "footBrakeP", label: "" },
  { field: "footBrakeA", label: "Respond to defect" },
  { field: "footBrakeF", label: "" },
  { field: "handBrake", label: "5.เบรคมือ*" },
  { field: "handBrakeR", label: "" },
  { field: "handBrakeP", label: "" },
  { field: "handBrakeA", label: "Respond to defect" },
  { field: "handBrakeF", label: "" },
  { field: "belt", label: "6.เข็มขัดนิรภัย" },
  { field: "beltR", label: "" },
  { field: "beltP", label: "" },
  { field: "beltA", label: "Respond to defect" },
  { field: "beltF", label: "" },
  { field: "door", label: "7.ประตู" },
  { field: "doorR", label: "" },
  { field: "doorP", label: "" },
  { field: "doorA", label: "Respond to defect" },
  { field: "doorF", label: "" },
  { field: "mirrorL", label: "8.1 กระจกซ้าย" },
  { field: "mirrorLR", label: "" },
  { field: "mirrorLP", label: "" },
  { field: "mirrorLA", label: "Respond to defect" },
  { field: "mirrorLF", label: "" },
  { field: "mirrorR", label: "8.2 กระจกขวา" },
  { field: "mirrorRR", label: "" },
  { field: "mirrorRP", label: "" },
  { field: "mirrorRA", label: "Respond to defect" },
  { field: "mirrorRF", label: "" },
  { field: "lampL", label: "9.1 ไฟหน้าซ้าย**" },
  { field: "lampLR", label: "" },
  { field: "lampLP", label: "" },
  { field: "lampLA", label: "Respond to defect" },
  { field: "lampLF", label: "" },
  { field: "lampR", label: "9.2 ไฟหน้าขวา**" },
  { field: "lampRR", label: "" },
  { field: "lampRP", label: "" },
  { field: "lampRA", label: "Respond to defect" },
  { field: "lampRF", label: "" },
  { field: "turnLightL", label: "10.1 ไฟเลี้ยวซ้าย**" },
  { field: "turnLightLR", label: "" },
  { field: "turnLightLP", label: "" },
  { field: "turnLightLA", label: "Respond to defect" },
  { field: "turnLightLF", label: "" },
  { field: "turnLightR", label: "10.2 ไฟเลี้ยวขวา**" },
  { field: "turnLightRR", label: "" },
  { field: "turnLightRP", label: "" },
  { field: "turnLightRA", label: "Respond to defect" },
  { field: "turnLightRF", label: "" },
  { field: "nut", label: "11.น๊อตล้อ**" },
  { field: "nutR", label: "" },
  { field: "nutP", label: "" },
  { field: "nutA", label: "Respond to defect" },
  { field: "nutF", label: "" },
  { field: "frontWheelL", label: "12.1 ล้อหน้า **ซ้าย" },
  { field: "frontWheelLR", label: "" },
  { field: "frontWheelLP", label: "" },
  { field: "frontWheelLA", label: "Respond to defect" },
  { field: "frontWheelLF", label: "" },
  { field: "frontWheelR", label: "12.2 ล้อหน้า **ขวา" },
  { field: "frontWheelRR", label: "" },
  { field: "frontWheelRP", label: "" },
  { field: "frontWheelRA", label: "Respond to defect" },
  { field: "frontWheelRF", label: "" },
  { field: "lub", label: "13.น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม" },
  { field: "lubR", label: "" },
  { field: "lubP", label: "" },
  { field: "lubA", label: "Respond to defect" },
  { field: "lubF", label: "" },
  { field: "brakeOil", label: "14.น้ำมันเบรคเพียงพอ/ไม่รั่วซึม" },
  { field: "brakeOilR", label: "" },
  { field: "brakeOilP", label: "" },
  { field: "brakeOilA", label: "Respond to defect" },
  { field: "brakeOilF", label: "" },
  { field: "backSound", label: "15.สัญญาณเสียงถอย" },
  { field: "backSoundR", label: "" },
  { field: "backSoundP", label: "" },
  { field: "backSoundA", label: "Respond to defect" },
  { field: "backSoundF", label: "" },
  { field: "backLight", label: "16.สัญญาณไฟถอย" },
  { field: "backLightR", label: "" },
  { field: "backLightP", label: "" },
  { field: "backLightA", label: "Respond to defect" },
  { field: "backLightF", label: "" },
  { field: "rearLampL", label: "17.1 ไฟท้าย **ซ้าย" },
  { field: "rearLampLR", label: "" },
  { field: "rearLampLP", label: "" },
  { field: "rearLampLA", label: "Respond to defect" },
  { field: "rearLampLF", label: "" },
  { field: "rearLampR", label: "17.2 ไฟท้าย **ขวา" },
  { field: "rearLampRR", label: "" },
  { field: "rearLampRP", label: "" },
  { field: "rearLampRA", label: "Respond to defect" },
  { field: "rearLampRF", label: "" },
  { field: "rearWheelL", label: "18.1 ล้อหลัง **ซ้าย" },
  { field: "rearWheelLR", label: "" },
  { field: "rearWheelLP", label: "" },
  { field: "rearWheelLA", label: "Respond to defect" },
  { field: "rearWheelLF", label: "" },
  { field: "rearWheelR", label: "18.2 ล้อหลัง **ขวา" },
  { field: "rearWheelRR", label: "" },
  { field: "rearWheelRP", label: "" },
  { field: "rearWheelRA", label: "Respond to defect" },
  { field: "rearWheelRF", label: "" },
  { field: "extinguisher", label: "19.ถังดับเพลิง" },
  { field: "extinguisherR", label: "" },
  { field: "extinguisherP", label: "" },
  { field: "extinguisherA", label: "Respond to defect" },
  { field: "extinguisherF", label: "" },
  { field: "pvcChuteD", label: "20.ราง PVC" },
  { field: "pvcChuteDR", label: "" },
  { field: "pvcChuteDP", label: "" },
  { field: "pvcChuteDA", label: "Respond to defect" },
  { field: "pvcChuteDF", label: "" },
  //weekly
  { field: "wiper", label: "1.ใบปัดน้ำฝน" },
  { field: "wiperR", label: "" },
  { field: "wiperP", label: "" },
  { field: "wiperA", label: "Respond to defect" },
  { field: "wiperF", label: "" },
  { field: "cone", label: "2.กรวยจราจร" },
  { field: "coneR", label: "" },
  { field: "coneP", label: "" },
  { field: "coneA", label: "Respond to defect" },
  { field: "coneF", label: "" },
  { field: "sideGuardL", label: "3.1 การ์ดด้านข้างซ้าย" },
  { field: "sideGuardLR", label: "" },
  { field: "sideGuardLP", label: "" },
  { field: "sideGuardLA", label: "Respond to defect" },
  { field: "sideGuardLF", label: "" },
  { field: "sideGuardR", label: "3.2 การ์ดด้านข้างขวา" },
  { field: "sideGuardRR", label: "" },
  { field: "sideGuardRP", label: "" },
  { field: "sideGuardRA", label: "Respond to defect" },
  { field: "sideGuardRF", label: "" },
  { field: "waterReverse", label: "4.ถังน้ำสำรอง" },
  { field: "waterReverseR", label: "" },
  { field: "waterReverseP", label: "" },
  { field: "waterReverseA", label: "Respond to defect" },
  { field: "waterReverseF", label: "" },
  { field: "drum", label: "5.สภาพโม่" },
  { field: "drumR", label: "" },
  { field: "drumP", label: "" },
  { field: "drumA", label: "Respond to defect" },
  { field: "drumF", label: "" },
  { field: "hydrolic", label: "6.ปั๊มขับโม่" },
  { field: "hydrolicR", label: "" },
  { field: "hydrolicP", label: "" },
  { field: "hydrolicA", label: "Respond to defect" },
  { field: "hydrolicF", label: "" },
  { field: "guardShaft", label: "7.ฝาครอบเพลา" },
  { field: "guardShaftR", label: "" },
  { field: "guardShaftP", label: "" },
  { field: "guardShaftA", label: "Respond to defect" },
  { field: "guardShaftF", label: "" },
  { field: "valve", label: "8.วาล์วน้ำไม่รั่วซึม" },
  { field: "valveR", label: "" },
  { field: "valveP", label: "" },
  { field: "valveA", label: "Respond to defect" },
  { field: "valveF", label: "" },
  { field: "blade", label: "9.1 ใบกวนไม่ล้ม" },
  { field: "bladeR", label: "" },
  { field: "bladeP", label: "" },
  { field: "bladeA", label: "Respond to defect" },
  { field: "bladeF", label: "" },
  { field: "bladeTear", label: "9.2 ใบกวนไม่มีรอยฉีกขาด" },
  { field: "bladeTearR", label: "" },
  { field: "bladeTearP", label: "" },
  { field: "bladeTearA", label: "Respond to defect" },
  { field: "bladeTearF", label: "" },
  { field: "ladder", label: "10.บันได" },
  { field: "ladderR", label: "" },
  { field: "ladderP", label: "" },
  { field: "ladderA", label: "Respond to defect" },
  { field: "ladderF", label: "" },
  { field: "chain", label: "11.ราว/โซ่กันตก" },
  { field: "chainR", label: "" },
  { field: "chainP", label: "" },
  { field: "chainA", label: "Respond to defect" },
  { field: "chainF", label: "" },
  { field: "chute2", label: "12.ราง2 ล็อคแน่น" },
  { field: "chute2R", label: "" },
  { field: "chute2P", label: "" },
  { field: "chute2A", label: "Respond to defect" },
  { field: "chute2F", label: "" },
  { field: "chute3", label: "13.ราง3 ล็อคแน่น" },
  { field: "chute3R", label: "" },
  { field: "chute3P", label: "" },
  { field: "chute3A", label: "Respond to defect" },
  { field: "chute3F", label: "" },
  { field: "pvcChuteW", label: "14.ราง PVC" },
  { field: "pvcChuteWR", label: "" },
  { field: "pvcChuteWP", label: "" },
  { field: "pvcChuteWA", label: "Respond to defect" },
  { field: "pvcChuteWF", label: "" },
  { field: "atena", label: "15.เสาวัดความสูง" },
  { field: "atenaR", label: "" },
  { field: "atenaP", label: "" },
  { field: "atenaA", label: "Respond to defect" },
  { field: "atenaF", label: "" },
  { field: "chuteHandle", label: "16.โกร่ง-หูจับราง" },
  { field: "chuteHandleR", label: "" },
  { field: "chuteHandleP", label: "" },
  { field: "chuteHandleA", label: "Respond to defect" },
  { field: "chuteHandleF", label: "" },
  //Driver trainer
  { field: "gps", label: "1. ระบบ GPS ใช้งานได้ปกติ" },
  { field: "gpsR", label: "" },
  { field: "gpsP", label: "" },
  { field: "gpsA", label: "Respond to defect" },
  { field: "gpsF", label: "" },
  {
    field: "cameraMount",
    label: "2. ขาตั้งจุดยึด จอแสดงภาพและกล้องมองหน้าใช้งานได้ปกติ",
  },
  { field: "cameraMountR", label: "" },
  { field: "cameraMountP", label: "" },
  { field: "cameraMountA", label: "Respond to defect" },
  { field: "cameraMountF", label: "" },
  { field: "diffLock", label: "3. สวิทย์ดิ๊ฟล๊อค(DL)สภาพพร้อมใช้งาน" },
  { field: "diffLockR", label: "" },
  { field: "diffLockP", label: "" },
  { field: "diffLockA", label: "Respond to defect" },
  { field: "diffLockF", label: "" },
  { field: "roofLights", label: "4. ไฟหลังคาสีเขียว 4 ดวง" },
  { field: "roofLightsR", label: "" },
  { field: "roofLightsP", label: "" },
  { field: "roofLightsA", label: "Respond to defect" },
  { field: "roofLightsF", label: "" },
  { field: "wheelNuts", label: "5. น็อตล้อรถหน้าและล้อหลังครบทุกล้อ" },
  { field: "wheelNutsR", label: "" },
  { field: "wheelNutsP", label: "" },
  { field: "wheelNutsA", label: "Respond to defect" },
  { field: "wheelNutsF", label: "" },
  {
    field: "fireExtinguisher",
    label:
      "6. ถังดับเพลิงขนาด 15 ปอนด์ 1 ลูก และกรวยยางสะท้อนแสง จำนวน 2 อัน,ไม้หมอนหนุนล้อรถ จำนวน 2 อัน",
  },
  { field: "fireExtinguisherR", label: "" },
  { field: "fireExtinguisherP", label: "" },
  { field: "fireExtinguisherA", label: "Respond to defect" },
  { field: "fireExtinguisherF", label: "" },
  {
    field: "reflectiveTape",
    label: "7. แถบสะท้อนแสงรอบรถตามมาตราฐานและเสาวัดความสูงขนาดกับกรวยท้ายโม่",
  },
  { field: "reflectiveTapeR", label: "" },
  { field: "reflectiveTapeP", label: "" },
  { field: "reflectiveTapeA", label: "Respond to defect" },
  { field: "reflectiveTapeF", label: "" },
  { field: "seatBelt", label: "8. เข็มขัดนิรภัยสภาพพร้อมใช้งาน" },
  { field: "seatBeltR", label: "" },
  { field: "seatBeltP", label: "" },
  { field: "seatBeltA", label: "Respond to defect" },
  { field: "seatBeltF", label: "" },
  { field: "tachometer", label: "9. ไมล์วัดรอบเครื่อง" },
  { field: "tachometerR", label: "" },
  { field: "tachometerP", label: "" },
  { field: "tachometerA", label: "Respond to defect" },
  { field: "tachometerF", label: "" },
  { field: "wipers", label: "10. ปัดน้ำฝน+พร้อมน้ำฉีดล้างกระจก" },
  { field: "wipersR", label: "" },
  { field: "wipersP", label: "" },
  { field: "wipersA", label: "Respond to defect" },
  { field: "wipersF", label: "" },
  {
    field: "steps",
    label:
      "11. บันใดหน้าขึ้น-ลงซ้าย-ขวา บันใดท้ายโม่ด้านขวาพร้อมคอกและอุปกรณ์กันตก",
  },
  { field: "stepsR", label: "" },
  { field: "stepsP", label: "" },
  { field: "stepsA", label: "Respond to defect" },
  { field: "stepsF", label: "" },
  { field: "licensePlate", label: "12. ป้ายทะเบียนหน้ารถ/หลังรถ สภาพพร้อมใช้" },
  { field: "licensePlateR", label: "" },
  { field: "licensePlateP", label: "" },
  { field: "licensePlateA", label: "Respond to defect" },
  { field: "licensePlateF", label: "" },
  { field: "battery", label: "13. ชุดแบตเตอร์รี่สภาพสมบูรณ์ได้มาตราฐาน" },
  { field: "batteryR", label: "" },
  { field: "batteryP", label: "" },
  { field: "batteryA", label: "Respond to defect" },
  { field: "batteryF", label: "" },
  {
    field: "brakeLights",
    label:
      "14. สัญญานไฟเบรคหลังซ้าย-ขวา , สัญญานไฟถอยพร้อมเสียง , สัญญานไฟส่องป้าย",
  },
  { field: "brakeLightsR", label: "" },
  { field: "brakeLightsP", label: "" },
  { field: "brakeLightsA", label: "Respond to defect" },
  { field: "brakeLightsF", label: "" },
  {
    field: "lockSystem",
    label: "15. โกร่ง-หูจับราง/รางท้ายโม่/ราง3/รางPVC 4 เมตร พร้อมระบบล็อค",
  },
  { field: "lockSystemR", label: "" },
  { field: "lockSystemP", label: "" },
  { field: "lockSystemA", label: "Respond to defect" },
  { field: "lockSystemF", label: "" },
  {
    field: "rollerCovers",
    label: "16. ฝาคลอบโลเลอร์รับโม่ซ้าย-ขวา , ฝาคลอบเพลาปั่นโม่",
  },
  { field: "rollerCoversR", label: "" },
  { field: "rollerCoversP", label: "" },
  { field: "rollerCoversA", label: "Respond to defect" },
  { field: "rollerCoversF", label: "" },
  {
    field: "mudFlaps",
    label: "17. ยางกันฝุ่นหลังซ้าย-ขวา สูงกว่าพื้นระหว่าง 20-30 เซนติดเมตร",
  },
  { field: "mudFlapsR", label: "" },
  { field: "mudFlapsP", label: "" },
  { field: "mudFlapsA", label: "Respond to defect" },
  { field: "mudFlapsF", label: "" },
  { field: "handBrake", label: "18. เบรกมือ" },
  { field: "handBrakeR", label: "" },
  { field: "handBrakeP", label: "" },
  { field: "handBrakeA", label: "Respond to defect" },
  { field: "handBrakeF", label: "" },
  { field: "insurance", label: "19. ประกันภัย/พรบ./ป้ายวงกลม" },
  { field: "insuranceR", label: "" },
  { field: "insuranceP", label: "" },
  { field: "insuranceA", label: "Respond to defect" },
  { field: "insuranceF", label: "" },
  {
    field: "windows",
    label: "20. กระจกบังลมหน้า กระจกประตูซ้าย-ขวา กระจกมองข้างและกระจกมองกันชน",
  },
  { field: "windowsR", label: "" },
  { field: "windowsP", label: "" },
  { field: "windowsA", label: "Respond to defect" },
  { field: "windowsF", label: "" },
  { field: "headlights", label: "21. ไฟแสงสว่างหน้ารถซ้าย-ขวา" },
  { field: "headlightsR", label: "" },
  { field: "headlightsP", label: "" },
  { field: "headlightsA", label: "Respond to defect" },
  { field: "headlightsF", label: "" },
  {
    field: "turnSignals",
    label: "22. สัญญาณไฟเลี้ยว-ไฟหรี่หน้าหลังซ้าย-ขวา และไฟฉุกเฉิน",
  },
  { field: "turnSignalsR", label: "" },
  { field: "turnSignalsP", label: "" },
  { field: "turnSignalsA", label: "Respond to defect" },
  { field: "turnSignalsF", label: "" },
  {
    field: "brakeSystem",
    label:
      "23. ตรวจสอบระบบเบรกหลักและระบบลมทีใช้ในการเบรกต้องลดไม่เกิน 2 ปอนด์",
  },
  { field: "brakeSystemR", label: "" },
  { field: "brakeSystemP", label: "" },
  { field: "brakeSystemA", label: "Respond to defect" },
  { field: "brakeSystemF", label: "" },
  { field: "airDrain", label: "24. ระบบระบายน้ำในถังลมต้องพร้อมใช้งาน" },
  { field: "airDrainR", label: "" },
  { field: "airDrainP", label: "" },
  { field: "airDrainA", label: "Respond to defect" },
  { field: "airDrainF", label: "" },
  {
    field: "lowPressureWarning",
    label: "25. ระบบเบรกเมื่อแรงดันลมต่ำต้องมีสัญญาญเสียงหรือสัญลักษณ์ไฟเตือน",
  },
  { field: "lowPressureWarningR", label: "" },
  { field: "lowPressureWarningP", label: "" },
  { field: "lowPressureWarningA", label: "Respond to defect" },
  { field: "lowPressureWarningF", label: "" },
  {
    field: "motorcycleGuard",
    label: "26. โครงเซฟการ์ดกันมอเตอร์ไซด์ , ห่วงคล้องเพลากลาง",
  },
  { field: "motorcycleGuardR", label: "" },
  { field: "motorcycleGuardP", label: "" },
  { field: "motorcycleGuardA", label: "Respond to defect" },
  { field: "motorcycleGuardF", label: "" },
  { field: "ppe", label: "27. อุปกรณ์ PPE ของพนักงานจัดส่ง" },
  { field: "ppeR", label: "" },
  { field: "ppeP", label: "" },
  { field: "ppeA", label: "Respond to defect" },
  { field: "ppeF", label: "" },
  {
    field: "frontTires",
    label:
      "28. ยางคู่หน้าดอกสร้อยไม่หล่อดอก ยางชุดหลังสภาพพร้อมใช้งาน ดอกยางต้องเหลือไม่น้อยกว่า 2 มม.",
  },
  { field: "frontTiresR", label: "" },
  { field: "frontTiresP", label: "" },
  { field: "frontTiresA", label: "Respond to defect" },
  { field: "frontTiresF", label: "" },
  {
    field: "frontNumber",
    label:
      "29. ติดหมายเลขหน้าสีน้ำเงินซ้าย-ขวา ขนาด หนา 2 ซม.* สูง 12.5 ซม.* กว้าง 10 ซม.",
  },
  { field: "frontNumberR", label: "" },
  { field: "frontNumberP", label: "" },
  { field: "frontNumberA", label: "Respond to defect" },
  { field: "frontNumberF", label: "" },
  {
    field: "logo",
    label:
      "30. ติดโลโก้อินทรีคอนกรีตภาษาอังกฤษ ขนาด 23X50 ซม.พร้อมแถบสีแดง ที่ประตูหน้าซ้าย-ขวา",
  },
  { field: "logoR", label: "" },
  { field: "logoP", label: "" },
  { field: "logoA", label: "Respond to defect" },
  { field: "logoF", label: "" },
  {
    field: "cabinCleanliness",
    label: "31. ความสะอาดในห้องโดยสารและทัศนวิสัยในการมองเห็น",
  },
  { field: "cabinCleanlinessR", label: "" },
  { field: "cabinCleanlinessP", label: "" },
  { field: "cabinCleanlinessA", label: "Respond to defect" },
  { field: "cabinCleanlinessF", label: "" },
  { field: "vehicleCleanliness", label: "32. ความสะอาดรอบตัวรถโม่คอนกรีต" },
  { field: "vehicleCleanlinessR", label: "" },
  { field: "vehicleCleanlinessP", label: "" },
  { field: "vehicleCleanlinessA", label: "Respond to defect" },
  { field: "vehicleCleanlinessF", label: "" },
  {
    field: "mixerCondition",
    label: "33. คุณภาพตัวโม่และส่วนประกอบควบอื่นๆ อยู่ในสภาพดีพร้อมทำงาน",
  },
  { field: "mixerConditionR", label: "" },
  { field: "mixerConditionP", label: "" },
  { field: "mixerConditionA", label: "Respond to defect" },
  { field: "mixerConditionF", label: "" },
  {
    field: "logoAndColor",
    label: "34. โลโก้และสีรถถูกต้องตามแบบมาตรฐานที่กำหนด",
  },
  { field: "logoAndColorR", label: "" },
  { field: "logoAndColorP", label: "" },
  { field: "logoAndColorA", label: "Respond to defect" },
  { field: "logoAndColorF", label: "" },
  {
    field: "overallColorCondition",
    label:
      "35. สภาพสีโดยรวมทั้งคันรถ อยู่ในสภาพดีเหมาะสมในการเป็นตัวแทนภาพลักษณ์ที่ดีของแบรนด์อินทรี",
  },
  { field: "overallColorConditionR", label: "" },
  { field: "overallColorConditionP", label: "" },
  { field: "overallColorConditionA", label: "Respond to defect" },
  { field: "overallColorConditionF", label: "" },

  { field: "remark", label: "หมายเหตุ Remark" },
  { field: "lat", label: "" },
  { field: "url", label: "" },
];
