export const questions = [
  {
    id: 1,
    name: 'plugProtectionStandard',
    question:
      'Tiêu chuẩn bảo vệ của phích cắm có đạt yêu cầu không? / Does the plug meet protection standards?',
    howto: 'Kiểm tra tiêu chuẩn bảo vệ và ghi giá trị đạt được (Trong nhà: Ít nhất IP 42, ngoài trời: Ít nhất IP 67).',
    accept: 'Tiêu chuẩn bảo vệ đạt yêu cầu: trong nhà ít nhất IP 42, ngoài trời ít nhất IP 67.',
  },
  {
    id: 2,
    name: 'plugCableCompatibility',
    question:
      'Phích cắm có phù hợp với dây dẫn không? / Is the plug compatible with the cable?',
    howto: 'Kiểm tra sự phù hợp giữa phích cắm với dây dẫn về kích thước và loại.',
    accept: 'Phích cắm phù hợp hoàn toàn với dây dẫn được sử dụng.',
  },
  {
    id: 3,
    name: 'heatDamageCheck',
    question:
      'Phích cắm có bị hư hỏng do nhiệt không? / Is there any heat damage to the plug?',
    howto: 'Kiểm tra sự hư hỏng do nhiệt, bị cháy hay bị biến dạng trên phích cắm.',
    accept: 'Phích cắm không có dấu hiệu hư hỏng do nhiệt, cháy hay biến dạng.',
  },
  {
    id: 4,
    name: 'wireScrewTightness',
    question:
      'Các vít xiết dây dẫn có chắc chắn không? / Are the wire connection screws tight?',
    howto: 'Kiểm tra sự xiết chặt của các vít xiết dây dẫn trong phích cắm.',
    accept: 'Tất cả các vít xiết dây dẫn được siết chặt đúng mức.',
  },
  {
    id: 5,
    name: 'terminalCondition',
    question:
      'Trạm đấu nối có trong tình trạng tốt không? / Are the terminals in good condition?',
    howto: 'Kiểm tra tình trạng của các trạm đấu nối, không có dấu hiệu ăn mòn hay hư hỏng.',
    accept: 'Trạm đấu nối trong tình trạng tốt, không có ăn mòn hay hư hỏng.',
  },
  {
    id: 6,
    name: 'waterproofSafety',
    question:
      'Đầu bịt chống nước có an toàn không? / Is the waterproof cap safe?',
    howto: 'Kiểm tra sự an toàn của đầu bịt chống nước và sự kết nối chống nước (thiết bị sử dụng ngoài trời).',
    accept: 'Đầu bịt chống nước an toàn và kết nối chống nước hiệu quả.',
  },
  {
    id: 7,
    name: 'cableCompatibility',
    question:
      'Dây điện có phù hợp với thiết bị không? / Is the electrical cable compatible with the equipment?',
    howto: 'Kiểm tra sự phù hợp với thiết bị (thiết diện lõi / công suất / loại dây).',
    accept: 'Dây điện phù hợp hoàn toàn với thiết bị về thiết diện lõi, công suất và loại dây.',
  },
  {
    id: 8,
    name: 'doubleInsulation',
    question:
      'Dây điện có đủ 2 lớp cách ly không? / Does the electrical cable have double insulation?',
    howto: 'Kiểm tra dây điện có 2 lớp cách ly theo tiêu chuẩn an toàn.',
    accept: 'Dây điện có đủ 2 lớp cách ly theo đúng tiêu chuẩn.',
  },
  {
    id: 9,
    name: 'outerSheathDamage',
    question:
      'Lớp vỏ bọc bảo vệ bên ngoài có bị cắt xuyên qua không? / Is there any cut through the outer protective sheath?',
    howto: 'Kiểm tra xem có vết cắt xuyên qua lớp vỏ bọc bảo vệ bên ngoài của dây điện không.',
    accept: 'Lớp vỏ bọc bảo vệ bên ngoài không có vết cắt hay hư hỏng.',
  },
  {
    id: 10,
    name: 'cableFixing',
    question:
      'Dây dẫn có được cố định chặt không? / Is the cable properly fixed?',
    howto: 'Kiểm tra dây dẫn được cố định chặt trong hộp đấu nối bởi kẹp, cable glands hay phương pháp được chấp thuận.',
    accept: 'Dây dẫn được cố định chặt và an toàn bằng phương pháp được chấp thuận.',
  },
  {
    id: 11,
    name: 'insulationEntry',
    question:
      'Dây dẫn có được luồn qua bộ phận cách điện không? / Does the cable pass through insulation components?',
    howto: 'Kiểm tra dây dẫn đi vào vỏ máy, hộp đấu dây phải được luồn qua bộ phận cách điện.',
    accept: 'Dây dẫn được luồn qua bộ phận cách điện đúng cách.',
  },
  {
    id: 12,
    name: 'wirePolarity',
    question:
      'Cực của các dây dẫn có đúng và đủ không? / Are the wire polarities correct and complete?',
    howto: 'Kiểm tra cực của các dây dẫn (đủ và đúng cực) theo sơ đồ kết nối.',
    accept: 'Cực của các dây dẫn đúng và đủ theo yêu cầu kỹ thuật.',
  },
  {
    id: 13,
    name: 'earthingConnection',
    question:
      'Điểm giao giữa dây dẫn và chi tiết nối đất có tốt không? / Is the connection between conductors and earthing components good?',
    howto: 'Kiểm tra điểm giao giữa các dây dẫn và các chi tiết nối đất.',
    accept: 'Điểm giao giữa dây dẫn và chi tiết nối đất kết nối tốt và an toàn.',
  },
  {
    id: 14,
    name: 'cableLength',
    question:
      'Chiều dài dây có vượt quá 5m không? / Does the cable length exceed 5m?',
    howto: 'Đo chiều dài dây điện để đảm bảo không quá 5m theo quy định.',
    accept: 'Chiều dài dây điện không vượt quá 5m.',
  },
  {
    id: 15,
    name: 'overallCableCondition',
    question:
      'Tất cả dây dẫn có trong điều kiện tốt không? / Are all conductors in good condition?',
    howto: 'Kiểm tra tất cả dây dẫn (sạch sẽ, cách điện tốt) để đảm bảo an toàn.',
    accept: 'Tất cả dây dẫn sạch sẽ, cách điện tốt và trong điều kiện an toàn.',
  },
  {
    id: 16,
    name: 'sheathDamage',
    question:
      'Vỏ bọc dây có bị hư hỏng không? / Is the cable sheath damaged?',
    howto: 'Kiểm tra hư hỏng của vỏ bọc dây điện trên toàn bộ chiều dài.',
    accept: 'Vỏ bọc dây không có hư hỏng, vết nứt hay mài mòn.',
  },
  {
    id: 17,
    name: 'guardingCondition',
    question:
      'Bộ phận che chắn có hoạt động tốt không? / Are the guarding components working properly?',
    howto: 'Kiểm tra tình trạng và hoạt động của bộ phận che chắn theo mục FPE-Machine Guarding.',
    accept: 'Bộ phận che chắn hoạt động tốt và đảm bảo an toàn.',
  },
  {
    id: 18,
    name: 'housingDamage',
    question:
      'Vỏ máy có bị hư hỏng không? / Is the machine housing damaged?',
    howto: 'Kiểm tra hư hỏng của vỏ bọc thân máy, tìm vết nứt, biến dạng.',
    accept: 'Vỏ máy không có hư hỏng, vết nứt hay biến dạng.',
  },
  {
    id: 19,
    name: 'onOffSwitch',
    question:
      'Công tắc ĐÓNG-MỞ có hoạt động tốt không? / Does the ON-OFF switch work properly?',
    howto: 'Kiểm tra hoạt động của công tắc ĐÓNG-MỞ, đảm bảo đóng ngắt chính xác.',
    accept: 'Công tắc ĐÓNG-MỞ hoạt động chính xác và mượt mà.',
  },
  {
    id: 20,
    name: 'safetyDevices',
    question:
      'Các thiết bị an toàn có hoạt động không? / Do the safety devices work?',
    howto: 'Kiểm tra hoạt động của tất cả các thiết bị an toàn trên máy.',
    accept: 'Tất cả thiết bị an toàn hoạt động đúng chức năng.',
  },
  {
    id: 21,
    name: 'connectionTerminals',
    question:
      'Trạm đấu nối có trong tình trạng tốt không? / Are the connection terminals in good condition?',
    howto: 'Kiểm tra tình trạng của các trạm đấu nối trong thân máy.',
    accept: 'Các trạm đấu nối trong tình trạng tốt, không có ăn mòn.',
  },
  {
    id: 22,
    name: 'handleSafety',
    question:
      'Tay cầm có an toàn không? / Is the handle safe?',
    howto: 'Kiểm tra tình trạng an toàn của tay cầm máy, không có hư hỏng hay lỏng lẻo.',
    accept: 'Tay cầm an toàn, chắc chắn và không có hư hỏng.',
  },
  {
    id: 23,
    name: 'clampLockCondition',
    question:
      'Bàn kẹp và khóa mở có tốt không? / Are the clamp and lock in good condition?',
    howto: 'Kiểm tra tình trạng của bàn kẹp và khóa mở, đảm bảo hoạt động chính xác.',
    accept: 'Bàn kẹp và khóa mở hoạt động chính xác và an toàn.',
  },
  {
    id: 24,
    name: 'carbonBrushCondition',
    question:
      'Chổi than có trong tình trạng tốt không? / Are the carbon brushes in good condition?',
    howto: 'Kiểm tra tình trạng của chổi than, độ mài mòn và tiếp xúc.',
    accept: 'Chổi than trong tình trạng tốt, chưa mài mòn quá mức.',
  },
  {
    id: 25,
    name: 'insulationResistance',
    question:
      'Điện trở cách điện có đạt yêu cầu không? / Does the insulation resistance meet requirements?',
    howto: 'Đo điện trở cách điện (Ohm) giữa nguồn sơ cấp và vỏ của máy và ghi vào mục ghi chú.',
    accept: 'Điện trở cách điện đạt giá trị yêu cầu theo tiêu chuẩn an toàn.',
  },
  {
    id: 26,
    name: 'accessoryCondition',
    question:
      'Phụ kiện có trong tình trạng tốt không? / Are the accessories in good condition?',
    howto: 'Kiểm tra tình trạng của phụ kiện (VD: Đá mài, mũi khoan, chổi...).',
    accept: 'Tất cả phụ kiện trong tình trạng tốt và an toàn sử dụng.',
  },
  {
    id: 27,
    name: 'labelingIdentification',
    question:
      'Nhãn/Dấu hiệu nhận dạng có đầy đủ không? / Are the labels/identification marks complete?',
    howto: 'Kiểm tra tên/mã số nhận dạng thiết bị/HAC có đầy đủ và rõ ràng.',
    accept: 'Nhãn và dấu hiệu nhận dạng thiết bị đầy đủ, rõ ràng và chính xác.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'plugProtectionStandard', label: '1. Tiêu chuẩn bảo vệ của phích cắm có đạt yêu cầu không? / Does the plug meet protection standards?'},
  { field: 'plugProtectionStandardR', label: '' },
  { field: 'plugProtectionStandardP', label: '' },
  { field: 'plugProtectionStandardA', label: '' },
  { field: 'plugProtectionStandardF', label: '' },
  { field: 'plugCableCompatibility', label: '2. Phích cắm có phù hợp với dây dẫn không? / Is the plug compatible with the cable?'},
  { field: 'plugCableCompatibilityR', label: '' },
  { field: 'plugCableCompatibilityP', label: '' },
  { field: 'plugCableCompatibilityA', label: '' },
  { field: 'plugCableCompatibilityF', label: '' },
  { field: 'heatDamageCheck', label: '3. Phích cắm có bị hư hỏng do nhiệt không? / Is there any heat damage to the plug?'},
  { field: 'heatDamageCheckR', label: '' },
  { field: 'heatDamageCheckP', label: '' },
  { field: 'heatDamageCheckA', label: '' },
  { field: 'heatDamageCheckF', label: '' },
  { field: 'wireScrewTightness', label: '4. Các vít xiết dây dẫn có chắc chắn không? / Are the wire connection screws tight?'},
  { field: 'wireScrewTightnessR', label: '' },
  { field: 'wireScrewTightnessP', label: '' },
  { field: 'wireScrewTightnessA', label: '' },
  { field: 'wireScrewTightnessF', label: '' },
  { field: 'terminalCondition', label: '5. Trạm đấu nối có trong tình trạng tốt không? / Are the terminals in good condition?'},
  { field: 'terminalConditionR', label: '' },
  { field: 'terminalConditionP', label: '' },
  { field: 'terminalConditionA', label: '' },
  { field: 'terminalConditionF', label: '' },
  { field: 'waterproofSafety', label: '6. Đầu bịt chống nước có an toàn không? / Is the waterproof cap safe?'},
  { field: 'waterproofSafetyR', label: '' },
  { field: 'waterproofSafetyP', label: '' },
  { field: 'waterproofSafetyA', label: '' },
  { field: 'waterproofSafetyF', label: '' },
  { field: 'cableCompatibility', label: '7. Dây điện có phù hợp với thiết bị không? / Is the electrical cable compatible with the equipment?'},
  { field: 'cableCompatibilityR', label: '' },
  { field: 'cableCompatibilityP', label: '' },
  { field: 'cableCompatibilityA', label: '' },
  { field: 'cableCompatibilityF', label: '' },
  { field: 'doubleInsulation', label: '8. Dây điện có đủ 2 lớp cách ly không? / Does the electrical cable have double insulation?'},
  { field: 'doubleInsulationR', label: '' },
  { field: 'doubleInsulationP', label: '' },
  { field: 'doubleInsulationA', label: '' },
  { field: 'doubleInsulationF', label: '' },
  { field: 'outerSheathDamage', label: '9. Lớp vỏ bọc bảo vệ bên ngoài có bị cắt xuyên qua không? / Is there any cut through the outer protective sheath?'},
  { field: 'outerSheathDamageR', label: '' },
  { field: 'outerSheathDamageP', label: '' },
  { field: 'outerSheathDamageA', label: '' },
  { field: 'outerSheathDamageF', label: '' },
  { field: 'cableFixing', label: '10. Dây dẫn có được cố định chặt không? / Is the cable properly fixed?'},
  { field: 'cableFixingR', label: '' },
  { field: 'cableFixingP', label: '' },
  { field: 'cableFixingA', label: '' },
  { field: 'cableFixingF', label: '' },
  { field: 'insulationEntry', label: '11. Dây dẫn có được luồn qua bộ phận cách điện không? / Does the cable pass through insulation components?'},
  { field: 'insulationEntryR', label: '' },
  { field: 'insulationEntryP', label: '' },
  { field: 'insulationEntryA', label: '' },
  { field: 'insulationEntryF', label: '' },
  { field: 'wirePolarity', label: '12. Cực của các dây dẫn có đúng và đủ không? / Are the wire polarities correct and complete?'},
  { field: 'wirePolarityR', label: '' },
  { field: 'wirePolarityP', label: '' },
  { field: 'wirePolarityA', label: '' },
  { field: 'wirePolarityF', label: '' },
  { field: 'earthingConnection', label: '13. Điểm giao giữa dây dẫn và chi tiết nối đất có tốt không? / Is the connection between conductors and earthing components good?'},
  { field: 'earthingConnectionR', label: '' },
  { field: 'earthingConnectionP', label: '' },
  { field: 'earthingConnectionA', label: '' },
  { field: 'earthingConnectionF', label: '' },
  { field: 'cableLength', label: '14. Chiều dài dây có vượt quá 5m không? / Does the cable length exceed 5m?'},
  { field: 'cableLengthR', label: '' },
  { field: 'cableLengthP', label: '' },
  { field: 'cableLengthA', label: '' },
  { field: 'cableLengthF', label: '' },
  { field: 'overallCableCondition', label: '15. Tất cả dây dẫn có trong điều kiện tốt không? / Are all conductors in good condition?'},
  { field: 'overallCableConditionR', label: '' },
  { field: 'overallCableConditionP', label: '' },
  { field: 'overallCableConditionA', label: '' },
  { field: 'overallCableConditionF', label: '' },
  { field: 'sheathDamage', label: '16. Vỏ bọc dây có bị hư hỏng không? / Is the cable sheath damaged?'},
  { field: 'sheathDamageR', label: '' },
  { field: 'sheathDamageP', label: '' },
  { field: 'sheathDamageA', label: '' },
  { field: 'sheathDamageF', label: '' },
  { field: 'guardingCondition', label: '17. Bộ phận che chắn có hoạt động tốt không? / Are the guarding components working properly?'},
  { field: 'guardingConditionR', label: '' },
  { field: 'guardingConditionP', label: '' },
  { field: 'guardingConditionA', label: '' },
  { field: 'guardingConditionF', label: '' },
  { field: 'housingDamage', label: '18. Vỏ máy có bị hư hỏng không? / Is the machine housing damaged?'},
  { field: 'housingDamageR', label: '' },
  { field: 'housingDamageP', label: '' },
  { field: 'housingDamageA', label: '' },
  { field: 'housingDamageF', label: '' },
  { field: 'onOffSwitch', label: '19. Công tắc ĐÓNG-MỞ có hoạt động tốt không? / Does the ON-OFF switch work properly?'},
  { field: 'onOffSwitchR', label: '' },
  { field: 'onOffSwitchP', label: '' },
  { field: 'onOffSwitchA', label: '' },
  { field: 'onOffSwitchF', label: '' },
  { field: 'safetyDevices', label: '20. Các thiết bị an toàn có hoạt động không? / Do the safety devices work?'},
  { field: 'safetyDevicesR', label: '' },
  { field: 'safetyDevicesP', label: '' },
  { field: 'safetyDevicesA', label: '' },
  { field: 'safetyDevicesF', label: '' },
  { field: 'connectionTerminals', label: '21. Trạm đấu nối có trong tình trạng tốt không? / Are the connection terminals in good condition?'},
  { field: 'connectionTerminalsR', label: '' },
  { field: 'connectionTerminalsP', label: '' },
  { field: 'connectionTerminalsA', label: '' },
  { field: 'connectionTerminalsF', label: '' },
  { field: 'handleSafety', label: '22. Tay cầm có an toàn không? / Is the handle safe?'},
  { field: 'handleSafetyR', label: '' },
  { field: 'handleSafetyP', label: '' },
  { field: 'handleSafetyA', label: '' },
  { field: 'handleSafetyF', label: '' },
  { field: 'clampLockCondition', label: '23. Bàn kẹp và khóa mở có tốt không? / Are the clamp and lock in good condition?'},
  { field: 'clampLockConditionR', label: '' },
  { field: 'clampLockConditionP', label: '' },
  { field: 'clampLockConditionA', label: '' },
  { field: 'clampLockConditionF', label: '' },
  { field: 'carbonBrushCondition', label: '24. Chổi than có trong tình trạng tốt không? / Are the carbon brushes in good condition?'},
  { field: 'carbonBrushConditionR', label: '' },
  { field: 'carbonBrushConditionP', label: '' },
  { field: 'carbonBrushConditionA', label: '' },
  { field: 'carbonBrushConditionF', label: '' },
  { field: 'insulationResistance', label: '25. Điện trở cách điện có đạt yêu cầu không? / Does the insulation resistance meet requirements?'},
  { field: 'insulationResistanceR', label: '' },
  { field: 'insulationResistanceP', label: '' },
  { field: 'insulationResistanceA', label: '' },
  { field: 'insulationResistanceF', label: '' },
  { field: 'accessoryCondition', label: '26. Phụ kiện có trong tình trạng tốt không? / Are the accessories in good condition?'},
  { field: 'accessoryConditionR', label: '' },
  { field: 'accessoryConditionP', label: '' },
  { field: 'accessoryConditionA', label: '' },
  { field: 'accessoryConditionF', label: '' },
  { field: 'labelingIdentification', label: '27. Nhãn/Dấu hiệu nhận dạng có đầy đủ không? / Are the labels/identification marks complete?'},
  { field: 'labelingIdentificationR', label: '' },
  { field: 'labelingIdentificationP', label: '' },
  { field: 'labelingIdentificationA', label: '' },
  { field: 'labelingIdentificationF', label: '' },
  { field: 'tag', label: 'Tag' },
  { field: 'collection', label: 'Type of Equipment' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
