export const questions = [
  {
    id: 1,
    name: 'control',
    question: 'ปุ่มควบคุม, ปุ่มบังคับ, ปุ่มหยุดฉุกเฉิน',
    howto: 'ทดสอบ /ประเมิน',
    accept:
      'สามารถหยุดการทำงานของเครนได้ และเมื่อปล่อยมือปุ่มไม่ค้าง สภาพปุ่มไม่แตกหรือชำรุด',
  },
  {
    id: 2,
    name: 'switch',
    question: 'ชุดลิมิทซ์สวิทซ์ (รางสั้น /รางยาว)',
    howto: 'ทดสอบ / ประเมิน',
    accept: 'กดบังคับเครนไปจนสุดราง (ลิมิทสวิทซ์ทำงานหรือไม่)',
  },
  {
    id: 3,
    name: 'sling',
    question: 'สลิง, ลิมิทซ์ (เมื่อสลิงขึ้นสูงสุด, ลงสูงสุด)',
    howto: 'ทดสอบ / ประเมิน',
    accept:
      'กดปุ่มบังคับสลิงเปล่าขึ้น/ลงจนสุดสลิง ลิมิทซ์จะทำงานและสลิงจะไม่สามารถขึ้น/ลงได้อีก,  สภาพสลิงปลอดภัยไม่ขาดชหรือชำรุด	',
  },
  {
    id: 4,
    name: 'sound',
    question: 'สัญญาณเสียงเตือน/แสง',
    howto: 'สายตา / ประเมิน',
    accept: 'ขณะเครนทำงานมีเสียงสัญญาณเตือน หรือแสงวับวามเตือนหรือไม่',
  },
  {
    id: 5,
    name: 'doc',
    question: 'มีเอกสารแสดงขั้นตอนการใช้งาน ระบุพิกันน้ำหนักปลอดภัย',
    howto: 'สังเกต / ประเมิน',
    accept: 'มีเอกสารแสดงขั้นตอนการใช้งาน มองเห็นได้อย่างชัดเจน',
  },
  {
    id: 6,
    name: 'ppe',
    question: 'อุปกรณ์นิรภัยคุ้มครองส่วนบุคคลของผู้ปฏิบัติงาน',
    howto: 'สังเกต / ประเมิน',
    accept: 'ผู้ปฏิบัติงานมีการสวมใส่อุปกรณ์ป้องกันส่วนบุคคลครบถ้วนปลอดภัย',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'control', label: '1. ปุ่มควบคุม, ปุ่มบังคับ, ปุ่มหยุดฉุกเฉิน' },
  { field: 'controlR', label: '' },
  { field: 'controlP', label: '' },
  { field: 'controlA', label: 'Respond to defect' },
  { field: 'controlF', label: '' },
  { field: 'switch', label: '2. ชุดลิมิทซ์สวิทซ์ (รางสั้น /รางยาว)' },
  { field: 'switchR', label: '' },
  { field: 'switchP', label: '' },
  { field: 'switchA', label: 'Respond to defect' },
  { field: 'switchF', label: '' },
  { field: 'sling', label: '3. สลิง, ลิมิทซ์ (เมื่อสลิงขึ้นสูงสุด, ลงสูงสุด)' },
  { field: 'slingR', label: '' },
  { field: 'slingP', label: '' },
  { field: 'slingA', label: 'Respond to defect' },
  { field: 'slingF', label: '' },
  { field: 'sound', label: '4. สัญญาณเสียงเตือน/แสง' },
  { field: 'soundR', label: '' },
  { field: 'soundP', label: '' },
  { field: 'soundA', label: 'Respond to defect' },
  { field: 'soundF', label: '' },
  {
    field: 'doc',
    label: '5. มีเอกสารแสดงขั้นตอนการใช้งาน ระบุพิกันน้ำหนักปลอดภัย',
  },
  { field: 'docR', label: '' },
  { field: 'docP', label: '' },
  { field: 'docA', label: 'Respond to defect' },
  { field: 'docF', label: '' },
  { field: 'ppe', label: '6. อุปกรณ์นิรภัยคุ้มครองส่วนบุคคลของผู้ปฏิบัติงาน' },
  { field: 'ppeR', label: '' },
  { field: 'ppeP', label: '' },
  { field: 'ppeA', label: 'Respond to defect' },
  { field: 'ppeF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
