export const questions = [
  {
    id: 1,
    name: 'Wheel',
    question: 'កង់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបង្វិលកង់',
    accept: 'សំបកកង់ល្អ ក្រឡានៅស្អាត ឬ ប៊ូឡុងខ្ចៅតឹងណែនល្អ',
  },
  {
    id: 2,
    name: 'Pillar',
    question: 'ដងសសរបង្គំមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងភាពស្អាត',
    accept: 'ដងសសរបង្គំស្ថានភាពល្អ គ្មានការបាក់ ឬការលេចធ្លាយប្រេង',
  },
  {
    id: 3,
    name: 'hydraulic',
    question: 'ដងហាយដ្រូលិកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការលេចធ្លាយ',
    accept: 'ដងហាយដ្រូលិកគ្មានការច្រេះ ឬការលេចធ្លាយប្រេង',
  },
  {
    id: 4,
    name: 'chain',
    question: 'ច្រវ៉ាក់យោងនិងដងចូកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការប្រើប្រាស់',
    accept: 'ច្រវ៉ាក់ស្ថានភាពល្អ, ប្រេងរអិលធម្មតា និងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 5,
    name: 'belt',
    question: 'កៅអី​ ខ្សែក្រវ៉ាត់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពកៅអី និងការដាក់ខ្សែក្រវ៉ាត់',
    accept: 'កៅអីស្ថានភាពល្អ និងខ្សែក្រវ៉ាត់ដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 6,
    name: 'battery',
    question: 'អាគុយមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងកំរិតថ្ម',
    accept: 'អាគុយស្ថានភាពល្អ គ្មានស្នាមច្រេះ ឬការច្រាលថ្ម',
  },
  {
    id: 7,
    name: 'brake',
    question: 'ហ្រ្វាងដៃ, ជើងមិនធម្មតា',
    howto: 'ជាន់ហ្រ្វាំងតេស្តមុនបើកបរ',
    accept: 'ហ្រ្វាំងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 8,
    name: 'steering',
    question: 'ចង្កូតមិនធម្មតា',
    howto: 'តេស្តបួងចង្កូតឆ្វេង-ស្តាំ២ជុំ',
    accept: 'ចង្កូតដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 9,
    name: 'accelerator',
    question: 'ហ្គ៊ែរមិនធម្មតា',
    howto: 'តេស្តលើការប្រើប្រាស់ហ្គែរជើង',
    accept: 'ហ្គែរដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 10,
    name: 'light',
    question: 'ភ្លើងមិនធម្មតា',
    howto: 'ពិនិត្យការដំណើរការរបស់ភ្លើង',
    accept: 'ភ្លើងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 11,
    name: 'signal',
    question: 'ស៊ីញ៉ូមិនធម្មតា',
    howto: 'បើកស៊ីញ៉ូ និងពិនិត្យស្ថានភាព',
    accept: 'ស៊ីញ៉ូដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 12,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'តេស្តសំលេងស៊ីផ្លេ',
    accept: 'ស៊ីផ្លេដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 13,
    name: 'extinguisher',
    question: 'បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការដំណើរការ',
    accept: 'បំពង់ដំណើរការបានត្រឹមត្រូវ',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'wheel', label: '1. កង់ - Tires' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'pillar', label: '2. ដងសសរ - Pillar' },
  { field: 'pillarR', label: '' },
  { field: 'pillarP', label: '' },
  { field: 'pillarA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'pillarF', label: '' },
  { field: 'hydraulic', label: '3. ដងហាយដ្រូលិក - Hydraulic' },
  { field: 'hydraulicR', label: '' },
  { field: 'hydraulicP', label: '' },
  { field: 'hydraulicA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydraulicF', label: '' },
  { field: 'chain', label: '4. ច្រវ៉ាក់ - Chain' },
  { field: 'chainR', label: '' },
  { field: 'chainP', label: '' },
  { field: 'chainA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'chainF', label: '' },
  { field: 'belt', label: '5. ខ្សែក្រវ៉ាត់ - Belt' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'battery', label: '6. អាគុយ - Battery' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'brake', label: '7. ហ្រ្វាំង - Brake' },
  { field: 'brakeR', label: '' },
  { field: 'brakeP', label: '' },
  { field: 'brakeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'brakeF', label: '' },
  { field: 'steering', label: '8. ចង្កូត - Steering' },
  { field: 'steeringR', label: '' },
  { field: 'steeringP', label: '' },
  { field: 'steeringA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'steeringF', label: '' },
  { field: 'accelerator', label: '9. ហ្គែរជើង - Accelerator' },
  { field: 'acceleratorR', label: '' },
  { field: 'acceleratorP', label: '' },
  { field: 'acceleratorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'acceleratorF', label: '' },
  { field: 'light', label: '10. ភ្លើង - Light' },
  { field: 'lightR', label: '' },
  { field: 'lightP', label: '' },
  { field: 'lightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'lightF', label: '' },
  { field: 'signal', label: '11. ស៊ីញ៉ូ - Signal' },
  { field: 'signalR', label: '' },
  { field: 'signalP', label: '' },
  { field: 'signalA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'signalF', label: '' },
  { field: 'horn', label: '12. ស៊ីផ្លេ - Horn' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'extinguisher', label: '13. បំពង់ពន្លត់អគ្គីភ័យ - Extinguisher' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'remark', label: 'ចំណាំ Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
