export const questions = [
  {
    id: 1,
    name: 'horn',
    question: 'Còi báo',
    howto: 'Kiểm tra còi báo hoạt động đúng cách.',
    accept: 'Còi báo hoạt động bình thường.',
  },
  {
    id: 2,
    name: 'lights',
    question: 'Đèn báo',
    howto: 'Kiểm tra đèn báo hoạt động đúng cách.',
    accept: 'Đèn báo hoạt động bình thường.',
  },
  {
    id: 3,
    name: 'isolator',
    question: 'Isolator',
    howto: 'Kiểm tra isolator hoạt động đúng cách.',
    accept: 'Isolator hoạt động bình thường.',
  },
  {
    id: 4,
    name: 'limitSwitch',
    question: 'Công tắc hành trình',
    howto: 'Kiểm tra công tắc hành trình hoạt động đúng cách.',
    accept: 'Công tắc hành trình hoạt động bình thường.',
  },
  {
    id: 5,
    name: 'loadLimit',
    question: 'Giới hạn tải trọng',
    howto: 'Kiểm tra giới hạn tải trọng hoạt động đúng cách.',
    accept: 'Giới hạn tải trọng hoạt động bình thường.',
  },
  {
    id: 6,
    name: 'safetyLatch',
    question: 'Lẫy an toàn của móc',
    howto: 'Kiểm tra lẫy an toàn của móc hoạt động đúng cách.',
    accept: 'Lẫy an toàn của móc hoạt động bình thường.',
  },
  {
    id: 7,
    name: 'loadChart',
    question: 'Sơ đồ tải trọng',
    howto: 'Kiểm tra sơ đồ tải trọng hoạt động đúng cách.',
    accept: 'Sơ đồ tải trọng hoạt động bình thường.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  {
    field: 'certificate',
    label:
      'Chứng nhận kiểm định/đăng kiểm còn hiệu lực đến ngày. Inspection/register certificate valid to',
  },
  { field: 'responder', label: 'Responder' },
  { field: 'horn', label: '1. Còi báo *' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'lights', label: '2. Đèn báo *' },
  { field: 'lightsR', label: '' },
  { field: 'lightsP', label: '' },
  { field: 'lightsA', label: 'Respond to defect' },
  { field: 'lightsF', label: '' },
  { field: 'isolator', label: '3. Isolator *' },
  { field: 'isolatorR', label: '' },
  { field: 'isolatorP', label: '' },
  { field: 'isolatorA', label: 'Respond to defect' },
  { field: 'isolatorF', label: '' },
  { field: 'limitSwitch', label: '4. Công tắc hành trình *' },
  { field: 'limitSwitchR', label: '' },
  { field: 'limitSwitchP', label: '' },
  { field: 'limitSwitchA', label: 'Respond to defect' },
  { field: 'limitSwitchF', label: '' },
  { field: 'loadLimit', label: '5. Giới hạn tải trọng *' },
  { field: 'loadLimitR', label: '' },
  { field: 'loadLimitP', label: '' },
  { field: 'loadLimitA', label: 'Respond to defect' },
  { field: 'loadLimitF', label: '' },
  { field: 'safetyLatch', label: '6. Lẫy an toàn của móc *' },
  { field: 'safetyLatchR', label: '' },
  { field: 'safetyLatchP', label: '' },
  { field: 'safetyLatchA', label: 'Respond to defect' },
  { field: 'safetyLatchF', label: '' },
  { field: 'loadChart', label: '7. Sơ đồ tải trọng *' },
  { field: 'loadChartR', label: '' },
  { field: 'loadChartP', label: '' },
  { field: 'loadChartA', label: 'Respond to defect' },
  { field: 'loadChartF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
