export const questions = [
  {
    id: 1,
    name: 'steeringCondition',
    question: 'Steering condition* (স্টিয়ারিংঅবস্থা)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: 'স্টিয়ারিংসিস্টেম সঠিক এবং কার্যকরঅবস্থায় আছে।',
  },
  {
    id: 2,
    name: 'tyreCondition',
    question: 'Tyre condition* (টায়ারেরঅবস্থা)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: ' সকলটায়ার সঠিক, নিরাপদ এবং সঠিক চাপআছে।',
  },
  {
    id: 3,
    name: 'seatBelts',
    question: 'Seat belts* (সীটবেল্ট)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: 'সীটবেল্ট সঠিক এবং কার্যকরঅবস্থায় আছে।',
  },
  {
    id: 4,
    name: 'mirrors',
    question: 'Mirrors (মিরররস)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: 'আয়নাগুলিপরিষ্কার, ফাটল এবং ত্রুটিমুক্তহওয়া উচিত।',
  },
  {
    id: 5,
    name: 'waterOilLevel',
    question: 'Water/oil level (ওয়াটার/অয়েল লেভেল)',
    howto: 'বাহ্যিক পরিদর্শন',
    accept: 'পানিএবং তেলের পরিমান পর্যাপ্ত আছে।',
  },
  {
    id: 6,
    name: 'brakeFluid',
    question: 'Brake fluid (ব্রেকফ্লুইড)',
    howto: ' বাহ্যিক পরিদর্শন',
    accept: 'ব্রেকতেলের পরিমান পর্যাপ্ত আছে।',
  },
  {
    id: 7,
    name: 'gaugesWorking',
    question: 'Gauges working (গেজওয়ার্কিং)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: 'সমস্তগেজগুলি ঠিক আছে এবংসঠিক ভাবে কাজ করে।',
  },
  {
    id: 8,
    name: 'indicators',
    question: 'Indicators (ইন্ডিকেটরস)',
    howto: ' বাহ্যিক পরিদর্শন',
    accept: 'সমস্তইন্ডিকেটরগুলি ঠিক আছে এবংসঠিক ভাবে কাজ করে।',
  },
  {
    id: 9,
    name: 'headParkLights',
    question: 'Head/parking lights (হেড/পার্কিং লাইটস)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: 'হেডলাইটএবং পার্কিং লাইটগুলি ঠিক আছে এবংসঠিকভাবে কাজ করে।',
  },
  {
    id: 10,
    name: 'tailStopLights',
    question: 'Tail/stop lights* (টেইল/স্টপ লাইটস)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: ' সকলটেইল এবং স্টপ লাইটগুলিঠিক আছে এবং সঠিকভাবেকাজ করে।',
  },
  {
    id: 11,
    name: 'brakesHandFoot',
    question: 'Brakes hand/foot* (হাতের/ পায়ের ব্রেক)',
    howto: ' বাহ্যিকএবং কার্যকরী পরীক্ষা',
    accept: ' হাতেরএবং পায়ের ব্রেকগুলি ঠিক আছে এবংসঠিক ভাবে কাজ করে।',
  },
  {
    id: 12,
    name: 'wipersWasher',
    question: 'Wipers/washer (ওয়াইপার/ওয়াশার)',
    howto: 'কার্যকরীপরীক্ষা',
    accept:
      'ওয়াইপারএবং ওয়াশার সঠিকভাবে কাজ করে এবংপর্যাপ্ত পরিমান ওয়াশিং তরল আছে।',
  },
  {
    id: 13,
    name: 'horn',
    question: 'Horn* (হৰ্ণ)',
    howto: 'কার্যকরীপরীক্ষা',
    accept: 'হর্ণেরশব্দ স্পষ্ট এবং শ্রবণযোগ্য হওয়াউচিত।',
  },
  {
    id: 14,
    name: 'firstAidKit',
    question:
      'First Aid Kit (vehicles in public areas) (প্রাথমিক চিকিৎসার সরঞ্জাম)',
    howto: 'মজুদপরীক্ষা',
    accept: 'সিলযুক্ত এবং প্রয়োজনীয় সমস্তজিনিসসহ প্রাথমিক চিকিৎসা কিট আছে। ',
  },
  {
    id: 15,
    name: 'safetyTriangle',
    question: 'Safety Triangle (সেফটিট্রায়াঙ্গল)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: ' ব্যবহারযোগ্যনিরাপত্তা ত্রিভুজ আছে।',
  },
  {
    id: 16,
    name: 'toolbox',
    question: 'Toolbox (টুলবক্স)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept:
      'প্রয়োজনীয় সমস্ত টুলস সহ (যেমনঃ স্প্যানার, জ্যাক, জ্যাকের হ্যান্ডেল, ইত্যাদি) টুলবক্স আছে।',
  },
  {
    id: 17,
    name: 'rotaryFlashLamp',
    question: 'Rotary/ Flash lamp (রোটারি/ ফ্ল্যাশ লাইট)',
    howto: 'Functional test',
    accept: 'রোটারি/ফ্ল্যাশ লাইট আছে এবংসঠিক ভাবে কাজ করে।',
  },
  {
    id: 18,
    name: 'reflectiveStrip',
    question: 'Reflective Strip (রিফ্লেক্টিভস্ট্রিপ)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept:
      'রিফ্লেক্টিভস্ট্রিপ পরিষ্কার, অক্ষত, এবং ঠিকভাবে যানবাহনেলাগানো আছে।',
  },
  {
    id: 19,
    name: 'vehicleNumbers',
    question: 'Vehicle Numbers Plate (গাড়ির নম্বর প্লেট)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: 'গাড়ীরনাম্বার প্লেট আছে এবং নাম্বারগুলো সঠিকভাবে পড়া যায়।',
  },
  {
    id: 20,
    name: 'communicationRadio',
    question: 'Communication radio (যোগাযোগরেডিও)',
    howto: ' বাহ্যিকপরিদর্শন',
    accept: 'যোগাযোগকরার জন্য রেডিও আছেএবং তা সঠিক ভাবেকাজ করে।',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'তারিখঃ - Date' },
  { field: 'inspector', label: 'পরিদর্শক - Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'steeringCondition',
    label: '1. Steering condition - স্টিয়ারিং অবস্থা',
  },
  { field: 'steeringConditionR', label: '' },
  { field: 'steeringConditionP', label: '' },
  { field: 'steeringConditionA', label: 'Respond to defect' },
  { field: 'steeringConditionF', label: '' },
  { field: 'tyreCondition', label: '2. Tyre condition - টায়ারের অবস্থা' },
  { field: 'tyreConditionR', label: '' },
  { field: 'tyreConditionP', label: '' },
  { field: 'tyreConditionA', label: 'Respond to defect' },
  { field: 'tyreConditionF', label: '' },
  { field: 'seatBelts', label: '3. Seat belts - সীটবেল্ট' },
  { field: 'seatBeltsR', label: '' },
  { field: 'seatBeltsP', label: '' },
  { field: 'seatBeltsA', label: 'Respond to defect' },
  { field: 'seatBeltsF', label: '' },
  { field: 'mirrors', label: '4. Mirrors - মিরররস' },
  { field: 'mirrorsR', label: '' },
  { field: 'mirrorsP', label: '' },
  { field: 'mirrorsA', label: 'Respond to defect' },
  { field: 'mirrorsF', label: '' },
  { field: 'waterOilLevel', label: '5. Water/oil level - ওয়াটার/অয়েল লেভেল' },
  { field: 'waterOilLevelR', label: '' },
  { field: 'waterOilLevelP', label: '' },
  { field: 'waterOilLevelA', label: 'Respond to defect' },
  { field: 'waterOilLevelF', label: '' },
  { field: 'brakeFluid', label: '6. Brake fluid - ব্রেকফ্লুইড' },
  { field: 'brakeFluidR', label: '' },
  { field: 'brakeFluidP', label: '' },
  { field: 'brakeFluidA', label: 'Respond to defect' },
  { field: 'brakeFluidF', label: '' },
  { field: 'gaugesWorking', label: '7. Gauges working - গেজ ওয়ার্কিং' },
  { field: 'gaugesWorkingR', label: '' },
  { field: 'gaugesWorkingP', label: '' },
  { field: 'gaugesWorkingA', label: 'Respond to defect' },
  { field: 'gaugesWorkingF', label: '' },
  { field: 'indicators', label: '8. Indicators - ইন্ডিকেটরস' },
  { field: 'indicatorsR', label: '' },
  { field: 'indicatorsP', label: '' },
  { field: 'indicatorsA', label: 'Respond to defect' },
  { field: 'indicatorsF', label: '' },
  {
    field: 'headParkLights',
    label: '9. Head/parking lights - হেড/পার্কিং লাইটস',
  },
  { field: 'headParkLightsR', label: '' },
  { field: 'headParkLightsP', label: '' },
  { field: 'headParkLightsA', label: 'Respond to defect' },
  { field: 'headParkLightsF', label: '' },
  { field: 'tailStopLights', label: '10. Tail/stop lights - টেইল/স্টপ লাইটস' },
  { field: 'tailStopLightsR', label: '' },
  { field: 'tailStopLightsP', label: '' },
  { field: 'tailStopLightsA', label: 'Respond to defect' },
  { field: 'tailStopLightsF', label: '' },
  {
    field: 'brakesHandFoot',
    label: '11. Brakes hand/foot - হাতের/পায়ের ব্রেক',
  },
  { field: 'brakesHandFootR', label: '' },
  { field: 'brakesHandFootP', label: '' },
  { field: 'brakesHandFootA', label: 'Respond to defect' },
  { field: 'brakesHandFootF', label: '' },
  { field: 'wipersWasher', label: '12. Wipers/washer - ওয়াইপার/ওয়াশার' },
  { field: 'wipersWasherR', label: '' },
  { field: 'wipersWasherP', label: '' },
  { field: 'wipersWasherA', label: 'Respond to defect' },
  { field: 'wipersWasherF', label: '' },
  { field: 'horn', label: '13. Horn - হৰ্ণ' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  {
    field: 'firstAidKit',
    label: '14. First Aid Kit - প্রাথমিক চিকিৎসার সরঞ্জাম',
  },
  { field: 'firstAidKitR', label: '' },
  { field: 'firstAidKitP', label: '' },
  { field: 'firstAidKitA', label: 'Respond to defect' },
  { field: 'firstAidKitF', label: '' },
  { field: 'safetyTriangle', label: '15. Safety Triangle - সেফটিট্রায়াঙ্গল' },
  { field: 'safetyTriangleR', label: '' },
  { field: 'safetyTriangleP', label: '' },
  { field: 'safetyTriangleA', label: 'Respond to defect' },
  { field: 'safetyTriangleF', label: '' },
  { field: 'toolbox', label: '16. Toolbox - টুলবক্স' },
  { field: 'toolboxR', label: '' },
  { field: 'toolboxP', label: '' },
  { field: 'toolboxA', label: 'Respond to defect' },
  { field: 'toolboxF', label: '' },
  {
    field: 'rotaryFlashLamp',
    label: '17. Rotary/ Flash lamp - রোটারি/ ফ্ল্যাশ ল্যাম্প',
  },
  { field: 'rotaryFlashLampR', label: '' },
  { field: 'rotaryFlashLampP', label: '' },
  { field: 'rotaryFlashLampA', label: 'Respond to defect' },
  { field: 'rotaryFlashLampF', label: '' },
  {
    field: 'reflectiveStrip',
    label: '18. Reflective Strip - রিফ্লেক্টিভ স্ট্রিপ',
  },
  { field: 'reflectiveStripR', label: '' },
  { field: 'reflectiveStripP', label: '' },
  { field: 'reflectiveStripA', label: 'Respond to defect' },
  { field: 'reflectiveStripF', label: '' },
  { field: 'vehicleNumbers', label: '19. Vehicle Numbers - গাড়ির নম্বর' },
  { field: 'vehicleNumbersR', label: '' },
  { field: 'vehicleNumbersP', label: '' },
  { field: 'vehicleNumbersA', label: 'Respond to defect' },
  { field: 'vehicleNumbersF', label: '' },
  {
    field: 'communicationRadio',
    label: '20. Communication radio - যোগাযোগ রেডিও',
  },
  { field: 'communicationRadioR', label: '' },
  { field: 'communicationRadioP', label: '' },
  { field: 'communicationRadioA', label: 'Respond to defect' },
  { field: 'communicationRadioF', label: '' },
  { field: 'remark', label: 'মন্তব্য - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
