export const questions = [
  {
    id: 1,
    name: 'hose',
    question: 'สภาพสายฉีด ไม่แตกร้าว ขาด ชำรุด Hose Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ',
  },
  {
    id: 2,
    name: 'handle',
    question: 'สลัก คันบีบ พร้อมซีลล็อคอยู่ในสภาพเรียบร้อย Handle Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ',
  },
  {
    id: 3,
    name: 'cylinder',
    question: 'สภาพถัง ไม่บุบ หรือบวม และไม่ขึ้นสนิม Cylinder Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ',
  },
  {
    id: 4,
    name: 'gauge',
    question: 'เกจความดัน/น้ำหนัก เข็มชี้ตรงแถบสีเขียว/ตรงกลาง Gauge',
    howto: 'สายตา / สัมผัส / ชั่งน้ำหนัก',
    accept: 'มีน้ำหนัก เข็มชี้ตรงแถบสีเขียว',
  },
  {
    id: 5,
    name: 'obstruction',
    question: 'ติดตั้งในที่มองเห็นชัดเจน ไม่มีสิ่งกีดขวาง Obstruction',
    howto: 'สายตา',
    accept: 'เห็นชัดเจน เข้าถึงได้ง่าย',
  },
  {
    id: 6,
    name: 'cabinet',
    question: 'สภาพตู้เก็บถังดับเพลิง Cabinet',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ ไม่ผุพัง',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'hose', label: '1. สภาพสายฉีด ไม่แตกร้าว ขาด ชำรุด Hose Condition' },
  { field: 'hoseR', label: '' },
  { field: 'hoseP', label: '' },
  { field: 'hoseA', label: 'Respond to defect' },
  { field: 'hoseF', label: '' },
  {
    field: 'handle',
    label: '2. สลัก คันบีบ พร้อมซีลล็อคอยู่ในสภาพเรียบร้อย Handle Condition',
  },
  { field: 'handleR', label: '' },
  { field: 'handleP', label: '' },
  { field: 'handleA', label: 'Respond to defect' },
  { field: 'handleF', label: '' },
  {
    field: 'cylinder',
    label: '3. สภาพถัง ไม่บุบ หรือบวม และไม่ขึ้นสนิม Cylinder Condition',
  },
  { field: 'cylinderR', label: '' },
  { field: 'cylinderP', label: '' },
  { field: 'cylinderA', label: 'Respond to defect' },
  { field: 'cylinderF', label: '' },
  {
    field: 'gauge',
    label: '4. เกจความดัน/น้ำหนัก เข็มชี้ตรงแถบสีเขียว/ตรงกลาง Gauge',
  },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'Respond to defect' },
  { field: 'gaugeF', label: '' },
  {
    field: 'obstruction',
    label: '5. ติดตั้งในที่มองเห็นชัดเจน ไม่มีสิ่งกีดขวาง Obstruction',
  },
  { field: 'obstructionR', label: '' },
  { field: 'obstructionP', label: '' },
  { field: 'obstructionA', label: 'Respond to defect' },
  { field: 'obstructionF', label: '' },
  { field: 'cabinet', label: '6. สภาพตู้เก็บถังดับเพลิง Cabinet' },
  { field: 'cabinetR', label: '' },
  { field: 'cabinetP', label: '' },
  { field: 'cabinetA', label: 'Respond to defect' },
  { field: 'cabinetF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
