export const questions = [
  {
    id: 1,
    name: 'forkliftCondition',
    question: 'Forklift Condition',
    howto: 'Inspect the condition of forks, backrest, and carriage.',
    accept: 'Forklift is in normal condition.',
  },
  {
    id: 2,
    name: 'beltAndChain',
    question: 'Belt and Chain',
    howto: 'Check if the belt and chain system is in good condition.',
    accept: 'Belt and chain system is functioning normally.',
  },
  {
    id: 3,
    name: 'hydraulicLine',
    question: 'All Hydraulic Lines',
    howto: 'Ensure there are no hydraulic leaks or other leaks.',
    accept: 'Hydraulic system is in good condition.',
  },
  {
    id: 4,
    name: 'rop',
    question: 'Overhead Guard',
    howto: 'Check if the overhead guard is adequate and in good condition.',
    accept: 'Overhead guard is adequate and in good condition.',
  },
  {
    id: 5,
    name: 'fuelLevel',
    question: 'Fuel Level',
    howto:
      'Check if the fuel level, engine oil, and radiator water level are sufficient.',
    accept: 'Fuel level is sufficient.',
  },
  {
    id: 6,
    name: 'seatAndSeatBelt',
    question: 'Seat and Seat Belt',
    howto:
      'Check if the seat is in good condition and the seat belt is functional.',
    accept: 'Seat is in good condition and the seat belt is functional.',
  },
  {
    id: 7,
    name: 'electricalSystem',
    question: 'Electrical System',
    howto: 'Inspect for any faults in the electrical system.',
    accept: 'No faults in the electrical system.',
  },
  {
    id: 8,
    name: 'batteryCondition',
    question: 'Battery Condition',
    howto: 'Check battery terminals and overall battery condition.',
    accept: 'No faults in the battery.',
  },
  {
    id: 9,
    name: 'hornSystem',
    question: 'Horn System',
    howto: 'Check the functionality of the front and rear horns.',
    accept: 'No faults in the front and rear horns.',
  },
  {
    id: 10,
    name: 'lampCondition',
    question: 'All Lights Condition',
    howto:
      'Inspect main lights, signal lights, brake lights, and parking lights.',
    accept: 'No faults in the lights.',
  },
  {
    id: 11,
    name: 'beaconLamp',
    question: 'Beacon Light Condition',
    howto: 'Check if the beacon lights are functional.',
    accept: 'No faults in the beacon lights.',
  },
  {
    id: 12,
    name: 'gauge',
    question: 'Gauges',
    howto: 'Ensure that gauges are functioning properly.',
    accept: 'No faults in the gauges.',
  },
  {
    id: 13,
    name: 'brakeSystem',
    question: 'Brake System',
    howto: 'Check the condition of the foot brake and parking brake.',
    accept: 'No faults in the brake system.',
  },
  {
    id: 14,
    name: 'steeringSystem',
    question: 'Steering System',
    howto: 'Check if the steering system is operating correctly.',
    accept: 'No faults in the steering system.',
  },
  {
    id: 15,
    name: 'fireExtinguisher',
    question: 'Fire Extinguisher',
    howto:
      'Ensure the fire extinguisher is in good condition and has been inspected monthly.',
    accept: 'No faults in the fire extinguisher.',
  },
  {
    id: 16,
    name: 'thirdPartyLiftingCertificate',
    question: 'Third-Party Lifting Certificate',
    howto: 'Is the third-party lifting certificate valid within the year?',
    accept: 'The third-party lifting certificate is valid within the year.',
  },
  {
    id: 17,
    name: 'operatorCertificate',
    question: 'Certified Operator',
    howto:
      'Has the forklift operator been certified by a recognized institution?',
    accept: 'The forklift operator is certified by a recognized institution.',
  },
  {
    id: 18,
    name: 'tyreCondition',
    question: 'Tire Condition',
    howto: 'Inspect if the tires are worn out.',
    accept: 'All tires are in good condition.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Inspector' },
  { field: 'responder', label: 'Responder' },

  { field: 'forkliftCondition', label: '1. Forklift Condition *' },
  { field: 'forkliftConditionR', label: '' },
  { field: 'forkliftConditionP', label: '' },
  { field: 'forkliftConditionA', label: 'Respond to defect' },
  { field: 'forkliftConditionF', label: '' },

  { field: 'beltAndChain', label: '2. Belt and Chain *' },
  { field: 'beltAndChainR', label: '' },
  { field: 'beltAndChainP', label: '' },
  { field: 'beltAndChainA', label: 'Respond to defect' },
  { field: 'beltAndChainF', label: '' },

  { field: 'hydraulicLine', label: '3. All Hydraulic Lines *' },
  { field: 'hydraulicLineR', label: '' },
  { field: 'hydraulicLineP', label: '' },
  { field: 'hydraulicLineA', label: 'Respond to defect' },
  { field: 'hydraulicLineF', label: '' },

  { field: 'rop', label: '4. Overhead Guard *' },
  { field: 'ropR', label: '' },
  { field: 'ropP', label: '' },
  { field: 'ropA', label: 'Respond to defect' },
  { field: 'ropF', label: '' },

  { field: 'fuelLevel', label: '5. Fuel Level *' },
  { field: 'fuelLevelR', label: '' },
  { field: 'fuelLevelP', label: '' },
  { field: 'fuelLevelA', label: 'Respond to defect' },
  { field: 'fuelLevelF', label: '' },

  { field: 'seatAndSeatBelt', label: '6. Seat and Seat Belt *' },
  { field: 'seatAndSeatBeltR', label: '' },
  { field: 'seatAndSeatBeltP', label: '' },
  { field: 'seatAndSeatBeltA', label: 'Respond to defect' },
  { field: 'seatAndSeatBeltF', label: '' },

  { field: 'electricalSystem', label: '7. Electrical System *' },
  { field: 'electricalSystemR', label: '' },
  { field: 'electricalSystemP', label: '' },
  { field: 'electricalSystemA', label: 'Respond to defect' },
  { field: 'electricalSystemF', label: '' },

  { field: 'batteryCondition', label: '8. Battery Condition *' },
  { field: 'batteryConditionR', label: '' },
  { field: 'batteryConditionP', label: '' },
  { field: 'batteryConditionA', label: 'Respond to defect' },
  { field: 'batteryConditionF', label: '' },

  { field: 'hornSystem', label: '9. Horn System *' },
  { field: 'hornSystemR', label: '' },
  { field: 'hornSystemP', label: '' },
  { field: 'hornSystemA', label: 'Respond to defect' },
  { field: 'hornSystemF', label: '' },

  { field: 'lampCondition', label: '10. Condition of All Lamps *' },
  { field: 'lampConditionR', label: '' },
  { field: 'lampConditionP', label: '' },
  { field: 'lampConditionA', label: 'Respond to defect' },
  { field: 'lampConditionF', label: '' },

  { field: 'beaconLamp', label: '11. Beacon Lamp Condition *' },
  { field: 'beaconLampR', label: '' },
  { field: 'beaconLampP', label: '' },
  { field: 'beaconLampA', label: 'Respond to defect' },
  { field: 'beaconLampF', label: '' },

  { field: 'gauge', label: '12. Gauges *' },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'Respond to defect' },
  { field: 'gaugeF', label: '' },

  { field: 'brakeSystem', label: '13. Brake System *' },
  { field: 'brakeSystemR', label: '' },
  { field: 'brakeSystemP', label: '' },
  { field: 'brakeSystemA', label: 'Respond to defect' },
  { field: 'brakeSystemF', label: '' },

  { field: 'steeringSystem', label: '14. Steering System *' },
  { field: 'steeringSystemR', label: '' },
  { field: 'steeringSystemP', label: '' },
  { field: 'steeringSystemA', label: 'Respond to defect' },
  { field: 'steeringSystemF', label: '' },

  { field: 'fireExtinguisher', label: '15. Fire Extinguisher *' },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },

  {
    field: 'thirdPartyLiftingCertificate',
    label: '16. Third-Party Lifting Certificate *',
  },
  { field: 'thirdPartyLiftingCertificateR', label: '' },
  { field: 'thirdPartyLiftingCertificateP', label: '' },
  { field: 'thirdPartyLiftingCertificateA', label: 'Respond to defect' },
  { field: 'thirdPartyLiftingCertificateF', label: '' },

  { field: 'operatorCertificate', label: '17. Certified Operator? *' },
  { field: 'operatorCertificateR', label: '' },
  { field: 'operatorCertificateP', label: '' },
  { field: 'operatorCertificateA', label: 'Respond to defect' },
  { field: 'operatorCertificateF', label: '' },

  { field: 'tyreCondition', label: '18. tyreCondition' },
  { field: 'tyreConditionR', label: '' },
  { field: 'tyreConditionP', label: '' },
  { field: 'tyreConditionA', label: 'Respond to defect' },
  { field: 'tyreConditionF', label: '' },
  { field: 'remark', label: 'Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
