export const questions = [
  {
    id: 1,
    name: 'engineOilLevel',
    question: 'ระดับน้ำมันหล่อลื่นเครื่องยนต์',
    howto: 'ตรวจสอบระดับด้วยก้านวัดน้ำมัน',
    accept: 'ระดับอยู่ในช่วงที่กำหนดบนก้านวัด',
  },
  {
    id: 2,
    name: 'autoGearOilLevel',
    question: 'ระดับน้ำมันเกียรต์ออโต้',
    howto: 'ตรวจสอบด้วยก้านวัดน้ำมันเกียร์',
    accept: 'ระดับอยู่ในช่วงที่กำหนดบนก้านวัด',
  },
  {
    id: 3,
    name: 'brakeOilAndPedalFreePlay',
    question: 'ระดับน้ำมันเบรก และระยะฟรีของแป้นเบรค',
    howto: 'ตรวจสอบระดับน้ำมันเบรกในกระปุกและทดสอบระยะฟรีแป้นเบรก',
    accept:
      'ระดับน้ำมันเบรกอยู่ในช่วงปกติ และระยะฟรีของแป้นเบรกไม่เกินค่ามาตรฐาน',
  },
  {
    id: 4,
    name: 'steeringOilAndFreePlay',
    question: 'ระดับน้ำมันเพาเวอร์พวงมาลัย และระยะฟรีพวงมาลัย',
    howto: 'ตรวจสอบระดับน้ำมันเพาเวอร์และหมุนพวงมาลัยเพื่อตรวจสอบระยะฟรี',
    accept: 'ระดับน้ำมันเพาเวอร์อยู่ในเกณฑ์ และระยะฟรีพวงมาลัยไม่เกินมาตรฐาน',
  },
  {
    id: 5,
    name: 'hydraulicSealAndLeaks',
    question: 'รอยรั่วตามซีลกระบอกไฮโดรลิกและที่พื้น',
    howto: 'ตรวจสอบด้วยสายตาในบริเวณซีลและพื้น',
    accept: 'ไม่มีรอยรั่วที่ซีลและบริเวณพื้น',
  },
  {
    id: 6,
    name: 'bucketCondition',
    question: 'ตรวจสอบสภาพบุ้งกี๋',
    howto: 'ตรวจสอบด้วยสายตาและการใช้งาน',
    accept: 'ไม่มีรอยแตกหรือชำรุดที่บุ้งกี๋',
  },
  {
    id: 7,
    name: 'tiresAndRims',
    question: 'สภาพของยางและกะทะล้อ',
    howto: 'ตรวจสอบรอยแตก การสึกหรอ และความดันลม',
    accept: 'ยางไม่มีรอยแตก การสึกหรอเกินมาตรฐาน และกะทะล้อไม่เสียหาย',
  },
  {
    id: 8,
    name: 'beltTension',
    question: 'ความตึงของสายพาน',
    howto: 'ตรวจสอบด้วยการกดสายพานหรือวัดความตึง',
    accept: 'สายพานมีความตึงในระดับปกติ',
  },
  {
    id: 9,
    name: 'dashboardWarningLights',
    question: 'ไฟเตือนบนแผงหน้าปัด',
    howto: 'ตรวจสอบการทำงานของไฟเตือนต่างๆ',
    accept: 'ไฟเตือนทำงานปกติ ไม่มีไฟแจ้งเตือนผิดปกติ',
  },
  {
    id: 10,
    name: 'hornAndLights',
    question: 'การทำงานของแตร,ไฟเบรค,ไฟเลี้ยว,ไฟถอย',
    howto: 'ทดสอบการใช้งานแตรและไฟต่างๆ',
    accept: 'แตรและไฟทั้งหมดทำงานปกติ',
  },
  {
    id: 11,
    name: 'tireCondition',
    question: 'สภาพของยาง',
    howto: 'ตรวจสอบรอยแตกและการสึกหรอ',
    accept: 'ยางไม่มีรอยแตกหรือสึกหรอเกินมาตรฐาน',
  },
  {
    id: 12,
    name: 'fuelLevel',
    question: 'ระดับน้ำมันเชื้อเพลิง',
    howto: 'ตรวจสอบระดับน้ำมันเชื้อเพลิงในถัง',
    accept: 'ระดับน้ำมันอยู่ในช่วงเพียงพอสำหรับการใช้งาน',
  },
  {
    id: 13,
    name: 'airFilterCleaning',
    question: 'เป่ากรองอากาศ',
    howto: 'ถอดและทำความสะอาดกรองอากาศ',
    accept: 'กรองอากาศสะอาด ไม่มีฝุ่นอุดตัน',
  },
  {
    id: 14,
    name: 'batteryWaterLevel',
    question: 'ระดับน้ำกลั่นในแบตเตอรี่น้ำกลั่น',
    howto: 'ตรวจสอบระดับน้ำกลั่นในแบตเตอรี่',
    accept: 'ระดับน้ำกลั่นอยู่ในช่วงที่กำหนด',
  },
  {
    id: 15,
    name: 'cleaning',
    question: 'ทำความสะอาด',
    howto: 'เช็ดทำความสะอาดทั้งภายนอกและภายใน',
    accept: 'ทำความสะอาดเรียบร้อย ไม่มีคราบสกปรก',
  },
  {
    id: 16,
    name: 'handBrake',
    question: 'การทำงานของเบรคมือ',
    howto: 'ทดสอบการดึงและล็อคเบรคมือ',
    accept: 'เบรคมือใช้งานได้ดี ไม่มีการลื่นหลุด',
  },
  {
    id: 17,
    name: 'forwardReverseControl',
    question: 'การควบคุมเดินหน้า-หลัง',
    howto: 'ทดสอบการเปลี่ยนเกียร์และควบคุมการเดินหน้า-หลัง',
    accept: 'ระบบควบคุมเดินหน้า-หลังทำงานได้ดี',
  },
  {
    id: 18,
    name: 'steeringFunction',
    question: 'การทำงานของระบบเลี้ยว',
    howto: 'ทดสอบการเลี้ยวซ้ายและขวา',
    accept: 'ระบบเลี้ยวตอบสนองได้ดี ไม่มีปัญหา',
  },
  {
    id: 19,
    name: 'brakeFunction',
    question: 'การทำงานของเบรก',
    howto: 'ทดสอบการหยุดรถในระยะที่กำหนด',
    accept: 'เบรกทำงานได้ดี รถหยุดในระยะที่ปลอดภัย',
  },
  {
    id: 20,
    name: 'turnSignalLights',
    question: 'ไฟเลี้ยว ซ้าย ขวา',
    howto: 'ทดสอบการใช้งานไฟเลี้ยวทั้งสองด้าน',
    accept: 'ไฟเลี้ยวซ้ายและขวาทำงานปกติ',
  },
  {
    id: 21,
    name: 'reverseLights',
    question: 'ไฟถอยหลัง',
    howto: 'ทดสอบการใช้งานไฟถอยหลัง',
    accept: 'ไฟถอยหลังทำงานปกติ',
  },
  {
    id: 22,
    name: 'signalLights',
    question: 'ไฟสัญญาณทำงาน',
    howto: 'ตรวจสอบไฟสัญญาณทั้งหมด',
    accept: 'ไฟสัญญาณทำงานครบถ้วนและปกติ',
  },
  {
    id: 23,
    name: 'fireExtinguisher',
    question: 'ถังดับเพลิงประจำรถ',
    howto: 'ตรวจสอบถังดับเพลิงและเกจแรงดัน',
    accept: 'ถังดับเพลิงอยู่ในสภาพพร้อมใช้งาน เกจแรงดันอยู่ในโซนสีเขียว',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'engineOilLevel', label: '1 ระดับน้ำมันหล่อลื่นเครื่องยนต์' },
  { field: 'engineOilLevelR', label: '' },
  { field: 'engineOilLevelP', label: '' },
  { field: 'engineOilLevelA', label: 'Respond to defect' },
  { field: 'engineOilLevelF', label: '' },
  { field: 'autoGearOilLevel', label: '2 ระดับน้ำมันเกียรต์ออโต้' },
  { field: 'autoGearOilLevelR', label: '' },
  { field: 'autoGearOilLevelP', label: '' },
  { field: 'autoGearOilLevelA', label: 'Respond to defect' },
  { field: 'autoGearOilLevelF', label: '' },
  {
    field: 'brakeOilAndPedalFreePlay',
    label: '3 ระดับน้ำมันเบรก และระยะฟรีของแป้นเบรค',
  },
  { field: 'brakeOilAndPedalFreePlayR', label: '' },
  { field: 'brakeOilAndPedalFreePlayP', label: '' },
  { field: 'brakeOilAndPedalFreePlayA', label: 'Respond to defect' },
  { field: 'brakeOilAndPedalFreePlayF', label: '' },
  {
    field: 'steeringOilAndFreePlay',
    label: '4 ระดับน้ำมันเพาเวอร์พวงมาลัย และระยะฟรีพวงมาลัย',
  },
  { field: 'steeringOilAndFreePlayR', label: '' },
  { field: 'steeringOilAndFreePlayP', label: '' },
  { field: 'steeringOilAndFreePlayA', label: 'Respond to defect' },
  { field: 'steeringOilAndFreePlayF', label: '' },
  {
    field: 'hydraulicSealAndLeaks',
    label: '5 รอยรั่วตามซีลกระบอกไฮโดรลิกและที่พื้น',
  },
  { field: 'hydraulicSealAndLeaksR', label: '' },
  { field: 'hydraulicSealAndLeaksP', label: '' },
  { field: 'hydraulicSealAndLeaksA', label: 'Respond to defect' },
  { field: 'hydraulicSealAndLeaksF', label: '' },
  { field: 'bucketCondition', label: '6 ตรวจสอบสภาพบุ้งกี๋' },
  { field: 'bucketConditionR', label: '' },
  { field: 'bucketConditionP', label: '' },
  { field: 'bucketConditionA', label: 'Respond to defect' },
  { field: 'bucketConditionF', label: '' },
  { field: 'tiresAndRims', label: '7 สภาพของยางและกะทะล้อ' },
  { field: 'tiresAndRimsR', label: '' },
  { field: 'tiresAndRimsP', label: '' },
  { field: 'tiresAndRimsA', label: 'Respond to defect' },
  { field: 'tiresAndRimsF', label: '' },
  { field: 'beltTension', label: '8 ความตึงของสายพาน' },
  { field: 'beltTensionR', label: '' },
  { field: 'beltTensionP', label: '' },
  { field: 'beltTensionA', label: 'Respond to defect' },
  { field: 'beltTensionF', label: '' },
  { field: 'dashboardWarningLights', label: '9 ไฟเตือนบนแผงหน้าปัด' },
  { field: 'dashboardWarningLightsR', label: '' },
  { field: 'dashboardWarningLightsP', label: '' },
  { field: 'dashboardWarningLightsA', label: 'Respond to defect' },
  { field: 'dashboardWarningLightsF', label: '' },
  { field: 'hornAndLights', label: '10 การทำงานของแตร,ไฟเบรค,ไฟเลี้ยว,ไฟถอย' },
  { field: 'hornAndLightsR', label: '' },
  { field: 'hornAndLightsP', label: '' },
  { field: 'hornAndLightsA', label: 'Respond to defect' },
  { field: 'hornAndLightsF', label: '' },
  { field: 'tireCondition', label: '11 สภาพของยาง' },
  { field: 'tireConditionR', label: '' },
  { field: 'tireConditionP', label: '' },
  { field: 'tireConditionA', label: 'Respond to defect' },
  { field: 'tireConditionF', label: '' },
  { field: 'fuelLevel', label: '12 ระดับน้ำมันเชื้อเพลิง' },
  { field: 'fuelLevelR', label: '' },
  { field: 'fuelLevelP', label: '' },
  { field: 'fuelLevelA', label: 'Respond to defect' },
  { field: 'fuelLevelF', label: '' },
  { field: 'airFilterCleaning', label: '13 เป่ากรองอากาศ' },
  { field: 'airFilterCleaningR', label: '' },
  { field: 'airFilterCleaningP', label: '' },
  { field: 'airFilterCleaningA', label: 'Respond to defect' },
  { field: 'airFilterCleaningF', label: '' },
  { field: 'batteryWaterLevel', label: '14 ระดับน้ำกลั่นในแบตเตอรี่น้ำกลั่น' },
  { field: 'batteryWaterLevelR', label: '' },
  { field: 'batteryWaterLevelP', label: '' },
  { field: 'batteryWaterLevelA', label: 'Respond to defect' },
  { field: 'batteryWaterLevelF', label: '' },
  { field: 'cleaning', label: '15 ทำความสะอาด' },
  { field: 'cleaningR', label: '' },
  { field: 'cleaningP', label: '' },
  { field: 'cleaningA', label: 'Respond to defect' },
  { field: 'cleaningF', label: '' },
  { field: 'handBrake', label: '16 การทำงานของเบรคมือ' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'forwardReverseControl', label: '17 การควบคุมเดินหน้า-หลัง' },
  { field: 'forwardReverseControlR', label: '' },
  { field: 'forwardReverseControlP', label: '' },
  { field: 'forwardReverseControlA', label: 'Respond to defect' },
  { field: 'forwardReverseControlF', label: '' },
  { field: 'steeringFunction', label: '18 การทำงานของระบบเลี้ยว' },
  { field: 'steeringFunctionR', label: '' },
  { field: 'steeringFunctionP', label: '' },
  { field: 'steeringFunctionA', label: 'Respond to defect' },
  { field: 'steeringFunctionF', label: '' },
  { field: 'brakeFunction', label: '19 การทำงานของเบรก' },
  { field: 'brakeFunctionR', label: '' },
  { field: 'brakeFunctionP', label: '' },
  { field: 'brakeFunctionA', label: 'Respond to defect' },
  { field: 'brakeFunctionF', label: '' },
  { field: 'turnSignalLights', label: '20 ไฟเลี้ยว ซ้าย ขวา' },
  { field: 'turnSignalLightsR', label: '' },
  { field: 'turnSignalLightsP', label: '' },
  { field: 'turnSignalLightsA', label: 'Respond to defect' },
  { field: 'turnSignalLightsF', label: '' },
  { field: 'reverseLights', label: '21 ไฟถอยหลัง' },
  { field: 'reverseLightsR', label: '' },
  { field: 'reverseLightsP', label: '' },
  { field: 'reverseLightsA', label: 'Respond to defect' },
  { field: 'reverseLightsF', label: '' },
  { field: 'signalLights', label: '22 ไฟสัญญาณทำงาน' },
  { field: 'signalLightsR', label: '' },
  { field: 'signalLightsP', label: '' },
  { field: 'signalLightsA', label: 'Respond to defect' },
  { field: 'signalLightsF', label: '' },
  { field: 'fireExtinguisher', label: '23 ถังดับเพลิงประจำรถ' },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
