export const questions = [
  {
    id: 1,
    name: 'buoyCondition',
    question:
      'Phao có trong tình trạng tốt không? / Is the buoy in good condition?',
    howto: 'Kiểm tra tổng thể tình trạng bề ngoài của phao để phát hiện các hư hỏng rõ ràng.',
    accept: 'Phao trong tình trạng tốt, không có hư hỏng rõ ràng.',
  },
  {
    id: 2,
    name: 'serialNumberIdentification',
    question:
      'Có số hiệu/số sêri để nhận dạng không? / Is there a serial number/mark for identification?',
    howto: 'Kiểm tra xem phao có được đánh dấu số hiệu hoặc số sêri để nhận dạng rõ ràng không.',
    accept: 'Có số hiệu/số sêri được đánh dấu rõ ràng để nhận dạng.',
  },
  {
    id: 3,
    name: 'noExcessiveContamination',
    question:
      'Không có dầu, mỡ hay bụi quá mức? / No excessive oil, grease or dust?',
    howto: 'Kiểm tra bề mặt phao xem có tích tụ dầu, mỡ hoặc bụi quá mức không.',
    accept: 'Không có dầu, mỡ hay bụi tích tụ quá mức.',
  },
  {
    id: 4,
    name: 'noSaltBuildupCorrosion',
    question:
      'Không có sự tích tụ muối hay ăn mòn các dây? / No salt build-up or corrosion on the ropes?',
    howto: 'Kiểm tra các dây cáp kết nối với phao để phát hiện sự tích tụ muối hoặc ăn mòn.',
    accept: 'Không có sự tích tụ muối hay ăn mòn trên các dây cáp.',
  },
  {
    id: 5,
    name: 'webbingCondition',
    question:
      'Dây đai xung quanh có trong điều kiện tốt không? / Is the surrounding webbing in good condition?',
    howto: 'Kiểm tra tình trạng của dây đai xung quanh phao để phát hiện hư hỏng.',
    accept: 'Dây đai xung quanh trong điều kiện tốt.',
  },
  {
    id: 6,
    name: 'coveringFabricIntegrity',
    question:
      'Vải bọc có bị rách không? / Is the covering fabric torn?',
    howto: 'Kiểm tra vải bọc của phao để phát hiện các vết rách hoặc hư hỏng.',
    accept: 'Vải bọc không bị rách.',
  },
  {
    id: 7,
    name: 'connectingRopeCondition',
    question:
      'Dây nối với phao có đủ dài, không bị hư và cuốn đúng không? / Is the rope connecting the buoy long enough, not damaged, and properly wound?',
    howto: 'Kiểm tra chiều dài, tình trạng và cách cuốn của dây nối với phao.',
    accept: 'Dây nối với phao đủ dài, không bị hư hỏng và được cuốn đúng cách.',
  },
  {
    id: 8,
    name: 'reflectiveMaterialCondition',
    question:
      'Vật liệu phản quang có bị phai màu hay bị thiếu không? / Is the reflective material faded or missing?',
    howto: 'Kiểm tra tình trạng của vật liệu phản quang trên phao.',
    accept: 'Vật liệu phản quang không bị phai màu hay thiếu.',
  },
  {
    id: 9,
    name: 'buoyColorCondition',
    question:
      'Màu của phao có bị phai không? / Is the buoyant color faded?',
    howto: 'Kiểm tra màu sắc của phao để xem có bị phai hay không.',
    accept: 'Màu của phao không bị phai.',
  },
  {
    id: 10,
    name: 'plasticBuoyIntegrity',
    question:
      'Phao bằng nhựa có bị bể, nứt, hay mục nát không? / Is the plastic buoy broken, cracked, or rotted?',
    howto: 'Kiểm tra kỹ lưỡng phao nhựa để phát hiện các vết nứt, gãy hoặc mục nát.',
    accept: 'Phao bằng nhựa không bị bể, nứt, hay mục nát.',
  },
  {
    id: 11,
    name: 'webbingStrengthCondition',
    question:
      'Dây đai và vải làm đai có trong điều kiện tốt và đủ mạnh không? / Are the webbing and webbing in good condition and strong enough?',
    howto: 'Kiểm tra độ bền và tình trạng của dây đai và vải làm đai.',
    accept: 'Dây đai và vải làm đai trong điều kiện tốt và đủ mạnh.',
  },
  {
    id: 12,
    name: 'buoyancyEffectiveness',
    question:
      'Sức nổi của phao vẫn còn hiệu quả về năng suất được đánh giá như hướng dẫn của nhà sản xuất không? (chứng minh bằng cách thử dưới nước) / Is the buoyant still effective in terms of rated performance as recommended by the manufacturer? (prove by underwater test)',
    howto: 'Thực hiện thử nghiệm dưới nước để kiểm tra sức nổi của phao theo thông số kỹ thuật của nhà sản xuất.',
    accept: 'Sức nổi của phao vẫn hiệu quả theo thông số kỹ thuật của nhà sản xuất.',
  },
  {
    id: 13,
    name: 'properStorageRack',
    question:
      'Phao có được lưu giữ phù hợp trên giá sắt, trong phạm vi nhiệt độ hợp lý (dưới 60°C) không? / Is the buoy stored properly on a metal rack, within a reasonable temperature range (below 60°C)?',
    howto: 'Kiểm tra cách lưu trữ phao trên giá sắt và nhiệt độ môi trường lưu trữ.',
    accept: 'Phao được lưu giữ phù hợp trên giá sắt, trong phạm vi nhiệt độ dưới 60°C.',
  },
  {
    id: 14,
    name: 'cementDustProtection',
    question:
      'Phao có được lưu trữ tránh bụi xi măng bám không? / Is the buoy stored away from cement dust?',
    howto: 'Kiểm tra môi trường lưu trữ để đảm bảo phao không bị phơi nhiễm bụi xi măng.',
    accept: 'Phao được lưu trữ tránh xa bụi xi măng.',
  },
  {
    id: 15,
    name: 'dryStorageCondition',
    question:
      'Phao có được cất giữ ở nơi khô ráo không? (đối với phao đang được lưu trữ) / Is the buoy stored in a dry place? (for buoys in storage)',
    howto: 'Kiểm tra độ ẩm của môi trường lưu trữ phao.',
    accept: 'Phao được cất giữ ở nơi khô ráo.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'buoyCondition', label: '1. Phao có trong tình trạng tốt không? / Is the buoy in good condition?'},
  { field: 'buoyConditionR', label: '' },
  { field: 'buoyConditionP', label: '' },
  { field: 'buoyConditionA', label: '' },
  { field: 'buoyConditionF', label: '' },
  { field: 'serialNumberIdentification', label: '2. Có số hiệu/số sêri để nhận dạng không? / Is there a serial number/mark for identification?'},
  { field: 'serialNumberIdentificationR', label: '' },
  { field: 'serialNumberIdentificationP', label: '' },
  { field: 'serialNumberIdentificationA', label: '' },
  { field: 'serialNumberIdentificationF', label: '' },
  { field: 'noExcessiveContamination', label: '3. Không có dầu, mỡ hay bụi quá mức? / No excessive oil, grease or dust?'},
  { field: 'noExcessiveContaminationR', label: '' },
  { field: 'noExcessiveContaminationP', label: '' },
  { field: 'noExcessiveContaminationA', label: '' },
  { field: 'noExcessiveContaminationF', label: '' },
  { field: 'noSaltBuildupCorrosion', label: '4. Không có sự tích tụ muối hay ăn mòn các dây? / No salt build-up or corrosion on the ropes?'},
  { field: 'noSaltBuildupCorrosionR', label: '' },
  { field: 'noSaltBuildupCorrosionP', label: '' },
  { field: 'noSaltBuildupCorrosionA', label: '' },
  { field: 'noSaltBuildupCorrosionF', label: '' },
  { field: 'webbingCondition', label: '5. Dây đai xung quanh có trong điều kiện tốt không? / Is the surrounding webbing in good condition?'},
  { field: 'webbingConditionR', label: '' },
  { field: 'webbingConditionP', label: '' },
  { field: 'webbingConditionA', label: '' },
  { field: 'webbingConditionF', label: '' },
  { field: 'coveringFabricIntegrity', label: '6. Vải bọc có bị rách không? / Is the covering fabric torn?'},
  { field: 'coveringFabricIntegrityR', label: '' },
  { field: 'coveringFabricIntegrityP', label: '' },
  { field: 'coveringFabricIntegrityA', label: '' },
  { field: 'coveringFabricIntegrityF', label: '' },
  { field: 'connectingRopeCondition', label: '7. Dây nối với phao có đủ dài, không bị hư và cuốn đúng không? / Is the rope connecting the buoy long enough, not damaged, and properly wound?'},
  { field: 'connectingRopeConditionR', label: '' },
  { field: 'connectingRopeConditionP', label: '' },
  { field: 'connectingRopeConditionA', label: '' },
  { field: 'connectingRopeConditionF', label: '' },
  { field: 'reflectiveMaterialCondition', label: '8. Vật liệu phản quang có bị phai màu hay bị thiếu không? / Is the reflective material faded or missing?'},
  { field: 'reflectiveMaterialConditionR', label: '' },
  { field: 'reflectiveMaterialConditionP', label: '' },
  { field: 'reflectiveMaterialConditionA', label: '' },
  { field: 'reflectiveMaterialConditionF', label: '' },
  { field: 'buoyColorCondition', label: '9. Màu của phao có bị phai không? / Is the buoyant color faded?'},
  { field: 'buoyColorConditionR', label: '' },
  { field: 'buoyColorConditionP', label: '' },
  { field: 'buoyColorConditionA', label: '' },
  { field: 'buoyColorConditionF', label: '' },
  { field: 'plasticBuoyIntegrity', label: '10. Phao bằng nhựa có bị bể, nứt, hay mục nát không? / Is the plastic buoy broken, cracked, or rotted?'},
  { field: 'plasticBuoyIntegrityR', label: '' },
  { field: 'plasticBuoyIntegrityP', label: '' },
  { field: 'plasticBuoyIntegrityA', label: '' },
  { field: 'plasticBuoyIntegrityF', label: '' },
  { field: 'webbingStrengthCondition', label: '11. Dây đai và vải làm đai có trong điều kiện tốt và đủ mạnh không? / Are the webbing and webbing in good condition and strong enough?'},
  { field: 'webbingStrengthConditionR', label: '' },
  { field: 'webbingStrengthConditionP', label: '' },
  { field: 'webbingStrengthConditionA', label: '' },
  { field: 'webbingStrengthConditionF', label: '' },
  { field: 'buoyancyEffectiveness', label: '12. Sức nổi của phao vẫn còn hiệu quả về năng suất được đánh giá như hướng dẫn của nhà sản xuất không? (chứng minh bằng cách thử dưới nước) / Is the buoyant still effective in terms of rated performance as recommended by the manufacturer? (prove by underwater test)'},
  { field: 'buoyancyEffectivenessR', label: '' },
  { field: 'buoyancyEffectivenessP', label: '' },
  { field: 'buoyancyEffectivenessA', label: '' },
  { field: 'buoyancyEffectivenessF', label: '' },
  { field: 'properStorageRack', label: '13. Phao có được lưu giữ phù hợp trên giá sắt, trong phạm vi nhiệt độ hợp lý (dưới 60°C) không? / Is the buoy stored properly on a metal rack, within a reasonable temperature range (below 60°C)?'},
  { field: 'properStorageRackR', label: '' },
  { field: 'properStorageRackP', label: '' },
  { field: 'properStorageRackA', label: '' },
  { field: 'properStorageRackF', label: '' },
  { field: 'cementDustProtection', label: '14. Phao có được lưu trữ tránh bụi xi măng bám không? / Is the buoy stored away from cement dust?'},
  { field: 'cementDustProtectionR', label: '' },
  { field: 'cementDustProtectionP', label: '' },
  { field: 'cementDustProtectionA', label: '' },
  { field: 'cementDustProtectionF', label: '' },
  { field: 'dryStorageCondition', label: '15. Phao có được cất giữ ở nơi khô ráo không? (đối với phao đang được lưu trữ) / Is the buoy stored in a dry place? (for buoys in storage)'},
  { field: 'dryStorageConditionR', label: '' },
  { field: 'dryStorageConditionP', label: '' },
  { field: 'dryStorageConditionA', label: '' },
  { field: 'dryStorageConditionF', label: '' },
  { field: 'tag', label: 'Tag' },
  { field: 'collection', label: 'Type of Equipment' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
