export const questions = [
  {
    id: 1,
    name: 'steeringCondition',
    question: 'Steering condition* (স্টিয়ারিং অবস্থা)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'স্টিয়ারিং সিস্টেম সঠিক এবং কার্যকর অবস্থায় আছে',
  },
  {
    id: 2,
    name: 'tyreCondition',
    question: 'Tyre condition* (টায়ারের অবস্থা)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত টায়ার সঠিক এবং নিরাপদ আছে',
  },
  {
    id: 3,
    name: 'seatBelts',
    question: 'Seat belts* (সীট বেল্ট)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত সীট বেল্ট সঠিক এবং কার্যকর অবস্থায় আছে',
  },
  {
    id: 4,
    name: 'mirrors',
    question: 'Mirrors (মিরররস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'আয়নাগুলি পরিষ্কার, সামঞ্জস্যযোগ্য এবং ফাটল মুক্ত হওয়া উচিত।',
  },
  {
    id: 5,
    name: 'waterOilLevel',
    question: 'Water/oil level (ওয়াটার/অয়েল লেভেল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'পানি এবং তেলের মাত্রা নির্দিষ্ট সীমার মধ্যে হওয়া উচিত।',
  },
  {
    id: 6,
    name: 'brakeFluid',
    question: 'Brake fluid (ব্রেক ফ্লুইড)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'ব্রেক তরল উপযুক্ত মাত্রায় এবং দূষিত না হওয়া উচিত।',
  },
  {
    id: 7,
    name: 'powerSteeringFluid',
    question: 'Power steering fluid (পাওয়ার স্টিয়ারিং ফ্লুইড)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'পাওয়ার স্টিয়ারিং তরল সঠিক মাত্রায় এবং পরিষ্কার থাকা উচিত।',
  },
  {
    id: 8,
    name: 'gaugesWorking',
    question: 'Gauges working (গাউজেস ওয়ার্কিং)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত গেজগুলি ঠিকভাবে কাজ করা উচিত',
  },
  {
    id: 9,
    name: 'indicators',
    question: 'Indicators (ইন্ডিকেটরস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত ইন্ডিকেটরগুলি কার্যকর হওয়া উচিত',
  },
  {
    id: 10,
    name: 'headParkLights',
    question: 'Head/park lights (হেড/পার্ক লাইটস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'হেডলাইট এবং পার্ক লাইটগুলি কাজ করা এবং সঠিকভাবে সামঞ্জস্যপূর্ণ হওয়া উচিত',
  },
  {
    id: 11,
    name: 'tailStopLights',
    question: 'Tail/stop lights* (টেইল/স্টপ লাইটস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত টেল এবং স্টপ লাইটগুলি কার্যকর এবং ক্ষতিমুক্ত হওয়া উচিত',
  },
  {
    id: 12,
    name: 'brakesHandFoot',
    question: 'Brakes hand/foot* (ব্র্যাক্স হাত/পা)',
    howto: 'দৃষ্টিগত এবং কার্যকরী পরীক্ষা',
    accept: 'হ্যান্ড এবং ফুট ব্রেকগুলি সঠিকভাবে এবং কার্যকরভাবে কাজ করা উচিত',
  },
  {
    id: 13,
    name: 'wipersWasher',
    question: 'Wipers/washer (ওইপার্স/ওয়াশার)',
    howto: 'কার্যকরী পরীক্ষা',
    accept:
      'ওয়াইপার এবং ওয়াশার সঠিকভাবে কাজ করা এবং ওয়াশার তরলের পরিমাণ যথেষ্ট হওয়া উচিত',
  },
  {
    id: 14,
    name: 'horn',
    question: 'Horn* (হর্ন)',
    howto: 'কার্যকরী পরীক্ষা',
    accept: 'হর্নের শব্দ স্পষ্ট এবং সঠিক আওয়াজে হওয়া উচিত',
  },
  {
    id: 15,
    name: 'firstAidKit',
    question:
      'First Aid Kit (vehicles in public areas) (প্রাথমিক চিকিৎসার সরঞ্জাম)',
    howto: 'মজুদ পরীক্ষা',
    accept:
      'প্রাথমিক চিকিৎসা কিট উপস্থিত, সিলমোহরযুক্ত এবং সমস্ত প্রয়োজনীয় জিনিস সম্বলিত হওয়া উচিত',
  },
  {
    id: 16,
    name: 'safetyTriangle',
    question: 'Safety Triangle (সেফটি ট্রায়াঙ্গল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'নিরাপত্তা ত্রিভুজ উপস্থিত এবং ব্যবহারযোগ্য অবস্থায় হওয়া উচিত',
  },
  {
    id: 17,
    name: 'jack',
    question: 'Jack (জ্যাক)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'জ্যাক উপস্থিত এবং ভালো কাজ করা অবস্থায় হওয়া উচিত',
  },
  {
    id: 18,
    name: 'wheelSpanner',
    question: 'Wheel spanner (হুইল স্প্যানার)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'হুইল স্প্যানার সঠিক আকারের এবং ভালো অবস্থায় হওয়া উচিত',
  },
  {
    id: 19,
    name: 'jackHandle',
    question: 'Jack handle (জ্যাক হ্যান্ডেল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'জ্যাক হ্যান্ডেল উপস্থিত থাকা উচিত এবং ঠিকভাবে জ্যাকের সাথে মানানসই হওয়া উচিত',
  },
  {
    id: 20,
    name: 'rotaryFlashLamp',
    question: 'Rotary/ Flash lamp (রোটারি/ ফ্ল্যাশ ল্যাম্প)',
    howto: 'Functional test',
    accept: 'রোটারি/ফ্ল্যাশ ল্যাম্প কার্যকর এবং দৃশ্যমান হওয়া উচিত',
  },
  {
    id: 21,
    name: 'reflectiveStrip',
    question: 'Reflective Strip (রিফ্লেক্টিভ স্ট্রিপ)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'রিফ্লেক্টিভ স্ট্রিপ পরিষ্কার, অক্ষত, এবং ঠিকভাবে যানবাহনের সাথে সংযুক্ত থাকা উচিত',
  },
  {
    id: 22,
    name: 'vehicleNumbers',
    question: 'Vehicle Numbers (গাড়ির নম্বর)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'গাড়ির নম্বরগুলি স্পষ্টভাবে দৃশ্যমান এবং পাঠযোগ্য হওয়া উচিত',
  },
  {
    id: 23,
    name: 'communicationRadio',
    question: 'Communication radio (যোগাযোগ রেডিও)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'যোগাযোগ রেডিও সঠিকভাবে কাজ করছে এবং সঠিকভাবে সংযুক্ত আছে',
  },
];

export const detailFields = [
  { field: 'inspector', label: 'পরিদর্শক - Inspector' },
  { field: 'date', label: 'তারিখঃ - Date' },
  { field: 'runningMeter', label: 'রানিং মিটার রিডিং - Running Meter Reading' },
  {
    field: 'steeringCondition',
    label: 'স্টিয়ারিং অবস্থা - Steering Condition',
  },
  { field: 'steeringConditionR', label: '' },
  { field: 'tyreCondition', label: 'টায়ারের অবস্থা - Tyre Condition' },
  { field: 'tyreConditionR', label: '' },
  { field: 'seatBelts', label: 'সীট বেল্ট - Seat Belts' },
  { field: 'seatBeltsR', label: '' },
  { field: 'mirrors', label: 'মিরর - Mirrors' },
  { field: 'mirrorsR', label: '' },
  { field: 'waterOilLevel', label: 'ওয়াটার/অয়েল লেভেল - Water/Oil Level' },
  { field: 'waterOilLevelR', label: '' },
  { field: 'brakeFluid', label: 'ব্রেক ফ্লুইড - Brake Fluid' },
  { field: 'brakeFluidR', label: '' },
  {
    field: 'powerSteeringFluid',
    label: 'পাওয়ার স্টিয়ারিং ফ্লুইড - Power Steering Fluid',
  },
  { field: 'powerSteeringFluidR', label: '' },
  { field: 'gaugesWorking', label: 'গেজস কাজ করছে - Gauges Working' },
  { field: 'gaugesWorkingR', label: '' },
  { field: 'indicators', label: 'ইন্ডিকেটরস - Indicators' },
  { field: 'indicatorsR', label: '' },
  { field: 'headParkLights', label: 'হেড/পার্ক লাইটস - Head/Park Lights' },
  { field: 'headParkLightsR', label: '' },
  { field: 'tailStopLights', label: 'টেইল/স্টপ লাইটস - Tail/Stop Lights' },
  { field: 'tailStopLightsR', label: '' },
  { field: 'brakesHandFoot', label: 'হাত/পায়ের ব্রেক - Brakes Hand/Foot' },
  { field: 'brakesHandFootR', label: '' },
  { field: 'wipersWasher', label: 'ওয়াইপার/ওয়াশার - Wipers/Washer' },
  { field: 'wipersWasherR', label: '' },
  { field: 'horn', label: 'হর্ন - Horn' },
  { field: 'hornR', label: '' },
  { field: 'firstAidKit', label: 'ফার্স্ট এইড কিট - First Aid Kit' },
  { field: 'firstAidKitR', label: '' },
  { field: 'safetyTriangle', label: 'সেফটি ট্রায়াঙ্গল - Safety Triangle' },
  { field: 'safetyTriangleR', label: '' },
  { field: 'jack', label: 'জ্যাক - Jack' },
  { field: 'jackR', label: '' },
  { field: 'wheelSpanner', label: 'হুইল স্প্যানার - Wheel Spanner' },
  { field: 'wheelSpannerR', label: '' },
  { field: 'jackHandle', label: 'জ্যাক হ্যান্ডেল - Jack Handle' },
  { field: 'jackHandleR', label: '' },
  {
    field: 'rotaryFlashLamp',
    label: 'রোটারি/ফ্ল্যাশ ল্যাম্প - Rotary/Flash Lamp',
  },
  { field: 'rotaryFlashLampR', label: '' },
  { field: 'reflectiveStrip', label: 'রিফ্লেক্টিভ স্ট্রিপ - Reflective Strip' },
  { field: 'reflectiveStripR', label: '' },
  { field: 'vehicleNumbers', label: 'যানবাহন নম্বর - Vehicle Numbers' },
  { field: 'vehicleNumbersR', label: '' },
  {
    field: 'communicationRadio',
    label: 'কমিউনিকেশন রেডিও - Communication Radio',
  },
  { field: 'communicationRadioR', label: '' },
  {
    field: 'diesel',
    label: 'ডিজেলের পরিমান - Diesel quantity',
  },
  { field: 'remark', label: 'মন্তব্য - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
