export const questions = [
  {
    id: 1,
    name: 'loadChart',
    question: 'Bảng khả năng tải',
    howto:
      'Kiểm tra bảng khả năng tải được lắp đặt, dễ đọc và thông tin chính xác.',
    accept: 'Bảng khả năng tải được lắp đặt đúng cách và thông tin chính xác.',
  },
  {
    id: 2,
    name: 'forksAccessories',
    question: 'Càng nâng và phụ kiện',
    howto:
      'Kiểm tra càng nâng và các phụ kiện không có bất kỳ dấu hiệu hư hỏng nào.',
    accept: 'Càng nâng và phụ kiện không có dấu hiệu hư hỏng.',
  },
  {
    id: 3,
    name: 'tiresBelts',
    question: 'Lốp và dây đai',
    howto: 'Kiểm tra lốp, các dây đai và sự rò rỉ phía dưới thân xe.',
    accept: 'Lốp và dây đai không có dấu hiệu rò rỉ hoặc hư hỏng.',
  },
  {
    id: 4,
    name: 'mastHydraulic',
    question: 'Trụ nâng và ben thủy lực',
    howto: 'Kiểm tra trụ nâng và ben thủy lực, tìm bất kỳ sự rò rỉ nào.',
    accept: 'Trụ nâng và ben thủy lực không có dấu hiệu rò rỉ.',
  },
  {
    id: 5,
    name: 'battery',
    question: 'Bình ắc quy',
    howto: 'Kiểm tra bình ắc quy.',
    accept: 'Bình ắc quy hoạt động bình thường.',
  },
  {
    id: 6,
    name: 'coolantCheck',
    question:
      'Việc kiểm tra nước làm mát sẽ chỉ được kiểm tra mực nước trong bình nước phụ và không cần mở nắp bình nước phụ cũng như két làm mát.',
    howto:
      'Kiểm tra mực nước làm mát trong bình nước phụ bằng cách quan sát vạch chỉ mực nước, không cần mở nắp bình nước phụ hoặc két làm mát.',
    accept:
      'Mực nước làm mát trong bình nước phụ nằm trong giới hạn cho phép và không có dấu hiệu rò rỉ.',
  },
  {
    id: 7,
    name: 'seatBelts',
    question: 'Ghế ngồi và dây an toàn',
    howto:
      'Kiểm tra tình trạng và khả năng điều chỉnh của ghế ngồi và dây an toàn.',
    accept:
      'Ghế ngồi và dây an toàn ở tình trạng tốt và có thể điều chỉnh được.',
  },
  {
    id: 8,
    name: 'pedalsControls',
    question: 'Bàn đạp và cần điều khiển',
    howto:
      'Sau khi khởi động, kiểm tra tất cả các bàn đạp và cần điều khiển về sự vận hành trơn tru.',
    accept: 'Bàn đạp và cần điều khiển vận hành trơn tru.',
  },
  {
    id: 9,
    name: 'brakes',
    question: 'Thắng chính và thắng tay',
    howto:
      'Kiểm tra tính hoạt động đúng chức năng của thắng chính và thắng tay.',
    accept: 'Thắng chính và thắng tay hoạt động đúng chức năng.',
  },
  {
    id: 10,
    name: 'lightsHorn',
    question: 'Đèn và còi',
    howto: 'Kiểm tra đèn, đèn cảnh báo, kèn/còi và còi de/lùi.',
    accept: 'Đèn và còi hoạt động bình thường.',
  },
  {
    id: 11,
    name: 'damageDefects',
    question: 'Hư hỏng hoặc khuyết tật',
    howto: 'Kiểm tra bất kỳ sự hư hỏng hoặc khuyết tật nào thấy được.',
    accept: 'Không có dấu hiệu hư hỏng hoặc khuyết tật.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'loadChart', label: '1. Bảng khả năng tải *' },
  { field: 'loadChartR', label: '' },
  { field: 'loadChartP', label: '' },
  { field: 'loadChartA', label: 'Respond to defect' },
  { field: 'loadChartF', label: '' },
  { field: 'forksAccessories', label: '2. Càng nâng và phụ kiện *' },
  { field: 'forksAccessoriesR', label: '' },
  { field: 'forksAccessoriesP', label: '' },
  { field: 'forksAccessoriesA', label: 'Respond to defect' },
  { field: 'forksAccessoriesF', label: '' },
  { field: 'tiresBelts', label: '3. Lốp và dây đai *' },
  { field: 'tiresBeltsR', label: '' },
  { field: 'tiresBeltsP', label: '' },
  { field: 'tiresBeltsA', label: 'Respond to defect' },
  { field: 'tiresBeltsF', label: '' },
  { field: 'mastHydraulic', label: '4. Trụ nâng và ben thủy lực *' },
  { field: 'mastHydraulicR', label: '' },
  { field: 'mastHydraulicP', label: '' },
  { field: 'mastHydraulicA', label: 'Respond to defect' },
  { field: 'mastHydraulicF', label: '' },
  { field: 'battery', label: '5. Bình ắc quy *' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  {
    field: 'coolantCheck',
    label:
      '6. Việc kiểm tra nước làm mát sẽ chỉ được kiểm tra mực nước trong bình nước phụ và không cần mở nắp bình nước phụ cũng như két làm mát.',
  },
  { field: 'coolantCheckR', label: '' },
  { field: 'coolantCheckP', label: '' },
  { field: 'coolantCheckA', label: 'Respond to defect' },
  { field: 'coolantCheckF', label: '' },
  { field: 'seatBelts', label: '7. Ghế ngồi và dây an toàn *' },
  { field: 'seatBeltsR', label: '' },
  { field: 'seatBeltsP', label: '' },
  { field: 'seatBeltsA', label: 'Respond to defect' },
  { field: 'seatBeltsF', label: '' },
  { field: 'pedalsControls', label: '8. Bàn đạp và cần điều khiển *' },
  { field: 'pedalsControlsR', label: '' },
  { field: 'pedalsControlsP', label: '' },
  { field: 'pedalsControlsA', label: 'Respond to defect' },
  { field: 'pedalsControlsF', label: '' },
  { field: 'brakes', label: '9. Thắng chính và thắng tay *' },
  { field: 'brakesR', label: '' },
  { field: 'brakesP', label: '' },
  { field: 'brakesA', label: 'Respond to defect' },
  { field: 'brakesF', label: '' },
  { field: 'lightsHorn', label: '10. Đèn và còi *' },
  { field: 'lightsHornR', label: '' },
  { field: 'lightsHornP', label: '' },
  { field: 'lightsHornA', label: 'Respond to defect' },
  { field: 'lightsHornF', label: '' },
  { field: 'damageDefects', label: '11. Hư hỏng hoặc khuyết tật *' },
  { field: 'damageDefectsR', label: '' },
  { field: 'damageDefectsP', label: '' },
  { field: 'damageDefectsA', label: 'Respond to defect' },
  { field: 'damageDefectsF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
