export const questions = [
  {
    id: 1,
    name: 'wheel',
    question: 'កង់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបង្វិលកង់',
    accept: 'កង់ស្ថានភាពល្អ គ្មានការច្រេះ ឬការជ្រាបទឹក',
  },
  {
    id: 2,
    name: 'hydralic',
    question: 'ដងហាយដ្រូលិកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការលេចធ្លាយ',
    accept: 'ដងហាយដ្រូលិកគ្មានការច្រេះ ឬការលេចធ្លាយ',
  },
  {
    id: 3,
    name: 'shovel',
    question: 'ប៉ែលចូកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការដំណើរការ',
    accept: 'ប៉ែលស្ថានភាពល្អ និងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 4,
    name: 'seat',
    question: 'កៅអី,​ ខ្សែក្រវាត់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពកៅអី និងការដាក់ខ្សែក្រវ៉ាត់',
    accept: 'កៅអីស្ថានភាពល្អ និងខ្សែក្រវ៉ាត់ដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 5,
    name: 'mirror',
    question: 'កញ្ចក់មើលក្រោយមិនធម្មតា',
    howto: 'ពិនិត្យសភាពកញ្ចក់ និងភាពច្បាស់',
    accept: 'កញ្ចក់ស្ថានភាពល្អ គ្មានការបាក់ ឬស្នាមប៉ះ',
  },
  {
    id: 6,
    name: 'handBrake',
    question: 'ហ្រ្វាងដៃ, ជើងមិនធម្មតា',
    howto: 'សាកសួរនិងពិនិត្យប្រព័ន្ធហ្រ្វាំង',
    accept: 'ហ្រ្វាំងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 7,
    name: 'steer',
    question: 'ចង្កូតមិនធម្មតា',
    howto: 'សាកសួរស្ថានភាពចង្កូត និងការបង្វិល',
    accept: 'ចង្កូតដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 8,
    name: 'accelerator',
    question: 'ហ្គ៊ែរមិនធម្មតា',
    howto: 'សាកសួរស្ថានភាព និងការប្រើប្រាស់ហ្គែរជើង',
    accept: 'ហ្គែរដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 9,
    name: 'light',
    question: 'អំពូលភ្លើងទាំងអស់មិនធម្មតា',
    howto: 'ពិនិត្យការដំណើរការរបស់អំពូលភ្លើង',
    accept: 'អំពូលភ្លើងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 10,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'សាកសួរសំលេងស៊ីផ្លេ',
    accept: 'ស៊ីផ្លេដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 11,
    name: 'reversing',
    question: 'សឺរ៉ែនថយក្រោយមិនធម្មតា',
    howto: 'សាកសួរស្ថានភាព និងសំលេងសឺរ៉ែន',
    accept: 'សឺរ៉ែនដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 12,
    name: 'extinguisher',
    question: 'បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការដំណើរការ',
    accept: 'បំពង់ដំណើរការបានត្រឹមត្រូវ',
  },
];

export const detailFields = [
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'wheel', label: '1. កង់ - Tires' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'hydralic', label: '2. ដងហាយដ្រូលិក - Hydraulic Rod' },
  { field: 'hydralicR', label: '' },
  { field: 'hydralicP', label: '' },
  { field: 'hydralicA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydralicF', label: '' },
  { field: 'shovel', label: '3. ប៉ែលចូក - Shovel' },
  { field: 'shovelR', label: '' },
  { field: 'shovelP', label: '' },
  { field: 'shovelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'shovelF', label: '' },
  { field: 'seat', label: '4. កៅអី,​ ខ្សែក្រវ៉ាត់ - Seat and Seat Belt' },
  { field: 'seatR', label: '' },
  { field: 'seatP', label: '' },
  { field: 'seatA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'seatF', label: '' },
  { field: 'mirror', label: '5. កញ្ចក់មើលក្រោយ - Rearview Mirror' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'handBrake', label: '6. ហ្រ្វាំងដៃ - Hand Brake' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'steer', label: '7. ចង្កូត - Steering' },
  { field: 'steerR', label: '' },
  { field: 'steerP', label: '' },
  { field: 'steerA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'steerF', label: '' },
  { field: 'accelerator', label: '8. ហ្គ៊ែរ - Accelerator' },
  { field: 'acceleratorR', label: '' },
  { field: 'acceleratorP', label: '' },
  { field: 'acceleratorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'acceleratorF', label: '' },
  { field: 'light', label: '9. អំពូលភ្លើងទាំងអស់ - Lights' },
  { field: 'lightR', label: '' },
  { field: 'lightP', label: '' },
  { field: 'lightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'lightF', label: '' },
  { field: 'horn', label: '10. ស៊ីផ្លេ - Horn' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'reversing', label: '11. សឺរ៉ែនថយក្រោយ - Reversing Alarm' },
  { field: 'reversingR', label: '' },
  { field: 'reversingP', label: '' },
  { field: 'reversingA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'reversingF', label: '' },
  {
    field: 'extinguisher',
    label: '12. បំពង់ពន្លត់អគ្គីភ័យ - Fire Extinguisher',
  },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'remark', label: 'មតិយោបល់ - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
