export const questions = [
  {
    id: 1,
    name: 'lifejacketCondition',
    question:
      'Áo phao có trong điều kiện tốt không? / Is the lifejacket in good condition?',
    howto: 'Kiểm tra tổng thể tình trạng bề ngoài của áo phao để phát hiện các hư hỏng rõ ràng.',
    accept: 'Áo phao trong điều kiện tốt, không có hư hỏng rõ ràng.',
  },
  {
    id: 2,
    name: 'noExcessiveContamination',
    question:
      'Không có dầu, mỡ hay bụi quá mức? / No excessive oil, grease or dust?',
    howto: 'Kiểm tra bề mặt áo phao xem có tích tụ dầu, mỡ hoặc bụi quá mức không.',
    accept: 'Không có dầu, mỡ hay bụi tích tụ quá mức.',
  },
  {
    id: 3,
    name: 'noSaltBuildupCorrosion',
    question:
      'Không có sự tích tụ muối hay ăn mòn các khóa? / No salt build-up or corrosion of buckles?',
    howto: 'Kiểm tra các khóa cài và phụ kiện kim loại để phát hiện sự tích tụ muối hoặc ăn mòn.',
    accept: 'Không có sự tích tụ muối hay ăn mòn trên các khóa cài.',
  },
  {
    id: 4,
    name: 'webbingZippersCondition',
    question:
      'Dây đai hay dây kéo có trong điều kiện tốt không? / Are webbing or zippers in good condition?',
    howto: 'Kiểm tra tình trạng của dây đai và dây kéo để phát hiện hư hỏng hoặc mài mòn.',
    accept: 'Dây đai và dây kéo trong điều kiện tốt.',
  },
  {
    id: 5,
    name: 'webbingIntegrity',
    question:
      'Vải không bị rách? / Is the webbing not torn?',
    howto: 'Kiểm tra vải của áo phao để phát hiện các vết rách hoặc hư hỏng.',
    accept: 'Vải không bị rách.',
  },
  {
    id: 6,
    name: 'reflectiveMaterialCondition',
    question:
      'Vật liệu phản chiếu không bị phai màu hay bị thiếu? / Is the reflective material not faded or missing?',
    howto: 'Kiểm tra tình trạng của vật liệu phản chiếu trên áo phao.',
    accept: 'Vật liệu phản chiếu không bị phai màu hay thiếu.',
  },
  {
    id: 7,
    name: 'jacketColorCondition',
    question:
      'Màu áo không bị phai? / Is the colour of the jacket not faded?',
    howto: 'Kiểm tra màu sắc của áo phao để xem có bị phai hay không.',
    accept: 'Màu của áo phao không bị phai.',
  },
  {
    id: 8,
    name: 'webbingStrengthCondition',
    question:
      'Dây đai và vải làm đai có trong điều kiện tốt và đủ mạnh không? / Are the webbing and webbing in good condition and strong enough?',
    howto: 'Kiểm tra độ bền và tình trạng của dây đai và vải làm đai.',
    accept: 'Dây đai và vải làm đai trong điều kiện tốt và đủ mạnh.',
  },
  {
    id: 9,
    name: 'buoyancyEffectiveness',
    question:
      'Sức nổi của áo vẫn còn hiệu quả về năng suất được đánh giá như hướng dẫn của nhà sản xuất không? (chứng minh bằng cách thử dưới nước) / Does the buoyancy of the jacket still perform as rated by the manufacturer? (prove by underwater testing)',
    howto: 'Thực hiện thử nghiệm dưới nước để kiểm tra sức nổi của áo phao theo thông số kỹ thuật của nhà sản xuất.',
    accept: 'Sức nổi của áo phao vẫn hiệu quả theo thông số kỹ thuật của nhà sản xuất.',
  },
  {
    id: 10,
    name: 'properStorageCondition',
    question:
      'Áo có được lưu giữ phù hợp, trong phạm vi nhiệt độ hợp lý (dưới 60°C), tránh được bụi không? / Is the jacket stored properly, within a reasonable temperature range (below 60°C), and protected from dust?',
    howto: 'Kiểm tra cách lưu trữ áo phao, nhiệt độ môi trường lưu trữ và sự bảo vệ khỏi bụi.',
    accept: 'Áo phao được lưu giữ phù hợp, trong phạm vi nhiệt độ dưới 60°C và tránh được bụi.',
  },
  {
    id: 11,
    name: 'dryStorageCondition',
    question:
      'Áo có được cất giữ ở nơi khô ráo không? / Is the jacket stored in a dry place?',
    howto: 'Kiểm tra độ ẩm của môi trường lưu trữ áo phao.',
    accept: 'Áo phao được cất giữ ở nơi khô ráo.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'lifejacketCondition', label: '1. Áo phao có trong điều kiện tốt không? / Is the lifejacket in good condition?'},
  { field: 'lifejacketConditionR', label: '' },
  { field: 'lifejacketConditionP', label: '' },
  { field: 'lifejacketConditionA', label: '' },
  { field: 'lifejacketConditionF', label: '' },
  { field: 'noExcessiveContamination', label: '2. Không có dầu, mỡ hay bụi quá mức? / No excessive oil, grease or dust?'},
  { field: 'noExcessiveContaminationR', label: '' },
  { field: 'noExcessiveContaminationP', label: '' },
  { field: 'noExcessiveContaminationA', label: '' },
  { field: 'noExcessiveContaminationF', label: '' },
  { field: 'noSaltBuildupCorrosion', label: '3. Không có sự tích tụ muối hay ăn mòn các khóa? / No salt build-up or corrosion of buckles?'},
  { field: 'noSaltBuildupCorrosionR', label: '' },
  { field: 'noSaltBuildupCorrosionP', label: '' },
  { field: 'noSaltBuildupCorrosionA', label: '' },
  { field: 'noSaltBuildupCorrosionF', label: '' },
  { field: 'webbingZippersCondition', label: '4. Dây đai hay dây kéo có trong điều kiện tốt không? / Are webbing or zippers in good condition?'},
  { field: 'webbingZippersConditionR', label: '' },
  { field: 'webbingZippersConditionP', label: '' },
  { field: 'webbingZippersConditionA', label: '' },
  { field: 'webbingZippersConditionF', label: '' },
  { field: 'webbingIntegrity', label: '5. Vải không bị rách? / Is the webbing not torn?'},
  { field: 'webbingIntegrityR', label: '' },
  { field: 'webbingIntegrityP', label: '' },
  { field: 'webbingIntegrityA', label: '' },
  { field: 'webbingIntegrityF', label: '' },
  { field: 'reflectiveMaterialCondition', label: '6. Vật liệu phản chiếu không bị phai màu hay bị thiếu? / Is the reflective material not faded or missing?'},
  { field: 'reflectiveMaterialConditionR', label: '' },
  { field: 'reflectiveMaterialConditionP', label: '' },
  { field: 'reflectiveMaterialConditionA', label: '' },
  { field: 'reflectiveMaterialConditionF', label: '' },
  { field: 'jacketColorCondition', label: '7. Màu áo không bị phai? / Is the colour of the jacket not faded?'},
  { field: 'jacketColorConditionR', label: '' },
  { field: 'jacketColorConditionP', label: '' },
  { field: 'jacketColorConditionA', label: '' },
  { field: 'jacketColorConditionF', label: '' },
  { field: 'webbingStrengthCondition', label: '8. Dây đai và vải làm đai có trong điều kiện tốt và đủ mạnh không? / Are the webbing and webbing in good condition and strong enough?'},
  { field: 'webbingStrengthConditionR', label: '' },
  { field: 'webbingStrengthConditionP', label: '' },
  { field: 'webbingStrengthConditionA', label: '' },
  { field: 'webbingStrengthConditionF', label: '' },
  { field: 'buoyancyEffectiveness', label: '9. Sức nổi của áo vẫn còn hiệu quả về năng suất được đánh giá như hướng dẫn của nhà sản xuất không? (chứng minh bằng cách thử dưới nước) / Does the buoyancy of the jacket still perform as rated by the manufacturer? (prove by underwater testing)'},
  { field: 'buoyancyEffectivenessR', label: '' },
  { field: 'buoyancyEffectivenessP', label: '' },
  { field: 'buoyancyEffectivenessA', label: '' },
  { field: 'buoyancyEffectivenessF', label: '' },
  { field: 'properStorageCondition', label: '10. Áo có được lưu giữ phù hợp, trong phạm vi nhiệt độ hợp lý (dưới 60°C), tránh được bụi không? / Is the jacket stored properly, within a reasonable temperature range (below 60°C), and protected from dust?'},
  { field: 'properStorageConditionR', label: '' },
  { field: 'properStorageConditionP', label: '' },
  { field: 'properStorageConditionA', label: '' },
  { field: 'properStorageConditionF', label: '' },
  { field: 'dryStorageCondition', label: '11. Áo có được cất giữ ở nơi khô ráo không? / Is the jacket stored in a dry place?'},
  { field: 'dryStorageConditionR', label: '' },
  { field: 'dryStorageConditionP', label: '' },
  { field: 'dryStorageConditionA', label: '' },
  { field: 'dryStorageConditionF', label: '' },
  { field: 'tag', label: 'Tag' },
  { field: 'collection', label: 'Type of Equipment' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
