export const questions = [
  {
    id: 1,
    name: 'foamAmount',
    question: 'Lượng Foam trong bồn còn đủ theo yêu cầu',
    howto: 'Kiểm tra lượng foam trong bồn còn đủ theo yêu cầu.',
    accept: 'Lượng foam trong bồn còn đủ theo yêu cầu.',
  },
  {
    id: 2,
    name: 'valvesReady',
    question: 'Các van nước van foam được mở ở trạng thái sẵn sàng',
    howto: 'Kiểm tra các van nước và van foam được mở ở trạng thái sẵn sàng.',
    accept: 'Các van nước và van foam được mở ở trạng thái sẵn sàng.',
  },
  {
    id: 3,
    name: 'rustFree',
    question: 'Bồn và đường ống không bị rỉ sét',
    howto: 'Kiểm tra bồn và đường ống không bị rỉ sét.',
    accept: 'Bồn và đường ống không bị rỉ sét.',
  },
  {
    id: 4,
    name: 'instructionsAvailable',
    question: 'Có đủ thông tin hướng dẫn sử dụng',
    howto: 'Kiểm tra có đủ thông tin hướng dẫn sử dụng.',
    accept: 'Có đủ thông tin hướng dẫn sử dụng.',
  },
  {
    id: 5,
    name: 'cleanliness',
    question: 'Tình trạng vệ sinh khu vực sạch sẽ',
    howto: 'Kiểm tra tình trạng vệ sinh khu vực sạch sẽ.',
    accept: 'Tình trạng vệ sinh khu vực sạch sẽ.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'foamAmount',
    label: '1. Lượng Foam trong bồn còn đủ theo yêu cầu *',
  },
  { field: 'foamAmountR', label: '' },
  { field: 'foamAmountP', label: '' },
  { field: 'foamAmountA', label: 'Respond to defect' },
  { field: 'foamAmountF', label: '' },
  {
    field: 'valvesReady',
    label: '2. Các van nước van foam được mở ở trạng thái sẵn sàng *',
  },
  { field: 'valvesReadyR', label: '' },
  { field: 'valvesReadyP', label: '' },
  { field: 'valvesReadyA', label: 'Respond to defect' },
  { field: 'valvesReadyF', label: '' },
  { field: 'rustFree', label: '3. Bồn và đường ống không bị rỉ sét *' },
  { field: 'rustFreeR', label: '' },
  { field: 'rustFreeP', label: '' },
  { field: 'rustFreeA', label: 'Respond to defect' },
  { field: 'rustFreeF', label: '' },
  {
    field: 'instructionsAvailable',
    label: '4. Có đủ thông tin hướng dẫn sử dụng *',
  },
  { field: 'instructionsAvailableR', label: '' },
  { field: 'instructionsAvailableP', label: '' },
  { field: 'instructionsAvailableA', label: 'Respond to defect' },
  { field: 'instructionsAvailableF', label: '' },
  { field: 'cleanliness', label: '5. Tình trạng vệ sinh khu vực sạch sẽ *' },
  { field: 'cleanlinessR', label: '' },
  { field: 'cleanlinessP', label: '' },
  { field: 'cleanlinessA', label: 'Respond to defect' },
  { field: 'cleanlinessF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
