export const questions = [
  {
    id: 1,
    name: 'alcohol',
    question: 'Alcohol',
    howto: 'Kiểm tra số lượng Alcohol tại thời điểm kiểm tra.',
    accept: 'Số lượng Alcohol là 3 chai.',
  },
  {
    id: 2,
    name: 'hydrogenPeroxide',
    question: 'Oxy già (Hydrogen peroxide)',
    howto: 'Kiểm tra số lượng Oxy già tại thời điểm kiểm tra.',
    accept: 'Số lượng Oxy già là 3 chai.',
  },
  {
    id: 3,
    name: 'povidine',
    question: 'Povidin10%',
    howto: 'Kiểm tra số lượng Povidin10% tại thời điểm kiểm tra.',
    accept: 'Số lượng Povidin10% là 1 chai.',
  },
  {
    id: 4,
    name: 'tamanuOil',
    question: 'Dầu mù u',
    howto: 'Kiểm tra số lượng Dầu mù u tại thời điểm kiểm tra.',
    accept: 'Số lượng Dầu mù u là 1 chai.',
  },
  {
    id: 5,
    name: 'bandAid',
    question: 'Băng cá nhân (Band aid)',
    howto: 'Kiểm tra số lượng Băng cá nhân tại thời điểm kiểm tra.',
    accept: 'Số lượng Băng cá nhân là 30 miếng.',
  },
  {
    id: 6,
    name: 'eyeDrops',
    question: 'Thuốc nhỏ mắt (NaCl 0.9%)',
    howto: 'Kiểm tra số lượng Thuốc nhỏ mắt tại thời điểm kiểm tra.',
    accept: 'Số lượng Thuốc nhỏ mắt là 3 chai.',
  },
  {
    id: 7,
    name: 'gauze',
    question: 'Gạc vô trùng (Absorbent gauze)',
    howto: 'Kiểm tra số lượng Gạc vô trùng tại thời điểm kiểm tra.',
    accept: 'Số lượng Gạc vô trùng là 10 miếng.',
  },
  {
    id: 8,
    name: 'rollerGauze',
    question: 'Băng cuộn vải (Roler Gauze)',
    howto: 'Kiểm tra số lượng Băng cuộn vải tại thời điểm kiểm tra.',
    accept: 'Số lượng Băng cuộn vải là 10 cuộn.',
  },
  {
    id: 9,
    name: 'cotton',
    question: 'Bông gòn y tế (Absorbent cotton)',
    howto: 'Kiểm tra số lượng Bông gòn y tế tại thời điểm kiểm tra.',
    accept: 'Số lượng Bông gòn y tế là 1 bịch.',
  },
  {
    id: 10,
    name: 'glove',
    question: 'Găng tay sạch (Glove)',
    howto: 'Kiểm tra số lượng Găng tay sạch tại thời điểm kiểm tra.',
    accept: 'Số lượng Găng tay sạch là 1 đôi.',
  },
  {
    id: 11,
    name: 'elasticBandage',
    question: 'Băng cuộn thun 3 móc (Elastic bandage)',
    howto: 'Kiểm tra số lượng Băng cuộn thun 3 móc tại thời điểm kiểm tra.',
    accept: 'Số lượng Băng cuộn thun 3 móc là 1 cuộn.',
  },
  {
    id: 12,
    name: 'triangularBandage',
    question: 'Băng tam giác (Triangular bandage)',
    howto: 'Kiểm tra số lượng Băng tam giác tại thời điểm kiểm tra.',
    accept: 'Số lượng Băng tam giác là 1 cái.',
  },
  {
    id: 13,
    name: 'adhesiveTape',
    question: 'Băng keo Urgo (Adhesive tape roll)',
    howto: 'Kiểm tra số lượng Băng keo Urgo tại thời điểm kiểm tra.',
    accept: 'Số lượng Băng keo Urgo là 1 cuộn.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'alcohol', label: '1. Alcohol' },
  { field: 'alcoholR', label: '' },
  { field: 'alcoholP', label: '' },
  { field: 'alcoholA', label: 'Respond to defect' },
  { field: 'alcoholF', label: '' },
  { field: 'hydrogenPeroxide', label: '2. Oxy già (Hydrogen peroxide)' },
  { field: 'hydrogenPeroxideR', label: '' },
  { field: 'hydrogenPeroxideP', label: '' },
  { field: 'hydrogenPeroxideA', label: 'Respond to defect' },
  { field: 'hydrogenPeroxideF', label: '' },
  { field: 'povidine', label: '3. Povidin10%' },
  { field: 'povidineR', label: '' },
  { field: 'povidineP', label: '' },
  { field: 'povidineA', label: 'Respond to defect' },
  { field: 'povidineF', label: '' },
  { field: 'tamanuOil', label: '4. Dầu mù u' },
  { field: 'tamanuOilR', label: '' },
  { field: 'tamanuOilP', label: '' },
  { field: 'tamanuOilA', label: 'Respond to defect' },
  { field: 'tamanuOilF', label: '' },
  { field: 'bandAid', label: '5. Băng cá nhân (Band aid)' },
  { field: 'bandAidR', label: '' },
  { field: 'bandAidP', label: '' },
  { field: 'bandAidA', label: 'Respond to defect' },
  { field: 'bandAidF', label: '' },
  { field: 'eyeDrops', label: '6. Thuốc nhỏ mắt (NaCl 0.9%)' },
  { field: 'eyeDropsR', label: '' },
  { field: 'eyeDropsP', label: '' },
  { field: 'eyeDropsA', label: 'Respond to defect' },
  { field: 'eyeDropsF', label: '' },
  { field: 'gauze', label: '7. Gạc vô trùng (Absorbent gauze)' },
  { field: 'gauzeR', label: '' },
  { field: 'gauzeP', label: '' },
  { field: 'gauzeA', label: 'Respond to defect' },
  { field: 'gauzeF', label: '' },
  { field: 'rollerGauze', label: '8. Băng cuộn vải (Roler Gauze)' },
  { field: 'rollerGauzeR', label: '' },
  { field: 'rollerGauzeP', label: '' },
  { field: 'rollerGauzeA', label: 'Respond to defect' },
  { field: 'rollerGauzeF', label: '' },
  { field: 'cotton', label: '9. Bông gòn y tế (Absorbent cotton)' },
  { field: 'cottonR', label: '' },
  { field: 'cottonP', label: '' },
  { field: 'cottonA', label: 'Respond to defect' },
  { field: 'cottonF', label: '' },
  { field: 'glove', label: '10. Găng tay sạch (Glove)' },
  { field: 'gloveR', label: '' },
  { field: 'gloveP', label: '' },
  { field: 'gloveA', label: 'Respond to defect' },
  { field: 'gloveF', label: '' },
  {
    field: 'elasticBandage',
    label: '11. Băng cuộn thun 3 móc (Elastic bandage)',
  },
  { field: 'elasticBandageR', label: '' },
  { field: 'elasticBandageP', label: '' },
  { field: 'elasticBandageA', label: 'Respond to defect' },
  { field: 'elasticBandageF', label: '' },
  {
    field: 'triangularBandage',
    label: '12. Băng tam giác (Triangular bandage)',
  },
  { field: 'triangularBandageR', label: '' },
  { field: 'triangularBandageP', label: '' },
  { field: 'triangularBandageA', label: 'Respond to defect' },
  { field: 'triangularBandageF', label: '' },
  { field: 'adhesiveTape', label: '13. Băng keo Urgo (Adhesive tape roll)' },
  { field: 'adhesiveTapeR', label: '' },
  { field: 'adhesiveTapeP', label: '' },
  { field: 'adhesiveTapeA', label: 'Respond to defect' },
  { field: 'adhesiveTapeF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
