export const questions = [
  {
    id: 1,
    name: 'strapCondition',
    question: 'สายรัดไม่มีรอยขาด, รอยถลอก, หรือฉีกขาด',
    howto: 'ตรวจสอบด้วยสายตา และสัมผัสตลอดแนวสายรัด',
    accept: 'สายรัดอยู่ในสภาพดี ไม่มีรอยขาด ถลอก หรือฉีกขาด',
  },
  {
    id: 2,
    name: 'strapCleanliness',
    question: 'ไม่มีรอยเปื้อนสารเคมี, น้ำมัน, หรือสิ่งสกปรกที่อาจทำลายวัสดุ',
    howto: 'ใช้สายตาตรวจสอบคราบหรือสิ่งสกปรกตลอดสาย',
    accept: 'ไม่มีคราบสารเคมี, น้ำมัน หรือสิ่งสกปรก',
  },
  {
    id: 3,
    name: 'heatDamage',
    question: 'ไม่มีรอยไหม้จากความร้อน',
    howto: 'ตรวจสอบด้วยสายตาและสัมผัสเพื่อหาจุดผิดปกติ',
    accept: 'ไม่พบรอยไหม้ สีเปลี่ยน หรือผิววัสดุผิดปกติจากความร้อน',
  },
  {
    id: 4,
    name: 'stitchingCheck',
    question: 'ตรวจสอบรอยเย็บ ว่ายังแน่นหนา ไม่หลุดหรือหลวม',
    howto: 'ใช้สายตาและนิ้วลูบรอยเย็บตามแนว',
    accept: 'รอยเย็บแน่น ไม่มีรอยขาด หลุด หรือหลวม',
  },
  {
    id: 5,
    name: 'dringCondition',
    question: 'D-rings ไม่บิดเบี้ยว แตกหัก หรือขึ้นสนิม',
    howto: 'ใช้สายตาและมือจับดูความแข็งแรง',
    accept: 'D-rings อยู่ในรูปทรงปกติ ไม่มีรอยแตก หรือสนิม',
  },
  {
    id: 6,
    name: 'buckleFunction',
    question: 'หัวเข็มขัดทำงานได้ดี สามารถล็อกและปลดได้ตามปกติ',
    howto: 'ทดสอบการล็อกและปลดหัวเข็มขัดด้วยมือ',
    accept: 'หัวเข็มขัดทำงานได้ลื่นไหล ไม่มีติดขัด',
  },
  {
    id: 7,
    name: 'metalIntegrity',
    question: 'ไม่มีรอยร้าวหรือจุดอ่อนในโลหะ',
    howto: 'ตรวจสอบสายตาและสัมผัสส่วนโลหะ',
    accept: 'โลหะเรียบ ไม่มีรอยร้าว หรือจุดเปราะบาง',
  },
  {
    id: 8,
    name: 'lockingSystem',
    question: 'ระบบล็อกสามารถใช้งานได้อย่างถูกต้อง',
    howto: 'ทดสอบระบบล็อกโดยการใช้งานจริง',
    accept: 'ระบบล็อกทำงานได้ดี ไม่มีหลวม หรือขัดข้อง',
  },
  {
    id: 9,
    name: 'dringAttachment',
    question: 'ตรวจสอบความแน่นของการติดตั้ง D-Ring กับสายรัด',
    howto: 'จับ D-Ring แล้วโยกเบา ๆ ตรวจสอบความมั่นคง',
    accept: 'D-Ring ยึดแน่นกับสายรัด ไม่หลุดหรือคลอน',
  }
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'strapCondition', label: '1. สายรัดไม่มีรอยขาด, รอยถลอก, หรือฉีกขาด' },
  { field: 'strapConditionR', label: '' },
  { field: 'strapConditionP', label: '' },
  { field: 'strapConditionA', label: 'Respond to defect' },
  { field: 'strapConditionF', label: '' },
  { field: 'strapCleanliness', label: '2. ไม่มีรอยเปื้อนสารเคมี, น้ำมัน, หรือสิ่งสกปรกที่อาจทำลายวัสดุ' },
  { field: 'strapCleanlinessR', label: '' },
  { field: 'strapCleanlinessP', label: '' },
  { field: 'strapCleanlinessA', label: 'Respond to defect' },
  { field: 'strapCleanlinessF', label: '' },
  { field: 'heatDamage', label: '3. ไม่มีรอยไหม้จากความร้อน' },
  { field: 'heatDamageR', label: '' },
  { field: 'heatDamageP', label: '' },
  { field: 'heatDamageA', label: 'Respond to defect' },
  { field: 'heatDamageF', label: '' },
  { field: 'stitchingCheck', label: '4. ตรวจสอบรอยเย็บ ว่ายังแน่นหนา ไม่หลุดหรือหลวม' },
  { field: 'stitchingCheckR', label: '' },
  { field: 'stitchingCheckP', label: '' },
  { field: 'stitchingCheckA', label: 'Respond to defect' },
  { field: 'stitchingCheckF', label: '' },
  { field: 'dringCondition', label: '5. D-rings ไม่บิดเบี้ยว แตกหัก หรือขึ้นสนิม' },
  { field: 'dringConditionR', label: '' },
  { field: 'dringConditionP', label: '' },
  { field: 'dringConditionA', label: 'Respond to defect' },
  { field: 'dringConditionF', label: '' },
  { field: 'buckleFunction', label: '6. หัวเข็มขัดทำงานได้ดี สามารถล็อกและปลดได้ตามปกติ' },
  { field: 'buckleFunctionR', label: '' },
  { field: 'buckleFunctionP', label: '' },
  { field: 'buckleFunctionA', label: 'Respond to defect' },
  { field: 'buckleFunctionF', label: '' },
  { field: 'metalIntegrity', label: '7. ไม่มีรอยร้าวหรือจุดอ่อนในโลหะ' },
  { field: 'metalIntegrityR', label: '' },
  { field: 'metalIntegrityP', label: '' },
  { field: 'metalIntegrityA', label: 'Respond to defect' },
  { field: 'metalIntegrityF', label: '' },
  { field: 'lockingSystem', label: '8. ระบบล็อกสามารถใช้งานได้อย่างถูกต้อง' },
  { field: 'lockingSystemR', label: '' },
  { field: 'lockingSystemP', label: '' },
  { field: 'lockingSystemA', label: 'Respond to defect' },
  { field: 'lockingSystemF', label: '' },
  { field: 'dringAttachment', label: '9. ตรวจสอบความแน่นของการติดตั้ง D-Ring กับสายรัด' },
  { field: 'dringAttachmentR', label: '' },
  { field: 'dringAttachmentP', label: '' },
  { field: 'dringAttachmentA', label: 'Respond to defect' },
  { field: 'dringAttachmentF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];

