export const questions = [
  {
    id: 1,
    name: 'hose',
    question: 'สภาพสายฉีด ไม่แตกร้าว ขาด ชำรุด Hose Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ',
  },
  {
    id: 2,
    name: 'handle',
    question: 'สลัก คันบีบ พร้อมซีลล็อคอยู่ในสภาพเรียบร้อย Handle Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ',
  },
  {
    id: 3,
    name: 'cylinder',
    question: 'สภาพถัง ไม่บุบ หรือบวม และไม่ขึ้นสนิม Cylinder Condition',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ',
  },
  {
    id: 4,
    name: 'gauge',
    question: 'เกจความดัน/น้ำหนัก เข็มชี้ตรงแถบสีเขียว/ตรงกลาง Gauge',
    howto: 'สายตา / สัมผัส / ชั่งน้ำหนัก',
    accept: 'มีน้ำหนัก เข็มชี้ตรงแถบสีเขียว',
  },
  {
    id: 5,
    name: 'obstruction',
    question: 'ติดตั้งในที่มองเห็นชัดเจน ไม่มีสิ่งกีดขวาง Obstruction',
    howto: 'สายตา',
    accept: 'เห็นชัดเจน เข้าถึงได้ง่าย',
  },
  {
    id: 6,
    name: 'cabinet',
    question: 'สภาพตู้เก็บถังดับเพลิง Cabinet',
    howto: 'สายตา / สัมผัส',
    accept: 'มีสภาพปกติ อุปกรณ์ครบ ไม่ผุพัง',
  },
];

export const detailFields = [
  { field: 'date', label: 'วันที่ Date' },
  { field: 'inspector', label: 'ผู้ตรวจ Inspector' },
  { field: 'mileage', label: 'เลขไมล์ Mileage' },
  { field: 'tyre', label: 'น็อตล้อ ลมยาง สภาพยาง' },
  { field: 'tyreR', label: '' },
  { field: 'tyreP', label: '' },
  { field: 'tyreA', label: 'Respond to defect' },
  { field: 'tyreF', label: '' },
  { field: 'engine', label: 'เครื่องยนต์ และท่อไอเสีย' },
  { field: 'engineR', label: '' },
  { field: 'engineP', label: '' },
  { field: 'engineA', label: 'Respond to defect' },
  { field: 'engineF', label: '' },
  { field: 'battery', label: 'แบตเตอรี่' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'gauge', label: 'มาตรวัดความเร็ว และระบบไฟเตือน' },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'Respond to defect' },
  { field: 'gaugeF', label: '' },
  { field: 'whipper', label: 'เครื่องปัดน้ำฝน' },
  { field: 'whipperR', label: '' },
  { field: 'whipperP', label: '' },
  { field: 'whipperA', label: 'Respond to defect' },
  { field: 'whipperF', label: '' },
  { field: 'horn', label: 'แตร/กริ่งสัญญาณ' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'lamp', label: 'ไฟส่องสว่าง(ไฟหน้า)' },
  { field: 'lampR', label: '' },
  { field: 'lampP', label: '' },
  { field: 'lampA', label: 'Respond to defect' },
  { field: 'lampF', label: '' },
  { field: 'tail', label: 'ไฟถอยหลัง ไฟท้าย ไฟเบรค' },
  { field: 'tailR', label: '' },
  { field: 'tailP', label: '' },
  { field: 'tailA', label: 'Respond to defect' },
  { field: 'tailF', label: '' },
  { field: 'turn', label: 'สัญญาณ(ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน)' },
  { field: 'turnR', label: '' },
  { field: 'turnP', label: '' },
  { field: 'turnA', label: 'Respond to defect' },
  { field: 'turnF', label: '' },
  { field: 'mirror', label: 'กระจกหน้า, กระจกมองหลัง และ กระจกมองข้าง' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'belt', label: 'อุปกรณ์ป้องกันภัยเข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'bump', label: 'สภาพโดยรวมทั่วไป และกันชน' },
  { field: 'bumpR', label: '' },
  { field: 'bumpP', label: '' },
  { field: 'bumpA', label: 'Respond to defect' },
  { field: 'bumpF', label: '' },
  { field: 'breakSys', label: 'ระบบเบรค' },
  { field: 'breakSysR', label: '' },
  { field: 'breakSysP', label: '' },
  { field: 'breakSysA', label: 'Respond to defect' },
  { field: 'breakSysF', label: '' },
  { field: 'camera', label: 'กล้องบันทึกภาพหน้ารถ' },
  { field: 'cameraR', label: '' },
  { field: 'cameraP', label: '' },
  { field: 'cameraA', label: 'Respond to defect' },
  { field: 'cameraF', label: '' },
  { field: 'extinguisher', label: 'ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'reverseCam', label: 'กล้องมองถอยหลัง' },
  { field: 'reverseCamR', label: '' },
  { field: 'reverseCamP', label: '' },
  { field: 'reverseCamA', label: 'Respond to defect' },
  { field: 'reverseCamF', label: '' },
  { field: 'sensor', label: 'สัญญาณถอยหลัง (Sensor)' },
  { field: 'sensorR', label: '' },
  { field: 'sensorP', label: '' },
  { field: 'sensorA', label: 'Respond to defect' },
  { field: 'sensorF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
