export const questions = [
  {
    id: 1,
    name: 'cuttingHead',
    question: 'สภาพหัวตัด หัวเชื่อม จุดต่อ, การรั่วซึ่ม',
    howto: 'ตรวจสอบด้วยสายตาและทดสอบการใช้งาน',
    accept: 'จุดต่อแน่น ไม่มีรั่วซึม',
  },
  {
    id: 2,
    name: 'gasHose',
    question: 'สภาพสายแก็ส, จุดต่อ การรั่วซึม',
    howto: 'ตรวจสอบด้วยสายตาและใช้ฟองสบู่ทดสอบ',
    accept: 'สายแก๊สไม่มีรอยรั่ว จุดต่อแน่น',
  },
  {
    id: 3,
    name: 'pressureControl',
    question: 'สภาพอุปกรณ์ควบคุมแรงดัน สภาพมาตรวัด, การรั่วซึ่ม',
    howto: 'ตรวจสอบมาตรวัดและเช็คการรั่วซึม',
    accept: 'มาตรวัดใช้งานได้ ไม่มีรั่วซึม',
  },
  {
    id: 4,
    name: 'flashbackArrestor',
    question: 'สภาพและมาตรฐานอุปกรณ์ ป้องกันไฟย้อนกลับ 4 จุด',
    howto: 'ตรวจสอบว่ามีอุปกรณ์ครบและติดตั้งถูกต้อง',
    accept: 'มีอุปกรณ์ป้องกันไฟย้อนครบ 4 จุด',
  },
  {
    id: 5,
    name: 'gasEquipmentStandard',
    question: 'มาตรฐานอุปกรณ์ อุปกรณ์ GasEquipment',
    howto: 'ตรวจสอบยี่ห้อและมาตรฐานของอุปกรณ์',
    accept: 'อุปกรณ์เป็นไปตามมาตรฐานที่กำหนด',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'cuttingHead',
    label: '1. สภาพหัวตัด หัวเชื่อม จุดต่อ, การรั่วซึ่ม',
  },
  { field: 'cuttingHeadR', label: '' },
  { field: 'cuttingHeadP', label: '' },
  { field: 'cuttingHeadA', label: 'Respond to defect' },
  { field: 'cuttingHeadF', label: '' },
  { field: 'gasHose', label: '2. สภาพสายแก็ส, จุดต่อ การรั่วซึม' },
  { field: 'gasHoseR', label: '' },
  { field: 'gasHoseP', label: '' },
  { field: 'gasHoseA', label: 'Respond to defect' },
  { field: 'gasHoseF', label: '' },
  {
    field: 'pressureControl',
    label: '3. สภาพอุปกรณ์ควบคุมแรงดัน สภาพมาตรวัด, การรั่วซึ่ม',
  },
  { field: 'pressureControlR', label: '' },
  { field: 'pressureControlP', label: '' },
  { field: 'pressureControlA', label: 'Respond to defect' },
  { field: 'pressureControlF', label: '' },
  {
    field: 'flashbackArrestor',
    label: '4. สภาพและมาตรฐานอุปกรณ์ ป้องกันไฟย้อนกลับ 4 จุด',
  },
  { field: 'flashbackArrestorR', label: '' },
  { field: 'flashbackArrestorP', label: '' },
  { field: 'flashbackArrestorA', label: 'Respond to defect' },
  { field: 'flashbackArrestorF', label: '' },
  {
    field: 'gasEquipmentStandard',
    label: '5. มาตรฐานอุปกรณ์ อุปกรณ์ GasEquipment',
  },
  { field: 'gasEquipmentStandardR', label: '' },
  { field: 'gasEquipmentStandardP', label: '' },
  { field: 'gasEquipmentStandardA', label: 'Respond to defect' },
  { field: 'gasEquipmentStandardF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
