export const questions = [
  {
    id: 1,
    name: 'brakeOil',
    question: 'ตรวจสอบน้ำมันเบรก',
    howto: 'สายตา/ประเมิน',
    accept: 'สภาพสี ความขุ่นของน้ำมันเบรก และระดับของน้ำมันเบรก',
  },
  {
    id: 2,
    name: 'brakeHose',
    question: 'ตรวจสอบสภาพท่อยางเบรก',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การพับงอ บิด บวมตัวเสียรูป รอยฉีกขาด รั่วซึม',
  },
  {
    id: 3,
    name: 'airSystem',
    question: 'ตรวจสอบสภาพการรั่วซึมของระบบลม',
    howto: 'ฟังเสียง/สังเกต',
    accept: 'การรั่วซึมของลมเบรก เสียงลมรั่ว',
  },
  {
    id: 4,
    name: 'airTank',
    question: 'ตรวจสอบถังลมเบรก',
    howto: 'สายตา/ถ่ายน้ำออก',
    accept: 'มีน้ำในถังควรถ่ายน้ำออกจากถัง',
  },
  {
    id: 5,
    name: 'dashboard',
    question: 'ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ',
    howto: 'สายตา/สังเกต',
    accept: 'ความสมบูรณ์ของระบบควบคุม เช่น เกจความดันลม ไฟเตือน',
  },
  {
    id: 6,
    name: 'clutch',
    question: 'ตรวจสภาพระบบคลัช',
    howto: 'ทดลองเหยียบ/สังเกต',
    accept: 'ระยะฟรีขาเหยียบคลัชช์ และการลื่นไถลของคลัทช์',
  },
  {
    id: 7,
    name: 'hydraulic',
    question: 'ตรวจสายไฮโดรลิค',
    howto: 'สายตา/สังเกต',
    accept: 'รอยแตกของสาย รอยรั่ว หรือการเสื่อมสภาพของจุดต่อรั่วซึม',
  },
  {
    id: 8,
    name: 'dumpCylinder',
    question: 'ตรวจกระบอกดั๊ม',
    howto: 'ทดสอบการใช้งาน',
    accept:
      'สภาพสมบูรณ์ ไม่ชำรุด ยกต่อเนื่อง ไม่กระตุก มีเสียงเตือนเมื่อยกขึ้นลง',
  },
  {
    id: 9,
    name: 'frontRearBearing',
    question: 'ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)',
    howto: 'ทดลองหมุนพวงมาลัย',
    accept: 'การหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 10,
    name: 'tieRod',
    question: 'ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย - ขวา)',
    howto: 'ทดลองหมุนพวงมาลัย',
    accept: 'การหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 11,
    name: 'tires',
    question: 'ตรวจสภาพยางทุกเส้น',
    howto: 'สายตา/วัดความลึกดอกยาง',
    accept: 'ความสึกหรอ รอยแตกของผิวแก้มยาง (ทุกเส้น)',
  },
  {
    id: 12,
    name: 'wheelRim',
    question: 'ตรวจสอบสภาพกระทะล้อ และน็อตล้อ',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การแตกร้าว, รอยขาดของน็อตล้อ หลุดหาย (ทุกล้อ)',
  },
  {
    id: 13,
    name: 'headlightHorn',
    question: 'ตรวจสภาพไฟหน้า/ แตรสัญญาณ',
    howto: 'ทดลองใช้งาน',
    accept: 'ความสมบูรณ์พร้อมใช้งานของไฟหน้า และแตร',
  },
  {
    id: 14,
    name: 'tailBrakeLight',
    question: 'ตรวจสภาพไฟท้าย / ไฟเบรก',
    howto: 'ทดลองใช้งาน',
    accept: 'ความพร้อมใช้งานของไฟท้าย/ไฟเบรก, สัญญาณเสียงถอย',
  },
  {
    id: 15,
    name: 'turnSideLight',
    question: 'ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง',
    howto: 'ทดลองใช้งาน',
    accept: 'ความพร้อมใช้งานของไฟเลี้ยว / ไฟด้านข้าง',
  },
  {
    id: 16,
    name: 'tailgate',
    question: 'ตรวจเช็คฝาท้าย / ปากนกแก้ว',
    howto: 'สายตา/ทดลองใช้งาน',
    accept: 'ฝาท้ายปิดสนิท , ไม่ล้า ล็อกได้สนิททุกตัว ไม่มีการรั่วไหลของแร่',
  },
  {
    id: 17,
    name: 'hitch',
    question: 'ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การสึกหรอ รอยแตก รอยร้าว ของสลัก',
  },
  {
    id: 18,
    name: 'licensePlate',
    question: 'สภาพแผ่นป้ายทะเบียน',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'ครบ สะอาดมองเห็นชัดเจน ไม่เลือนลาง และเป็นป้ายที่ทางราชการออกให้',
  },
  {
    id: 19,
    name: 'wheelChock',
    question: 'ตรวจสอบอุปกรณ์หนุนล้อ',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'ขนาด 6×6×9 นิ้วพร้อมใช้งาน (2 อันรถบรรทุก 4 อันรถบรรทุกพ่วง)',
  },
  {
    id: 20,
    name: 'canvasChock',
    question: 'ตรวจสอบผ้าใบ',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'สภาพผ้าใบไม่ฉีกขาด ปิดสนิทคลุมกระบะบรรทุก',
  },
  {
    id: 21,
    name: 'reflectiveCone',
    question: 'ตรวจสอบกรวยจราจร / สามเหลี่ยมสะท้อนแสง',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'สภาพสมบูรณ์มีแถบสะท้อนแสง, ไม่สกปรก,สีไม่ซีด',
  },
  {
    id: 22,
    name: 'fireExtinguisher',
    question: 'ตรวจสอบถังดับเพลิง',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'สภาพพร้อมใช้งาน เกจวัดแรงดันชี้โซนสีเขียว อายุไม่เกิน 5 ปี',
  },
  {
    id: 23,
    name: 'insuranceTag',
    question: 'เครื่องหมายเสียภาษี / พรบ / ป้ายประกอบการ',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'ตรวจเช็คสภาพไม่ฉีกขาดมองเห็นชัดเจน,ไม่หมดอายุ',
  },
  {
    id: 24,
    name: 'gps',
    question: 'ระบบ GPS',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'พร้อมใช้งานมีเสียงหรือแสงเตือนกรณีความเร็วเกินกำหนด',
  },
  {
    id: 25,
    name: 'camera',
    question: 'กล้องติดตั้งหน้ารถ',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'พร้อมใช้งานตลอดเวลา',
  },
  {
    id: 26,
    name: 'airFilter',
    question: 'ตรวจสอบตัวกรองอากาศหรือกรองแอร์',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'ตรวจเช็คและเป่าตัวกรองทำความสะอาด',
  },
  {
    id: 27,
    name: 'aroundTruck',
    question: 'ตรวจสอบรอบรถ',
    howto: 'เดินตรวจสอบรอบรถ',
    accept: 'ตรวจสอบรอบรถและทำความสะอาด เช่น ระบบไฟ, กระจก, ภายในรถ',
  },
  {
    id: 28,
    name: 'brakeTest',
    question: 'ตรวจสอบระบบเบรก',
    howto: 'ทดลองเบรก',
    accept:
      'ออกเกียร์ 1 ความเร็ว 10 กม./ชม. ระยะ 5 ม. แล้วเหยีบเบรก รถหยุดใน 1 ม.',
  },
  {
    id: 29,
    name: 'seatBelt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'ใช้งานได้ปกติ กระตุกแล้วล็อค',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'remark', label: 'หมายเหตุ - Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
  { field: '1_brakeOil', label: '1. ตรวจสอบน้ำมันเบรก' },
  { field: '1_brakeOilR', label: '' },
  { field: '2_brakeHose', label: '2. ตรวจสอบสภาพท่อยางเบรก' },
  { field: '2_brakeHoseR', label: '' },
  { field: '3_airLeak', label: '3. ตรวจสอบสภาพการรั่วซึมของระบบลม' },
  { field: '3_airLeakR', label: '' },
  { field: '4_airTank', label: '4. ตรวจสอบถังลมเบรก' },
  { field: '4_airTankR', label: '' },
  {
    field: '5_dashboardLight',
    label: '5. ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ',
  },
  { field: '5_dashboardLightR', label: '' },
  { field: '6_clutchSystem', label: '6. ตรวจสภาพระบบคลัช' },
  { field: '6_clutchSystemR', label: '' },
  { field: '7_hydraulicLine', label: '7. ตรวจสายไฮโดรลิค' },
  { field: '7_hydraulicLineR', label: '' },
  { field: '8_dumpCylinder', label: '8. ตรวจกระบอกดั๊ม' },
  { field: '8_dumpCylinderR', label: '' },
  {
    field: '9_steeringBearing',
    label: '9. ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)',
  },
  { field: '9_steeringBearingR', label: '' },
  { field: '10_tieRodEnd', label: '10. ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย-ขวา)' },
  { field: '10_tieRodEndR', label: '' },
  { field: '11_tires', label: '11. ตรวจสภาพยางทุกเส้น' },
  { field: '11_tiresR', label: '' },
  { field: '12_rimAndNuts', label: '12. ตรวจสอบสภาพกระทะล้อ และน็อตล้อ' },
  { field: '12_rimAndNutsR', label: '' },
  { field: '13_headlightHorn', label: '13. ตรวจสภาพไฟหน้า/แตรสัญญาณ' },
  { field: '13_headlightHornR', label: '' },
  { field: '14_taillightBrakeLight', label: '14. ตรวจสภาพไฟท้าย / ไฟเบรก' },
  { field: '14_taillightBrakeLightR', label: '' },
  { field: '15_turnSignal', label: '15. ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง' },
  { field: '15_turnSignalR', label: '' },
  { field: '16_tailgateLock', label: '16. ตรวจเช็คฝาท้าย / ปากนกแก้ว' },
  { field: '16_tailgateLockR', label: '' },
  {
    field: '17_trailerPin',
    label: '17. ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง',
  },
  { field: '17_trailerPinR', label: '' },
  { field: '18_licensePlate', label: '18. สภาพแผ่นป้ายทะเบียน' },
  { field: '18_licensePlateR', label: '' },
  { field: '19_wheelChock', label: '19. ตรวจสอบอุปกรณ์หนุนล้อ' },
  { field: '19_wheelChockR', label: '' },
  { field: '20_canvasChock', label: '20. ตรวจสอบผ้าใบ' },
  { field: '20_canvasChockR', label: '' },
  {
    field: '21_reflectiveCone',
    label: '21. ตรวจสอบกรวยจราจร / สามเหลี่ยมสะท้อนแสง',
  },
  { field: '21_reflectiveConeR', label: '' },
  { field: '22_fireExtinguisher', label: '22. ตรวจสอบถังดับเพลิง' },
  { field: '22_fireExtinguisherR', label: '' },
  {
    field: '23_insuranceTag',
    label: '23. เครื่องหมายเสียภาษี / พรบ / ป้ายประกอบการ',
  },
  { field: '23_insuranceTagR', label: '' },
  { field: '24_gps', label: '24. ระบบ GPS' },
  { field: '24_gpsR', label: '' },
  { field: '25_camera', label: '25. กล้องติดตั้งหน้ารถ' },
  { field: '25_cameraR', label: '' },
  { field: '26_airFilter', label: '26. ตรวจสอบตัวกรองอากาศหรือกรองแอร์' },
  { field: '26_airFilterR', label: '' },
  { field: '27_aroundTruck', label: '27. ตรวจสอบรอบรถ' },
  { field: '27_aroundTruckR', label: '' },
  { field: '28_brakeTest', label: '28. ตรวจสอบระบบเบรก' },
  { field: '28_brakeTestR', label: '' },
  { field: '29_seatBelt', label: '29. เข็มขัดนิรภัย' },
  { field: '29_seatBeltR', label: '' },
];
