export const questions = [
  {
    id: 1,
    name: 'tyre',
    question: 'ดอกยาง,ลมยาง',
    howto: 'ดูสภาพยางและลมยาง',
    accept: 'มีดอกยางและมีลมปกติ',
  },
  {
    id: 2,
    name: 'horn',
    question: 'แตร/กริ่งสัญญาณ',
    howto: 'กดแตร/กริ่งสัญญาณ',
    accept: 'มีเสียงดังชัดเจน',
  },
  {
    id: 3,
    name: 'headLight',
    question: 'ไฟส่องสว่าง (ไฟหน้า,ไฟท้าย)',
    howto: 'เปิด / กดสวิชท์ไฟส่องสว่าง',
    accept: 'โคมไฟสว่างชัดเจนทุกดวง',
  },
  {
    id: 4,
    name: 'warningLight',
    question: 'ระบบไฟเตือน',
    howto: 'หมุนสวิชท์ไปยังตำแหน่ง ON',
    accept: 'ไฟที่แผงหน้าปัดติดแสดงเครื่องหมายต่างๆ ครบ',
  },
  {
    id: 5,
    name: 'signalLight',
    question: 'สัญญาณ(ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน*)',
    howto: 'เปิดสวิชท์ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน*',
    accept: 'แสงไฟกระพริบเป็นจังหวะปกติทุกดวง',
  },
  {
    id: 6,
    name: 'mirror',
    question: 'กระจกมองข้าง,กระจกมองหลัง*',
    howto: 'ดูสภาพความสะอาดและการปรับทิศทาง',
    accept: 'สะอาด ไม่หลวมและปรับมองตำแหน่งได้ชัดเจน',
  },
  {
    id: 7,
    name: 'exhaust',
    question: 'ท่อไอเสีย',
    howto: 'ตรวจสภาพ, ควัน, เสียง',
    accept: 'ไม่มีน้ำมันหยด, ไม่มีควันขาว, เสียงไม่ผิดปกติ',
  },
  {
    id: 8,
    name: 'chainGuard',
    question: 'โซ่และการ์ดป้องกัน',
    howto: 'ดูสภาพความตึงและความสมบูรณ์',
    accept: 'ไม่โยกหรือหลวม',
  },
  {
    id: 9,
    name: 'overallCondition',
    question: 'สภาพโดยรวม',
    howto: 'ดูสภาพโดยรวม',
    accept: 'สะอาด, สามารถใช้งานได้',
  },
  {
    id: 10,
    name: 'brake',
    question: 'ระบบเบรค',
    howto: 'เหยียบแป้นเบรกและ/หรือบีบเบรกมือ',
    accept: 'มีแรงดันตอบสนองการเบรค',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'tyre', label: '1. ดอกยาง,ลมยาง' },
  { field: 'tyreR', label: '' },
  { field: 'tyreP', label: '' },
  { field: 'tyreA', label: 'Respond to defect' },
  { field: 'tyreF', label: '' },
  { field: 'horn', label: '2. แตร/กริ่งสัญญาณ' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'headLight', label: '3. ไฟส่องสว่าง (ไฟหน้า,ไฟท้าย)' },
  { field: 'headLightR', label: '' },
  { field: 'headLightP', label: '' },
  { field: 'headLightA', label: 'Respond to defect' },
  { field: 'headLightF', label: '' },
  { field: 'warningLight', label: '4. ระบบไฟเตือน' },
  { field: 'warningLightR', label: '' },
  { field: 'warningLightP', label: '' },
  { field: 'warningLightA', label: 'Respond to defect' },
  { field: 'warningLightF', label: '' },
  { field: 'signalLight', label: '5. สัญญาณ(ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน*)' },
  { field: 'signalLightR', label: '' },
  { field: 'signalLightP', label: '' },
  { field: 'signalLightA', label: 'Respond to defect' },
  { field: 'signalLightF', label: '' },
  { field: 'mirror', label: '6. กระจกมองข้าง,กระจกมองหลัง*' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'exhaust', label: '7. ท่อไอเสีย' },
  { field: 'exhaustR', label: '' },
  { field: 'exhaustP', label: '' },
  { field: 'exhaustA', label: 'Respond to defect' },
  { field: 'exhaustF', label: '' },
  { field: 'chainGuard', label: '8. โซ่และการ์ดป้องกัน' },
  { field: 'chainGuardR', label: '' },
  { field: 'chainGuardP', label: '' },
  { field: 'chainGuardA', label: 'Respond to defect' },
  { field: 'chainGuardF', label: '' },
  { field: 'overallCondition', label: '9. สภาพโดยรวม' },
  { field: 'overallConditionR', label: '' },
  { field: 'overallConditionP', label: '' },
  { field: 'overallConditionA', label: 'Respond to defect' },
  { field: 'overallConditionF', label: '' },
  { field: 'brake', label: '10. ระบบเบรค' },
  { field: 'brakeR', label: '' },
  { field: 'brakeP', label: '' },
  { field: 'brakeA', label: 'Respond to defect' },
  { field: 'brakeF', label: '' },
  { field: 'remark', label: 'หมายเหตุ - Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
