export const questions = [
  {
    id: 1,
    name: 'battery',
    question: 'អាគុយមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងកំរិតថ្ម',
    accept: 'គ្មានស្នាមច្រេះ និងស្ថានភាពអាគុយនៅល្អ',
  },
  {
    id: 2,
    name: 'headLight',
    question: 'ភ្លើងចង្កៀងមុខមិនធម្មតា',
    howto: 'បើកតេស្តស្ថានភាពភ្លើង',
    accept: 'មិនដាច់ភ្លើង និង ភ្លើងនៅភ្លឺច្បាស់',
  },
  {
    id: 3,
    name: 'signalLight',
    question: 'ភ្លើងស៊ីញ៉ូមិនធម្មតា',
    howto: 'បើកភ្លើងស៊ីញ៉ូ ពិនិត្យការដំណើរការ',
    accept: 'ភ្លើងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 4,
    name: 'brakeLight',
    question: 'ភ្លើងហ្រាំងមិនធម្មតា',
    howto: 'ជាន់ហ្រាំងពិនិត្យ',
    accept: 'ភ្លឺច្បាស់ មិនមានបញ្ហាខុសប្រក្រតី',
  },
  {
    id: 5,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'តេស្តចុចស៊ីផ្លេ',
    accept: 'បញ្ជារដោយរលូន និងលឺច្បាស់',
  },
  {
    id: 6,
    name: 'wiper',
    question: 'ផ្លឹតទឹកជូតកញ្ចក់មិនធម្មតា',
    howto: 'តេស្តប្រើផ្លិតទឹកជូតកញ្ចក់',
    accept: 'បញ្ជារដោយរលូន មានទឹកគ្រប់គ្រាន់ និងជូតបានស្អាត',
  },
  {
    id: 7,
    name: 'windshield',
    question: 'កញ្ចក់មុខ កញ្ចក់មើលក្រោយ ទ្វា និងបង្អួចមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពជាក់ស្តែង',
    accept: 'មានគ្រប់គ្រាន់ មិនបែកបាក់ និងមើលឃើញច្បាស់',
  },
  {
    id: 8,
    name: 'belt',
    question: 'ខ្សែក្រវ៉ាត់សុវត្តិភាពមិនធម្មតា',
    howto: 'តេស្តពាក់ និងចុចគន្លឹះដំណើរការដែរទេ',
    accept: 'ពាក់ជាប់ល្អ ស្ថានភាពខ្សែក្រវ៉ាត់នៅល្អ និង គន្លឹះដំណើរការល្អ',
  },
  {
    id: 9,
    name: 'dashboard',
    question: 'ពិនិត្យនាឡិកាសំម្ពាធខ្យល់ និងពត៌មានលើតាបឡូមិនធម្មតា',
    howto: 'ពិនិត្យការបង្ហាញពត៍មាន',
    accept: 'ការបង្ហាញពត៌មានត្រឹមត្រូវ',
  },
  {
    id: 10,
    name: 'wheel',
    question: 'កង់ឡានមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពសំពាធខ្យល់ និងសំបកកង់',
    accept: 'មានខ្យល់គ្រប់គ្រាន់ សំបកកង់នៅក្រឡាល្អ និងប៊ូឡុងខ្ចៅនៅល្អ',
  },
  {
    id: 11,
    name: 'brakeSys',
    question: 'ប្រពន្ទហ្រ្វាំងមិនធម្មតា',
    howto: 'តេស្តជាន់សាកល្បង',
    accept: 'ជាន់ជាប់ល្អ មិនមានបញ្ហាលេខធ្លាយខ្យល់ ឬ លេចធ្លាយប្រេង',
  },
  {
    id: 12,
    name: 'hose',
    question: 'ស្ថានភាពពោង ទុយោ និងវ៉ានមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបំពង់',
    accept: 'គ្មានការច្រេះ និងលេចធ្លាយ',
  },
  {
    id: 13,
    name: 'equipment',
    question: 'សម្ភារៈសុវត្ថិភាពមិនធម្មតា (កោន, កំណល់កង់ និង ចំណាំងផ្លាត)',
    howto: 'ពិនិត្យសម្ភារៈសុវត្ថិភាព',
    accept: 'សម្ភារៈស្ថានភាពល្អ គ្មានការខូចខាត',
  },
  {
    id: 14,
    name: 'extinguisher',
    question: 'បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'មានបំពង់ពន្លត់អគ្គីភ័យ និងនៅដំណើរការ',
    accept: 'មិនបាត់ក្រឡាស់ និង ទ្រនិចនៅចំណុចពណ៌ខៀវ',
  },
  {
    id: 15,
    name: 'ppe',
    question: 'សម្ភារៈការពារខ្លួន (PPE)មិនធម្មតា',
    howto: 'ពិនិត្យសម្ភារៈការពារខ្លួន',
    accept: 'ស្ថានភាពល្អ គ្មានការខូចខាត',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'battery', label: '1. អាគុយមិនធម្មតា' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'headLight', label: '2. ភ្លើងចង្កៀងមុខមិនធម្មតា' },
  { field: 'headLightR', label: '' },
  { field: 'headLightP', label: '' },
  { field: 'headLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'headLightF', label: '' },
  { field: 'signalLight', label: '3. ភ្លើងស៊ីញ៉ូមិនធម្មតា' },
  { field: 'signalLightR', label: '' },
  { field: 'signalLightP', label: '' },
  { field: 'signalLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'signalLightF', label: '' },
  { field: 'brakeLight', label: '4. ភ្លើងហ្រាំងមិនធម្មតា' },
  { field: 'brakeLightR', label: '' },
  { field: 'brakeLightP', label: '' },
  { field: 'brakeLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'brakeLightF', label: '' },
  { field: 'horn', label: '5. ស៊ីផ្លេមិនធម្មតា' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'wiper', label: '6. ផ្លឹតទឹកជូតកញ្ចក់មិនធម្មតា' },
  { field: 'wiperR', label: '' },
  { field: 'wiperP', label: '' },
  { field: 'wiperA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wiperF', label: '' },
  {
    field: 'windshield',
    label: '7. កញ្ចក់មុខ កញ្ចក់មើលក្រោយ ទ្វា និងបង្អួចមិនធម្មតា',
  },
  { field: 'windshieldR', label: '' },
  { field: 'windshieldP', label: '' },
  { field: 'windshieldA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'windshieldF', label: '' },
  { field: 'belt', label: '8. ខ្សែក្រវ៉ាត់សុវត្តិភាពមិនធម្មតា' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'beltF', label: '' },
  {
    field: 'dashboard',
    label: '9. ពិនិត្យនាឡិកាសំម្ពាធខ្យល់ និងពត៌មានលើតាបឡូមិនធម្មតា',
  },
  { field: 'dashboardR', label: '' },
  { field: 'dashboardP', label: '' },
  { field: 'dashboardA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'dashboardF', label: '' },
  { field: 'wheel', label: '10. កង់ឡានមិនធម្មតា' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'brakeSys', label: '11. ប្រពន្ទហ្រ្វាំងមិនធម្មតា' },
  { field: 'brakeSysR', label: '' },
  { field: 'brakeSysP', label: '' },
  { field: 'brakeSysA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'brakeSysF', label: '' },
  { field: 'hose', label: '12. ស្ថានភាពពោង ទុយោ និងវ៉ានមិនធម្មតា' },
  { field: 'hoseR', label: '' },
  { field: 'hoseP', label: '' },
  { field: 'hoseA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hoseF', label: '' },
  {
    field: 'equipment',
    label: '13. សម្ភារៈសុវត្ថិភាពមិនធម្មតា (កោន, កំណល់កង់ និង ចំណាំងផ្លាត)',
  },
  { field: 'equipmentR', label: '' },
  { field: 'equipmentP', label: '' },
  { field: 'equipmentA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'equipmentF', label: '' },
  { field: 'extinguisher', label: '14. បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'ppe', label: '15. សម្ភារៈការពារខ្លួន (PPE)មិនធម្មតា' },
  { field: 'ppeR', label: '' },
  { field: 'ppeP', label: '' },
  { field: 'ppeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'ppeF', label: '' },
  { field: 'remark', label: 'មតិយោបល់ - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
