export const questions = [
  {
    id: 1,
    name: 'carBodyColor',
    question: 'สภาพสีรถและตัวถัง',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'สีของตัวถังไม่มีรอยถลอก รอยบุบ หรือซีดจาง',
  },
  {
    id: 2,
    name: 'seatBelt',
    question: 'เข็มขัดนิรภัย',
    howto: 'ตรวจสอบด้วยการดึงและล็อก',
    accept: 'สภาพสมบูรณ์ ล็อกใช้งานได้แน่นหนา',
  },
  {
    id: 3,
    name: 'tireFront',
    question: 'สภาพยาง (หน้า)',
    howto: 'วัดความลึกของดอกยางด้วยเครื่องมือ',
    accept:
      'มาตรฐานของบริษัทยาง เช่น บริดจสโตน และ ยูโรไทร์ กำหนดไว้ 2 มม. ยางดอกบั้งและดอกสร้อยวัดความลึกเหมือนกัน',
  },
  {
    id: 4,
    name: 'tireOther',
    question: 'สภาพยาง (เส้นอื่น)',
    howto: 'วัดความลึกของดอกยางด้วยเครื่องมือ',
    accept:
      'มาตรฐานของบริษัทยาง เช่น บริดจสโตน และ ยูโรไทร์ กำหนดไว้ 2 มม. ยางดอกบั้งและดอกสร้อยวัดความลึกเหมือนกัน',
  },
  {
    id: 5,
    name: 'tireProductionDate',
    question: 'สัปดาห์และปีการผลิต (ทุกเส้น)',
    howto: 'ตรวจดูข้อมูลที่แก้มยาง',
    accept: 'สัปดาห์และปีการผลิตระบุไว้อย่างชัดเจน',
  },
  {
    id: 6,
    name: 'spareTire',
    question: 'ยางอะไหล่สภาพพร้อมใช้งาน',
    howto: 'ตรวจสอบด้วยสายตาและลองสูบลม',
    accept: 'ดอกยางลึกพอสมควร ไม่มีรอยรั่ว',
  },
  {
    id: 7,
    name: 'rimAndNuts',
    question: 'กระทะล้อ , น๊อตล้อ (ทุกล้อ)',
    howto: 'ตรวจสอบด้วยสายตาและใช้ประแจขัน',
    accept: 'กระทะล้อไม่มีรอยแตก น๊อตล้อครบทุกตัวและแน่น',
  },
  {
    id: 8,
    name: 'steeringBallJoint',
    question: 'ลูกหมากคันชัก (หน้า หลัง)',
    howto: 'ตรวจสอบการเคลื่อนไหวและระยะฟรีของพวงมาลัย',
    accept: 'ไม่มีการหลวมตัวหรือรอยสึกหรอ',
  },
  {
    id: 9,
    name: 'tieRodEnd',
    question: 'ลูกหมากคันส่ง (หน้า หลัง)',
    howto: 'ตรวจสอบด้วยการโยกพวงมาลัย',
    accept: 'ไม่มีเสียงผิดปกติหรือรอยหลวม',
  },
  {
    id: 10,
    name: 'fluids',
    question: 'น้ำมัน(เครื่อง,เกียร์,เฟืองท้าย,เบรค,เพาเวอร์)',
    howto: 'ตรวจระดับด้วยก้านวัดหรือตรวจดูในช่อง',
    accept: 'ระดับน้ำมันอยู่ในเกณฑ์ที่กำหนด ไม่มีรอยรั่ว',
  },
  {
    id: 11,
    name: 'clampJaw',
    question: 'สภาพปากนกแก้ว',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่มีรอยแตกหรือหลวม',
  },
  {
    id: 12,
    name: 'clampLock',
    question: 'สภาพตัวล็อคปากนกแก้ว',
    howto: 'ตรวจสอบด้วยการลองล็อค',
    accept: 'ล็อคแน่นหนาและไม่มีรอยเสียหาย',
  },
  {
    id: 13,
    name: 'bedCondition',
    question: 'สภาพพื้นกระบะ',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'พื้นกระบะไม่มีรอยแตกร้าวหรือเป็นสนิม',
  },
  {
    id: 14,
    name: 'hydraulicCylinder',
    question:
      'ชุดกระบอกไฮดรอลิกยกดั๊มพ์ , (ความแข็งแรงของแกนยก ,ขาตั๊กแตนหรือตัวประคองแกนยก)',
    howto: 'ตรวจสอบด้วยสายตาและลองใช้งาน',
    accept: 'ไม่มีรอยรั่วหรือเสียหาย การทำงานเป็นไปอย่างราบรื่น',
  },
  {
    id: 15,
    name: 'trailerSystem',
    question: 'ระบบส่วนพ่วง',
    howto: 'ตรวจสอบการเชื่อมต่อและความแน่นหนา',
    accept: 'ไม่มีจุดหลวม การเชื่อมต่อมั่นคง',
  },
  {
    id: 16,
    name: 'wheelBlock',
    question: 'ขอนหนุนล้อขนาด 6 นิ้ว , จำนวน 2 ชิ้น',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ขอนหนุนล้ออยู่ในสภาพสมบูรณ์ ขนาดตามที่กำหนด',
  },
  {
    id: 17,
    name: 'reflectiveDevices',
    question:
      'อุปกรณ์สะท้อนแสง 2 อัน, ป้ายสามเหลี่ยมด้านเท่าสูงไม่ต่ำกว่าด้านละ 50 ซ.ม',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'แถบสะท้อนแสงอยู่ในสภาพดี มองเห็นได้ชัดเจน',
  },
  {
    id: 18,
    name: 'reflectiveStrips',
    question:
      'แถบสะท้อนแสง รอบคัน , มีแถบสะท้อนแสงรอบคันรถ มองเห็นได้ในระยะ 150 เมตรในกลางคืน',
    howto: 'ตรวจสอบด้วยสายตาในที่มืด',
    accept: 'แถบสะท้อนแสงอยู่ในสภาพดี ไม่มีรอยหลุดหรือจาง',
  },
  {
    id: 19,
    name: 'fireExtinguisher',
    question:
      'ถังดับเพลิง 10 - 15 ปอนด์, จำนวน 1 ถัง สำหรับเชื้อเพลิงประเภท ABC',
    howto: 'ตรวจสอบเกจวัดแรงดันและวันหมดอายุ',
    accept: 'แรงดันอยู่ในโซนสีเขียว และยังไม่หมดอายุ',
  },
  {
    id: 20,
    name: 'headLights',
    question: 'ไฟหน้า(สูง,ต่ำ)/ไฟหรี่',
    howto: 'ทดสอบการเปิดใช้งานทุกระดับ',
    accept: 'ไฟหน้าทุกดวงติดครบถ้วนและให้แสงสว่างปกติ',
  },
  {
    id: 21,
    name: 'reverseLightsAndAlarm',
    question: 'สัญญาณถอยหลัง,แสงและเสียง',
    howto: 'ใส่เกียร์ถอยหลังแล้วตรวจสอบแสงและเสียง',
    accept: 'สัญญาณถอยหลังทำงานปกติ มีทั้งแสงและเสียงเตือน',
  },
  {
    id: 22,
    name: 'turnSignals',
    question: 'ไฟเลี้ยว หน้า/หลัง',
    howto: 'เปิดไฟเลี้ยวทั้งสองด้านและตรวจสอบ',
    accept: 'ไฟเลี้ยวกระพริบครบทุกดวง',
  },
  {
    id: 23,
    name: 'brakeAndHazardLights',
    question: 'ไฟเบรค/ไฟฉุกเฉิน',
    howto: 'เหยียบเบรคและเปิดไฟฉุกเฉินเพื่อตรวจสอบ',
    accept: 'ไฟเบรคและไฟฉุกเฉินติดครบทุกดวง',
  },
  {
    id: 24,
    name: 'sideSignalLights',
    question: 'ไฟสัญญาณข้างตัวรถ',
    howto: 'เปิดไฟเลี้ยวและตรวจสอบไฟข้างตัวรถ',
    accept: 'ไฟสัญญาณข้างตัวรถทำงานปกติ',
  },
  {
    id: 25,
    name: 'horn',
    question: 'สัญญานเสียงแตร',
    howto: 'กดแตรเพื่อตรวจสอบ',
    accept: 'แตรเสียงดังชัดเจน',
  },
  {
    id: 26,
    name: 'parkingBrake',
    question:
      'เบรคมือ, (ทดสอบจอดพื้นที่ลาดเอียง ปลดเกียร์ว่าง ดึงเบรคมือ รถไม่เคลื่อน)',
    howto: 'ดึงเบรคมือและทดสอบในพื้นที่ลาดเอียง',
    accept: 'เบรคมือสามารถหยุดรถบนพื้นที่ลาดเอียงได้',
  },
  {
    id: 27,
    name: 'brakeAirPressure',
    question:
      'เดินเครื่องให้ระบบลมเบรคเต็ม(สังเกตุจากระบบตัดลมหรือ blow ออก) อ่านค่าได้, kg/cm2 หรือ x100 kPa',
    howto: 'เดินเครื่องยนต์และรอจนแรงดันลมถึงค่ามาตรฐาน',
    accept: 'ระบบลมเบรคเต็มตามค่าที่กำหนด',
  },
  {
    id: 28,
    name: 'brakeTest',
    question:
      'ทดสอบเหยียบเบรค 4 ครั้งติดต่อกัน สังเกตลมในระบบจะลดลงอ่านค่าได้, kg/cm2 หรือ x100 kPa (กำหนดไม่ให้ต่ำกว่า 25%)',
    howto: 'ทดสอบเหยียบเบรคซ้ำและอ่านค่าลม',
    accept: 'แรงดันลมไม่ต่ำกว่า 25% หลังการทดสอบ',
  },
  {
    id: 29,
    name: 'airPressureRetention',
    question:
      'ดับเครื่องยนต์ (งดใช้งานระบบลมทุกชนิด) ระยะเวลา 15 นาทีลมในระบบลดลงเหลือ, kg/cm2 หรือ x100 kPa (กำหนดไม่ให้ต่ำกว่า 25%)',
    howto: 'ดับเครื่องและรอ 15 นาที จากนั้นตรวจสอบค่าลม',
    accept: 'แรงดันลมลดลงไม่เกิน 25% ในเวลา 15 นาที',
  },
  {
    id: 30,
    name: 'lowPressureWarning',
    question:
      'ทดสอบเหยียบเบรคจนแรงดันต่ำสุดเพื่อตรวจสอบสัญญาณเตือน ลมในระบบลดลงเหลือ, kg/cm2 หรือ x100 kPa',
    howto: 'เหยียบเบรคจนแรงดันต่ำสุดและตรวจสอบสัญญาณเตือน',
    accept: 'ระบบเตือนทำงานเมื่อแรงดันต่ำกว่าค่ามาตรฐาน',
  },
  {
    id: 31,
    name: 'warningSignals',
    question: 'สัญญาณเสียง / แสงเตือน',
    howto: 'ตรวจสอบการทำงานของไฟและเสียงเตือนในทุกระบบ',
    accept: 'ระบบเตือนทำงานสมบูรณ์',
  },
  {
    id: 32,
    name: 'speedometer',
    question: 'เครื่องวัดความเร็ว',
    howto: 'ทดสอบโดยการขับรถและตรวจสอบค่าความเร็ว',
    accept: 'เครื่องวัดความเร็วแสดงค่าถูกต้อง',
  },
  {
    id: 33,
    name: 'mirrors',
    question: 'กระจกมองหลัง/ข้าง',
    howto: 'ตรวจสอบความสะอาดและการปรับมุมมอง',
    accept: 'กระจกปรับมุมมองได้สะดวกและไม่มีรอยร้าว',
  },
  {
    id: 34,
    name: 'tachometer',
    question: 'เครื่องวัดรอบ',
    howto: 'ตรวจสอบการแสดงค่าขณะเครื่องยนต์ทำงาน',
    accept: 'เครื่องวัดรอบแสดงค่าปกติ',
  },
  {
    id: 35,
    name: 'wipers',
    question: 'ที่ปัดน้ำฝน ซ้าย-ขวา',
    howto: 'เปิดใช้งานและตรวจสอบการปัดน้ำ',
    accept: 'ปัดน้ำได้สะอาดและไม่มีเสียงดังผิดปกติ',
  },
  {
    id: 36,
    name: 'washerSystem',
    question: 'ระบบฉีดน้ำล้างกระจก',
    howto: 'เปิดระบบฉีดน้ำล้างกระจกและตรวจสอบ',
    accept: 'น้ำฉีดแรงสม่ำเสมอ',
  },
  {
    id: 37,
    name: 'ignitionSwitch',
    question: 'ระบบสวิทกุญแจสตาร์ท',
    howto: 'บิดกุญแจและตรวจสอบการทำงาน',
    accept: 'สตาร์ทเครื่องยนต์ได้ปกติ',
  },
  {
    id: 38,
    name: 'engine',
    question: 'เครื่องยนต์, (เสียงเครื่องยนต์, ควันจากท่อไอเสีย ฯลฯ)',
    howto: 'สังเกตเสียงและควันขณะเครื่องยนต์ทำงาน',
    accept: 'เสียงเครื่องยนต์เรียบ ควันไม่มีสีผิดปกติ',
  },
  {
    id: 39,
    name: 'driveShaft',
    question: 'ข้อต่อเพลาส่งกำลัง',
    howto: 'ตรวจสอบความแข็งแรงของข้อต่อ',
    accept: 'ไม่มีรอยหลวม หรือสึกหรอ',
  },
  {
    id: 40,
    name: 'clutchAndGear',
    question:
      'อุปกรณ์ระบบเกียร์และคลัทช์ , (สังเกตุจากเสียงผิดปกติเมื่อปลดหรือเข้าเกียร์)',
    howto: 'ทดสอบการเปลี่ยนเกียร์ในทุกตำแหน่ง',
    accept: 'ไม่มีเสียงผิดปกติหรือการกระตุก',
  },
  {
    id: 41,
    name: 'batteryClamp',
    question: 'การยึดแบตเตอรี่',
    howto: 'ตรวจสอบการขันน๊อตและขาตั้ง',
    accept: 'แบตเตอรี่ยึดแน่นไม่มีการเคลื่อนตัว',
  },
  {
    id: 42,
    name: 'batteryCondition',
    question: 'สภาพแบตเตอรี่',
    howto: 'ตรวจดูคราบสกปรกและตรวจระดับน้ำกลั่น',
    accept: 'แบตเตอรี่อยู่ในสภาพดี ไม่มีรอยแตกร้าว',
  },
  {
    id: 43,
    name: 'overallInspection',
    question: 'การตรวจสภาพทั่วไป',
    howto: 'ตรวจสอบภาพรวมทั้งหมด',
    accept: 'ทุกระบบทำงานปกติและผ่านมาตรฐาน',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'carBodyColor', label: '1. สภาพสีรถและตัวถัง' },
  { field: 'carBodyColorR', label: '' },
  { field: 'carBodyColorP', label: '' },
  { field: 'carBodyColorA', label: 'Respond to defect' },
  { field: 'carBodyColorF', label: '' },
  { field: 'seatBelt', label: '2. เข็มขัดนิรภัย' },
  { field: 'seatBeltR', label: '' },
  { field: 'seatBeltP', label: '' },
  { field: 'seatBeltA', label: 'Respond to defect' },
  { field: 'seatBeltF', label: '' },
  { field: 'tireFront', label: '3. สภาพยาง (หน้า)' },
  { field: 'tireFrontR', label: '' },
  { field: 'tireFrontP', label: '' },
  { field: 'tireFrontA', label: 'Respond to defect' },
  { field: 'tireFrontF', label: '' },
  { field: 'tireOther', label: '4. สภาพยาง (เส้นอื่น)' },
  { field: 'tireOtherR', label: '' },
  { field: 'tireOtherP', label: '' },
  { field: 'tireOtherA', label: 'Respond to defect' },
  { field: 'tireOtherF', label: '' },
  { field: 'tireProductionDate', label: '5. สัปดาห์และปีการผลิต (ทุกเส้น)' },
  { field: 'tireProductionDateR', label: '' },
  { field: 'tireProductionDateP', label: '' },
  { field: 'tireProductionDateA', label: 'Respond to defect' },
  { field: 'tireProductionDateF', label: '' },
  { field: 'spareTire', label: '6. ยางอะไหล่สภาพพร้อมใช้งาน' },
  { field: 'spareTireR', label: '' },
  { field: 'spareTireP', label: '' },
  { field: 'spareTireA', label: 'Respond to defect' },
  { field: 'spareTireF', label: '' },
  { field: 'rimAndNuts', label: '7. กระทะล้อ , น๊อตล้อ (ทุกล้อ)' },
  { field: 'rimAndNutsR', label: '' },
  { field: 'rimAndNutsP', label: '' },
  { field: 'rimAndNutsA', label: 'Respond to defect' },
  { field: 'rimAndNutsF', label: '' },
  { field: 'steeringBallJoint', label: '8. ลูกหมากคันชัก (หน้า หลัง)' },
  { field: 'steeringBallJointR', label: '' },
  { field: 'steeringBallJointP', label: '' },
  { field: 'steeringBallJointA', label: 'Respond to defect' },
  { field: 'steeringBallJointF', label: '' },
  { field: 'tieRodEnd', label: '9. ลูกหมากคันส่ง (หน้า หลัง)' },
  { field: 'tieRodEndR', label: '' },
  { field: 'tieRodEndP', label: '' },
  { field: 'tieRodEndA', label: 'Respond to defect' },
  { field: 'tieRodEndF', label: '' },
  {
    field: 'fluids',
    label: '10. น้ำมัน(เครื่อง,เกียร์,เฟืองท้าย,เบรค,เพาเวอร์)',
  },
  { field: 'fluidsR', label: '' },
  { field: 'fluidsP', label: '' },
  { field: 'fluidsA', label: 'Respond to defect' },
  { field: 'fluidsF', label: '' },
  { field: 'clampJaw', label: '11. สภาพปากนกแก้ว' },
  { field: 'clampJawR', label: '' },
  { field: 'clampJawP', label: '' },
  { field: 'clampJawA', label: 'Respond to defect' },
  { field: 'clampJawF', label: '' },
  { field: 'clampLock', label: '12. สภาพตัวล็อคปากนกแก้ว' },
  { field: 'clampLockR', label: '' },
  { field: 'clampLockP', label: '' },
  { field: 'clampLockA', label: 'Respond to defect' },
  { field: 'clampLockF', label: '' },
  { field: 'bedCondition', label: '13. สภาพพื้นกระบะ' },
  { field: 'bedConditionR', label: '' },
  { field: 'bedConditionP', label: '' },
  { field: 'bedConditionA', label: 'Respond to defect' },
  { field: 'bedConditionF', label: '' },
  {
    field: 'hydraulicCylinder',
    label:
      '14. ชุดกระบอกไฮดรอลิกยกดั๊มพ์ , (ความแข็งแรงของแกนยก ,ขาตั๊กแตนหรือตัวประคองแกนยก)',
  },
  { field: 'hydraulicCylinderR', label: '' },
  { field: 'hydraulicCylinderP', label: '' },
  { field: 'hydraulicCylinderA', label: 'Respond to defect' },
  { field: 'hydraulicCylinderF', label: '' },
  { field: 'trailerSystem', label: '15. ระบบส่วนพ่วง' },
  { field: 'trailerSystemR', label: '' },
  { field: 'trailerSystemP', label: '' },
  { field: 'trailerSystemA', label: 'Respond to defect' },
  { field: 'trailerSystemF', label: '' },
  { field: 'wheelBlock', label: '16. ขอนหนุนล้อขนาด 6 นิ้ว , จำนวน 2 ชิ้น' },
  { field: 'wheelBlockR', label: '' },
  { field: 'wheelBlockP', label: '' },
  { field: 'wheelBlockA', label: 'Respond to defect' },
  { field: 'wheelBlockF', label: '' },
  {
    field: 'reflectiveDevices',
    label:
      '17. อุปกรณ์สะท้อนแสง 2 อัน, ป้ายสามเหลี่ยมด้านเท่าสูงไม่ต่ำกว่าด้านละ 50 ซ.ม',
  },
  { field: 'reflectiveDevicesR', label: '' },
  { field: 'reflectiveDevicesP', label: '' },
  { field: 'reflectiveDevicesA', label: 'Respond to defect' },
  { field: 'reflectiveDevicesF', label: '' },
  {
    field: 'reflectiveStrips',
    label:
      '18. แถบสะท้อนแสง รอบคัน , มีแถบสะท้อนแสงรอบคันรถ มองเห็นได้ในระยะ 150 เมตรในกลางคืน',
  },
  { field: 'reflectiveStripsR', label: '' },
  { field: 'reflectiveStripsP', label: '' },
  { field: 'reflectiveStripsA', label: 'Respond to defect' },
  { field: 'reflectiveStripsF', label: '' },
  {
    field: 'fireExtinguisher',
    label:
      '19. ถังดับเพลิง 10 - 15 ปอนด์, จำนวน 1 ถัง สำหรับเชื้อเพลิงประเภท ABC',
  },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  { field: 'headLights', label: '20. ไฟหน้า(สูง,ต่ำ)/ไฟหรี่' },
  { field: 'headLightsR', label: '' },
  { field: 'headLightsP', label: '' },
  { field: 'headLightsA', label: 'Respond to defect' },
  { field: 'headLightsF', label: '' },
  { field: 'reverseLightsAndAlarm', label: '21. สัญญาณถอยหลัง,แสงและเสียง' },
  { field: 'reverseLightsAndAlarmR', label: '' },
  { field: 'reverseLightsAndAlarmP', label: '' },
  { field: 'reverseLightsAndAlarmA', label: 'Respond to defect' },
  { field: 'reverseLightsAndAlarmF', label: '' },
  { field: 'turnSignals', label: '22. ไฟเลี้ยว หน้า/หลัง' },
  { field: 'turnSignalsR', label: '' },
  { field: 'turnSignalsP', label: '' },
  { field: 'turnSignalsA', label: 'Respond to defect' },
  { field: 'turnSignalsF', label: '' },
  { field: 'brakeAndHazardLights', label: '23. ไฟเบรค/ไฟฉุกเฉิน' },
  { field: 'brakeAndHazardLightsR', label: '' },
  { field: 'brakeAndHazardLightsP', label: '' },
  { field: 'brakeAndHazardLightsA', label: 'Respond to defect' },
  { field: 'brakeAndHazardLightsF', label: '' },
  { field: 'sideSignalLights', label: '24. ไฟสัญญาณข้างตัวรถ' },
  { field: 'sideSignalLightsR', label: '' },
  { field: 'sideSignalLightsP', label: '' },
  { field: 'sideSignalLightsA', label: 'Respond to defect' },
  { field: 'sideSignalLightsF', label: '' },
  { field: 'horn', label: '25. สัญญานเสียงแตร' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  {
    field: 'parkingBrake',
    label:
      '26. เบรคมือ, (ทดสอบจอดพื้นที่ลาดเอียง ปลดเกียร์ว่าง ดึงเบรคมือ รถไม่เคลื่อน)',
  },
  { field: 'parkingBrakeR', label: '' },
  { field: 'parkingBrakeP', label: '' },
  { field: 'parkingBrakeA', label: 'Respond to defect' },
  { field: 'parkingBrakeF', label: '' },
  {
    field: 'brakeAirPressure',
    label:
      '27. เดินเครื่องให้ระบบลมเบรคเต็ม(สังเกตุจากระบบตัดลมหรือ blow ออก) อ่านค่าได้, kg/cm2 หรือ x100 kPa',
  },
  { field: 'brakeAirPressureR', label: '' },
  { field: 'brakeAirPressureP', label: '' },
  { field: 'brakeAirPressureA', label: 'Respond to defect' },
  { field: 'brakeAirPressureF', label: '' },
  {
    field: 'brakeTest',
    label:
      '28. ทดสอบเหยียบเบรค 4 ครั้งติดต่อกัน สังเกตลมในระบบจะลดลงอ่านค่าได้, kg/cm2 หรือ x100 kPa (กำหนดไม่ให้ต่ำกว่า 25%)',
  },
  { field: 'brakeTestR', label: '' },
  { field: 'brakeTestP', label: '' },
  { field: 'brakeTestA', label: 'Respond to defect' },
  { field: 'brakeTestF', label: '' },
  {
    field: 'airPressureRetention',
    label:
      '29. ดับเครื่องยนต์ (งดใช้งานระบบลมทุกชนิด) ระยะเวลา 15 นาทีลมในระบบลดลงเหลือ, kg/cm2 หรือ x100 kPa (กำหนดไม่ให้ต่ำกว่า 25%)',
  },
  { field: 'airPressureRetentionR', label: '' },
  { field: 'airPressureRetentionP', label: '' },
  { field: 'airPressureRetentionA', label: 'Respond to defect' },
  { field: 'airPressureRetentionF', label: '' },
  {
    field: 'lowPressureWarning',
    label:
      '30. ทดสอบเหยียบเบรคจนแรงดันต่ำสุดเพื่อตรวจสอบสัญญาณเตือน ลมในระบบลดลงเหลือ, kg/cm2 หรือ x100 kPa',
  },
  { field: 'lowPressureWarningR', label: '' },
  { field: 'lowPressureWarningP', label: '' },
  { field: 'lowPressureWarningA', label: 'Respond to defect' },
  { field: 'lowPressureWarningF', label: '' },
  { field: 'warningSignals', label: '31. สัญญาณเสียง / แสงเตือน' },
  { field: 'warningSignalsR', label: '' },
  { field: 'warningSignalsP', label: '' },
  { field: 'warningSignalsA', label: 'Respond to defect' },
  { field: 'warningSignalsF', label: '' },
  { field: 'speedometer', label: '32. เครื่องวัดความเร็ว' },
  { field: 'speedometerR', label: '' },
  { field: 'speedometerP', label: '' },
  { field: 'speedometerA', label: 'Respond to defect' },
  { field: 'speedometerF', label: '' },
  { field: 'mirrors', label: '33. กระจกมองหลัง/ข้าง' },
  { field: 'mirrorsR', label: '' },
  { field: 'mirrorsP', label: '' },
  { field: 'mirrorsA', label: 'Respond to defect' },
  { field: 'mirrorsF', label: '' },
  { field: 'tachometer', label: '34. เครื่องวัดรอบ' },
  { field: 'tachometerR', label: '' },
  { field: 'tachometerP', label: '' },
  { field: 'tachometerA', label: 'Respond to defect' },
  { field: 'tachometerF', label: '' },
  { field: 'wipers', label: '35. ที่ปัดน้ำฝน ซ้าย-ขวา' },
  { field: 'wipersR', label: '' },
  { field: 'wipersP', label: '' },
  { field: 'wipersA', label: 'Respond to defect' },
  { field: 'wipersF', label: '' },
  { field: 'washerSystem', label: '36. ระบบฉีดน้ำล้างกระจก' },
  { field: 'washerSystemR', label: '' },
  { field: 'washerSystemP', label: '' },
  { field: 'washerSystemA', label: 'Respond to defect' },
  { field: 'washerSystemF', label: '' },
  { field: 'ignitionSwitch', label: '37. ระบบสวิทกุญแจสตาร์ท' },
  { field: 'ignitionSwitchR', label: '' },
  { field: 'ignitionSwitchP', label: '' },
  { field: 'ignitionSwitchA', label: 'Respond to defect' },
  { field: 'ignitionSwitchF', label: '' },
  {
    field: 'engine',
    label: '38. เครื่องยนต์, (เสียงเครื่องยนต์, ควันจากท่อไอเสีย ฯลฯ)',
  },
  { field: 'engineR', label: '' },
  { field: 'engineP', label: '' },
  { field: 'engineA', label: 'Respond to defect' },
  { field: 'engineF', label: '' },
  { field: 'driveShaft', label: '39. ข้อต่อเพลาส่งกำลัง' },
  { field: 'driveShaftR', label: '' },
  { field: 'driveShaftP', label: '' },
  { field: 'driveShaftA', label: 'Respond to defect' },
  { field: 'driveShaftF', label: '' },
  {
    field: 'clutchAndGear',
    label:
      '40. อุปกรณ์ระบบเกียร์และคลัทช์ , (สังเกตุจากเสียงผิดปกติเมื่อปลดหรือเข้าเกียร์)',
  },
  { field: 'clutchAndGearR', label: '' },
  { field: 'clutchAndGearP', label: '' },
  { field: 'clutchAndGearA', label: 'Respond to defect' },
  { field: 'clutchAndGearF', label: '' },
  { field: 'batteryClamp', label: '41. การยึดแบตเตอรี่' },
  { field: 'batteryClampR', label: '' },
  { field: 'batteryClampP', label: '' },
  { field: 'batteryClampA', label: 'Respond to defect' },
  { field: 'batteryClampF', label: '' },
  { field: 'batteryCondition', label: '42. สภาพแบตเตอรี่' },
  { field: 'batteryConditionR', label: '' },
  { field: 'batteryConditionP', label: '' },
  { field: 'batteryConditionA', label: 'Respond to defect' },
  { field: 'batteryConditionF', label: '' },
  { field: 'overallInspection', label: '43. การตรวจสภาพทั่วไป' },
  { field: 'overallInspectionR', label: '' },
  { field: 'overallInspectionP', label: '' },
  { field: 'overallInspectionA', label: 'Respond to defect' },
  { field: 'overallInspectionF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
