export const questions = [
  {
    id: 1,
    name: 'headlight',
    question: 'ភ្លើងកូដមិនធម្មតា',
    howto: 'បើកតេស្តស្ថានភាពភ្លើង',
    accept: 'មិនដាច់ភ្លើង និង ភ្លើងនៅភ្លឺច្បាស់',
  },
  {
    id: 2,
    name: 'doorsAccessibility',
    question: 'ទ្វាទាំងអស់មិនធម្មតា',
    howto: 'បើកតេស្តស្ថានភាពទ្វា',
    accept: 'ទ្វាបើកបានធម្មតា និងគន្លឹះដំណើរការល្អ',
  },
  {
    id: 3,
    name: 'reversing',
    question: 'សឺរ៉ែនថយក្រោយមិនធម្មតា',
    howto: 'តេស្តស្ថានភាព និងសម្លេងសឺរ៉ែន',
    accept: 'សឺរ៉ែនដំណើរការត្រឹមត្រូវ និងលឺច្បាស់',
  },
  {
    id: 4,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'តេស្តចុចស៊ីផ្លេ',
    accept: 'បញ្ជារដោយរលូន និងលឺច្បាស់',
  },
  {
    id: 5,
    name: 'wiper',
    question: 'ផ្លិតទឹកជូតកញ្ចក់មិនធម្មតា',
    howto: 'តេស្តប្រើផ្លិតទឹកជូតកញ្ចក់',
    accept: 'បញ្ជារដោយរលូន មានទឹកគ្រប់គ្រាន់ និង ជូតបានស្អាត',
  },
  {
    id: 6,
    name: 'windshield',
    question: 'កញ្ចក់មុខ,​ ក្រោយ ទ្វារ មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពជាក់ស្តែង',
    accept: 'មានគ្រប់គ្រាន់ មិនមានបែកបាក់ និងមើលឃើញច្បាស់',
  },
  {
    id: 7,
    name: 'safetyBelt',
    question: 'ខ្សែក្រវ៉ាត់សុវត្ថិភាពមិនធម្មតា',
    howto: 'តេស្តពាក់ និង ចុចគន្លឹះដំណើរការដែរទេ',
    accept: 'ពាក់ជាប់ល្អ ស្ថានភាពខ្សែក្រវ៉ាត់នៅល្អ និង គន្លឹះដំណើរការល្អ',
  },
  {
    id: 8,
    name: 'hydraulicCylinder',
    question: 'ស្ថានភាពសារាងមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងប្រេងលេចធ្លាយ',
    accept: 'ដងហាយដ្រូលិកគ្មានការច្រេះនិង មិនមានលេចធ្លាយ',
  },
  {
    id: 9,
    name: 'hydraulicHose',
    question: 'ប្រពន្ធ័ទុយោមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងប្រេងលេចធ្លាយ',
    accept: 'ដងហាយដ្រូលិកគ្មានការច្រេះនិង មិនមានលេចធ្លាយ',
  },
  {
    id: 10,
    name: 'hydraulicLevel',
    question: 'កំរិតប្រេងមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពប្រេង',
    accept: 'ប្រេងនៅគ្រប់តាមស្តង់តា និងមិនមានលេចធ្លាយ',
  },
  {
    id: 11,
    name: 'engineOil',
    question: 'កំរិតប្រេងម៉ាស៊ីនមិនធម្មតា',
    howto: 'ពិនិត្យមើលនិងភ្នែក',
    accept: 'ប្រេងនៅគ្រប់តាមស្តង់តា និងមិនមានលេចធ្លាយ',
  },
  {
    id: 12,
    name: 'windshield',
    question: 'អាគុយមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពនិងកំរិតថ្ម',
    accept: 'អាគុយស្ថានភាពល្អ គ្មានស្នាមច្រេះ ឬការច្រាលថ្ម',
  },
  {
    id: 13,
    name: 'extinguisher',
    question: 'បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'មានបំពង់ពន្លត់អគ្គីភ័យ និង នៅដំណើរការ',
    accept: 'មិនបាត់ក្រឡាស់ និង ទ្រនិចនៅចំណុចពណ៌ខៀវ',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'headlight', label: '1. ភ្លើងកូដមិនធម្មតា' },
  { field: 'headlightR', label: '' },
  { field: 'headlightP', label: '' },
  { field: 'headlightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'headlightF', label: '' },
  { field: 'doorsAccessibility', label: '2. ទ្វាទាំងអស់មិនធម្មតា' },
  { field: 'doorsAccessibilityR', label: '' },
  { field: 'doorsAccessibilityP', label: '' },
  {
    field: 'doorsAccessibilityA',
    label: 'ឆ្លើយតបដល់កំហុស - Respond to defect',
  },
  { field: 'doorsAccessibilityF', label: '' },
  { field: 'reversing', label: '3. សឺរ៉ែនថយក្រោយមិនធម្មតា' },
  { field: 'reversingR', label: '' },
  { field: 'reversingP', label: '' },
  { field: 'reversingA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'reversingF', label: '' },
  { field: 'horn', label: '4. ស៊ីផ្លេមិនធម្មតា' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'wiper', label: '5. ផ្លិតទឹកជូតកញ្ចក់មិនធម្មតា' },
  { field: 'wiperR', label: '' },
  { field: 'wiperP', label: '' },
  { field: 'wiperA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wiperF', label: '' },
  { field: 'windshield', label: '6. កញ្ចក់មុខ, ក្រោយ ទ្វារ មិនធម្មតា' },
  { field: 'windshieldR', label: '' },
  { field: 'windshieldP', label: '' },
  { field: 'windshieldA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'windshieldF', label: '' },
  { field: 'safetyBelt', label: '7. ខ្សែក្រវ៉ាត់សុវត្ថិភាពមិនធម្មតា' },
  { field: 'safetyBeltR', label: '' },
  { field: 'safetyBeltP', label: '' },
  { field: 'safetyBeltA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'safetyBeltF', label: '' },
  { field: 'hydraulicCylinder', label: '8. ស្ថានភាពសារាងមិនធម្មតា' },
  { field: 'hydraulicCylinderR', label: '' },
  { field: 'hydraulicCylinderP', label: '' },
  { field: 'hydraulicCylinderA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydraulicCylinderF', label: '' },
  { field: 'hydraulicHose', label: '9. ប្រពន្ធ័ទុយោមិនធម្មតា' },
  { field: 'hydraulicHoseR', label: '' },
  { field: 'hydraulicHoseP', label: '' },
  { field: 'hydraulicHoseA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydraulicHoseF', label: '' },
  { field: 'hydraulicLevel', label: '10. កំរិតប្រេងមិនធម្មតា' },
  { field: 'hydraulicLevelR', label: '' },
  { field: 'hydraulicLevelP', label: '' },
  { field: 'hydraulicLevelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydraulicLevelF', label: '' },
  { field: 'engineOil', label: '11. កំរិតប្រេងម៉ាស៊ីនមិនធម្មតា' },
  { field: 'engineOilR', label: '' },
  { field: 'engineOilP', label: '' },
  { field: 'engineOilA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'engineOilF', label: '' },
  { field: 'windshield', label: '12. អាគុយមិនធម្មតា' },
  { field: 'windshieldR', label: '' },
  { field: 'windshieldP', label: '' },
  { field: 'windshieldA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'windshieldF', label: '' },
  { field: 'extinguisher', label: '13. បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'remark', label: 'ចំណាំ Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
