export const questions = [
  {
    id: 1,
    name: 'loadChart',
    question: 'බර පටිය',
    howto:
      'බර පටිය සවි කර ඇති බව, පහසුවෙන් කියවිය හැකි බව, සහ තොරතුරු නිවැරදි බව පරීක්ෂා කරන්න.',
    accept: 'බර පටිය නිවැරදිව සවි කර ඇති අතර තොරතුරු නිවැරදි වේ.',
  },
  {
    id: 2,
    name: 'forksAccessories',
    question: 'පොරෝන සහ උපාංග',
    howto: 'පොරෝන සහ උපාංග කිසිදු හානියකින් තොර බව පරීක්ෂා කරන්න.',
    accept: 'පොරෝන සහ උපාංග කිසිදු හානියකින් තොර වේ.',
  },
  {
    id: 3,
    name: 'tiresBelts',
    question: 'ටයර් සහ බෙල්ට්',
    howto: 'ටයර්, බෙල්ට් සහ වාහනයේ යට ඇති ඩිලික්ස් පරීක්ෂා කරන්න.',
    accept: 'ටයර් සහ බෙල්ට් කිසිදු ඩිලික්ස් හෝ හානියකින් තොර වේ.',
  },
  {
    id: 4,
    name: 'mastHydraulic',
    question: 'ස්ථාවරය සහ හයිඩ්රෝලික් අංශ',
    howto:
      'ස්ථාවරය සහ හයිඩ්රෝලික් අංශ පරීක්ෂා කරන්න, ඩිලික්ස් කිසිදු ලක්ෂණ සොයා ගැනීම සඳහා.',
    accept: 'ස්ථාවරය සහ හයිඩ්රෝලික් අංශ කිසිදු ඩිලික්ස් ලක්ෂණ නොමැත.',
  },
  {
    id: 5,
    name: 'battery',
    question: 'බැටරි',
    howto: 'බැටරි පරීක්ෂා කරන්න.',
    accept: 'බැටරි සාමාන්‍ය ක්‍රියාවලියෙන් පවතී.',
  },
  {
    id: 6,
    name: 'gasConnections',
    question: 'ගෑස් සහ සම්බන්ධතා',
    howto: 'ගෑස් සහ/හෝ බැටරි, නල, මානක, යොදා ගැනීමේ ස්ථාන පරීක්ෂා කරන්න.',
    accept: 'ගෑස් සහ සම්බන්ධතා දැඩිව පවතී, කිසිදු ඩිලික්ස් නැත.',
  },
  {
    id: 7,
    name: 'seatBelts',
    question: 'ආසන සහ ආරක්ෂිත බෙල්ට්',
    howto: 'ආසන සහ ආරක්ෂිත බෙල්ට් වල තත්ත්වය සහ සකසිය හැකි බව පරීක්ෂා කරන්න.',
    accept: 'ආසන සහ ආරක්ෂිත බෙල්ට් හොඳ තත්ත්වයෙන් පවතී සහ සකසිය හැකි වේ.',
  },
  {
    id: 8,
    name: 'pedalsControls',
    question: 'පෙඩල් සහ පාලක',
    howto: 'ආරම්භ කිරීමෙන් පසු, සියලු පෙඩල් සහ පාලක පැටවීම පරීක්ෂා කරන්න.',
    accept: 'පෙඩල් සහ පාලක පහසුවෙන් පැටවී ඇත.',
  },
  {
    id: 9,
    name: 'brakes',
    question: 'පැඩල් සහ අත් පැඩල්',
    howto: 'පැඩල් සහ අත් පැඩල් සාමාන්‍ය ලෙස ක්‍රියා කරන බව පරීක්ෂා කරන්න.',
    accept: 'පැඩල් සහ අත් පැඩල් සාමාන්‍ය ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 10,
    name: 'lightsHorn',
    question: 'අලෝක සහ හෝන්',
    howto: 'අලෝක, අනතුරු අලෝක, හෝන් සහ පිටවීමේ හෝන් පරීක්ෂා කරන්න.',
    accept: 'අලෝක සහ හෝන් සාමාන්‍ය ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 11,
    name: 'damageDefects',
    question: 'හානිය හෝ දෝෂ',
    howto: 'සැකසීමට හානිය හෝ දෝෂ සොයා ගැනීමට පරීක්ෂා කරන්න.',
    accept: 'කිසිදු හානිය හෝ දෝෂ නොමැත.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'දිනය Date' },
  { field: 'email', label: 'වගකීම භාරකරු Responsible person' },
  { field: 'inspector', label: 'පරීක්ෂක / Inspector' },
  { field: 'responder', label: 'ප්‍රතිචාරකයා Responder' },
  { field: 'loadChart', label: '1. බර පටිය *' },
  { field: 'loadChartR', label: '' },
  { field: 'loadChartP', label: '' },
  { field: 'loadChartA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'loadChartF', label: '' },
  { field: 'forksAccessories', label: '2. පොරෝන සහ උපාංග *' },
  { field: 'forksAccessoriesR', label: '' },
  { field: 'forksAccessoriesP', label: '' },
  {
    field: 'forksAccessoriesA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'forksAccessoriesF', label: '' },
  { field: 'tiresBelts', label: '3. ටයර් සහ බෙල්ට් *' },
  { field: 'tiresBeltsR', label: '' },
  { field: 'tiresBeltsP', label: '' },
  { field: 'tiresBeltsA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'tiresBeltsF', label: '' },
  { field: 'mastHydraulic', label: '4. ස්ථාවරය සහ හයිඩ්රෝලික් අංශ *' },
  { field: 'mastHydraulicR', label: '' },
  { field: 'mastHydraulicP', label: '' },
  {
    field: 'mastHydraulicA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'mastHydraulicF', label: '' },
  { field: 'battery', label: '5. බැටරි *' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'gasConnections', label: '6. ගෑස් සහ සම්බන්ධතා *' },
  { field: 'gasConnectionsR', label: '' },
  { field: 'gasConnectionsP', label: '' },
  {
    field: 'gasConnectionsA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'gasConnectionsF', label: '' },
  { field: 'seatBelts', label: '7. ආසන සහ ආරක්ෂිත බෙල්ට් *' },
  { field: 'seatBeltsR', label: '' },
  { field: 'seatBeltsP', label: '' },
  { field: 'seatBeltsA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'seatBeltsF', label: '' },
  { field: 'pedalsControls', label: '8. පෙඩල් සහ පාලක *' },
  { field: 'pedalsControlsR', label: '' },
  { field: 'pedalsControlsP', label: '' },
  {
    field: 'pedalsControlsA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'pedalsControlsF', label: '' },
  { field: 'brakes', label: '9. පැඩල් සහ අත් පැඩල් *' },
  { field: 'brakesR', label: '' },
  { field: 'brakesP', label: '' },
  { field: 'brakesA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'brakesF', label: '' },
  { field: 'lightsHorn', label: '10. අලෝක සහ හෝන් *' },
  { field: 'lightsHornR', label: '' },
  { field: 'lightsHornP', label: '' },
  { field: 'lightsHornA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'lightsHornF', label: '' },
  { field: 'damageDefects', label: '11. හානිය හෝ දෝෂ *' },
  { field: 'damageDefectsR', label: '' },
  { field: 'damageDefectsP', label: '' },
  {
    field: 'damageDefectsA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'damageDefectsF', label: '' },
  { field: 'remark', label: 'සටහන Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
