export const questions = [
  {
    id: 1,
    name: 'wheel',
    question: 'កង់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និង មើលស្ថានភាពកង់',
    accept: 'សំបកកង់ល្អ ក្រឡានៅស្អាត និង ប៊ូឡុងខ្ចៅតឹងណែនល្អ',
  },
  {
    id: 2,
    name: 'hydralic',
    question: 'ដងហាយដ្រូលិកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការលេចធ្លាយ',
    accept: 'ដងហាយដ្រូលិកគ្មានការច្រេះ ឬការលេចធ្លាយប្រេង',
  },
  {
    id: 3,
    name: 'shovel',
    question: 'ប៉ែលចូកមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការដំណើរការ',
    accept: 'ប៉ែលស្ថានភាពល្អ និងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 4,
    name: 'seat',
    question: 'កៅអី,​ ខ្សែក្រវាត់មិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាពកៅអី និងការដាក់ខ្សែក្រវ៉ាត់',
    accept: 'កៅអីស្ថានភាពល្អ និងខ្សែក្រវ៉ាត់ដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 5,
    name: 'mirror',
    question: 'កញ្ចក់មើលក្រោយមិនធម្មតា',
    howto: 'ពិនិត្យសភាពកញ្ចក់ និងភាពច្បាស់',
    accept: 'កញ្ចក់ស្ថានភាពល្អ គ្មានការបាក់ ឬស្នាមប៉ះ',
  },
  {
    id: 6,
    name: 'handBrake',
    question: 'ហ្រ្វាងដៃ, ជើងមិនធម្មតា',
    howto: 'តេស្តេជាន់ហ្រ្វាំងមុនបើកបរ',
    accept: 'ហ្រ្វាំងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 7,
    name: 'steer',
    question: 'ចង្កូតមិនធម្មតា',
    howto: 'តេស្តបួងចង្កូតឆ្វេង-ស្តាំ២ជុំ',
    accept: 'ចង្កូតដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 8,
    name: 'accelerator',
    question: 'ហ្គ៊ែរមិនធម្មតា',
    howto: 'តេស្តលើការប្រើប្រាស់ហ្គែរជើង',
    accept: 'ហ្គែរដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 9,
    name: 'light',
    question: 'អំពូលភ្លើងទាំងអស់មិនធម្មតា',
    howto: 'ពិនិត្យការដំណើរការរបស់អំពូលភ្លើង',
    accept: 'អំពូលភ្លើងដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 10,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'តេស្តសំលេងស៊ីផ្លេ',
    accept: 'ស៊ីផ្លេដំណើរការរលូន​​​ និងលឺច្បាស់',
  },
  {
    id: 11,
    name: 'reversing',
    question: 'សឺរ៉ែនថយក្រោយមិនធម្មតា',
    howto: 'តេស្តស្ថានភាព និងសំលេងសឺរ៉ែន',
    accept: 'សឺរ៉ែនដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 12,
    name: 'extinguisher',
    question: 'បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'មានបំពង់ពន្លត់អគ្គីភ័យ និងនៅដំណើរការ',
    accept: 'មិនបាត់ក្រឡាស់ និង ទ្រនិចនៅចំណុចពណ៌ខៀវ',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'wheel', label: '1. កង់មិនធម្មតា' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'hydralic', label: '2. ដងហាយដ្រូលិកមិនធម្មតា' },
  { field: 'hydralicR', label: '' },
  { field: 'hydralicP', label: '' },
  { field: 'hydralicA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hydralicF', label: '' },
  { field: 'shovel', label: '3. ប៉ែលចូកមិនធម្មតា' },
  { field: 'shovelR', label: '' },
  { field: 'shovelP', label: '' },
  { field: 'shovelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'shovelF', label: '' },
  { field: 'seat', label: '4. កៅអី,​ ខ្សែក្រវាត់មិនធម្មតា' },
  { field: 'seatR', label: '' },
  { field: 'seatP', label: '' },
  { field: 'seatA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'seatF', label: '' },
  { field: 'mirror', label: '5. កញ្ចក់មើលក្រោយមិនធម្មតា' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'handBrake', label: '6. ហ្រ្វាងដៃ, ជើងមិនធម្មតា' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'steer', label: '7. ចង្កូតមិនធម្មតា' },
  { field: 'steerR', label: '' },
  { field: 'steerP', label: '' },
  { field: 'steerA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'steerF', label: '' },
  { field: 'accelerator', label: '8. ហ្គ៊ែរមិនធម្មតា' },
  { field: 'acceleratorR', label: '' },
  { field: 'acceleratorP', label: '' },
  { field: 'acceleratorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'acceleratorF', label: '' },
  { field: 'light', label: '9. អំពូលភ្លើងទាំងអស់មិនធម្មតា' },
  { field: 'lightR', label: '' },
  { field: 'lightP', label: '' },
  { field: 'lightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'lightF', label: '' },
  { field: 'horn', label: '10. ស៊ីផ្លេមិនធម្មតា' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'reversing', label: '11. សឺរ៉ែនថយក្រោយមិនធម្មតា' },
  { field: 'reversingR', label: '' },
  { field: 'reversingP', label: '' },
  { field: 'reversingA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'reversingF', label: '' },
  { field: 'extinguisher', label: '12. បំពង់ពន្លត់អគ្គីភ័យមិនធម្មតា' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'remark', label: 'ាម់មុទរនានីអាវា - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
