export const questions = [
  {
    id: 1,
    name: 'steering',
    question: 'พวงมาลัย *',
    howto: 'หมุนซ้าย/ขวา',
    accept: 'ไม่สั่นคลอน หมุนซ้าย-ขวา บังคับล้อได้ปกติ',
  },
  {
    id: 2,
    name: 'horn',
    question: 'แตร*',
    howto: 'กดแตร',
    accept: 'เสียงดังชัดเจน ไม่ใช้แตรลม',
  },
  {
    id: 3,
    name: 'gear',
    question: 'เกียร์*',
    howto: 'เหยีบคลัท และเปลี่ยนเกียร์',
    accept: 'เข้าเกียร์ได้ไม่ติดขัด',
  },
  {
    id: 4,
    name: 'footBrake',
    question: 'เบรคเท้า**',
    howto: 'สัมผัส / สายตา',
    accept: 'หยุดนิ่ง รถไม่ไหล ไฟติดพร้อมกับเบรกเท้า',
  },
  {
    id: 5,
    name: 'handBrake',
    question: 'เบรคมือ*',
    howto: 'ดึงเบรคมือ ค่อยๆเดินรถไปข้างหน้า',
    accept: 'รถไม่เคลื่นตัว',
  },
  {
    id: 6,
    name: 'belt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา / สัมผัส',
    accept: 'กระชับ ปรับได้ ล็อคและปลดล็อคได้',
  },
  {
    id: 7,
    name: 'door',
    question: 'ประตู',
    howto: 'สายตา / สัมผัส',
    accept: 'เปิด ปิด ล็อคได้ ไม่ชำรุด กระจกเลื่อนขึ้นลงได้',
  },
  {
    id: 8.1,
    name: 'mirrorL',
    question: 'กระจกซ้าย',
    howto: 'สายตา',
    accept: 'สะอาดใส ไม่แตก ไม่ชำรุด ปรับตำแหน่งได้',
  },
  {
    id: 8.2,
    name: 'mirrorR',
    question: 'กระจกขวา',
    howto: 'สายตา',
    accept: 'สะอาดใส ไม่แตก ไม่ชำรุด ปรับตำแหน่งได้',
  },
  {
    id: 9.1,
    name: 'lampL',
    question: 'ไฟหน้าซ้าย**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 9.2,
    name: 'lampR',
    question: 'ไฟหน้าขวา**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 10.1,
    name: 'turnLightL',
    question: 'ไฟเลี้ยวซ้าย**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจน กระพริบเป็นจังหวะทุกดวง',
  },
  {
    id: 10.1,
    name: 'turnLightR',
    question: 'ไฟเลี้ยวขวา**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจน กระพริบเป็นจังหวะทุกดวง',
  },
  {
    id: 11,
    name: 'nut',
    question: 'น๊อตล้อ**',
    howto: 'สายตา / สัมผัส',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 12.1,
    name: 'frontWheelL',
    question: 'ล้อหน้า **ซ้าย',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 12.2,
    name: 'frontWheelR',
    question: 'ล้อหน้า **ขวา',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 13,
    name: 'lub',
    question: 'น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 14,
    name: 'brakeOil',
    question: 'น้ำมันเบรคเพียงพอ/ไม่รั่วซึม',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 15,
    name: 'backSound',
    question: 'สัญญาณเสียงถอย',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 16,
    name: 'backLight',
    question: 'สัญญาณไฟถอย',
    howto: 'ฟังเสียง / สายตา',
    accept: 'เสียงเตือนดังและไฟติด',
  },
  {
    id: 17.1,
    name: 'rearLampL',
    question: 'ไฟท้าย **ซ้าย',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 17.2,
    name: 'rearLampR',
    question: 'ไฟท้าย **ขวา',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 18.1,
    name: 'rearWheelL',
    question: 'ล้อหลัง **ซ้าย',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 18.2,
    name: 'rearWheelR',
    question: 'ล้อหลัง **ขวา',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 19,
    name: 'extinguisher',
    question: 'ถังดับเพลิง',
    howto: 'สายตา / สัมผัส',
    accept: 'เกจชี้ในช่องสีเขียว มีเข็มขัดรัดสลัก พร้อมใช้',
  },
  {
    id: 20,
    name: 'pvcChuteD',
    question: 'ราง PVC',
    howto: 'สายตา',
    accept: 'ไม่มีเศษคอนกรีตแห้งติดสะสม',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'type', label: 'ประเภทการตรวจ' },
  { field: 'responder', label: 'Responder' },
  { field: 'steering', label: '1.พวงมาลัย *' },
  { field: 'steeringR', label: '' },
  { field: 'steeringP', label: '' },
  { field: 'steeringA', label: 'Respond to defect' },
  { field: 'steeringF', label: '' },
  { field: 'horn', label: '2.แตร*' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'gear', label: '3.เกียร์*' },
  { field: 'gearR', label: '' },
  { field: 'gearP', label: '' },
  { field: 'gearA', label: 'Respond to defect' },
  { field: 'gearF', label: '' },
  { field: 'footBrake', label: '4.เบรคเท้า**' },
  { field: 'footBrakeR', label: '' },
  { field: 'footBrakeP', label: '' },
  { field: 'footBrakeA', label: 'Respond to defect' },
  { field: 'footBrakeF', label: '' },
  { field: 'handBrake', label: '5.เบรคมือ*' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'belt', label: '6.เข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'door', label: '7.ประตู' },
  { field: 'doorR', label: '' },
  { field: 'doorP', label: '' },
  { field: 'doorA', label: 'Respond to defect' },
  { field: 'doorF', label: '' },
  { field: 'mirrorL', label: '8.1 กระจกซ้าย' },
  { field: 'mirrorLR', label: '' },
  { field: 'mirrorLP', label: '' },
  { field: 'mirrorLA', label: 'Respond to defect' },
  { field: 'mirrorLF', label: '' },
  { field: 'mirrorR', label: '8.2 กระจกขวา' },
  { field: 'mirrorRR', label: '' },
  { field: 'mirrorRP', label: '' },
  { field: 'mirrorRA', label: 'Respond to defect' },
  { field: 'mirrorRF', label: '' },
  { field: 'lampL', label: '9.1 ไฟหน้าซ้าย**' },
  { field: 'lampLR', label: '' },
  { field: 'lampLP', label: '' },
  { field: 'lampLA', label: 'Respond to defect' },
  { field: 'lampLF', label: '' },
  { field: 'lampR', label: '9.2 ไฟหน้าขวา**' },
  { field: 'lampRR', label: '' },
  { field: 'lampRP', label: '' },
  { field: 'lampRA', label: 'Respond to defect' },
  { field: 'lampRF', label: '' },
  { field: 'turnLightL', label: '10.1 ไฟเลี้ยวซ้าย**' },
  { field: 'turnLightLR', label: '' },
  { field: 'turnLightLP', label: '' },
  { field: 'turnLightLA', label: 'Respond to defect' },
  { field: 'turnLightLF', label: '' },
  { field: 'turnLightR', label: '10.2 ไฟเลี้ยวขวา**' },
  { field: 'turnLightRR', label: '' },
  { field: 'turnLightRP', label: '' },
  { field: 'turnLightRA', label: 'Respond to defect' },
  { field: 'turnLightRF', label: '' },
  { field: 'nut', label: '11.น๊อตล้อ**' },
  { field: 'nutR', label: '' },
  { field: 'nutP', label: '' },
  { field: 'nutA', label: 'Respond to defect' },
  { field: 'nutF', label: '' },
  { field: 'frontWheelL', label: '12.1 ล้อหน้า **ซ้าย' },
  { field: 'frontWheelLR', label: '' },
  { field: 'frontWheelLP', label: '' },
  { field: 'frontWheelLA', label: 'Respond to defect' },
  { field: 'frontWheelLF', label: '' },
  { field: 'frontWheelR', label: '12.2 ล้อหน้า **ขวา' },
  { field: 'frontWheelRR', label: '' },
  { field: 'frontWheelRP', label: '' },
  { field: 'frontWheelRA', label: 'Respond to defect' },
  { field: 'frontWheelRF', label: '' },
  { field: 'lub', label: '13.น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม' },
  { field: 'lubR', label: '' },
  { field: 'lubP', label: '' },
  { field: 'lubA', label: 'Respond to defect' },
  { field: 'lubF', label: '' },
  { field: 'brakeOil', label: '14.น้ำมันเบรคเพียงพอ/ไม่รั่วซึม' },
  { field: 'brakeOilR', label: '' },
  { field: 'brakeOilP', label: '' },
  { field: 'brakeOilA', label: 'Respond to defect' },
  { field: 'brakeOilF', label: '' },
  { field: 'backSound', label: '15.สัญญาณเสียงถอย' },
  { field: 'backSoundR', label: '' },
  { field: 'backSoundP', label: '' },
  { field: 'backSoundA', label: 'Respond to defect' },
  { field: 'backSoundF', label: '' },
  { field: 'backLight', label: '16.สัญญาณไฟถอย' },
  { field: 'backLightR', label: '' },
  { field: 'backLightP', label: '' },
  { field: 'backLightA', label: 'Respond to defect' },
  { field: 'backLightF', label: '' },
  { field: 'rearLampL', label: '17.1 ไฟท้าย **ซ้าย' },
  { field: 'rearLampLR', label: '' },
  { field: 'rearLampLP', label: '' },
  { field: 'rearLampLA', label: 'Respond to defect' },
  { field: 'rearLampLF', label: '' },
  { field: 'rearLampR', label: '17.2 ไฟท้าย **ขวา' },
  { field: 'rearLampRR', label: '' },
  { field: 'rearLampRP', label: '' },
  { field: 'rearLampRA', label: 'Respond to defect' },
  { field: 'rearLampRF', label: '' },
  { field: 'rearWheelL', label: '18.1 ล้อหลัง **ซ้าย' },
  { field: 'rearWheelLR', label: '' },
  { field: 'rearWheelLP', label: '' },
  { field: 'rearWheelLA', label: 'Respond to defect' },
  { field: 'rearWheelLF', label: '' },
  { field: 'rearWheelR', label: '18.2 ล้อหลัง **ขวา' },
  { field: 'rearWheelRR', label: '' },
  { field: 'rearWheelRP', label: '' },
  { field: 'rearWheelRA', label: 'Respond to defect' },
  { field: 'rearWheelRF', label: '' },
  { field: 'extinguisher', label: '19.ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'pvcChuteD', label: '20.ราง PVC' },
  { field: 'pvcChuteDR', label: '' },
  { field: 'pvcChuteDP', label: '' },
  { field: 'pvcChuteDA', label: 'Respond to defect' },
  { field: 'pvcChuteDF', label: '' },
  //weekly
  { field: 'wiper', label: '1.ใบปัดน้ำฝน' },
  { field: 'wiperR', label: '' },
  { field: 'wiperP', label: '' },
  { field: 'wiperA', label: 'Respond to defect' },
  { field: 'wiperF', label: '' },
  { field: 'cone', label: '2.กรวยจราจร' },
  { field: 'coneR', label: '' },
  { field: 'coneP', label: '' },
  { field: 'coneA', label: 'Respond to defect' },
  { field: 'coneF', label: '' },
  { field: 'sideGuardL', label: '3.1 การ์ดด้านข้างซ้าย' },
  { field: 'sideGuardLR', label: '' },
  { field: 'sideGuardLP', label: '' },
  { field: 'sideGuardLA', label: 'Respond to defect' },
  { field: 'sideGuardLF', label: '' },
  { field: 'sideGuardR', label: '3.2 การ์ดด้านข้างขวา' },
  { field: 'sideGuardRR', label: '' },
  { field: 'sideGuardRP', label: '' },
  { field: 'sideGuardRA', label: 'Respond to defect' },
  { field: 'sideGuardRF', label: '' },
  { field: 'waterReverse', label: '4.ถังน้ำสำรอง' },
  { field: 'waterReverseR', label: '' },
  { field: 'waterReverseP', label: '' },
  { field: 'waterReverseA', label: 'Respond to defect' },
  { field: 'waterReverseF', label: '' },
  { field: 'drum', label: '5.สภาพโม่' },
  { field: 'drumR', label: '' },
  { field: 'drumP', label: '' },
  { field: 'drumA', label: 'Respond to defect' },
  { field: 'drumF', label: '' },
  { field: 'hydrolic', label: '6.ปั๊มขับโม่' },
  { field: 'hydrolicR', label: '' },
  { field: 'hydrolicP', label: '' },
  { field: 'hydrolicA', label: 'Respond to defect' },
  { field: 'hydrolicF', label: '' },
  { field: 'guardShaft', label: '7.ฝาครอบเพลา' },
  { field: 'guardShaftR', label: '' },
  { field: 'guardShaftP', label: '' },
  { field: 'guardShaftA', label: 'Respond to defect' },
  { field: 'guardShaftF', label: '' },
  { field: 'valve', label: '8.วาล์วน้ำไม่รั่วซึม' },
  { field: 'valveR', label: '' },
  { field: 'valveP', label: '' },
  { field: 'valveA', label: 'Respond to defect' },
  { field: 'valveF', label: '' },
  { field: 'blade', label: '9.1 ใบกวนไม่ล้ม' },
  { field: 'bladeR', label: '' },
  { field: 'bladeP', label: '' },
  { field: 'bladeA', label: 'Respond to defect' },
  { field: 'bladeF', label: '' },
  { field: 'bladeTear', label: '9.2 ใบกวนไม่มีรอยฉีกขาด' },
  { field: 'bladeTearR', label: '' },
  { field: 'bladeTearP', label: '' },
  { field: 'bladeTearA', label: 'Respond to defect' },
  { field: 'bladeTearF', label: '' },
  { field: 'ladder', label: '10.บันได' },
  { field: 'ladderR', label: '' },
  { field: 'ladderP', label: '' },
  { field: 'ladderA', label: 'Respond to defect' },
  { field: 'ladderF', label: '' },
  { field: 'chain', label: '11.ราว/โซ่กันตก' },
  { field: 'chainR', label: '' },
  { field: 'chainP', label: '' },
  { field: 'chainA', label: 'Respond to defect' },
  { field: 'chainF', label: '' },
  { field: 'chute2', label: '12.ราง2 ล็อคแน่น' },
  { field: 'chute2R', label: '' },
  { field: 'chute2P', label: '' },
  { field: 'chute2A', label: 'Respond to defect' },
  { field: 'chute2F', label: '' },
  { field: 'chute3', label: '13.ราง3 ล็อคแน่น' },
  { field: 'chute3R', label: '' },
  { field: 'chute3P', label: '' },
  { field: 'chute3A', label: 'Respond to defect' },
  { field: 'chute3F', label: '' },
  { field: 'pvcChuteW', label: '14.ราง PVC' },
  { field: 'pvcChuteWR', label: '' },
  { field: 'pvcChuteWP', label: '' },
  { field: 'pvcChuteWA', label: 'Respond to defect' },
  { field: 'pvcChuteWF', label: '' },
  { field: 'atena', label: '15.เสาวัดความสูง' },
  { field: 'atenaR', label: '' },
  { field: 'atenaP', label: '' },
  { field: 'atenaA', label: 'Respond to defect' },
  { field: 'atenaF', label: '' },
  { field: 'chuteHandle', label: '16.โกร่ง-หูจับราง' },
  { field: 'chuteHandleR', label: '' },
  { field: 'chuteHandleP', label: '' },
  { field: 'chuteHandleA', label: 'Respond to defect' },
  { field: 'chuteHandleF', label: '' },
  //Driver trainer
  { field: 'gps', label: '1. ระบบ GPS ใช้งานได้ปกติ' },
  { field: 'gpsR', label: '' },
  { field: 'gpsP', label: '' },
  { field: 'gpsA', label: 'Respond to defect' },
  { field: 'gpsF', label: '' },
  {
    field: 'cameraMount',
    label: '2. ขาตั้งจุดยึด จอแสดงภาพและกล้องมองหน้าใช้งานได้ปกติ',
  },
  { field: 'cameraMountR', label: '' },
  { field: 'cameraMountP', label: '' },
  { field: 'cameraMountA', label: 'Respond to defect' },
  { field: 'cameraMountF', label: '' },
  { field: 'diffLock', label: '3. สวิทย์ดิ๊ฟล๊อค(DL)สภาพพร้อมใช้งาน' },
  { field: 'diffLockR', label: '' },
  { field: 'diffLockP', label: '' },
  { field: 'diffLockA', label: 'Respond to defect' },
  { field: 'diffLockF', label: '' },
  { field: 'roofLights', label: '4. ไฟหลังคาสีเขียว 4 ดวง' },
  { field: 'roofLightsR', label: '' },
  { field: 'roofLightsP', label: '' },
  { field: 'roofLightsA', label: 'Respond to defect' },
  { field: 'roofLightsF', label: '' },
  { field: 'wheelNuts', label: '5. น็อตล้อรถหน้าและล้อหลังครบทุกล้อ' },
  { field: 'wheelNutsR', label: '' },
  { field: 'wheelNutsP', label: '' },
  { field: 'wheelNutsA', label: 'Respond to defect' },
  { field: 'wheelNutsF', label: '' },
  {
    field: 'fireExtinguisher',
    label:
      '6. ถังดับเพลิงขนาด 15 ปอนด์ 1 ลูก และกรวยยางสะท้อนแสง จำนวน 2 อัน,ไม้หมอนหนุนล้อรถ จำนวน 2 อัน',
  },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  {
    field: 'reflectiveTape',
    label: '7. แถบสะท้อนแสงรอบรถตามมาตราฐานและเสาวัดความสูงขนาดกับกรวยท้ายโม่',
  },
  { field: 'reflectiveTapeR', label: '' },
  { field: 'reflectiveTapeP', label: '' },
  { field: 'reflectiveTapeA', label: 'Respond to defect' },
  { field: 'reflectiveTapeF', label: '' },
  { field: 'seatBelt', label: '8. เข็มขัดนิรภัยสภาพพร้อมใช้งาน' },
  { field: 'seatBeltR', label: '' },
  { field: 'seatBeltP', label: '' },
  { field: 'seatBeltA', label: 'Respond to defect' },
  { field: 'seatBeltF', label: '' },
  { field: 'tachometer', label: '9. ไมล์วัดรอบเครื่อง' },
  { field: 'tachometerR', label: '' },
  { field: 'tachometerP', label: '' },
  { field: 'tachometerA', label: 'Respond to defect' },
  { field: 'tachometerF', label: '' },
  { field: 'wipers', label: '10. ปัดน้ำฝน+พร้อมน้ำฉีดล้างกระจก' },
  { field: 'wipersR', label: '' },
  { field: 'wipersP', label: '' },
  { field: 'wipersA', label: 'Respond to defect' },
  { field: 'wipersF', label: '' },
  {
    field: 'steps',
    label:
      '11. บันใดหน้าขึ้น-ลงซ้าย-ขวา บันใดท้ายโม่ด้านขวาพร้อมคอกและอุปกรณ์กันตก',
  },
  { field: 'stepsR', label: '' },
  { field: 'stepsP', label: '' },
  { field: 'stepsA', label: 'Respond to defect' },
  { field: 'stepsF', label: '' },
  { field: 'licensePlate', label: '12. ป้ายทะเบียนหน้ารถ/หลังรถ สภาพพร้อมใช้' },
  { field: 'licensePlateR', label: '' },
  { field: 'licensePlateP', label: '' },
  { field: 'licensePlateA', label: 'Respond to defect' },
  { field: 'licensePlateF', label: '' },
  { field: 'battery', label: '13. ชุดแบตเตอร์รี่สภาพสมบูรณ์ได้มาตราฐาน' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  {
    field: 'brakeLights',
    label:
      '14. สัญญานไฟเบรคหลังซ้าย-ขวา , สัญญานไฟถอยพร้อมเสียง , สัญญานไฟส่องป้าย',
  },
  { field: 'brakeLightsR', label: '' },
  { field: 'brakeLightsP', label: '' },
  { field: 'brakeLightsA', label: 'Respond to defect' },
  { field: 'brakeLightsF', label: '' },
  {
    field: 'lockSystem',
    label: '15. โกร่ง-หูจับราง/รางท้ายโม่/ราง3/รางPVC 4 เมตร พร้อมระบบล็อค',
  },
  { field: 'lockSystemR', label: '' },
  { field: 'lockSystemP', label: '' },
  { field: 'lockSystemA', label: 'Respond to defect' },
  { field: 'lockSystemF', label: '' },
  {
    field: 'rollerCovers',
    label: '16. ฝาคลอบโลเลอร์รับโม่ซ้าย-ขวา , ฝาคลอบเพลาปั่นโม่',
  },
  { field: 'rollerCoversR', label: '' },
  { field: 'rollerCoversP', label: '' },
  { field: 'rollerCoversA', label: 'Respond to defect' },
  { field: 'rollerCoversF', label: '' },
  {
    field: 'mudFlaps',
    label: '17. ยางกันฝุ่นหลังซ้าย-ขวา สูงกว่าพื้นระหว่าง 20-30 เซนติดเมตร',
  },
  { field: 'mudFlapsR', label: '' },
  { field: 'mudFlapsP', label: '' },
  { field: 'mudFlapsA', label: 'Respond to defect' },
  { field: 'mudFlapsF', label: '' },
  { field: 'handBrake', label: '18. เบรกมือ' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'insurance', label: '19. ประกันภัย/พรบ./ป้ายวงกลม' },
  { field: 'insuranceR', label: '' },
  { field: 'insuranceP', label: '' },
  { field: 'insuranceA', label: 'Respond to defect' },
  { field: 'insuranceF', label: '' },
  {
    field: 'windows',
    label: '20. กระจกบังลมหน้า กระจกประตูซ้าย-ขวา กระจกมองข้างและกระจกมองกันชน',
  },
  { field: 'windowsR', label: '' },
  { field: 'windowsP', label: '' },
  { field: 'windowsA', label: 'Respond to defect' },
  { field: 'windowsF', label: '' },
  { field: 'headlights', label: '21. ไฟแสงสว่างหน้ารถซ้าย-ขวา' },
  { field: 'headlightsR', label: '' },
  { field: 'headlightsP', label: '' },
  { field: 'headlightsA', label: 'Respond to defect' },
  { field: 'headlightsF', label: '' },
  {
    field: 'turnSignals',
    label: '22. สัญญาณไฟเลี้ยว-ไฟหรี่หน้าหลังซ้าย-ขวา และไฟฉุกเฉิน',
  },
  { field: 'turnSignalsR', label: '' },
  { field: 'turnSignalsP', label: '' },
  { field: 'turnSignalsA', label: 'Respond to defect' },
  { field: 'turnSignalsF', label: '' },
  {
    field: 'brakeSystem',
    label:
      '23. ตรวจสอบระบบเบรกหลักและระบบลมทีใช้ในการเบรกต้องลดไม่เกิน 2 ปอนด์',
  },
  { field: 'brakeSystemR', label: '' },
  { field: 'brakeSystemP', label: '' },
  { field: 'brakeSystemA', label: 'Respond to defect' },
  { field: 'brakeSystemF', label: '' },
  { field: 'airDrain', label: '24. ระบบระบายน้ำในถังลมต้องพร้อมใช้งาน' },
  { field: 'airDrainR', label: '' },
  { field: 'airDrainP', label: '' },
  { field: 'airDrainA', label: 'Respond to defect' },
  { field: 'airDrainF', label: '' },
  {
    field: 'lowPressureWarning',
    label: '25. ระบบเบรกเมื่อแรงดันลมต่ำต้องมีสัญญาญเสียงหรือสัญลักษณ์ไฟเตือน',
  },
  { field: 'lowPressureWarningR', label: '' },
  { field: 'lowPressureWarningP', label: '' },
  { field: 'lowPressureWarningA', label: 'Respond to defect' },
  { field: 'lowPressureWarningF', label: '' },
  {
    field: 'motorcycleGuard',
    label: '26. โครงเซฟการ์ดกันมอเตอร์ไซด์ , ห่วงคล้องเพลากลาง',
  },
  { field: 'motorcycleGuardR', label: '' },
  { field: 'motorcycleGuardP', label: '' },
  { field: 'motorcycleGuardA', label: 'Respond to defect' },
  { field: 'motorcycleGuardF', label: '' },
  { field: 'ppe', label: '27. อุปกรณ์ PPE ของพนักงานจัดส่ง' },
  { field: 'ppeR', label: '' },
  { field: 'ppeP', label: '' },
  { field: 'ppeA', label: 'Respond to defect' },
  { field: 'ppeF', label: '' },
  {
    field: 'frontTires',
    label:
      '28. ยางคู่หน้าดอกสร้อยไม่หล่อดอก ยางชุดหลังสภาพพร้อมใช้งาน ดอกยางต้องเหลือไม่น้อยกว่า 2 มม.',
  },
  { field: 'frontTiresR', label: '' },
  { field: 'frontTiresP', label: '' },
  { field: 'frontTiresA', label: 'Respond to defect' },
  { field: 'frontTiresF', label: '' },
  {
    field: 'frontNumber',
    label:
      '29. ติดหมายเลขหน้าสีน้ำเงินซ้าย-ขวา ขนาด หนา 2 ซม.* สูง 12.5 ซม.* กว้าง 10 ซม.',
  },
  { field: 'frontNumberR', label: '' },
  { field: 'frontNumberP', label: '' },
  { field: 'frontNumberA', label: 'Respond to defect' },
  { field: 'frontNumberF', label: '' },
  {
    field: 'logo',
    label:
      '30. ติดโลโก้อินทรีคอนกรีตภาษาอังกฤษ ขนาด 23X50 ซม.พร้อมแถบสีแดง ที่ประตูหน้าซ้าย-ขวา',
  },
  { field: 'logoR', label: '' },
  { field: 'logoP', label: '' },
  { field: 'logoA', label: 'Respond to defect' },
  { field: 'logoF', label: '' },
  {
    field: 'cabinCleanliness',
    label: '31. ความสะอาดในห้องโดยสารและทัศนวิสัยในการมองเห็น',
  },
  { field: 'cabinCleanlinessR', label: '' },
  { field: 'cabinCleanlinessP', label: '' },
  { field: 'cabinCleanlinessA', label: 'Respond to defect' },
  { field: 'cabinCleanlinessF', label: '' },
  { field: 'vehicleCleanliness', label: '32. ความสะอาดรอบตัวรถโม่คอนกรีต' },
  { field: 'vehicleCleanlinessR', label: '' },
  { field: 'vehicleCleanlinessP', label: '' },
  { field: 'vehicleCleanlinessA', label: 'Respond to defect' },
  { field: 'vehicleCleanlinessF', label: '' },
  {
    field: 'mixerCondition',
    label: '33. คุณภาพตัวโม่และส่วนประกอบควบอื่นๆ อยู่ในสภาพดีพร้อมทำงาน',
  },
  { field: 'mixerConditionR', label: '' },
  { field: 'mixerConditionP', label: '' },
  { field: 'mixerConditionA', label: 'Respond to defect' },
  { field: 'mixerConditionF', label: '' },
  {
    field: 'logoAndColor',
    label: '34. โลโก้และสีรถถูกต้องตามแบบมาตรฐานที่กำหนด',
  },
  { field: 'logoAndColorR', label: '' },
  { field: 'logoAndColorP', label: '' },
  { field: 'logoAndColorA', label: 'Respond to defect' },
  { field: 'logoAndColorF', label: '' },
  {
    field: 'overallColorCondition',
    label:
      '35. สภาพสีโดยรวมทั้งคันรถ อยู่ในสภาพดีเหมาะสมในการเป็นตัวแทนภาพลักษณ์ที่ดีของแบรนด์อินทรี',
  },
  { field: 'overallColorConditionR', label: '' },
  { field: 'overallColorConditionP', label: '' },
  { field: 'overallColorConditionA', label: 'Respond to defect' },
  { field: 'overallColorConditionF', label: '' },

  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
