export const questions = [
  {
    id: 1,
    name: 'steering',
    question: 'พวงมาลัย *',
    howto: 'หมุนซ้าย/ขวา',
    accept: 'ไม่สั่นคลอน หมุนซ้าย-ขวา บังคับล้อได้ปกติ',
  },
  {
    id: 2,
    name: 'horn',
    question: 'แตร*',
    howto: 'กดแตร',
    accept: 'เสียงดังชัดเจน ไม่ใช้แตรลม',
  },
  {
    id: 3,
    name: 'gear',
    question: 'เกียร์*',
    howto: 'เหยีบคลัท และเปลี่ยนเกียร์',
    accept: 'เข้าเกียร์ได้ไม่ติดขัด',
  },
  {
    id: 4,
    name: 'footBrake',
    question: 'เบรคเท้า**',
    howto: 'สัมผัส / สายตา',
    accept: 'หยุดนิ่ง รถไม่ไหล ไฟติดพร้อมกับเบรกเท้า',
  },
  {
    id: 5,
    name: 'handBrake',
    question: 'เบรคมือ*',
    howto: 'ดึงเบรคมือ ค่อยๆเดินรถไปข้างหน้า',
    accept: 'รถไม่เคลื่นตัว',
  },
  {
    id: 6,
    name: 'belt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา / สัมผัส',
    accept: 'กระชับ ปรับได้ ล็อคและปลดล็อคได้',
  },
  {
    id: 7,
    name: 'door',
    question: 'ประตู',
    howto: 'สายตา / สัมผัส',
    accept: 'เปิด ปิด ล็อคได้ ไม่ชำรุด กระจกเลื่อนขึ้นลงได้',
  },
  {
    id: 8,
    name: 'mirror',
    question: 'กระจก',
    howto: 'สายตา',
    accept: 'สะอาดใส ไม่แตก ไม่ชำรุด ปรับตำแหน่งได้',
  },
  {
    id: 9,
    name: 'lamp',
    question: 'ไฟหน้าใหม่**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 10,
    name: 'turnLight',
    question: 'ไฟเลี้ยว**',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจน กระพริบเป็นจังหวะทุกดวง',
  },
  {
    id: 11,
    name: 'nut',
    question: 'น๊อตล้อ**',
    howto: 'สายตา / สัมผัส',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 12,
    name: 'frontWheelL',
    question: 'ล้อหน้า **ซ้าย',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 13,
    name: 'frontWheelR',
    question: 'ล้อหน้า **ขวา',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 14,
    name: 'lub',
    question: 'น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 15,
    name: 'brakeOil',
    question: 'น้ำมันเบรคเพียงพอ/ไม่รั่วซึม',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 16,
    name: 'backSound',
    question: 'สัญญาณเสียงถอย',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 17,
    name: 'backLight',
    question: 'สัญญาณไฟถอย',
    howto: 'ฟังเสียง / สายตา',
    accept: 'เสียงเตือนดังและไฟติด',
  },
  {
    id: 18,
    name: 'rearLampL',
    question: 'ไฟท้าย **ซ้าย',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 19,
    name: 'rearLampR',
    question: 'ไฟท้าย **ขวา',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 20,
    name: 'rearWheelL',
    question: 'ล้อหลัง **ซ้าย',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 21,
    name: 'rearWheelR',
    question: 'ล้อหลัง **ขวา',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 22,
    name: 'extinguisher',
    question: 'ถังดับเพลิง',
    howto: 'สายตา / สัมผัส',
    accept: 'เกจชี้ในช่องสีเขียว มีเข็มขัดรัดสลัก พร้อมใช้',
  },
  {
    id: 23,
    name: 'pvcChuteD',
    question: 'ราง PVC',
    howto: 'สายตา',
    accept: 'ไม่มีเศษคอนกรีตแห้งติดสะสม',
  },
];

export const questionsWeek = [
  {
    id: 24,
    name: 'wiper',
    question: 'ใบปัดน้ำฝน',
    howto: 'สายตา',
    accept: 'ไม่เสื่อมสภาพ มีน้ำฉีดกระจก',
  },
  {
    id: 25,
    name: 'cone',
    question: 'กรวยจราจร',
    howto: 'สายตา',
    accept: 'สะอาด สะท้อนแสงได้ จำนวนครบถ้วน',
  },
  {
    id: 26,
    name: 'sideGuardL',
    question: 'การ์ดด้านข้างซ้าย',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 27,
    name: 'sideGuardR',
    question: 'การ์ดด้านข้างขวา',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 28,
    name: 'waterReverse',
    question: 'ถังน้ำสำรอง',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่รั่วซึม',
  },
  {
    id: 29,
    name: 'drum',
    question: 'สภาพโม่',
    howto: 'สายตา',
    accept: 'สะอาด สีไม่สีด โลโก้อยู่ในสภาพดี',
  },
  {
    id: 30,
    name: 'hydrolic',
    question: 'ปั๊มขับโม่',
    howto: 'สายตา',
    accept: 'ทำงานปกติ',
  },
  {
    id: 31,
    name: 'guardShaft',
    question: 'ฝาครอบเพลา',
    howto: 'สายตา',
    accept: 'มีการ์ดครอบคลุมจุดหมุน',
  },
  {
    id: 32,
    name: 'valve',
    question: 'วาล์วน้ำไม่รั่วซึม',
    howto: 'สายตา',
    accept: 'ไม่รั่วซึม',
  },
  {
    id: 33,
    name: 'blade',
    question: 'ใบกวนไม่ล้ม',
    howto: 'สายตา',
    accept: 'ไม่ล้ม',
  },
  {
    id: 34,
    name: 'bladeTear',
    question: 'ใบกวนไม่มีรอยฉีกขาด',
    howto: 'สายตา',
    accept: 'ไม่มีรอยฉีกขาด',
  },
  {
    id: 35,
    name: 'ladder',
    question: 'บันได',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม',
  },
  {
    id: 36,
    name: 'chain',
    question: 'ราว/โซ่กันตก',
    howto: 'สายตา',
    accept: 'แข็งแรง จำนวนครบถ้วน',
  },
  {
    id: 37,
    name: 'chute2',
    question: 'ราง2 ล็อคแน่น',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 38,
    name: 'chute3',
    question: 'ราง3 ล็อคแน่น',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 39,
    name: 'pvcChuteW',
    question: 'ราง PVC',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
  {
    id: 40,
    name: 'atena',
    question: 'เสาวัดความสูง',
    howto: 'สายตา',
    accept: 'ตั้งตรง มีความสูงตามที่กำหนด',
  },
  {
    id: 41,
    name: 'chuteHandle',
    question: 'โกร่ง-หูจับราง',
    howto: 'สายตา',
    accept: 'แข็งแรง ไม่หลวม ไม่มีเศษคอนกรีตติด',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'steering', label: '1.พวงมาลัย *' },
  { field: 'steeringR', label: '' },
  { field: 'steeringP', label: '' },
  { field: 'steeringA', label: 'Respond to defect' },
  { field: 'steeringF', label: '' },
  { field: 'horn', label: '2.แตร*' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'gear', label: '3.เกียร์*' },
  { field: 'gearR', label: '' },
  { field: 'gearP', label: '' },
  { field: 'gearA', label: 'Respond to defect' },
  { field: 'gearF', label: '' },
  { field: 'footBrake', label: '4.เบรคเท้า**' },
  { field: 'footBrakeR', label: '' },
  { field: 'footBrakeP', label: '' },
  { field: 'footBrakeA', label: 'Respond to defect' },
  { field: 'footBrakeF', label: '' },
  { field: 'handBrake', label: '5.เบรคมือ*' },
  { field: 'handBrakeR', label: '' },
  { field: 'handBrakeP', label: '' },
  { field: 'handBrakeA', label: 'Respond to defect' },
  { field: 'handBrakeF', label: '' },
  { field: 'belt', label: '6.เข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'door', label: '7.ประตู' },
  { field: 'doorR', label: '' },
  { field: 'doorP', label: '' },
  { field: 'doorA', label: 'Respond to defect' },
  { field: 'doorF', label: '' },
  { field: 'mirror', label: '8.กระจก' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'lamp', label: '9.ไฟหน้าใหม่**' },
  { field: 'lampR', label: '' },
  { field: 'lampP', label: '' },
  { field: 'lampA', label: 'Respond to defect' },
  { field: 'lampF', label: '' },
  { field: 'turnLight', label: '10.ไฟเลี้ยว**' },
  { field: 'turnLightR', label: '' },
  { field: 'turnLightP', label: '' },
  { field: 'turnLightA', label: 'Respond to defect' },
  { field: 'turnLightF', label: '' },
  { field: 'nut', label: '11.น๊อตล้อ**' },
  { field: 'nutR', label: '' },
  { field: 'nutP', label: '' },
  { field: 'nutA', label: 'Respond to defect' },
  { field: 'nutF', label: '' },
  { field: 'frontWheelL', label: '12.ล้อหน้า **ซ้าย' },
  { field: 'frontWheelLR', label: '' },
  { field: 'frontWheelLP', label: '' },
  { field: 'frontWheelLA', label: 'Respond to defect' },
  { field: 'frontWheelLF', label: '' },
  { field: 'frontWheelR', label: '13.ล้อหน้า **ขวา' },
  { field: 'frontWheelRR', label: '' },
  { field: 'frontWheelRP', label: '' },
  { field: 'frontWheelRA', label: 'Respond to defect' },
  { field: 'frontWheelRF', label: '' },
  { field: 'lub', label: '14.น้ำมันหล่อลื่นเพียงพอ/ไม่รั่วซึม' },
  { field: 'lubR', label: '' },
  { field: 'lubP', label: '' },
  { field: 'lubA', label: 'Respond to defect' },
  { field: 'lubF', label: '' },
  { field: 'brakeOil', label: '15.น้ำมันเบรคเพียงพอ/ไม่รั่วซึม' },
  { field: 'brakeOilR', label: '' },
  { field: 'brakeOilP', label: '' },
  { field: 'brakeOilA', label: 'Respond to defect' },
  { field: 'brakeOilF', label: '' },
  { field: 'backSound', label: '16.สัญญาณเสียงถอย' },
  { field: 'backSoundR', label: '' },
  { field: 'backSoundP', label: '' },
  { field: 'backSoundA', label: 'Respond to defect' },
  { field: 'backSoundF', label: '' },
  { field: 'backLight', label: '17.สัญญาณไฟถอย' },
  { field: 'backLightR', label: '' },
  { field: 'backLightP', label: '' },
  { field: 'backLightA', label: 'Respond to defect' },
  { field: 'backLightF', label: '' },
  { field: 'rearLampL', label: '18.ไฟท้าย **ซ้าย' },
  { field: 'rearLampLR', label: '' },
  { field: 'rearLampLP', label: '' },
  { field: 'rearLampLA', label: 'Respond to defect' },
  { field: 'rearLampLF', label: '' },
  { field: 'rearLampR', label: '19.ไฟท้าย **ขวา' },
  { field: 'rearLampRR', label: '' },
  { field: 'rearLampRP', label: '' },
  { field: 'rearLampRA', label: 'Respond to defect' },
  { field: 'rearLampRF', label: '' },
  { field: 'rearWheelL', label: '20.ล้อหลัง **ซ้าย' },
  { field: 'rearWheelLR', label: '' },
  { field: 'rearWheelLP', label: '' },
  { field: 'rearWheelLA', label: 'Respond to defect' },
  { field: 'rearWheelLF', label: '' },
  { field: 'rearWheelR', label: '21.ล้อหลัง **ขวา' },
  { field: 'rearWheelRR', label: '' },
  { field: 'rearWheelRP', label: '' },
  { field: 'rearWheelRA', label: 'Respond to defect' },
  { field: 'rearWheelRF', label: '' },
  { field: 'extinguisher', label: '22.ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'pvcChuteD', label: '23.ราง PVC' },
  { field: 'pvcChuteDR', label: '' },
  { field: 'pvcChuteDP', label: '' },
  { field: 'pvcChuteDA', label: 'Respond to defect' },
  { field: 'pvcChuteDF', label: '' },

  { field: 'wiper', label: '24.ใบปัดน้ำฝน' },
  { field: 'wiperR', label: '' },
  { field: 'wiperP', label: '' },
  { field: 'wiperA', label: 'Respond to defect' },
  { field: 'wiperF', label: '' },
  { field: 'cone', label: '25.กรวยจราจร' },
  { field: 'coneR', label: '' },
  { field: 'coneP', label: '' },
  { field: 'coneA', label: 'Respond to defect' },
  { field: 'coneF', label: '' },
  { field: 'sideGuardL', label: '26.การ์ดด้านข้างซ้าย' },
  { field: 'sideGuardLR', label: '' },
  { field: 'sideGuardLP', label: '' },
  { field: 'sideGuardLA', label: 'Respond to defect' },
  { field: 'sideGuardLF', label: '' },
  { field: 'sideGuardR', label: '27.การ์ดด้านข้างขวา' },
  { field: 'sideGuardRR', label: '' },
  { field: 'sideGuardRP', label: '' },
  { field: 'sideGuardRA', label: 'Respond to defect' },
  { field: 'sideGuardRF', label: '' },
  { field: 'waterReverse', label: '28.ถังน้ำสำรอง' },
  { field: 'waterReverseR', label: '' },
  { field: 'waterReverseP', label: '' },
  { field: 'waterReverseA', label: 'Respond to defect' },
  { field: 'waterReverseF', label: '' },
  { field: 'drum', label: '29.สภาพโม่' },
  { field: 'drumR', label: '' },
  { field: 'drumP', label: '' },
  { field: 'drumA', label: 'Respond to defect' },
  { field: 'drumF', label: '' },
  { field: 'hydrolic', label: '30.ปั๊มขับโม่' },
  { field: 'hydrolicR', label: '' },
  { field: 'hydrolicP', label: '' },
  { field: 'hydrolicA', label: 'Respond to defect' },
  { field: 'hydrolicF', label: '' },
  { field: 'guardShaft', label: '31.ฝาครอบเพลา' },
  { field: 'guardShaftR', label: '' },
  { field: 'guardShaftP', label: '' },
  { field: 'guardShaftA', label: 'Respond to defect' },
  { field: 'guardShaftF', label: '' },
  { field: 'valve', label: '32.วาล์วน้ำไม่รั่วซึม' },
  { field: 'valveR', label: '' },
  { field: 'valveP', label: '' },
  { field: 'valveA', label: 'Respond to defect' },
  { field: 'valveF', label: '' },
  { field: 'blade', label: '33.ใบกวนไม่ล้ม' },
  { field: 'bladeR', label: '' },
  { field: 'bladeP', label: '' },
  { field: 'bladeA', label: 'Respond to defect' },
  { field: 'bladeF', label: '' },
  { field: 'bladeTear', label: '34.ใบกวนไม่มีรอยฉีกขาด' },
  { field: 'bladeTearR', label: '' },
  { field: 'bladeTearP', label: '' },
  { field: 'bladeTearA', label: 'Respond to defect' },
  { field: 'bladeTearF', label: '' },
  { field: 'ladder', label: '35.บันได' },
  { field: 'ladderR', label: '' },
  { field: 'ladderP', label: '' },
  { field: 'ladderA', label: 'Respond to defect' },
  { field: 'ladderF', label: '' },
  { field: 'chain', label: '36.ราว/โซ่กันตก' },
  { field: 'chainR', label: '' },
  { field: 'chainP', label: '' },
  { field: 'chainA', label: 'Respond to defect' },
  { field: 'chainF', label: '' },
  { field: 'chute2', label: '37.ราง2 ล็อคแน่น' },
  { field: 'chute2R', label: '' },
  { field: 'chute2P', label: '' },
  { field: 'chute2A', label: 'Respond to defect' },
  { field: 'chute2F', label: '' },
  { field: 'chute3', label: '38.ราง3 ล็อคแน่น' },
  { field: 'chute3R', label: '' },
  { field: 'chute3P', label: '' },
  { field: 'chute3A', label: 'Respond to defect' },
  { field: 'chute3F', label: '' },
  { field: 'pvcChuteW', label: '39.ราง PVC' },
  { field: 'pvcChuteWR', label: '' },
  { field: 'pvcChuteWP', label: '' },
  { field: 'pvcChuteWA', label: 'Respond to defect' },
  { field: 'pvcChuteWF', label: '' },
  { field: 'atena', label: '40.เสาวัดความสูง' },
  { field: 'atenaR', label: '' },
  { field: 'atenaP', label: '' },
  { field: 'atenaA', label: 'Respond to defect' },
  { field: 'atenaF', label: '' },
  { field: 'chuteHandle', label: '41.โกร่ง-หูจับราง' },
  { field: 'chuteHandleR', label: '' },
  { field: 'chuteHandleP', label: '' },
  { field: 'chuteHandleA', label: 'Respond to defect' },
  { field: 'chuteHandleF', label: '' },

  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];

export const detailFieldsT = [
  { field: 'date', label: 'วันที่ Date' },
  { field: 'side', label: 'ด้านที่ถ่ายรูป' },
  { field: 'takenBy', label: 'ถ่ายโดย' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
