export const questions = [
  {
    id: 1,
    name: 'structure',
    question: 'Cấu trúc',
    howto: 'Kiểm tra cấu trúc có bị hư hỏng, rải đầy hay phủ đầy bụi bẩn.',
    accept: 'Cấu trúc không bị hư hỏng và sạch sẽ.',
  },
  {
    id: 2,
    name: 'hydraulicSystem',
    question: 'Hệ thống thủy lực',
    howto:
      'Kiểm tra hệ thống thủy lực về hỗ trợ, sử dụng, rò rỉ, kết nối và bảo trì.',
    accept: 'Hệ thống thủy lực hoạt động bình thường và không bị rò rỉ.',
  },
  {
    id: 3,
    name: 'towingSystem',
    question: 'Hệ thống kéo',
    howto:
      'Kiểm tra hệ thống kéo, bao gồm dán cảnh báo, móc kéo, thùng xe và thanh đổ.',
    accept: 'Hệ thống kéo hoạt động bình thường và an toàn.',
  },
  {
    id: 4,
    name: 'fluids',
    question: 'Chất lỏng',
    howto:
      'Kiểm tra các loại chất lỏng như dầu, nước làm mát, nhiên liệu, pin và chất tẩy rửa nhà vệ sinh. Việc kiểm tra nước làm mát sẽ chỉ được kiểm tra mực nước trong bình nước phụ và không cần mở mắt bình nước phụ cũng như két làm mát.',
    accept: 'Tất cả các chất lỏng ở mức phù hợp và không bị rò rỉ.',
  },
  {
    id: 5,
    name: 'cabin',
    question: 'Cabin',
    howto:
      'Kiểm tra cabin bao gồm phanh tay, phanh chân và bình khí nén hỗ trợ phanh.',
    accept: 'Cabin sạch sẽ và các hệ thống phanh hoạt động bình thường.',
  },
  {
    id: 6,
    name: 'brakes',
    question: 'Phanh',
    howto: 'Kiểm tra phanh tay, phanh chân và bình khí nén hỗ trợ phanh.',
    accept: 'Phanh tay và phanh chân hoạt động bình thường.',
  },
  {
    id: 7,
    name: 'operationSystem',
    question: 'Hệ thống vận hành',
    howto:
      'Kiểm tra vô lăng, bàn đạp, đèn phanh, đèn trước, đèn báo, xi nhan và công tắc.',
    accept:
      'Hệ thống vận hành hoạt động bình thường và tất cả các đèn sáng đúng cách.',
  },
  {
    id: 8,
    name: 'warnings',
    question: 'CẢNH BÁO',
    howto: 'Kiểm tra còi, tắt còi, còi cảnh báo, đèn cảnh báo và tắt đèn.',
    accept: 'Tất cả các thiết bị cảnh báo hoạt động bình thường.',
  },
  {
    id: 9,
    name: 'otherEquipment',
    question: 'THIẾT BỊ KHÁC',
    howto:
      'Kiểm tra biển số xe, sách hướng dẫn vận hành, bình chữa cháy và túi sơ cứu.',
    accept: 'Tất cả các thiết bị khác đều đầy đủ và trong tình trạng tốt.',
  },
  {
    id: 10,
    name: 'sanitation',
    question: 'Tình trạng vệ sinh',
    howto: 'Kiểm tra tình trạng vệ sinh tổng thể của xe.',
    accept: 'Xe được vệ sinh sạch sẽ và không có bụi bẩn.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  {
    field: 'certificate',
    label:
      'Chứng nhận kiểm định/đăng kiểm còn hiệu lực đến ngày. Inspection/register certificate valid to',
  },
  { field: 'responder', label: 'Responder' },
  { field: 'structure', label: '1. Cấu trúc *' },
  { field: 'structureR', label: '' },
  { field: 'structureP', label: '' },
  { field: 'structureA', label: 'Respond to defect' },
  { field: 'structureF', label: '' },
  { field: 'hydraulicSystem', label: '2. Hệ thống thủy lực *' },
  { field: 'hydraulicSystemR', label: '' },
  { field: 'hydraulicSystemP', label: '' },
  { field: 'hydraulicSystemA', label: 'Respond to defect' },
  { field: 'hydraulicSystemF', label: '' },
  { field: 'towingSystem', label: '3. Hệ thống kéo *' },
  { field: 'towingSystemR', label: '' },
  { field: 'towingSystemP', label: '' },
  { field: 'towingSystemA', label: 'Respond to defect' },
  { field: 'towingSystemF', label: '' },
  { field: 'fluids', label: '4. Chất lỏng *' },
  { field: 'fluidsR', label: '' },
  { field: 'fluidsP', label: '' },
  { field: 'fluidsA', label: 'Respond to defect' },
  { field: 'fluidsF', label: '' },
  { field: 'cabin', label: '5. Cabin *' },
  { field: 'cabinR', label: '' },
  { field: 'cabinP', label: '' },
  { field: 'cabinA', label: 'Respond to defect' },
  { field: 'cabinF', label: '' },
  { field: 'brakes', label: '6. Phanh *' },
  { field: 'brakesR', label: '' },
  { field: 'brakesP', label: '' },
  { field: 'brakesA', label: 'Respond to defect' },
  { field: 'brakesF', label: '' },
  { field: 'operationSystem', label: '7. Hệ thống vận hành *' },
  { field: 'operationSystemR', label: '' },
  { field: 'operationSystemP', label: '' },
  { field: 'operationSystemA', label: 'Respond to defect' },
  { field: 'operationSystemF', label: '' },
  { field: 'warnings', label: '8. CẢNH BÁO *' },
  { field: 'warningsR', label: '' },
  { field: 'warningsP', label: '' },
  { field: 'warningsA', label: 'Respond to defect' },
  { field: 'warningsF', label: '' },
  { field: 'otherEquipment', label: '9. THIẾT BỊ KHÁC *' },
  { field: 'otherEquipmentR', label: '' },
  { field: 'otherEquipmentP', label: '' },
  { field: 'otherEquipmentA', label: 'Respond to defect' },
  { field: 'otherEquipmentF', label: '' },
  { field: 'sanitation', label: '10. Tình trạng vệ sinh *' },
  { field: 'sanitationR', label: '' },
  { field: 'sanitationP', label: '' },
  { field: 'sanitationA', label: 'Respond to defect' },
  { field: 'sanitationF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
