export const questions = [
  {
    id: 1,
    name: 'loadSignageCheck',
    question: 'ป้ายเตือน/ข้อมูลโหลดสูงสุด (Load Capacity Signage) ติดตั้งและมองเห็นชัดเจน',
    howto: 'ตรวจสอบป้ายบนตัวเครนหรือตัวอุปกรณ์',
    accept: 'ป้ายติดตั้งแน่น อ่านชัดเจน ไม่หลุดหรือซีดจาง',
  },
  {
    id: 2,
    name: 'runwayRailCheck',
    question: 'รางเลื่อน (Runway Rails) ไม่มีรอยแตกร้าวหรือบิดงอ',
    howto: 'ตรวจสอบรางตลอดแนวด้วยสายตา',
    accept: 'รางเรียบตรง ไม่มีรอยแตกร้าวหรือบิดเบี้ยว',
  },
  {
    id: 3,
    name: 'hookConditionCheck',
    question: 'ตรวจสอบตะขอเครน (Hook) ไม่มีรอยแตกร้าว บิดงอ หรือบวม',
    howto: 'ตรวจสอบตะขอด้วยสายตาและมือสัมผัส',
    accept: 'ตะขออยู่ในรูปทรงเดิม ไม่มีความเสียหาย',
  },
  {
    id: 4,
    name: 'controlPendantTest',
    question: 'ปุ่มควบคุม (Control Pendant / Remote) ตอบสนองได้ถูกต้อง',
    howto: 'กดแต่ละปุ่มเพื่อตรวจสอบการตอบสนองของระบบ',
    accept: 'แต่ละปุ่มทำงานได้ตามคำสั่ง ไม่มีหน่วงหรือค้าง',
  },
  {
    id: 5,
    name: 'emergencyStopTest',
    question: 'ระบบหยุดฉุกเฉิน (Emergency Stop) ใช้งานได้',
    howto: 'กดปุ่มหยุดฉุกเฉิน และตรวจสอบว่าเครื่องหยุดทันที',
    accept: 'ระบบหยุดทำงานเมื่อกด Emergency Stop',
  },
  {
    id: 6,
    name: 'alarmSystemTest',
    question: 'ระบบเตือน (Alarm, Warning Light) ทำงานได้',
    howto: 'เปิดระบบและสังเกตว่าไฟ/เสียงเตือนทำงาน',
    accept: 'ไฟหรือเสียงเตือนทำงานได้ครบทุกจุด',
  },
  {
    id: 7,
    name: 'hookLatchCheck',
    question: 'ตรวจสอบ ตัวล็อกนิรภัยของตะขอ ว่ายังทำงานได้ปกติ',
    howto: 'ขยับกลไกล็อกของตะขอเพื่อดูการตอบสนอง',
    accept: 'ล็อกนิรภัยเด้งกลับได้ดี ไม่มีติดขัด',
  },
  {
    id: 8,
    name: 'hoistDrumNoiseCheck',
    question: 'ตรวจสอบ รอก (Hoist) และดรัมม้วนสายสลิง ว่าไม่มีเสียงหรือการสั่นผิดปกติ',
    howto: 'สังเกตและฟังเสียงขณะทดสอบการหมุนของดรัม',
    accept: 'ไม่มีเสียงดังผิดปกติหรือการสั่นที่ผิดสังเกต',
  },
  {
    id: 9,
    name: 'wireRopeChainCheck',
    question: 'ตรวจสอบ สายสลิง / เชือกสลิง / โซ่ ว่าไม่มีการแตก, ขาด, บิด, ชำรุด',
    howto: 'ตรวจสอบด้วยสายตาและมือสัมผัสตลอดแนวสาย',
    accept: 'สายสลิงอยู่ในสภาพสมบูรณ์ ไม่มีรอยขาดหรือบิดเบี้ยว',
  },
  {
    id: 10,
    name: 'limitSwitchTest',
    question: 'ทดสอบ Limit Switch (อุปกรณ์ตัดการทำงานเมื่อถึงจุดสูงสุด/ต่ำสุด) ว่าทำงานถูกต้อง',
    howto: 'ยกหรือลดตะขอจนถึงจุดตัดการทำงานแล้วสังเกตผล',
    accept: 'ระบบตัดการทำงานเมื่อถึงจุดสูงสุดหรือต่ำสุดตามกำหนด',
  },
  {
    id: 11,
    name: 'brakeSystemCheck',
    question: 'ตรวจสอบ เบรก (Brake System) ว่าสามารถหยุดการเคลื่อนไหวได้ดี ไม่มีการลื่นไถล',
    howto: 'ทดสอบการหยุดของตะขอเมื่อปล่อยปุ่มควบคุม',
    accept: 'ตะขอหยุดทันที ไม่ลื่นไถลหรือลงต่อเนื่อง',
  }
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'loadSignageCheck', label: '1. ป้ายเตือน/ข้อมูลโหลดสูงสุด (Load Capacity Signage) ติดตั้งและมองเห็นชัดเจน' },
  { field: 'loadSignageCheckR', label: '' },
  { field: 'loadSignageCheckP', label: '' },
  { field: 'loadSignageCheckA', label: 'Respond to defect' },
  { field: 'loadSignageCheckF', label: '' },
  { field: 'runwayRailCheck', label: '2. รางเลื่อน (Runway Rails) ไม่มีรอยแตกร้าวหรือบิดงอ' },
  { field: 'runwayRailCheckR', label: '' },
  { field: 'runwayRailCheckP', label: '' },
  { field: 'runwayRailCheckA', label: 'Respond to defect' },
  { field: 'runwayRailCheckF', label: '' },
  { field: 'hookConditionCheck', label: '3. ตรวจสอบตะขอเครน (Hook) ไม่มีรอยแตกร้าว บิดงอ หรือบวม' },
  { field: 'hookConditionCheckR', label: '' },
  { field: 'hookConditionCheckP', label: '' },
  { field: 'hookConditionCheckA', label: 'Respond to defect' },
  { field: 'hookConditionCheckF', label: '' },
  { field: 'controlPendantTest', label: '4. ปุ่มควบคุม (Control Pendant / Remote) ตอบสนองได้ถูกต้อง' },
  { field: 'controlPendantTestR', label: '' },
  { field: 'controlPendantTestP', label: '' },
  { field: 'controlPendantTestA', label: 'Respond to defect' },
  { field: 'controlPendantTestF', label: '' },
  { field: 'emergencyStopTest', label: '5. ระบบหยุดฉุกเฉิน (Emergency Stop) ใช้งานได้' },
  { field: 'emergencyStopTestR', label: '' },
  { field: 'emergencyStopTestP', label: '' },
  { field: 'emergencyStopTestA', label: 'Respond to defect' },
  { field: 'emergencyStopTestF', label: '' },
  { field: 'alarmSystemTest', label: '6. ระบบเตือน (Alarm, Warning Light) ทำงานได้' },
  { field: 'alarmSystemTestR', label: '' },
  { field: 'alarmSystemTestP', label: '' },
  { field: 'alarmSystemTestA', label: 'Respond to defect' },
  { field: 'alarmSystemTestF', label: '' },
  { field: 'hookLatchCheck', label: '7. ตรวจสอบ ตัวล็อกนิรภัยของตะขอ ว่ายังทำงานได้ปกติ' },
  { field: 'hookLatchCheckR', label: '' },
  { field: 'hookLatchCheckP', label: '' },
  { field: 'hookLatchCheckA', label: 'Respond to defect' },
  { field: 'hookLatchCheckF', label: '' },
  { field: 'hoistDrumNoiseCheck', label: '8. ตรวจสอบ รอก (Hoist) และดรัมม้วนสายสลิง ว่าไม่มีเสียงหรือการสั่นผิดปกติ' },
  { field: 'hoistDrumNoiseCheckR', label: '' },
  { field: 'hoistDrumNoiseCheckP', label: '' },
  { field: 'hoistDrumNoiseCheckA', label: 'Respond to defect' },
  { field: 'hoistDrumNoiseCheckF', label: '' },
  { field: 'wireRopeChainCheck', label: '9. ตรวจสอบ สายสลิง / เชือกสลิง / โซ่ ว่าไม่มีการแตก, ขาด, บิด, ชำรุด' },
  { field: 'wireRopeChainCheckR', label: '' },
  { field: 'wireRopeChainCheckP', label: '' },
  { field: 'wireRopeChainCheckA', label: 'Respond to defect' },
  { field: 'wireRopeChainCheckF', label: '' },
  { field: 'limitSwitchTest', label: '10. ทดสอบ Limit Switch (อุปกรณ์ตัดการทำงานเมื่อถึงจุดสูงสุด/ต่ำสุด) ว่าทำงานถูกต้อง' },
  { field: 'limitSwitchTestR', label: '' },
  { field: 'limitSwitchTestP', label: '' },
  { field: 'limitSwitchTestA', label: 'Respond to defect' },
  { field: 'limitSwitchTestF', label: '' },
  { field: 'brakeSystemCheck', label: '11. ตรวจสอบ เบรก (Brake System) ว่าสามารถหยุดการเคลื่อนไหวได้ดี ไม่มีการลื่นไถล' },
  { field: 'brakeSystemCheckR', label: '' },
  { field: 'brakeSystemCheckP', label: '' },
  { field: 'brakeSystemCheckA', label: 'Respond to defect' },
  { field: 'brakeSystemCheckF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
