export const questions = [
  {
    id: 1,
    name: 'brakeOil',
    question: 'ตรวจสอบน้ำมันเบรก',
    howto: 'สายตา/ประเมิน',
    accept: 'สภาพสี ความขุ่นของน้ำมันเบรก และระดับของน้ำมันเบรก',
  },
  {
    id: 2,
    name: 'brakeHose',
    question: 'ตรวจสอบสภาพท่อยางเบรก',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การพับงอ บิด บวมตัวเสียรูป รอยฉีกขาด รั่วซึม',
  },
  {
    id: 3,
    name: 'airSystem',
    question: 'ตรวจสอบสภาพการรั่วซึมของระบบลม',
    howto: 'ฟังเสียง/สังเกต',
    accept: 'การรั่วซึมของลมเบรก เสียงลมรั่ว',
  },
  {
    id: 4,
    name: 'airTank',
    question: 'ตรวจสอบถังลมเบรก',
    howto: 'สายตา/ถ่ายน้ำออก',
    accept: 'มีน้ำในถังควรถ่ายน้ำออกจากถัง',
  },
  {
    id: 5,
    name: 'dashboard',
    question: 'ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ',
    howto: 'สายตา/สังเกต',
    accept: 'ความสมบูรณ์ของระบบควบคุม เช่น เกจความดันลม ไฟเตือน',
  },
  {
    id: 6,
    name: 'clutch',
    question: 'ตรวจสภาพระบบคลัช',
    howto: 'ทดลองเหยียบ/สังเกต',
    accept: 'ระยะฟรีขาเหยียบคลัชช์ และการลื่นไถลของคลัทช์',
  },
  {
    id: 7,
    name: 'hydraulic',
    question: 'ตรวจสายไฮโดรลิค',
    howto: 'สายตา/สังเกต',
    accept: 'รอยแตกของสาย รอยรั่ว หรือการเสื่อมสภาพของจุดต่อรั่วซึม',
  },
  {
    id: 8,
    name: 'dumpCylinder',
    question: 'ตรวจกระบอกดั๊ม',
    howto: 'ทดสอบการใช้งาน',
    accept:
      'สภาพสมบูรณ์ ไม่ชำรุด ยกต่อเนื่อง ไม่กระตุก มีเสียงเตือนเมื่อยกขึ้นลง',
  },
  {
    id: 9,
    name: 'frontRearBearing',
    question: 'ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)',
    howto: 'ทดลองหมุนพวงมาลัย',
    accept: 'การหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 10,
    name: 'tieRod',
    question: 'ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย - ขวา)',
    howto: 'ทดลองหมุนพวงมาลัย',
    accept: 'การหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 11,
    name: 'tires',
    question: 'ตรวจสภาพยางทุกเส้น',
    howto: 'สายตา/วัดความลึกดอกยาง',
    accept: 'ความสึกหรอ รอยแตกของผิวแก้มยาง (ทุกเส้น)',
  },
  {
    id: 12,
    name: 'wheelRim',
    question: 'ตรวจสอบสภาพกระทะล้อ และน็อตล้อ',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การแตกร้าว, รอยขาดของน็อตล้อ หลุดหาย (ทุกล้อ)',
  },
  {
    id: 13,
    name: 'headlightHorn',
    question: 'ตรวจสภาพไฟหน้า/ แตรสัญญาณ',
    howto: 'ทดลองใช้งาน',
    accept: 'ความสมบูรณ์พร้อมใช้งานของไฟหน้า และแตร',
  },
  {
    id: 14,
    name: 'tailBrakeLight',
    question: 'ตรวจสภาพไฟท้าย / ไฟเบรก',
    howto: 'ทดลองใช้งาน',
    accept: 'ความพร้อมใช้งานของไฟท้าย/ไฟเบรก, สัญญาณเสียงถอย',
  },
  {
    id: 15,
    name: 'turnSideLight',
    question: 'ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง',
    howto: 'ทดลองใช้งาน',
    accept: 'ความพร้อมใช้งานของไฟเลี้ยว / ไฟด้านข้าง',
  },
  {
    id: 16,
    name: 'tailgate',
    question: 'ตรวจเช็คฝาท้าย / ปากนกแก้ว',
    howto: 'สายตา/ทดลองใช้งาน',
    accept: 'ฝาท้ายปิดสนิท , ไม่ล้า ล็อกได้สนิททุกตัว ไม่มีการรั่วไหลของแร่',
  },
  {
    id: 17,
    name: 'hitch',
    question: 'ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง',
    howto: 'สายตา/ตรวจสอบด้วยมือ',
    accept: 'การสึกหรอ รอยแตก รอยร้าว ของสลัก',
  },
  {
    id: 18,
    name: 'licensePlate',
    question: 'สภาพแผ่นป้ายทะเบียน',
    howto: 'สายตา/ตรวจสอบ',
    accept: 'ครบ สะอาดมองเห็นชัดเจน ไม่เลือนลาง และเป็นป้ายที่ทางราชการออกให้',
  },
  {
    id: 19,
    name: 'brakeTest',
    question: 'ตรวจสอบระบบเบรก',
    howto: 'ทดลองเบรก',
    accept:
      'ออกเกียร์ 1 ความเร็ว 10 กม./ชม. ระยะ 5 ม. แล้วเหยีบเบรก รถหยุดใน 1 ม.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'carBodyColor', label: '1. สภาพสีรถและตัวถัง' },
  { field: 'carBodyColorR', label: '' },
  { field: 'carBodyColorP', label: '' },
  { field: 'carBodyColorA', label: 'Respond to defect' },
  { field: 'carBodyColorF', label: '' },
  { field: 'brakeHose', label: '2. ตรวจสอบสภาพท่อยางเบรก' },
  { field: 'brakeHoseR', label: '' },
  { field: 'brakeHoseP', label: '' },
  { field: 'brakeHoseA', label: 'Respond to defect' },
  { field: 'brakeHoseF', label: '' },
  { field: 'airSystem', label: '3. ตรวจสอบสภาพการรั่วซึมของระบบลม' },
  { field: 'airSystemR', label: '' },
  { field: 'airSystemP', label: '' },
  { field: 'airSystemA', label: 'Respond to defect' },
  { field: 'airSystemF', label: '' },
  { field: 'airTank', label: '4. ตรวจสอบถังลมเบรก' },
  { field: 'airTankR', label: '' },
  { field: 'airTankP', label: '' },
  { field: 'airTankA', label: 'Respond to defect' },
  { field: 'airTankF', label: '' },
  { field: 'dashboard', label: '5. ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ' },
  { field: 'dashboardR', label: '' },
  { field: 'dashboardP', label: '' },
  { field: 'dashboardA', label: 'Respond to defect' },
  { field: 'dashboardF', label: '' },
  { field: 'clutch', label: '6. ตรวจสภาพระบบคลัช' },
  { field: 'clutchR', label: '' },
  { field: 'clutchP', label: '' },
  { field: 'clutchA', label: 'Respond to defect' },
  { field: 'clutchF', label: '' },
  { field: 'hydraulic', label: '7. ตรวจสายไฮโดรลิค' },
  { field: 'hydraulicR', label: '' },
  { field: 'hydraulicP', label: '' },
  { field: 'hydraulicA', label: 'Respond to defect' },
  { field: 'hydraulicF', label: '' },
  { field: 'dumpCylinder', label: '8. ตรวจกระบอกดั๊ม' },
  { field: 'dumpCylinderR', label: '' },
  { field: 'dumpCylinderP', label: '' },
  { field: 'dumpCylinderA', label: 'Respond to defect' },
  { field: 'dumpCylinderF', label: '' },
  { field: 'frontRearBearing', label: '9. ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)' },
  { field: 'frontRearBearingR', label: '' },
  { field: 'frontRearBearingP', label: '' },
  { field: 'frontRearBearingA', label: 'Respond to defect' },
  { field: 'frontRearBearingF', label: '' },
  { field: 'tieRod', label: '10. ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย - ขวา)' },
  { field: 'tieRodR', label: '' },
  { field: 'tieRodP', label: '' },
  { field: 'tieRodA', label: 'Respond to defect' },
  { field: 'tieRodF', label: '' },
  { field: 'tires', label: '11. ตรวจสภาพยางทุกเส้น' },
  { field: 'tiresR', label: '' },
  { field: 'tiresP', label: '' },
  { field: 'tiresA', label: 'Respond to defect' },
  { field: 'tiresF', label: '' },
  { field: 'wheelRim', label: '12. ตรวจสอบสภาพกระทะล้อ และน็อตล้อ' },
  { field: 'wheelRimR', label: '' },
  { field: 'wheelRimP', label: '' },
  { field: 'wheelRimA', label: 'Respond to defect' },
  { field: 'wheelRimF', label: '' },
  { field: 'headlightHorn', label: '13. ตรวจสภาพไฟหน้า/ แตรสัญญาณ' },
  { field: 'headlightHornR', label: '' },
  { field: 'headlightHornP', label: '' },
  { field: 'headlightHornA', label: 'Respond to defect' },
  { field: 'headlightHornF', label: '' },
  { field: 'tailBrakeLight', label: '14. ตรวจสภาพไฟท้าย / ไฟเบรก' },
  { field: 'tailBrakeLightR', label: '' },
  { field: 'tailBrakeLightP', label: '' },
  { field: 'tailBrakeLightA', label: 'Respond to defect' },
  { field: 'tailBrakeLightF', label: '' },
  { field: 'turnSideLight', label: '15. ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง' },
  { field: 'turnSideLightR', label: '' },
  { field: 'turnSideLightP', label: '' },
  { field: 'turnSideLightA', label: 'Respond to defect' },
  { field: 'turnSideLightF', label: '' },
  { field: 'tailgate', label: '16. ตรวจเช็คฝาท้าย / ปากนกแก้ว' },
  { field: 'tailgateR', label: '' },
  { field: 'tailgateP', label: '' },
  { field: 'tailgateA', label: 'Respond to defect' },
  { field: 'tailgateF', label: '' },
  { field: 'hitch', label: '17. ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง' },
  { field: 'hitchR', label: '' },
  { field: 'hitchP', label: '' },
  { field: 'hitchA', label: 'Respond to defect' },
  { field: 'hitchF', label: '' },
  { field: 'licensePlate', label: '18. สภาพแผ่นป้ายทะเบียน' },
  { field: 'licensePlateR', label: '' },
  { field: 'licensePlateP', label: '' },
  { field: 'licensePlateA', label: 'Respond to defect' },
  { field: 'licensePlateF', label: '' },
  { field: 'brakeTest', label: '19. ตรวจสอบระบบเบรก' },
  { field: 'brakeTestR', label: '' },
  { field: 'brakeTestP', label: '' },
  { field: 'brakeTestA', label: 'Respond to defect' },
  { field: 'brakeTestF', label: '' },
  { field: 'remark', label: 'หมายเหตุ - Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
