export const questions = [
  {
    id: 1,
    name: 'pipe',
    question: 'គ្មានដាច់រលាត់ថ្នាំ និង​​​​ មិនមានប្រេះស្រាំមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងភាពរលាត់ថ្នាំ',
    accept: 'ស្ថានភាពល្អ គ្មានដាច់រហែក ឬការលេចធ្លាយ',
  },
  {
    id: 2,
    name: 'vale',
    question: 'ត្រួតពិនិត្យមើលវ៉ាល់បិទបើកធ្វើការធម្មតាមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបិទបើកវ៉ាល់',
    accept: 'វ៉ាល់ដំណើរការបានត្រឹមត្រូវ គ្មានការខូចខាត',
  },
  {
    id: 3,
    name: 'hoseRack',
    question: 'លក្ខណៈគ្មានប្រេះស្រាំមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការការពារប្រើប្រាស់',
    accept: 'ស្ថានភាពល្អ គ្មានការច្រេះ ឬការបាក់',
  },
  {
    id: 4,
    name: 'hoseExtinguisher',
    question: 'លក្ខណៈគ្មានដាច់រហែក និង ទុយោរៀបតាមលំដាប់លំដោយមិនធម្មតា',
    howto: 'ពិនិត្យទុយោរៀបតាមលំដាប់ និងភាពស្អាត',
    accept: 'ទុយោរៀបតាមលំដាប់ល្អ គ្មានការខូចខាត',
  },
  {
    id: 5,
    name: 'reelRack',
    question: 'លក្ខណៈគ្មានប្រេះស្រាំមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការប្រើប្រាស់',
    accept: 'ស្ថានភាពល្អ គ្មានការខូចខាត',
  },
  {
    id: 6,
    name: 'reelExtinguisher',
    question: 'លក្ខណៈគ្មានដាច់រហែក និង សភាពស្អាតល្អមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងសភាពស្អាត',
    accept: 'ស្ថានភាពល្អ គ្មានការខូចខាត',
  },
  {
    id: 7,
    name: 'cabin',
    question: 'បិទជិត និង មិនមានខូចទ្រង់ទ្រាយមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបិទជិត',
    accept: 'បិទជិតល្អ គ្មានការខូចទ្រង់ទ្រាយ',
  },
];

export const detailFields = [
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'pipe', label: '1. គ្មានដាច់រលាត់ថ្នាំ - Pipe Condition' },
  { field: 'pipeR', label: '' },
  { field: 'pipeP', label: '' },
  { field: 'pipeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'pipeF', label: '' },
  { field: 'vale', label: '2. វ៉ាល់បិទបើក - Valve' },
  { field: 'valeR', label: '' },
  { field: 'valeP', label: '' },
  { field: 'valeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'valeF', label: '' },
  { field: 'hoseRack', label: '3. ទុយោរៀបតាមលំដាប់ - Hose Rack' },
  { field: 'hoseRackR', label: '' },
  { field: 'hoseRackP', label: '' },
  { field: 'hoseRackA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hoseRackF', label: '' },
  {
    field: 'hoseExtinguisher',
    label: '4. ទុយោ និងស្ថានភាព - Hose Extinguisher',
  },
  { field: 'hoseExtinguisherR', label: '' },
  { field: 'hoseExtinguisherP', label: '' },
  { field: 'hoseExtinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hoseExtinguisherF', label: '' },
  { field: 'reelRack', label: '5. លក្ខណៈផ្ទុក - Reel Rack' },
  { field: 'reelRackR', label: '' },
  { field: 'reelRackP', label: '' },
  { field: 'reelRackA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'reelRackF', label: '' },
  { field: 'reelExtinguisher', label: '6. សភាពស្អាត - Reel Extinguisher' },
  { field: 'reelExtinguisherR', label: '' },
  { field: 'reelExtinguisherP', label: '' },
  { field: 'reelExtinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'reelExtinguisherF', label: '' },
  { field: 'cabin', label: '7. បិទជិត - Cabin' },
  { field: 'cabinR', label: '' },
  { field: 'cabinP', label: '' },
  { field: 'cabinA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'cabinF', label: '' },
  { field: 'remark', label: 'មតិយោបល់ - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
