export const questions = [
  {
    id: 1,
    name: 'roadSlope',
    question: 'Độ dốc của đường phải nhỏ hơn <10%',
    howto: 'Kiểm tra độ dốc của đường đảm bảo nhỏ hơn 10%.',
    accept: 'Độ dốc của đường phù hợp với yêu cầu.',
  },
  {
    id: 2,
    name: 'roadBends',
    question:
      'Độ nghiêng của đường tại các khúc cua có phù hợp không. Có bờ chắn an toàn không',
    howto:
      'Kiểm tra độ nghiêng của các khúc cua và tình trạng bờ chắn an toàn.',
    accept: 'Các khúc cua có độ nghiêng phù hợp và có bờ chắn an toàn.',
  },
  {
    id: 3,
    name: 'roadSurface',
    question: 'Tình trạng mặt đường có bằng phẳng không?',
    howto: 'Kiểm tra mặt đường có bằng phẳng và không có vật cản.',
    accept: 'Mặt đường phẳng và không có vật cản.',
  },
  {
    id: 4,
    name: 'spilledMaterials',
    question: 'Có vật liệu tràn đổ trên đường không',
    howto: 'Kiểm tra xem có vật liệu tràn đổ trên đường không.',
    accept: 'Không có vật liệu tràn đổ trên đường.',
  },
  {
    id: 5,
    name: 'roadWidth',
    question:
      'Chiều rộng của đường có đảm bảo an toàn cho thiết bị di chuyển không',
    howto:
      'Kiểm tra chiều rộng của đường có đủ rộng cho các thiết bị di chuyển.',
    accept: 'Chiều rộng của đường đảm bảo an toàn cho thiết bị di chuyển.',
  },
  {
    id: 6,
    name: 'drainageDitch',
    question:
      'Có rãnh thoát nước không và tình trạng của rãnh còn đảm bảo thoát nước.',
    howto: 'Kiểm tra rãnh thoát nước và tình trạng thoát nước của rãnh.',
    accept: 'Rãnh thoát nước hoạt động tốt và đảm bảo thoát nước.',
  },
  {
    id: 7,
    name: 'visibility',
    question: 'Tầm nhìn có bị che khuất, hạn chế không',
    howto: 'Kiểm tra tình trạng tầm nhìn có bị che khuất hay hạn chế.',
    accept: 'Tầm nhìn không bị che khuất, hạn chế.',
  },
  {
    id: 8,
    name: 'hopperRamp',
    question:
      'Đường dốc lên phễu và miệng phễu phải có đai an toàn và đai an toàn phải cao hơn hoặc bằng 1/2 đường kính bánh xe?',
    howto: 'Kiểm tra đai an toàn ở phễu và miệng phễu.',
    accept: 'Đai an toàn có độ cao phù hợp và đảm bảo an toàn.',
  },
  {
    id: 9,
    name: 'signalSystem',
    question:
      'Hệ thống tín hiệu biển báo có phù hợp không có bị hư hỏng không.',
    howto: 'Kiểm tra hệ thống tín hiệu và biển báo xem có hư hỏng không.',
    accept: 'Hệ thống tín hiệu và biển báo không bị hư hỏng.',
  },
  {
    id: 10,
    name: 'lightingSystem',
    question: 'Hệ thống đèn chiếu sáng vào ban đêm có phù hợp không',
    howto: 'Kiểm tra hệ thống chiếu sáng vào ban đêm.',
    accept: 'Hệ thống chiếu sáng ban đêm hoạt động tốt.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'Ngày Date' },
  { field: 'email', label: 'Responsible person' },
  { field: 'inspector', label: 'Người kiểm tra Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'roadSlope', label: '1. Độ dốc của đường *' },
  { field: 'roadSlopeR', label: '' },
  { field: 'roadSlopeP', label: '' },
  { field: 'roadSlopeA', label: 'Respond to defect' },
  { field: 'roadSlopeF', label: '' },
  { field: 'roadBends', label: '2. Độ nghiêng của đường tại các khúc cua *' },
  { field: 'roadBendsR', label: '' },
  { field: 'roadBendsP', label: '' },
  { field: 'roadBendsA', label: 'Respond to defect' },
  { field: 'roadBendsF', label: '' },
  { field: 'roadSurface', label: '3. Tình trạng mặt đường *' },
  { field: 'roadSurfaceR', label: '' },
  { field: 'roadSurfaceP', label: '' },
  { field: 'roadSurfaceA', label: 'Respond to defect' },
  { field: 'roadSurfaceF', label: '' },
  { field: 'spilledMaterials', label: '4. Vật liệu tràn đổ trên đường *' },
  { field: 'spilledMaterialsR', label: '' },
  { field: 'spilledMaterialsP', label: '' },
  { field: 'spilledMaterialsA', label: 'Respond to defect' },
  { field: 'spilledMaterialsF', label: '' },
  { field: 'roadWidth', label: '5. Chiều rộng của đường *' },
  { field: 'roadWidthR', label: '' },
  { field: 'roadWidthP', label: '' },
  { field: 'roadWidthA', label: 'Respond to defect' },
  { field: 'roadWidthF', label: '' },
  { field: 'drainageDitch', label: '6. Rãnh thoát nước *' },
  { field: 'drainageDitchR', label: '' },
  { field: 'drainageDitchP', label: '' },
  { field: 'drainageDitchA', label: 'Respond to defect' },
  { field: 'drainageDitchF', label: '' },
  { field: 'visibility', label: '7. Tầm nhìn *' },
  { field: 'visibilityR', label: '' },
  { field: 'visibilityP', label: '' },
  { field: 'visibilityA', label: 'Respond to defect' },
  { field: 'visibilityF', label: '' },
  { field: 'hopperRamp', label: '8. Đường dốc lên phễu *' },
  { field: 'hopperRampR', label: '' },
  { field: 'hopperRampP', label: '' },
  { field: 'hopperRampA', label: 'Respond to defect' },
  { field: 'hopperRampF', label: '' },
  { field: 'signalSystem', label: '9. Hệ thống tín hiệu biển báo *' },
  { field: 'signalSystemR', label: '' },
  { field: 'signalSystemP', label: '' },
  { field: 'signalSystemA', label: 'Respond to defect' },
  { field: 'signalSystemF', label: '' },
  { field: 'lightingSystem', label: '10. Hệ thống đèn chiếu sáng *' },
  { field: 'lightingSystemR', label: '' },
  { field: 'lightingSystemP', label: '' },
  { field: 'lightingSystemA', label: 'Respond to defect' },
  { field: 'lightingSystemF', label: '' },
  { field: 'remark', label: 'Ghi chú Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
