export const questions = [
  {
    id: 1,
    name: 'tax',
    question: 'แผ่นป้ายทะเบียนหน้า-หลัง เครื่องหมายภาษีประจำปี',
    howto: 'สายตา',
    accept: 'สะอาด มองเห็นได้ชัดเจน ไม่หมดอายุ',
  },
  {
    id: 2,
    name: 'guard',
    question: 'การ์ดด้านข้างตัวรถ ',
    howto: 'สายตา / สัมผัส',
    accept: 'ไม่ชำรุด ล็อคแน่น แข็งแรง',
  },
  {
    id: 3,
    name: 'reflective',
    question: 'แถบสะท้อนแสงโดยรอบตัวรถ ',
    howto: 'สายตา',
    accept: 'ไม่ชำรุด ไม่ซีดจาง สะท้อนแสงได้ชัดเจน',
  },
  {
    id: 4,
    name: 'wheelNut',
    question: 'น็อตล้อทุกล้อ ',
    howto: 'สายตา / สัมผัส',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 5,
    name: 'tyre',
    question: 'ยางล้อรถ',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 6,
    name: 'door',
    question: 'ประตูซ้าย-ขวา',
    howto: 'สายตา / สัมผัส',
    accept: 'เปิด ปิด ล็อคได้ ไม่ชำรุด กระจกเลื่อนขึ้นลงได้',
  },
  {
    id: 7,
    name: 'mirror',
    question: 'กระจกมองทุกบาน หน้า-ซ้าย-ขวา-หลัง',
    howto: 'สายตา',
    accept: 'สะอาดใส ไม่แตก ไม่ชำรุด ปรับตำแหน่งได้',
  },
  {
    id: 8,
    name: 'seat',
    question: 'เบาะนั่ง และภายในห้องโดยสาร',
    howto: 'สายตา / สัมผัส',
    accept: 'สะอาด ไม่ฉีกขาด ไม่ชำรุด ติดตั้งมั่นคง',
  },
  {
    id: 9,
    name: 'belt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา / สัมผัส',
    accept: 'กระชับ ปรับได้ ล็อคและปลดล็อคได้',
  },
  {
    id: 10,
    name: 'breakRubber',
    question: 'แป้นเบรก/คันเร่ง',
    howto: 'สายตา',
    accept: 'มียางกันลื่น',
  },
  {
    id: 11,
    name: 'extinguisher',
    question: 'ถังดับเพลิง',
    howto: 'สายตา / สัมผัส',
    accept: 'เกจชี้ในช่องสีเขียว มีเข็มขัดรัดสลัก พร้อมใช้',
  },
  {
    id: 12,
    name: 'fuel',
    question: 'ระดับน้ำมันเชื้อเพลิง',
    howto: 'สายตา',
    accept: 'พร้อมใช้งาน ไม่รั่วซึม',
  },
  {
    id: 13,
    name: 'lub',
    question: 'ระดับน้ำมันเบรค น้ำมันเครื่อง น้ำมันพาวเวอร์ และน้ำหม้อน้ำ',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 14,
    name: 'battery',
    question: 'ขั้วแบตเตอรี่',
    howto: 'สายตา / สัมผัส',
    accept: 'สะอาด ไม่มีคราบสกปรก มีฝาครอบ',
  },
  {
    id: 15,
    name: 'chock',
    question: 'ขอนหนุนล้อ',
    howto: 'สายตา',
    accept: 'ขนาดมาตรฐาน จำนวนครบถ้วน',
  },
  {
    id: 16,
    name: 'ladder',
    question: 'บันไดขึ้น-ลงและราวกันตก',
    howto: 'สายตา / สัมผัส',
    accept: 'ก้าวขึ้น-ลงปลอดภัย มั่นคง',
  },
  {
    id: 17,
    name: 'cone',
    question: 'กรวยยางสะท้อนแสง/แผ่นป้ายสามเหลี่ยมสะท้อนแสง',
    howto: 'สายตา',
    accept: 'สะอาด สะท้อนแสงได้ จำนวนครบถ้วน',
  },
  {
    id: 18,
    name: 'breakChamber',
    question: 'หม้อลมเบรก',
    howto: 'สายตา / สัมผัส',
    accept: 'ไม่มีการต่อแตรลม เป่าลม ไม่มีน้ำ/น้ำมันสะสม',
  },
  {
    id: 19,
    name: 'dashboard',
    question: 'มาตรวัดต่างๆ บนแผงหน้าปัทม์',
    howto: 'สายตา',
    accept: 'แสดงผลปกติเมื่อเปิดสวิทช์กุญแจ',
  },
  {
    id: 20,
    name: 'gear',
    question: 'ระบบส่งกำลัง (ชุดคันเร่ง เกียร์)',
    howto: 'ฟังเสียง / สายตา',
    accept: 'ใช้ได้ปกติ',
  },
  {
    id: 21,
    name: 'breakLight',
    question: 'เบรกมือ เบรกเท้า ไฟเบรก',
    howto: 'สัมผัส / สายตา',
    accept: 'หยุดนิ่ง รถไม่ไหล ไฟติดพร้อมกับเบรกเท้า',
  },
  {
    id: 22,
    name: 'wheel',
    question: 'พวงมาลัย',
    howto: 'สัมผัส',
    accept: 'ไม่สั่นคลอน หมุนซ้าย-ขวา บังคับล้อได้ปกติ',
  },
  {
    id: 23,
    name: 'headLight',
    question: 'ไฟหน้า ไฟท้าย ซ้าย-ขวา-ข้างตัวรถ และไฟส่องป้ายทะเบียน',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 24,
    name: 'turnLight',
    question: 'ไฟเลี้ยว ซ้าย-ขวา-หน้า-หลัง-ข้างตัวรถ',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจน กระพริบเป็นจังหวะทุกดวง',
  },
  {
    id: 25,
    name: 'reverseLight',
    question: 'ไฟถอยหลัง',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 26,
    name: 'airBreak',
    question: 'ระบบลมเบรก',
    howto: 'ฟังเสียง / สายตา',
    accept: 'มีประสิทธิภาพดี ไม่รั่วซึม',
  },
  {
    id: 27,
    name: 'reverseSound',
    question: 'สัญญาณเสียงถอยหลัง',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 28,
    name: 'horn',
    question: 'สัญญาณเสียงแตร',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน ไม่ใช้แตรลม',
  },
  {
    id: 29,
    name: 'alarm',
    question: 'สัญญาณเสียงเตือน และไฟเตือนระดับลมเบรก',
    howto: 'ฟังเสียง / สายตา',
    accept: 'เสียงเตือนดังและไฟติด กรณีลมเบรกต่ำกว่ากำหนด',
  },
  {
    id: 30,
    name: 'whipper',
    question: 'ใบปัดน้ำฝน น้ำฉีดกระจก',
    howto: 'สายตา',
    accept: 'ไม่เสื่อมสภาพ มีน้ำฉีดกระจก',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ Date' },
  { field: 'inspector', label: 'ผู้ตรวจ Inspector' },
  { field: 'tax', label: 'แผ่นป้ายทะเบียนหน้า-หลัง เครื่องหมายภาษีประจำปี' },
  { field: 'taxR', label: '' },
  { field: 'taxP', label: '' },
  { field: 'taxA', label: 'Respond to defect' },
  { field: 'taxF', label: '' },
  { field: 'guard', label: 'การ์ดด้านข้างตัวรถ ' },
  { field: 'guardR', label: '' },
  { field: 'guardP', label: '' },
  { field: 'guardA', label: 'Respond to defect' },
  { field: 'guardF', label: '' },
  { field: 'reflective', label: 'แถบสะท้อนแสงโดยรอบตัวรถ ' },
  { field: 'reflectiveR', label: '' },
  { field: 'reflectiveP', label: '' },
  { field: 'reflectiveA', label: 'Respond to defect' },
  { field: 'reflectiveF', label: '' },
  { field: 'wheelNut', label: 'น็อตล้อทุกล้อ ' },
  { field: 'wheelNutR', label: '' },
  { field: 'wheelNutP', label: '' },
  { field: 'wheelNutA', label: 'Respond to defect' },
  { field: 'wheelNutF', label: '' },
  { field: 'tyre', label: 'ยางล้อรถ' },
  { field: 'tyreR', label: '' },
  { field: 'tyreP', label: '' },
  { field: 'tyreA', label: 'Respond to defect' },
  { field: 'tyreF', label: '' },
  { field: 'door', label: 'ประตูซ้าย-ขวา' },
  { field: 'doorR', label: '' },
  { field: 'doorP', label: '' },
  { field: 'doorA', label: 'Respond to defect' },
  { field: 'doorF', label: '' },
  { field: 'mirror', label: 'กระจกมองทุกบาน หน้า-ซ้าย-ขวา-หลัง' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'seat', label: 'เบาะนั่ง และภายในห้องโดยสาร' },
  { field: 'seatR', label: '' },
  { field: 'seatP', label: '' },
  { field: 'seatA', label: 'Respond to defect' },
  { field: 'seatF', label: '' },
  { field: 'belt', label: 'เข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'breakRubber', label: 'แป้นเบรก/คันเร่ง' },
  { field: 'breakRubberR', label: '' },
  { field: 'breakRubberP', label: '' },
  { field: 'breakRubberA', label: 'Respond to defect' },
  { field: 'breakRubberF', label: '' },
  { field: 'extinguisher', label: 'ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'fuel', label: 'ระดับน้ำมันเชื้อเพลิง' },
  { field: 'fuelR', label: '' },
  { field: 'fuelP', label: '' },
  { field: 'fuelA', label: 'Respond to defect' },
  { field: 'fuelF', label: '' },
  {
    field: 'lub',
    label: 'ระดับน้ำมันเบรค น้ำมันเครื่อง น้ำมันพาวเวอร์ และน้ำหม้อน้ำ',
  },
  { field: 'lubR', label: '' },
  { field: 'lubP', label: '' },
  { field: 'lubA', label: 'Respond to defect' },
  { field: 'lubF', label: '' },
  { field: 'battery', label: 'ขั้วแบตเตอรี่' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
