export const questions = [
  {
    id: 1,
    name: 'brakeOil',
    question: 'ตรวจสอบน้ำมันเบรก',
    howto: 'สายตา/ประเมิน',
    accept: 'สภาพสี ความขุ่นของน้ำมันเบรก และระดับของน้ำมันเบรก',
  },
  {
    id: 2,
    name: 'brakeHose',
    question: 'ตรวจสอบสภาพท่อยางเบรก',
    howto: 'สายตา/ประเมิน',
    accept: 'ตรวจเช็คสภาพการพับงอ บิด บวมตัวเสียรูป รอยฉีกขาด รั่วซึม',
  },
  {
    id: 3,
    name: 'airLeak',
    question: 'ตรวจสอบสภาพการรั่วซึมของระบบลม',
    howto: 'สายตา/ประเมิน',
    accept: 'ตรวจเช็คการรั่วซึมของลมเบรก ไม่มีเสียงลมรั่ว',
  },
  {
    id: 4,
    name: 'warningLights',
    question: 'ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คความสมบูรณ์ของระบบควบคุม เช่น เกจความดันลม ไฟเตือน',
  },
  {
    id: 5,
    name: 'clutch',
    question: 'ตรวจสภาพระบบคลัช',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คระยะฟรีขาเหยียบคลัชช์ และการลื่นไถลของคลัทช์',
  },
  {
    id: 6,
    name: 'hydraulicHose',
    question: 'ตรวจสายไฮดรอลิค',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็ครอยแตกของสาย รอยรั่ว หรือการเสื่อมสภาพของจุดต่อรั่วซึม',
  },
  {
    id: 7,
    name: 'steeringBearings',
    question: 'ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คการหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 8,
    name: 'tieRod',
    question: 'ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย-ขวา)',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คการหมุนของพวงมาลัย ระยะฟรีพวงมาลัย',
  },
  {
    id: 9,
    name: 'tyres',
    question: 'ตรวจสภาพยางทุกเส้น',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คความสึกหรอ รอยแตกของผิวแก้มยาง(ทุกเส้น)',
  },
  {
    id: 10,
    name: 'rimsAndNuts',
    question: 'ตรวจสอบสภาพกระทะล้อ และน็อตล้อ',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คการแตกร้าว, รอยขาดของน็อตล้อ หลุดหาย (ทุกล้อ)',
  },
  {
    id: 11,
    name: 'headlightsHorn',
    question: 'ตรวจสภาพไฟหน้า/แตรสัญญาณ',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คความสมบูรณ์พร้อมใช้งานของไฟหน้า และแตร',
  },
  {
    id: 12,
    name: 'brakeTailLights',
    question: 'ตรวจสภาพไฟท้าย / ไฟเบรก',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คความความพร้อมใช้งานของไฟท้าย/ไฟเบรก, สัญญาณเสียงถอย',
  },
  {
    id: 13,
    name: 'turnSignals',
    question: 'ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คความความพร้อมใช้งานของไฟเลี้ยว / ไฟด้านข้าง',
  },
  {
    id: 14,
    name: 'tailgate',
    question: 'ตรวจเช็คฝาท้าย / ปากนกแก้ว',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept:
      'ตรวจเช็คฝาท้ายปิดสนิท, ไม่ล้า, ล็อกได้สนิททุกตัว ไม่มีการรั่วไหลของแร่',
  },
  {
    id: 15,
    name: 'coupling',
    question: 'ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ตรวจเช็คสภาพการสึกหรอ รอยแตก รอยร้าว ของสลัก',
  },
  {
    id: 16,
    name: 'licensePlate',
    question: 'แผ่นป้ายทะเบียน',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ครบ สะอาดมองเห็นชัดเจน ไม่เลือนลาง และเป็นป้ายที่ทางราชการออกให้',
  },
  {
    id: 17,
    name: 'wheelChocks',
    question: 'ตรวจสอบอุปกรณ์หนุนล้อ',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'ขนาด 6×6×9 นิ้วพร้อมใช้งาน (2 อันรถบรรทุก 4 อันรถบรรทุกพ่วง)',
  },
  {
    id: 18,
    name: 'canvas',
    question: 'ตรวจสอบผ้าใบ',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'สภาพผ้าใบไม่ฉีกขาด ปิดสนิทคลุมกระบะบรรทุก',
  },
  {
    id: 19,
    name: 'trafficCones',
    question: 'ตรวจสอบกรวยจราจร/สามเหลี่ยมสะท้อนแสง',
    howto: 'สายตา / สัมผัส /ประเมิน',
    accept: 'สภาพสมบูรณ์มีแถบสะท้อนแสง, ไม่สกปรก, สีไม่ซีด',
  },
  {
    id: 20,
    name: 'fireExtinguisher',
    question: 'ตรวจสอบถังดับเพลิง',
    howto: 'ฟังเสียง / สายตา / ประเมิน',
    accept: 'สภาพพร้อมใช้งาน เกจวัดแรงดันชี้โซนสีเขียว อายุไม่เกิน 5 ปี',
  },
  {
    id: 21,
    name: 'taxSticker',
    question: 'เครื่องหมายเสียภาษี/ พรบ/ ป้ายประกอบการ',
    howto: 'สัมผัส / สายตา',
    accept: 'ตรวจเช็คสภาพไม่ฉีกขาดมองเห็นชัดเจน, ไม่หมดอายุ',
  },
  {
    id: 22,
    name: 'gps',
    question: 'ระบบ GPS',
    howto: 'สัมผัส',
    accept: 'พร้อมใช้งานมีเสียงหรือแสงเตือนกรณีความเร็วเกินกำหนด',
  },
  {
    id: 23,
    name: 'camera',
    question: 'กล้องติดตั้งหน้ารถ',
    howto: 'สายตา / สัมผัส / ประเมิน',
    accept: 'พร้อมใช้งานตลอดเวลา',
  },
  {
    id: 24,
    name: 'seatbelt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา / ประเมิน',
    accept: 'พร้อมใช้งานตลอดเวลา',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'brakeOil', label: '1. ตรวจสอบน้ำมันเบรก' },
  { field: 'brakeOilR', label: '' },
  { field: 'brakeOilP', label: '' },
  { field: 'brakeOilA', label: 'Respond to defect' },
  { field: 'brakeOilF', label: '' },
  { field: 'brakeHose', label: '2. ตรวจสอบสภาพท่อยางเบรก' },
  { field: 'brakeHoseR', label: '' },
  { field: 'brakeHoseP', label: '' },
  { field: 'brakeHoseA', label: 'Respond to defect' },
  { field: 'brakeHoseF', label: '' },
  { field: 'airLeak', label: '3. ตรวจสอบสภาพการรั่วซึมของระบบลม' },
  { field: 'airLeakR', label: '' },
  { field: 'airLeakP', label: '' },
  { field: 'airLeakA', label: 'Respond to defect' },
  { field: 'airLeakF', label: '' },
  { field: 'warningLights', label: '4. ตรวจสภาพไฟหน้าปัดเตือนระบบทำงานต่างๆ' },
  { field: 'warningLightsR', label: '' },
  { field: 'warningLightsP', label: '' },
  { field: 'warningLightsA', label: 'Respond to defect' },
  { field: 'warningLightsF', label: '' },
  { field: 'clutch', label: '5. ตรวจสภาพระบบคลัช' },
  { field: 'clutchR', label: '' },
  { field: 'clutchP', label: '' },
  { field: 'clutchA', label: 'Respond to defect' },
  { field: 'clutchF', label: '' },
  { field: 'hydraulicHose', label: '6. ตรวจสายไฮดรอลิค' },
  { field: 'hydraulicHoseR', label: '' },
  { field: 'hydraulicHoseP', label: '' },
  { field: 'hydraulicHoseA', label: 'Respond to defect' },
  { field: 'hydraulicHoseF', label: '' },
  { field: 'steeringBearings', label: '7. ตรวจสภาพลูกปืนคันชัก (หน้า - หลัง)' },
  { field: 'steeringBearingsR', label: '' },
  { field: 'steeringBearingsP', label: '' },
  { field: 'steeringBearingsA', label: 'Respond to defect' },
  { field: 'steeringBearingsF', label: '' },
  { field: 'tieRod', label: '8. ตรวจสอบสภาพลูกหมากคันส่ง (ซ้าย-ขวา)' },
  { field: 'tieRodR', label: '' },
  { field: 'tieRodP', label: '' },
  { field: 'tieRodA', label: 'Respond to defect' },
  { field: 'tieRodF', label: '' },
  { field: 'tyres', label: '9. ตรวจสภาพยางทุกเส้น' },
  { field: 'tyresR', label: '' },
  { field: 'tyresP', label: '' },
  { field: 'tyresA', label: 'Respond to defect' },
  { field: 'tyresF', label: '' },
  { field: 'rimsAndNuts', label: '10. ตรวจสอบสภาพกระทะล้อ และน็อตล้อ' },
  { field: 'rimsAndNutsR', label: '' },
  { field: 'rimsAndNutsP', label: '' },
  { field: 'rimsAndNutsA', label: 'Respond to defect' },
  { field: 'rimsAndNutsF', label: '' },
  { field: 'headlightsHorn', label: '11. ตรวจสภาพไฟหน้า/แตรสัญญาณ' },
  { field: 'headlightsHornR', label: '' },
  { field: 'headlightsHornP', label: '' },
  { field: 'headlightsHornA', label: 'Respond to defect' },
  { field: 'headlightsHornF', label: '' },
  { field: 'brakeTailLights', label: '12. ตรวจสภาพไฟท้าย / ไฟเบรก' },
  { field: 'brakeTailLightsR', label: '' },
  { field: 'brakeTailLightsP', label: '' },
  { field: 'brakeTailLightsA', label: 'Respond to defect' },
  { field: 'brakeTailLightsF', label: '' },
  { field: 'turnSignals', label: '13. ตรวจสภาพไฟเลี้ยว / ไฟด้านข้าง' },
  { field: 'turnSignalsR', label: '' },
  { field: 'turnSignalsP', label: '' },
  { field: 'turnSignalsA', label: 'Respond to defect' },
  { field: 'turnSignalsF', label: '' },
  { field: 'tailgate', label: '14. ตรวจเช็คฝาท้าย / ปากนกแก้ว' },
  { field: 'tailgateR', label: '' },
  { field: 'tailgateP', label: '' },
  { field: 'tailgateA', label: 'Respond to defect' },
  { field: 'tailgateF', label: '' },
  { field: 'coupling', label: '15. ตรวจสอบสลักยึดพ่วงระหว่างตัวรถและพ่วง' },
  { field: 'couplingR', label: '' },
  { field: 'couplingP', label: '' },
  { field: 'couplingA', label: 'Respond to defect' },
  { field: 'couplingF', label: '' },
  { field: 'licensePlate', label: '16. แผ่นป้ายทะเบียน' },
  { field: 'licensePlateR', label: '' },
  { field: 'licensePlateP', label: '' },
  { field: 'licensePlateA', label: 'Respond to defect' },
  { field: 'licensePlateF', label: '' },
  { field: 'wheelChocks', label: '17. ตรวจสอบอุปกรณ์หนุนล้อ' },
  { field: 'wheelChocksR', label: '' },
  { field: 'wheelChocksP', label: '' },
  { field: 'wheelChocksA', label: 'Respond to defect' },
  { field: 'wheelChocksF', label: '' },
  { field: 'canvas', label: '18. ตรวจสอบผ้าใบ' },
  { field: 'canvasR', label: '' },
  { field: 'canvasP', label: '' },
  { field: 'canvasA', label: 'Respond to defect' },
  { field: 'canvasF', label: '' },
  { field: 'trafficCones', label: '19. ตรวจสอบกรวยจราจร/สามเหลี่ยมสะท้อนแสง' },
  { field: 'trafficConesR', label: '' },
  { field: 'trafficConesP', label: '' },
  { field: 'trafficConesA', label: 'Respond to defect' },
  { field: 'trafficConesF', label: '' },
  { field: 'fireExtinguisher', label: '20. ตรวจสอบถังดับเพลิง' },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  { field: 'taxSticker', label: '21. เครื่องหมายเสียภาษี/ พรบ/ ป้ายประกอบการ' },
  { field: 'taxStickerR', label: '' },
  { field: 'taxStickerP', label: '' },
  { field: 'taxStickerA', label: 'Respond to defect' },
  { field: 'taxStickerF', label: '' },
  { field: 'gps', label: '22. ระบบ GPS' },
  { field: 'gpsR', label: '' },
  { field: 'gpsP', label: '' },
  { field: 'gpsA', label: 'Respond to defect' },
  { field: 'gpsF', label: '' },
  { field: 'camera', label: '23. กล้องติดตั้งหน้ารถ' },
  { field: 'cameraR', label: '' },
  { field: 'cameraP', label: '' },
  { field: 'cameraA', label: 'Respond to defect' },
  { field: 'cameraF', label: '' },
  { field: 'seatbelt', label: '24. เข็มขัดนิรภัย' },
  { field: 'seatbeltR', label: '' },
  { field: 'seatbeltP', label: '' },
  { field: 'seatbeltA', label: 'Respond to defect' },
  { field: 'seatbeltF', label: '' },
  { field: 'remark', label: 'หมายเหตุ - Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
