export const questions = [
  {
    id: 1,
    name: 'tyre',
    question: 'น็อตล้อ ลมยาง สภาพยาง',
    howto: 'ตรวจสภาพยาง ดอกยาง และลมยาง',
    accept:
      'ลมยางปกติ ยางไม่มีรอยบาด ฉีกยาวเกิน 2 ซ.ม. ยางไม่มีรอยบวมนูน ดอกยางลึกไม่น้อยกว่า 1.6 ม.ม. (ไม่ถึงสะพานยาง)',
  },
  {
    id: 2,
    name: 'engine',
    question: 'เครื่องยนต์ และท่อไอเสีย',
    howto:
      'การรอยรั่วซึมของน้ำมันเครื่อง และน้ำมันต่างๆ, เสียงเครื่องยนต์ไม่ดังผิดปกติ และตรวจสอบสภาพควัน และเสียงที่ท่อไอเสียรถ',
    accept:
      'ไม่มีรอยน้ำมันต่างๆรั่วซึมออกมา, ไม่มีเสียงดังผิดปกติจากเครื่องยนต์/ท่อไอเสีย, และไม่มีควันขาวจากท่อไอเสียรถ',
  },
  {
    id: 3,
    name: 'battery',
    question: 'แบตเตอรี่',
    howto: 'ตรวจสภาพของขั้วแบตเตอรี่',
    accept: 'ไม่มีคราบเกลือที่ขั้วแบตเตอรี่, แบตเตอรี่ไม่บวม',
  },
  {
    id: 4,
    name: 'guage',
    question: 'มาตรวัดความเร็ว และระบบไฟเตือน',
    howto:
      'ตรวจสภาพมาตรวัด, เมื่อหมุนสวิตซ์กุญแจไปยังตำแหน่ง ON หรือเมื่อกดปุ่ม Push Start ไฟแสงสว่างสำหรับอ่านค่า และไฟสัญญาณเตือนที่แผงหน้าปัทม์ต่างๆ ปรากฏครบเป็นปกติ',
    accept:
      'ไม่ชำรุด ทำงานได้ตามปกติ และไฟสัญญาณที่แผงหน้าปัทม์ติดแสดงเครื่องหมายต่างๆครบ',
  },
  {
    id: 5,
    name: 'whipper',
    question: 'เครื่องปัดน้ำฝน',
    howto: 'ตรวจสอบสภาพอุปกรณ์และการทำงาน / ระดับน้ำกระบอกฉีดกระจก',
    accept:
      'สวิตช์ทำงานได้ตามปกติ สามารถปัดและฉีดน้ำได้ / ยางปัดน้ำฝนสามารถปาดได้เรียบ / ระดับน้ำในกระบอกน้ำฉีดกระจกอยู่ในระดับปกติ',
  },
  {
    id: 6,
    name: 'horn',
    question: 'แตร/กริ่งสัญญาณ',
    howto: 'กดแตร/กริ่งสัญญาณ',
    accept: 'มีเสียงดังชัดเจน',
  },
  {
    id: 7,
    name: 'lamp',
    question: 'ไฟส่องสว่าง(ไฟหน้า)',
    howto: 'ตรวจสภาพโคมไฟ ตรวจการทำงานโดยการเปิดสวิตช์',
    accept:
      'มีภาพดี ไม่แตกร้าว หรือชำรุด สวิตช์ควบคุมการทำงาน และโคมไฟทำงานได้ตามปกติ',
  },
  {
    id: 8,
    name: 'tail',
    question: 'ไฟถอยหลัง ไฟท้าย ไฟเบรค',
    howto: 'ตรวจสภาพโคมไฟ ตรวจการทำงานโดยการเปิดสวิตช์',
    accept:
      'มีภาพดี ไม่แตกร้าว หรือชำรุด สวิตช์ควบคุมการทำงาน และโคมไฟทำงานได้ตามปกติ',
  },
  {
    id: 9,
    name: 'turn',
    question: 'สัญญาณ(ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน)',
    howto: 'เปิดสวิชท์ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน*',
    accept: 'แสงไฟกระพริบเป็นจังหวะปกติทุกดวง',
  },
  {
    id: 10,
    name: 'mirror',
    question: 'กระจกหน้า, กระจกมองหลัง และ กระจกมองข้าง',
    howto:
      'ดูสภาพความสะอาด ไม่มีรอยแตกร้าวหรือมีอุปสรรคในการมองเห็น ของกระจกทุกบาน และการปรับทิศทางของกระจกมองข้าง',
    accept:
      'กระจกทุกบาน สะอาด ไม่มีรอยแตกร้าวหรือมีอุปสรรคในการมองเห็น, กระจกมองข้างไม่หลวมและปรับมองตำแหน่งได้ชัดเจน',
  },
  {
    id: 11,
    name: 'belt',
    question: 'อุปกรณ์ป้องกันภัยเข็มขัดนิรภัย',
    howto: 'ดึงและกระตุก',
    accept: 'เลื่อนได้สะดวกและล็อคเมื่อมีแรงกระชาก',
  },
  {
    id: 12,
    name: 'bump',
    question: 'สภาพโดยรวมทั่วไป และกันชน',
    howto:
      'ดูสภาพโดยรวมไม่มีสิ่งใดเป็นอุปสรรคต่อการขับขี่ และตรวจสภาพกันชนและการติดตั้งต้องมั่นคงแข็งแรง ไม่ชำรุด ผุกร่อน หรือฉีกขาด',
    accept:
      'สะอาด,สภาพโดยรวมสามารถใช้งานได้อย่างปลอดภัยในการขับขี่ และกันชนไม่ชำรุด ผุกร่อน ฉีกขาด ติดตั้งได้อย่างมั่นคงแข็งแรง',
  },
  {
    id: 13,
    name: 'breakSys',
    question: 'ระบบเบรค',
    howto: 'เหยียบแป้นเบรคและ/หรือบีบเบรคมือ',
    accept: 'มีแรงดันตอบสนองการเบรคโดยทันที',
  },
  {
    id: 14,
    name: 'camera',
    question: 'กล้องบันทึกภาพหน้ารถ',
    howto: 'เปิดดูไฟล์วีดีโอย้อนหลังจากเครื่องบันทึก',
    accept: 'มีไฟล์วีดีโอบันทึกไว้ตลอดเวลา',
  },
  {
    id: 15,
    name: 'extinguisher',
    question: 'ถังดับเพลิง',
    howto: 'ตรวจสอบมาตรวัด/สลักและดูสภาพโดยรวม',
    accept: 'เข็มอยู่ในโซนสีเขียว, สลักอยู่ครบ, มีสารเคมีภายใน',
  },
  {
    id: 16,
    name: 'reverseCam',
    question: 'กล้องมองถอยหลัง',
    howto: 'เมื่อเข้าเกียร์ถอยหลัง(R) กล้องสามารถแสดงภาพด้านหลังรถได้ตามปกติ',
    accept: 'สามารถใช้งานได้ปกติ ภาพที่ปรากฏบนจอแสดงผลชัดเจน',
  },
  {
    id: 17,
    name: 'sensor',
    question: 'สัญญาณถอยหลัง (Sensor)',
    howto:
      'เมื่อถอยหลังเข้าใกล้สิ่งกีดขวาง มีเสียงสัญญาณเตือนปกติ ไม่มีเสียงสัญญาณดังเตือนค้าง',
    accept:
      'มีเสียงสัญญาณเตือนดังปกติ และไม่มีเสียงสัญญาณเตือนดังค้างเมื่อถอยรถ',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'mileage', label: 'เลขไมล์ Mileage' },
  { field: 'tyre', label: '1. น็อตล้อ ลมยาง สภาพยาง' },
  { field: 'tyreR', label: '' },
  { field: 'tyreP', label: '' },
  { field: 'tyreA', label: 'Respond to defect' },
  { field: 'tyreF', label: '' },
  { field: 'engine', label: '2. เครื่องยนต์ และท่อไอเสีย' },
  { field: 'engineR', label: '' },
  { field: 'engineP', label: '' },
  { field: 'engineA', label: 'Respond to defect' },
  { field: 'engineF', label: '' },
  { field: 'battery', label: '3. แบตเตอรี่' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'gauge', label: '4. มาตรวัดความเร็ว และระบบไฟเตือน' },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'Respond to defect' },
  { field: 'gaugeF', label: '' },
  { field: 'whipper', label: '5. เครื่องปัดน้ำฝน' },
  { field: 'whipperR', label: '' },
  { field: 'whipperP', label: '' },
  { field: 'whipperA', label: 'Respond to defect' },
  { field: 'whipperF', label: '' },
  { field: 'horn', label: '6. แตร/กริ่งสัญญาณ' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'lamp', label: '7. ไฟส่องสว่าง(ไฟหน้า)' },
  { field: 'lampR', label: '' },
  { field: 'lampP', label: '' },
  { field: 'lampA', label: 'Respond to defect' },
  { field: 'lampF', label: '' },
  { field: 'tail', label: '8. ไฟถอยหลัง ไฟท้าย ไฟเบรค' },
  { field: 'tailR', label: '' },
  { field: 'tailP', label: '' },
  { field: 'tailA', label: 'Respond to defect' },
  { field: 'tailF', label: '' },
  { field: 'turn', label: '9. สัญญาณ(ไฟเลี้ยว,ไฟเบรค,ไฟฉุกเฉิน)' },
  { field: 'turnR', label: '' },
  { field: 'turnP', label: '' },
  { field: 'turnA', label: 'Respond to defect' },
  { field: 'turnF', label: '' },
  { field: 'mirror', label: '10. กระจกหน้า, กระจกมองหลัง และ กระจกมองข้าง' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'belt', label: '11. อุปกรณ์ป้องกันภัยเข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'bump', label: '12. สภาพโดยรวมทั่วไป และกันชน' },
  { field: 'bumpR', label: '' },
  { field: 'bumpP', label: '' },
  { field: 'bumpA', label: 'Respond to defect' },
  { field: 'bumpF', label: '' },
  { field: 'breakSys', label: '13. ระบบเบรค' },
  { field: 'breakSysR', label: '' },
  { field: 'breakSysP', label: '' },
  { field: 'breakSysA', label: 'Respond to defect' },
  { field: 'breakSysF', label: '' },
  { field: 'camera', label: '14. กล้องบันทึกภาพหน้ารถ' },
  { field: 'cameraR', label: '' },
  { field: 'cameraP', label: '' },
  { field: 'cameraA', label: 'Respond to defect' },
  { field: 'cameraF', label: '' },
  { field: 'extinguisher', label: '15. ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'reverseCam', label: '16. กล้องมองถอยหลัง' },
  { field: 'reverseCamR', label: '' },
  { field: 'reverseCamP', label: '' },
  { field: 'reverseCamA', label: 'Respond to defect' },
  { field: 'reverseCamF', label: '' },
  { field: 'sensor', label: '17. สัญญาณถอยหลัง (Sensor)' },
  { field: 'sensorR', label: '' },
  { field: 'sensorP', label: '' },
  { field: 'sensorA', label: 'Respond to defect' },
  { field: 'sensorF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
