export const questions = [
  {
    id: 1,
    name: 'fallArrestMechanism',
    question: 'ตรวจสอบระบบกลไกการหยุดการตก เช่น ตัวยึด (Tethers) หรือกลไกดึงกลับ (Retractors) ว่าสามารถทำงานได้อย่างเหมาะสม',
    howto: 'ทดสอบการใช้งานกลไกโดยการดึง-ปล่อยเบา ๆ และตรวจสอบการทำงาน',
    accept: 'กลไกทำงานได้ราบรื่น ไม่มีการติดขัดหรือหลวม',
  },
  {
    id: 2,
    name: 'wireStrapConnection',
    question: 'ตรวจสอบจุดเชื่อมต่อระหว่างลวดกับสายรัด ว่ามีความแข็งแรงและไม่มีความเสียหาย',
    howto: 'ตรวจสอบด้วยสายตาและสัมผัส ตรวจดูรอยขาดหรือจุดอ่อน',
    accept: 'จุดเชื่อมต่อแน่น ไม่มีรอยขาด หลวม หรือแตกหัก',
  },
  {
    id: 3,
    name: 'carabinerDringCondition',
    question: 'ตรวจสอบสลักและฮาร์ดแวร์ (Carabiners, D-Rings) ว่าสามารถล็อคได้ดี และไม่มีการสึกหรอ',
    howto: 'ทดสอบการล็อกและปลดด้วยมือ พร้อมตรวจสอบสภาพภายนอก',
    accept: 'ล็อกได้มั่นคง ไม่มีสนิม หรือร่องรอยการสึกหรอ',
  },
  {
    id: 4,
    name: 'strapEquipmentConnection',
    question: 'ตรวจสอบจุดเชื่อมต่อสายรัดและอุปกรณ์อื่น ๆ ว่ามีการยึดติดอย่างแน่นหนา',
    howto: 'ใช้สายตาและมือจับตรวจสอบการยึดติด',
    accept: 'ไม่มีการหลุดหรือคลอน การยึดติดแข็งแรง',
  },
  {
    id: 5,
    name: 'anchorPointIntegrity',
    question: 'ตรวจสอบจุดยึดที่ติดตั้งว่าแข็งแรงและทนทาน ไม่มีการสึกหรอหรือชำรุด',
    howto: 'ตรวจสอบด้วยสายตาและมือ พร้อมทดสอบการโยกเบา ๆ',
    accept: 'จุดยึดแน่นหนา ไม่หลุด ไม่บิดงอ หรือแตกหัก',
  },
  {
    id: 6,
    name: 'anchorLockTest',
    question: 'ลองล็อกอุปกรณ์เข้ากับจุดยึดเพื่อตรวจสอบความแน่นหนา',
    howto: 'ใช้อุปกรณ์ล็อกเข้ากับจุดยึดแล้วดึงเบา ๆ ทดสอบการยึด',
    accept: 'การล็อกแน่นหนา ไม่มีการหลุดหรือคลอน',
  },
  {
    id: 7,
    name: 'wearRustLoosenCheck',
    question: 'ตรวจสอบว่าไม่มีการสึกหรอ สนิม หรือการโยกคลอน',
    howto: 'สังเกตด้วยสายตาและจับโยกอุปกรณ์เบา ๆ',
    accept: 'ไม่มีสนิม การสึกหรอ หรืออาการโยกคลอน',
  },
  {
    id: 8,
    name: 'ropeGrabSmoothness',
    question: 'กลไกการเลื่อน (สำหรับ Rope Grab) เคลื่อนขึ้น-ลงได้ลื่น ไม่ติดขัด',
    howto: 'เลื่อนอุปกรณ์ขึ้นลงตามสายทดสอบการลื่นไหล',
    accept: 'เลื่อนได้ลื่น ไม่มีสะดุด หรือติดขัด',
  },
  {
    id: 9,
    name: 'autoLockBrakeTest',
    question: 'ตัวล็อกอัตโนมัติหรือระบบเบรกทำงานได้สมบูรณ์ (ทดสอบโดยการกระตุกเบา ๆ)',
    howto: 'กระตุกสายเบา ๆ เพื่อดูการตอบสนองของระบบเบรก',
    accept: 'ระบบตอบสนองทันทีเมื่อกระตุก ไม่มีความล่าช้าหรือขัดข้อง',
  }
];


export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'fallArrestMechanism', label: '1. ตรวจสอบระบบกลไกการหยุดการตก เช่น ตัวยึด (Tethers) หรือกลไกดึงกลับ (Retractors) ว่าสามารถทำงานได้อย่างเหมาะสม' },
  { field: 'fallArrestMechanismR', label: '' },
  { field: 'fallArrestMechanismP', label: '' },
  { field: 'fallArrestMechanismA', label: 'Respond to defect' },
  { field: 'fallArrestMechanismF', label: '' },
  { field: 'wireStrapConnection', label: '2. ตรวจสอบจุดเชื่อมต่อระหว่างลวดกับสายรัด ว่ามีความแข็งแรงและไม่มีความเสียหาย' },
  { field: 'wireStrapConnectionR', label: '' },
  { field: 'wireStrapConnectionP', label: '' },
  { field: 'wireStrapConnectionA', label: 'Respond to defect' },
  { field: 'wireStrapConnectionF', label: '' },
  { field: 'carabinerDringCondition', label: '3. ตรวจสอบสลักและฮาร์ดแวร์ (Carabiners, D-Rings) ว่าสามารถล็อคได้ดี และไม่มีการสึกหรอ' },
  { field: 'carabinerDringConditionR', label: '' },
  { field: 'carabinerDringConditionP', label: '' },
  { field: 'carabinerDringConditionA', label: 'Respond to defect' },
  { field: 'carabinerDringConditionF', label: '' },
  { field: 'strapEquipmentConnection', label: '4. ตรวจสอบจุดเชื่อมต่อสายรัดและอุปกรณ์อื่น ๆ ว่ามีการยึดติดอย่างแน่นหนา' },
  { field: 'strapEquipmentConnectionR', label: '' },
  { field: 'strapEquipmentConnectionP', label: '' },
  { field: 'strapEquipmentConnectionA', label: 'Respond to defect' },
  { field: 'strapEquipmentConnectionF', label: '' },
  { field: 'anchorPointIntegrity', label: '5. ตรวจสอบจุดยึดที่ติดตั้งว่าแข็งแรงและทนทาน ไม่มีการสึกหรอหรือชำรุด' },
  { field: 'anchorPointIntegrityR', label: '' },
  { field: 'anchorPointIntegrityP', label: '' },
  { field: 'anchorPointIntegrityA', label: 'Respond to defect' },
  { field: 'anchorPointIntegrityF', label: '' },
  { field: 'anchorLockTest', label: '6. ลองล็อกอุปกรณ์เข้ากับจุดยึดเพื่อตรวจสอบความแน่นหนา' },
  { field: 'anchorLockTestR', label: '' },
  { field: 'anchorLockTestP', label: '' },
  { field: 'anchorLockTestA', label: 'Respond to defect' },
  { field: 'anchorLockTestF', label: '' },
  { field: 'wearRustLoosenCheck', label: '7. ตรวจสอบว่าไม่มีการสึกหรอ สนิม หรือการโยกคลอน' },
  { field: 'wearRustLoosenCheckR', label: '' },
  { field: 'wearRustLoosenCheckP', label: '' },
  { field: 'wearRustLoosenCheckA', label: 'Respond to defect' },
  { field: 'wearRustLoosenCheckF', label: '' },
  { field: 'ropeGrabSmoothness', label: '8. กลไกการเลื่อน (สำหรับ Rope Grab) เคลื่อนขึ้น-ลงได้ลื่น ไม่ติดขัด' },
  { field: 'ropeGrabSmoothnessR', label: '' },
  { field: 'ropeGrabSmoothnessP', label: '' },
  { field: 'ropeGrabSmoothnessA', label: 'Respond to defect' },
  { field: 'ropeGrabSmoothnessF', label: '' },
  { field: 'autoLockBrakeTest', label: '9. ตัวล็อกอัตโนมัติหรือระบบเบรกทำงานได้สมบูรณ์ (ทดสอบโดยการกระตุกเบา ๆ)' },
  { field: 'autoLockBrakeTestR', label: '' },
  { field: 'autoLockBrakeTestP', label: '' },
  { field: 'autoLockBrakeTestA', label: 'Respond to defect' },
  { field: 'autoLockBrakeTestF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];

