export const questions = [
  {
    id: 1,
    name: 'labelCheck',
    question: 'ป้ายชื่อ, โหลดสูงสุด, รุ่น และหมายเลขซีเรียลชัดเจน',
    howto: 'ใช้สายตาตรวจสอบป้ายข้อมูลบนตัวอุปกรณ์',
    accept: 'ข้อมูลทุกอย่างบนป้ายชัดเจน ครบถ้วน อ่านได้ง่าย',
  },
  {
    id: 2,
    name: 'bodyDamageCheck',
    question: 'ตัวเครื่องไม่มีการแตกร้าว, บุบ หรือเสียหาย',
    howto: 'ตรวจสอบภายนอกของตัวเครื่องด้วยสายตาและสัมผัส',
    accept: 'ไม่มีรอยแตกร้าว บุบ หรือชิ้นส่วนเสียหาย',
  },
  {
    id: 3,
    name: 'cleanlinessCheck',
    question: 'อุปกรณ์ไม่มีคราบน้ำมัน, สนิม, หรือเศษวัสดุสะสม',
    howto: 'ใช้สายตาสำรวจทั่วทั้งอุปกรณ์',
    accept: 'อุปกรณ์สะอาด ปราศจากคราบน้ำมัน สนิม และสิ่งสกปรก',
  },
  {
    id: 4,
    name: 'latchCondition',
    question: 'ตัวล็อกนิรภัย (Latch) อยู่ในสภาพใช้งานและปิดได้สนิท',
    howto: 'ทดลองเปิด-ปิด latch ด้วยมือ',
    accept: 'ล็อกแน่นหนา ปิดได้สนิท ไม่หลวม ไม่ฝืด',
  },
  {
    id: 5,
    name: 'chainSlingCheck',
    question: 'โซ่หรือสลิงไม่มีรอยแตก, ขาด, หรือการยืดผิดปกติ',
    howto: 'ใช้สายตาตรวจตลอดแนวโซ่หรือสลิง และลองดึงเบา ๆ',
    accept: 'ไม่มีรอยขาด รอยแตก หรือความยืดยาวผิดปกติ',
  },
  {
    id: 6,
    name: 'hookDamageCheck',
    question: 'ตรวจสอบ ตะขอ (Hook) ไม่มีการบิดเบี้ยว รอยแตก หรือการสึกหรอเกินกำหนด',
    howto: 'ตรวจสอบด้วยสายตาและสัมผัส พร้อมเทียบกับสเปก',
    accept: 'ตะขออยู่ในสภาพดี ไม่มีบิดเบี้ยว แตก หรือสึกหรอเกินเกณฑ์',
  },
  {
    id: 7,
    name: 'hookLatchFunction',
    question: 'ตรวจสอบว่า ตัวล็อกนิรภัย (Safety Latch) ที่ตะขอทำงานปกติ',
    howto: 'ทดลองเปิด-ปิด latch ที่ตะขอ',
    accept: 'ล็อกทำงานได้อย่างลื่นไหล ไม่มีติดขัด',
  },
  {
    id: 8,
    name: 'liftTestEmpty',
    question: 'ทดสอบการ ยก-ลด โหลดเปล่าให้แน่ใจว่าเครื่องยกได้ลื่นไหล ไม่มีเสียงผิดปกติ',
    howto: 'ทดลองสั่งยกและลดโหลดเปล่า',
    accept: 'การเคลื่อนที่ลื่น ไม่มีเสียงดังหรืออาการกระตุก',
  },
  {
    id: 9,
    name: 'swlVerification',
    question: 'ตรวจสอบว่า Hoist ยกน้ำหนักได้ภายในกำหนด SWL (Safe Working Load)',
    howto: 'ตรวจสอบน้ำหนักโหลดที่ใช้และเทียบกับ SWL ที่ระบุไว้',
    accept: 'โหลดที่ใช้ไม่เกิน SWL และยกได้อย่างปลอดภัย',
  },
  {
    id: 10,
    name: 'areaSafetyCheck',
    question: 'พื้นที่รอบจุดใช้งาน Hoist ปลอดภัย ไม่มีสิ่งกีดขวาง',
    howto: 'สำรวจบริเวณรอบจุดใช้งาน',
    accept: 'ไม่มีสิ่งกีดขวาง พื้นที่สะอาดและปลอดภัยในการใช้งาน',
  }
];


export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'labelCheck', label: '1. ป้ายชื่อ, โหลดสูงสุด, รุ่น และหมายเลขซีเรียลชัดเจน' },
  { field: 'labelCheckR', label: '' },
  { field: 'labelCheckP', label: '' },
  { field: 'labelCheckA', label: 'Respond to defect' },
  { field: 'labelCheckF', label: '' },
  { field: 'bodyDamageCheck', label: '2. ตัวเครื่องไม่มีการแตกร้าว, บุบ หรือเสียหาย' },
  { field: 'bodyDamageCheckR', label: '' },
  { field: 'bodyDamageCheckP', label: '' },
  { field: 'bodyDamageCheckA', label: 'Respond to defect' },
  { field: 'bodyDamageCheckF', label: '' },
  { field: 'cleanlinessCheck', label: '3. อุปกรณ์ไม่มีคราบน้ำมัน, สนิม, หรือเศษวัสดุสะสม' },
  { field: 'cleanlinessCheckR', label: '' },
  { field: 'cleanlinessCheckP', label: '' },
  { field: 'cleanlinessCheckA', label: 'Respond to defect' },
  { field: 'cleanlinessCheckF', label: '' },
  { field: 'latchCondition', label: '4. ตัวล็อกนิรภัย (Latch) อยู่ในสภาพใช้งานและปิดได้สนิท' },
  { field: 'latchConditionR', label: '' },
  { field: 'latchConditionP', label: '' },
  { field: 'latchConditionA', label: 'Respond to defect' },
  { field: 'latchConditionF', label: '' },
  { field: 'chainSlingCheck', label: '5. โซ่หรือสลิงไม่มีรอยแตก, ขาด, หรือการยืดผิดปกติ' },
  { field: 'chainSlingCheckR', label: '' },
  { field: 'chainSlingCheckP', label: '' },
  { field: 'chainSlingCheckA', label: 'Respond to defect' },
  { field: 'chainSlingCheckF', label: '' },
  { field: 'hookDamageCheck', label: '6. ตะขอ (Hook) ไม่มีการบิดเบี้ยว รอยแตก หรือการสึกหรอเกินกำหนด' },
  { field: 'hookDamageCheckR', label: '' },
  { field: 'hookDamageCheckP', label: '' },
  { field: 'hookDamageCheckA', label: 'Respond to defect' },
  { field: 'hookDamageCheckF', label: '' },
  { field: 'hookLatchFunction', label: '7. ตัวล็อกนิรภัย (Safety Latch) ที่ตะขอทำงานปกติ' },
  { field: 'hookLatchFunctionR', label: '' },
  { field: 'hookLatchFunctionP', label: '' },
  { field: 'hookLatchFunctionA', label: 'Respond to defect' },
  { field: 'hookLatchFunctionF', label: '' },
  { field: 'liftTestEmpty', label: '8. ทดสอบการ ยก-ลด โหลดเปล่าให้แน่ใจว่าเครื่องยกได้ลื่นไหล ไม่มีเสียงผิดปกติ' },
  { field: 'liftTestEmptyR', label: '' },
  { field: 'liftTestEmptyP', label: '' },
  { field: 'liftTestEmptyA', label: 'Respond to defect' },
  { field: 'liftTestEmptyF', label: '' },
  { field: 'swlVerification', label: '9. ตรวจสอบว่า Hoist ยกน้ำหนักได้ภายในกำหนด SWL (Safe Working Load)' },
  { field: 'swlVerificationR', label: '' },
  { field: 'swlVerificationP', label: '' },
  { field: 'swlVerificationA', label: 'Respond to defect' },
  { field: 'swlVerificationF', label: '' },
  { field: 'areaSafetyCheck', label: '10. พื้นที่รอบจุดใช้งาน Hoist ปลอดภัย ไม่มีสิ่งกีดขวาง' },
  { field: 'areaSafetyCheckR', label: '' },
  { field: 'areaSafetyCheckP', label: '' },
  { field: 'areaSafetyCheckA', label: 'Respond to defect' },
  { field: 'areaSafetyCheckF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];

