export const questions = [
  {
    id: 1,
    name: 'waterPipe',
    question: 'ท่อน้ำ',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่มีรั่วซึม',
  },
  {
    id: 2,
    name: 'waterBasin',
    question: 'อ่างรับน้ำ',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่แตกร้าว ไม่มีน้ำขัง',
  },
  {
    id: 3,
    name: 'shower',
    question: 'ฝักบัว',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่ชำรุด ไม่อุดตัน',
  },
  {
    id: 4,
    name: 'eyeWashShower',
    question: 'ฝักบัวล้างตา',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่ชำรุด ไม่อุดตัน ต้องมีฝาครอบปิด',
  },
  {
    id: 5,
    name: 'waterPressure',
    question: 'แรงดันน้ำ',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ต้องสูงเพียงพอ เพื่อให้น้ำไหลเข้าตา',
  },
  {
    id: 6,
    name: 'waterValve',
    question: 'วาล์วน้ำ',
    howto: 'ตรวจสอบด้วยสายตา / สัมผัส',
    accept:
      'ต้องยังคงเปิดและรักษาอัตราการไหลของน้ำสม่ำเสมอ โดยไม่ต้องใช้มือเปิด',
  },
  {
    id: 7,
    name: 'waterReplacement',
    question: 'เปลี่ยนถ่ายน้ำ',
    howto: 'ตรวจสอบด้วยสัมผัส',
    accept: 'เปลี่ยนน้ำ',
  },
  {
    id: 8,
    name: 'cleanliness',
    question: 'ความสะอาด',
    howto: 'ตรวจสอบด้วยสายตา / สัมผัส',
    accept: 'อุปกรณ์สะอาด ไม่มีคราบสกปรก',
  },
  {
    id: 9,
    name: 'obstructionSignage',
    question: 'สิ่งกีดขวาง/ป้ายชี้บ่ง',
    howto: 'ตรวจสอบด้วยสายตา',
    accept:
      'ไม่มีสิ่งกีดขวาง สามารถเข้าถึงได้อย่างทันท่วงที / ป้ายชี้บ่งมองเห็นได้อย่างชัดเจน',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'waterPipe', label: '1. ท่อน้ำ' },
  { field: 'waterPipeR', label: '' },
  { field: 'waterPipeP', label: '' },
  { field: 'waterPipeA', label: 'Respond to defect' },
  { field: 'waterPipeF', label: '' },
  { field: 'waterBasin', label: '2. อ่างรับน้ำ' },
  { field: 'waterBasinR', label: '' },
  { field: 'waterBasinP', label: '' },
  { field: 'waterBasinA', label: 'Respond to defect' },
  { field: 'waterBasinF', label: '' },
  { field: 'shower', label: '3. ฝักบัว' },
  { field: 'showerR', label: '' },
  { field: 'showerP', label: '' },
  { field: 'showerA', label: 'Respond to defect' },
  { field: 'showerF', label: '' },
  { field: 'eyeWashShower', label: '4. ฝักบัวล้างตา' },
  { field: 'eyeWashShowerR', label: '' },
  { field: 'eyeWashShowerP', label: '' },
  { field: 'eyeWashShowerA', label: 'Respond to defect' },
  { field: 'eyeWashShowerF', label: '' },
  { field: 'waterPressure', label: '5. แรงดันน้ำ' },
  { field: 'waterPressureR', label: '' },
  { field: 'waterPressureP', label: '' },
  { field: 'waterPressureA', label: 'Respond to defect' },
  { field: 'waterPressureF', label: '' },
  { field: 'waterValve', label: '6. วาล์วน้ำ' },
  { field: 'waterValveR', label: '' },
  { field: 'waterValveP', label: '' },
  { field: 'waterValveA', label: 'Respond to defect' },
  { field: 'waterValveF', label: '' },
  { field: 'waterChange', label: '7. เปลี่ยนถ่ายน้ำ' },
  { field: 'waterChangeR', label: '' },
  { field: 'waterChangeP', label: '' },
  { field: 'waterChangeA', label: 'Respond to defect' },
  { field: 'waterChangeF', label: '' },
  { field: 'cleanliness', label: '8. ความสะอาด' },
  { field: 'cleanlinessR', label: '' },
  { field: 'cleanlinessP', label: '' },
  { field: 'cleanlinessA', label: 'Respond to defect' },
  { field: 'cleanlinessF', label: '' },
  { field: 'obstructionSign', label: '9. สิ่งกีดขวาง/ป้ายชี้บ่ง' },
  { field: 'obstructionSignR', label: '' },
  { field: 'obstructionSignP', label: '' },
  { field: 'obstructionSignA', label: 'Respond to defect' },
  { field: 'obstructionSignF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
