export const questions = [
  {
    id: 1,
    name: 'steeringCondition',
    question: 'Steering condition* (স্টিয়ারিং অবস্থা)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'স্টিয়ারিং সিস্টেম সঠিক এবং কার্যকর অবস্থায় আছে',
  },
  {
    id: 2,
    name: 'tyreCondition',
    question: 'Tyre condition* (টায়ারের অবস্থা)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত টায়ার সঠিক এবং নিরাপদ আছে',
  },
  {
    id: 3,
    name: 'seatBelts',
    question: 'Seat belts* (সীট বেল্ট)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত সীট বেল্ট সঠিক এবং কার্যকর অবস্থায় আছে',
  },
  {
    id: 4,
    name: 'mirrors',
    question: 'Mirrors (মিরররস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'আয়নাগুলি পরিষ্কার, সামঞ্জস্যযোগ্য এবং ফাটল মুক্ত হওয়া উচিত।',
  },
  {
    id: 5,
    name: 'waterOilLevel',
    question: 'Water/oil level (ওয়াটার/অয়েল লেভেল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'পানি এবং তেলের মাত্রা নির্দিষ্ট সীমার মধ্যে হওয়া উচিত।',
  },
  {
    id: 6,
    name: 'brakeFluid',
    question: 'Brake fluid (ব্রেক ফ্লুইড)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'ব্রেক তরল উপযুক্ত মাত্রায় এবং দূষিত না হওয়া উচিত।',
  },
  {
    id: 7,
    name: 'powerSteeringFluid',
    question: 'Power steering fluid (পাওয়ার স্টিয়ারিং ফ্লুইড)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'পাওয়ার স্টিয়ারিং তরল সঠিক মাত্রায় এবং পরিষ্কার থাকা উচিত।',
  },
  {
    id: 8,
    name: 'gaugesWorking',
    question: 'Gauges working (গাউজেস ওয়ার্কিং)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত গেজগুলি ঠিকভাবে কাজ করা উচিত',
  },
  {
    id: 9,
    name: 'indicators',
    question: 'Indicators (ইন্ডিকেটরস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত ইন্ডিকেটরগুলি কার্যকর হওয়া উচিত',
  },
  {
    id: 10,
    name: 'headParkLights',
    question: 'Head/park lights (হেড/পার্ক লাইটস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'হেডলাইট এবং পার্ক লাইটগুলি কাজ করা এবং সঠিকভাবে সামঞ্জস্যপূর্ণ হওয়া উচিত',
  },
  {
    id: 11,
    name: 'tailStopLights',
    question: 'Tail/stop lights* (টেইল/স্টপ লাইটস)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'সমস্ত টেল এবং স্টপ লাইটগুলি কার্যকর এবং ক্ষতিমুক্ত হওয়া উচিত',
  },
  {
    id: 12,
    name: 'brakesHandFoot',
    question: 'Brakes hand/foot* (ব্র্যাক্স হাত/পা)',
    howto: 'দৃষ্টিগত এবং কার্যকরী পরীক্ষা',
    accept: 'হ্যান্ড এবং ফুট ব্রেকগুলি সঠিকভাবে এবং কার্যকরভাবে কাজ করা উচিত',
  },
  {
    id: 13,
    name: 'wipersWasher',
    question: 'Wipers/washer (ওইপার্স/ওয়াশার)',
    howto: 'কার্যকরী পরীক্ষা',
    accept:
      'ওয়াইপার এবং ওয়াশার সঠিকভাবে কাজ করা এবং ওয়াশার তরলের পরিমাণ যথেষ্ট হওয়া উচিত',
  },
  {
    id: 14,
    name: 'horn',
    question: 'Horn* (হর্ন)',
    howto: 'কার্যকরী পরীক্ষা',
    accept: 'হর্নের শব্দ স্পষ্ট এবং সঠিক আওয়াজে হওয়া উচিত',
  },
  {
    id: 15,
    name: 'firstAidKit',
    question:
      'First Aid Kit (vehicles in public areas) (প্রাথমিক চিকিৎসার সরঞ্জাম)',
    howto: 'মজুদ পরীক্ষা',
    accept:
      'প্রাথমিক চিকিৎসা কিট উপস্থিত, সিলমোহরযুক্ত এবং সমস্ত প্রয়োজনীয় জিনিস সম্বলিত হওয়া উচিত',
  },
  {
    id: 16,
    name: 'safetyTriangle',
    question: 'Safety Triangle (সেফটি ট্রায়াঙ্গল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'নিরাপত্তা ত্রিভুজ উপস্থিত এবং ব্যবহারযোগ্য অবস্থায় হওয়া উচিত',
  },
  {
    id: 17,
    name: 'jack',
    question: 'Jack (জ্যাক)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'জ্যাক উপস্থিত এবং ভালো কাজ করা অবস্থায় হওয়া উচিত',
  },
  {
    id: 18,
    name: 'wheelSpanner',
    question: 'Wheel spanner (হুইল স্প্যানার)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'হুইল স্প্যানার সঠিক আকারের এবং ভালো অবস্থায় হওয়া উচিত',
  },
  {
    id: 19,
    name: 'jackHandle',
    question: 'Jack handle (জ্যাক হ্যান্ডেল)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'জ্যাক হ্যান্ডেল উপস্থিত থাকা উচিত এবং ঠিকভাবে জ্যাকের সাথে মানানসই হওয়া উচিত',
  },
  {
    id: 20,
    name: 'rotaryFlashLamp',
    question: 'Rotary/ Flash lamp (রোটারি/ ফ্ল্যাশ ল্যাম্প)',
    howto: 'Functional test',
    accept: 'রোটারি/ফ্ল্যাশ ল্যাম্প কার্যকর এবং দৃশ্যমান হওয়া উচিত',
  },
  {
    id: 21,
    name: 'reflectiveStrip',
    question: 'Reflective Strip (রিফ্লেক্টিভ স্ট্রিপ)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept:
      'রিফ্লেক্টিভ স্ট্রিপ পরিষ্কার, অক্ষত, এবং ঠিকভাবে যানবাহনের সাথে সংযুক্ত থাকা উচিত',
  },
  {
    id: 22,
    name: 'vehicleNumbers',
    question: 'Vehicle Numbers (গাড়ির নম্বর)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'গাড়ির নম্বরগুলি স্পষ্টভাবে দৃশ্যমান এবং পাঠযোগ্য হওয়া উচিত',
  },
  {
    id: 23,
    name: 'communicationRadio',
    question: 'Communication radio (যোগাযোগ রেডিও)',
    howto: 'দৃষ্টিগত পরিদর্শন',
    accept: 'যোগাযোগ রেডিও সঠিকভাবে কাজ করছে এবং সঠিকভাবে সংযুক্ত আছে',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'তারিখঃ - Date' },
  { field: 'inspector', label: 'পরিদর্শক - Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'steeringCondition',
    label: 'Steering condition - স্টিয়ারিং অবস্থা',
  },
  { field: 'steeringConditionR', label: '' },

  { field: 'steeringConditionP', label: '' },
  { field: 'steeringConditionA', label: 'Respond to defect' },
  { field: 'steeringConditionF', label: '' },
  { field: 'tyreCondition', label: 'Tyre condition - টায়ারের অবস্থা' },
  { field: 'tyreConditionR', label: '' },
  { field: 'tyreConditionP', label: '' },
  { field: 'tyreConditionA', label: 'Respond to defect' },
  { field: 'tyreConditionF', label: '' },
  { field: 'seatBelts', label: 'Seat belts - সীট বেল্ট' },
  { field: 'seatBeltsR', label: '' },
  { field: 'seatBeltsP', label: '' },
  { field: 'seatBeltsA', label: 'Respond to defect' },
  { field: 'seatBeltsF', label: '' },
  { field: 'mirrors', label: 'Mirrors - মিরররস' },
  { field: 'mirrorsR', label: '' },
  { field: 'mirrorsP', label: '' },
  { field: 'mirrorsA', label: 'Respond to defect' },
  { field: 'mirrorsF', label: '' },
  { field: 'waterOilLevel', label: 'Water/oil level - ওয়াটার/অয়েল লেভেল' },
  { field: 'waterOilLevelR', label: '' },
  { field: 'waterOilLevelP', label: '' },
  { field: 'waterOilLevelA', label: 'Respond to defect' },
  { field: 'waterOilLevelF', label: '' },
  { field: 'brakeFluid', label: 'Brake fluid - ব্রেক ফ্লুইড' },
  { field: 'brakeFluidR', label: '' },
  { field: 'brakeFluidP', label: '' },
  { field: 'brakeFluidA', label: 'Respond to defect' },
  { field: 'brakeFluidF', label: '' },
  {
    field: 'powerSteeringFluid',
    label: 'Power steering fluid - পাওয়ার স্টিয়ারিং ফ্লুইড',
  },
  { field: 'powerSteeringFluidR', label: '' },
  { field: 'powerSteeringFluidP', label: '' },
  { field: 'powerSteeringFluidA', label: 'Respond to defect' },
  { field: 'powerSteeringFluidF', label: '' },
  { field: 'gaugesWorking', label: 'Gauges working - গাউজেস ওয়ার্কিং' },
  { field: 'gaugesWorkingR', label: '' },
  { field: 'gaugesWorkingP', label: '' },
  { field: 'gaugesWorkingA', label: 'Respond to defect' },
  { field: 'gaugesWorkingF', label: '' },
  { field: 'indicators', label: 'Indicators - ইন্ডিকেটরস' },
  { field: 'indicatorsR', label: '' },
  { field: 'indicatorsP', label: '' },
  { field: 'indicatorsA', label: 'Respond to defect' },
  { field: 'indicatorsF', label: '' },
  { field: 'headParkLights', label: 'Head/park lights - হেড/পার্ক লাইটস' },
  { field: 'headParkLightsR', label: '' },
  { field: 'headParkLightsP', label: '' },
  { field: 'headParkLightsA', label: 'Respond to defect' },
  { field: 'headParkLightsF', label: '' },
  { field: 'tailStopLights', label: 'Tail/stop lights - টেইল/স্টপ লাইটস' },
  { field: 'tailStopLightsR', label: '' },
  { field: 'tailStopLightsP', label: '' },
  { field: 'tailStopLightsA', label: 'Respond to defect' },
  { field: 'tailStopLightsF', label: '' },
  { field: 'brakesHandFoot', label: 'Brakes hand/foot - ব্র্যাক্স হাত/পা' },
  { field: 'brakesHandFootR', label: '' },
  { field: 'brakesHandFootP', label: '' },
  { field: 'brakesHandFootA', label: 'Respond to defect' },
  { field: 'brakesHandFootF', label: '' },
  { field: 'wipersWasher', label: 'Wipers/washer - ওইপার্স/ওয়াশার' },
  { field: 'wipersWasherR', label: '' },
  { field: 'wipersWasherP', label: '' },
  { field: 'wipersWasherA', label: 'Respond to defect' },
  { field: 'wipersWasherF', label: '' },
  { field: 'horn', label: 'Horn - হর্ন' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'firstAidKit', label: 'First Aid Kit - প্রাথমিক চিকিৎসার সরঞ্জাম' },
  { field: 'firstAidKitR', label: '' },
  { field: 'firstAidKitP', label: '' },
  { field: 'firstAidKitA', label: 'Respond to defect' },
  { field: 'firstAidKitF', label: '' },
  { field: 'safetyTriangle', label: 'Safety Triangle - সেফটি ট্রায়াঙ্গল' },
  { field: 'safetyTriangleR', label: '' },
  { field: 'safetyTriangleP', label: '' },
  { field: 'safetyTriangleA', label: 'Respond to defect' },
  { field: 'safetyTriangleF', label: '' },
  { field: 'jack', label: 'Jack - জ্যাক' },
  { field: 'jackR', label: '' },
  { field: 'jackP', label: '' },
  { field: 'jackA', label: 'Respond to defect' },
  { field: 'jackF', label: '' },
  { field: 'wheelSpanner', label: 'Wheel spanner - হুইল স্প্যানার' },
  { field: 'wheelSpannerR', label: '' },
  { field: 'wheelSpannerP', label: '' },
  { field: 'wheelSpannerA', label: 'Respond to defect' },
  { field: 'wheelSpannerF', label: '' },
  { field: 'jackHandle', label: 'Jack handle - জ্যাক হ্যান্ডেল' },
  { field: 'jackHandleR', label: '' },
  { field: 'jackHandleP', label: '' },
  { field: 'jackHandleA', label: 'Respond to defect' },
  { field: 'jackHandleF', label: '' },
  {
    field: 'rotaryFlashLamp',
    label: 'Rotary/ Flash lamp - রোটারি/ ফ্ল্যাশ ল্যাম্প',
  },
  { field: 'rotaryFlashLampR', label: '' },
  { field: 'rotaryFlashLampP', label: '' },
  { field: 'rotaryFlashLampA', label: 'Respond to defect' },
  { field: 'rotaryFlashLampF', label: '' },
  { field: 'reflectiveStrip', label: 'Reflective Strip - রিফ্লেক্টিভ স্ট্রিপ' },
  { field: 'reflectiveStripR', label: '' },
  { field: 'reflectiveStripP', label: '' },
  { field: 'reflectiveStripA', label: 'Respond to defect' },
  { field: 'reflectiveStripF', label: '' },
  { field: 'vehicleNumbers', label: 'Vehicle Numbers - গাড়ির নম্বর' },
  { field: 'vehicleNumbersR', label: '' },
  { field: 'vehicleNumbersP', label: '' },
  { field: 'vehicleNumbersA', label: 'Respond to defect' },
  { field: 'vehicleNumbersF', label: '' },
  { field: 'communicationRadio', label: 'Communication radio - যোগাযোগ রেডিও' },
  { field: 'communicationRadioR', label: '' },
  { field: 'communicationRadioP', label: '' },
  { field: 'communicationRadioA', label: 'Respond to defect' },
  { field: 'communicationRadioF', label: '' },
  { field: 'remark', label: 'মন্তব্য - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
