export const questions = [
  {
    id: 1,
    name: 'forkliftCondition',
    question: 'ෆෝර්ක්ලීෆ්ට් තත්වය',
    howto:
      'ෆෝර්ක්ලීෆ්ට් පද්ධතිය පරීක්ෂා කරන්න, බර භාරගැනීමේ හැකියාව සහ ආරක්ෂාව පිළිබඳ විමසුමක් කරන්න.',
    accept: 'ෆෝර්ක්ලීෆ්ට් තත්වය සාමාන්‍යය පවතී.',
  },
  {
    id: 2,
    name: 'brakesTest',
    question: 'පැඩල් පරීක්ෂාව',
    howto:
      'පැඩල් පද්ධතිය පරීක්ෂා කරන්න. පැඩල් නිවැරදිව ක්‍රියා කරයි කියලා තහවුරු කරන්න.',
    accept: 'පැඩල් පද්ධතිය සාමාන්‍ය ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 3,
    name: 'engineCondition',
    question: 'එන්ජිම තත්වය',
    howto:
      'එන්ජිමක් පරීක්ෂා කරන්න. එම එන්ජිම විශේෂයෙන් ඉතාම බලවත්, අඛණ්ඩ ක්‍රියා කරයි කියලා තහවුරු කරන්න.',
    accept: 'එන්ජිම සුපිරි තත්වයේ පවතී.',
  },
  {
    id: 4,
    name: 'emergencyBrake',
    question: 'අවසන් පැඩල්',
    howto:
      'අවසාන පැඩල් පද්ධතිය පරීක්ෂා කරන්න, අනතුරුකාරී අවස්ථාවක හෝ එය ක්‍රියාත්මක වන බව.',
    accept: 'අවසාන පැඩල් පද්ධතිය ක්‍රියාත්මක වේ.',
  },
  {
    id: 5,
    name: 'lightsFunction',
    question: 'ආලෝක පද්ධතිය',
    howto: 'ෆෝර්ක්ලීෆ්ට්හි ආලෝක පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'ආලෝක පද්ධතිය නිවැරදිව ක්‍රියා කරයි.',
  },
  {
    id: 6,
    name: 'hornCheck',
    question: 'හෝන් පරීක්ෂාව',
    howto: 'හෝන් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'හෝන් පද්ධතිය සාමාන්‍ය ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 7,
    name: 'seatBeltCheck',
    question: 'ආසන සහ ආරක්ෂක බෙල්ට්',
    howto: 'ආසන සහ ආරක්ෂක බෙල්ට් වල ක්‍රියාත්මක බව පරීක්ෂා කරන්න.',
    accept: 'ආසන සහ බෙල්ට් හොඳ තත්ත්වයෙන් පවතී.',
  },
  {
    id: 8,
    name: 'fuelSystemTest',
    question: 'ඇණුම් පද්ධතිය',
    howto: 'ඇණුම් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'ඇණුම් පද්ධතිය සාමාන්‍යය පවතී.',
  },
  {
    id: 9,
    name: 'hydraulicSystem',
    question: 'හයිඩ්රොලික් පද්ධතිය',
    howto: 'හයිඩ්රොලික් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'හයිඩ්රොලික් පද්ධතිය සාමාන්‍ය පවතී.',
  },
  {
    id: 10,
    name: 'batteryStatus',
    question: 'බැටරි තත්වය',
    howto: 'බැටරි පරීක්ෂා කරන්න.',
    accept: 'බැටරි සාමාන්‍ය ලෙස පවතී.',
  },
  {
    id: 11,
    name: 'oilLevel',
    question: 'තෙල් මට්ටම',
    howto: 'තෙල් මට්ටම පරීක්ෂා කරන්න.',
    accept: 'තෙල් මට්ටම සාමාන්‍යය පවතී.',
  },
  {
    id: 12,
    name: 'cableCondition',
    question: 'කේබල් තත්වය',
    howto: 'කේබල් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'කේබල් පද්ධතිය සුපිරි තත්වයේ පවතී.',
  },
  {
    id: 13,
    name: 'steeringSystem',
    question: 'සමඟ පාලක පද්ධතිය',
    howto: 'සමඟ පාලක පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'සමඟ පාලක පද්ධතිය නිවැරදිව ක්‍රියා කරයි.',
  },
  {
    id: 14,
    name: 'forkCondition',
    question: 'පොරෝන තත්වය',
    howto: 'පොරෝන පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'පොරෝන පද්ධතිය හොඳ තත්වයෙන් පවතී.',
  },
  {
    id: 15,
    name: 'brakeFluid',
    question: 'පැඩල් වාත පද්ධතිය',
    howto: 'පැඩල් වාත පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'පැඩල් වාත පද්ධතිය සුපිරි තත්වය පවතී.',
  },
  {
    id: 16,
    name: 'tyreCondition',
    question: 'ටයර් තත්වය',
    howto: 'ටයර් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'ටයර් තත්වය හොඳ පවතී.',
  },
  {
    id: 17,
    name: 'coolantCheck',
    question: 'කූලන්ට් පද්ධතිය',
    howto: 'කූලන්ට් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'කූලන්ට් පද්ධතිය සාමාන්‍ය ය.',
  },
  {
    id: 18,
    name: 'clutchTest',
    question: 'කලට් පද්ධතිය',
    howto: 'කලට් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'කලට් පද්ධතිය සාමාන්‍ය ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 19,
    name: 'transmission',
    question: 'සංක්‍රමණ පද්ධතිය',
    howto: 'සංක්‍රමණ පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'සංක්‍රමණ පද්ධතිය සාමාන්‍ය ක්‍රියාකාරී වේ.',
  },
  {
    id: 20,
    name: 'suspension',
    question: 'සස්පෙන්ෂන් පද්ධතිය',
    howto: 'සස්පෙන්ෂන් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'සස්පෙන්ෂන් පද්ධතිය නිවැරදි ලෙස ක්‍රියා කරයි.',
  },
  {
    id: 21,
    name: 'radiatorCondition',
    question: 'රේඩියටර් තත්වය',
    howto: 'රේඩියටර් පද්ධතිය පරීක්ෂා කරන්න.',
    accept: 'රේඩියටර් පද්ධතිය හොඳ තත්වය පවතී.',
  },
  {
    id: 22,
    name: 'inspectionChecklist',
    question: 'පරීක්ෂාවන් වාර්තා පත්‍රය',
    howto: 'සෑම පරීක්ෂාවක් මත, වාර්තා පත්‍රය පරීක්ෂා කරන්න.',
    accept: 'අවශ්‍ය සියළුම පරීක්ෂා කර ඇත.',
  },
  {
    id: 23,
    name: 'maintenanceCheck',
    question: 'අලුත්වැඩියාව පරීක්ෂාව',
    howto: 'අලුත්වැඩියාවක් කිරීම පරීක්ෂා කරන්න.',
    accept: 'අලුත්වැඩියා කටයුතු නිවැරදිව සිදු කර ඇත.',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'දිනය Date' },
  { field: 'email', label: 'වගකීම භාරකරු Responsible person' },
  { field: 'inspector', label: 'පරීක්ෂක / Inspector' },
  { field: 'responder', label: 'ප්‍රතිචාරකයා Responder' },

  { field: 'forkliftCondition', label: '1. ෆෝර්ක්ලීෆ්ට් තත්වය *' },
  { field: 'forkliftConditionR', label: '' },
  { field: 'forkliftConditionP', label: '' },
  {
    field: 'forkliftConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'forkliftConditionF', label: '' },

  { field: 'brakesTest', label: '2. පැඩල් පරීක්ෂාව *' },
  { field: 'brakesTestR', label: '' },
  { field: 'brakesTestP', label: '' },
  { field: 'brakesTestA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'brakesTestF', label: '' },

  { field: 'engineCondition', label: '3. එන්ජිම තත්වය *' },
  { field: 'engineConditionR', label: '' },
  { field: 'engineConditionP', label: '' },
  {
    field: 'engineConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'engineConditionF', label: '' },

  { field: 'emergencyBrake', label: '4. අවසන් පැඩල් *' },
  { field: 'emergencyBrakeR', label: '' },
  { field: 'emergencyBrakeP', label: '' },
  {
    field: 'emergencyBrakeA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'emergencyBrakeF', label: '' },

  { field: 'lightsFunction', label: '5. ආලෝක පද්ධතිය *' },
  { field: 'lightsFunctionR', label: '' },
  { field: 'lightsFunctionP', label: '' },
  {
    field: 'lightsFunctionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'lightsFunctionF', label: '' },

  { field: 'hornCheck', label: '6. හෝන් පරීක්ෂාව *' },
  { field: 'hornCheckR', label: '' },
  { field: 'hornCheckP', label: '' },
  { field: 'hornCheckA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'hornCheckF', label: '' },

  { field: 'seatBeltCheck', label: '7. ආසන සහ ආරක්ෂක බෙල්ට් *' },
  { field: 'seatBeltCheckR', label: '' },
  { field: 'seatBeltCheckP', label: '' },
  {
    field: 'seatBeltCheckA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'seatBeltCheckF', label: '' },

  { field: 'fuelSystemTest', label: '8. ඇණුම් පද්ධතිය *' },
  { field: 'fuelSystemTestR', label: '' },
  { field: 'fuelSystemTestP', label: '' },
  {
    field: 'fuelSystemTestA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'fuelSystemTestF', label: '' },

  { field: 'hydraulicSystem', label: '9. හයිඩ්රොලික් පද්ධතිය *' },
  { field: 'hydraulicSystemR', label: '' },
  { field: 'hydraulicSystemP', label: '' },
  {
    field: 'hydraulicSystemA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'hydraulicSystemF', label: '' },

  { field: 'batteryStatus', label: '10. බැටරි තත්වය *' },
  { field: 'batteryStatusR', label: '' },
  { field: 'batteryStatusP', label: '' },
  {
    field: 'batteryStatusA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'batteryStatusF', label: '' },

  { field: 'oilLevel', label: '11. තෙල් මට්ටම *' },
  { field: 'oilLevelR', label: '' },
  { field: 'oilLevelP', label: '' },
  { field: 'oilLevelA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'oilLevelF', label: '' },

  { field: 'cableCondition', label: '12. කේබල් තත්වය *' },
  { field: 'cableConditionR', label: '' },
  { field: 'cableConditionP', label: '' },
  {
    field: 'cableConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'cableConditionF', label: '' },

  { field: 'steeringSystem', label: '13. සමඟ පාලක පද්ධතිය *' },
  { field: 'steeringSystemR', label: '' },
  { field: 'steeringSystemP', label: '' },
  {
    field: 'steeringSystemA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'steeringSystemF', label: '' },

  { field: 'forkCondition', label: '14. පොරෝන තත්වය *' },
  { field: 'forkConditionR', label: '' },
  { field: 'forkConditionP', label: '' },
  {
    field: 'forkConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'forkConditionF', label: '' },

  { field: 'brakeFluid', label: '15. පැඩල් වාත පද්ධතිය *' },
  { field: 'brakeFluidR', label: '' },
  { field: 'brakeFluidP', label: '' },
  { field: 'brakeFluidA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'brakeFluidF', label: '' },

  { field: 'tyreCondition', label: '16. ටයර් තත්වය *' },
  { field: 'tyreConditionR', label: '' },
  { field: 'tyreConditionP', label: '' },
  {
    field: 'tyreConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'tyreConditionF', label: '' },

  { field: 'coolantCheck', label: '17. කූලන්ට් පද්ධතිය *' },
  { field: 'coolantCheckR', label: '' },
  { field: 'coolantCheckP', label: '' },
  {
    field: 'coolantCheckA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'coolantCheckF', label: '' },

  { field: 'clutchTest', label: '18. කලට් පද්ධතිය *' },
  { field: 'clutchTestR', label: '' },
  { field: 'clutchTestP', label: '' },
  { field: 'clutchTestA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'clutchTestF', label: '' },

  { field: 'transmission', label: '19. සංක්‍රමණ පද්ධතිය *' },
  { field: 'transmissionR', label: '' },
  { field: 'transmissionP', label: '' },
  {
    field: 'transmissionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'transmissionF', label: '' },

  { field: 'suspension', label: '20. සස්පෙන්ෂන් පද්ධතිය *' },
  { field: 'suspensionR', label: '' },
  { field: 'suspensionP', label: '' },
  { field: 'suspensionA', label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect' },
  { field: 'suspensionF', label: '' },

  { field: 'radiatorCondition', label: '21. රේඩියටර් තත්වය *' },
  { field: 'radiatorConditionR', label: '' },
  { field: 'radiatorConditionP', label: '' },
  {
    field: 'radiatorConditionA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'radiatorConditionF', label: '' },

  { field: 'inspectionChecklist', label: '22. පරීක්ෂාවන් වාර්තා පත්‍රය *' },
  { field: 'inspectionChecklistR', label: '' },
  { field: 'inspectionChecklistP', label: '' },
  {
    field: 'inspectionChecklistA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'inspectionChecklistF', label: '' },

  { field: 'maintenanceCheck', label: '23. අලුත්වැඩියාව පරීක්ෂාව *' },
  { field: 'maintenanceCheckR', label: '' },
  { field: 'maintenanceCheckP', label: '' },
  {
    field: 'maintenanceCheckA',
    label: 'දෝෂයට ප්‍රතිචාරය දක්වන්න Respond to defect',
  },
  { field: 'maintenanceCheckF', label: '' },
  { field: 'remark', label: 'සටහන Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
