export const questions = [
  {
    id: 1,
    name: 'machinePlacement',
    question: 'พื้นที่วางเครื่อง / การติดตั้งประกอบ',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ติดตั้งถูกต้อง ไม่มีสิ่งกีดขวาง',
  },
  {
    id: 2,
    name: 'structure',
    question: 'โครงสร้างอุปกรณ์ ฝาปิด ประตู หูยก ตัวล็อค',
    howto: 'ตรวจสอบด้วยสายตา',
    accept: 'ไม่มีความเสียหาย',
  },
  {
    id: 3,
    name: 'wiring',
    question: 'สภาพสายไฟ ขนาดสายไฟ การกวดขันแน่น',
    howto: 'ตรวจสอบด้วยสายตาและสัมผัส',
    accept: 'สายไฟไม่มีรอยชำรุด กวดขันแน่น',
  },
  {
    id: 4,
    name: 'switches',
    question: 'ปุ่มสวิตช์ต่างๆมีภาษาไทยกำกับ ไม่ชำรุด',
    howto: 'ทดสอบการใช้งาน',
    accept: 'ปุ่มใช้งานได้และมีฉลากภาษาไทย',
  },
  {
    id: 5,
    name: 'hpwjPump',
    question: 'ปั้ม HPWJ. ไม่รั่วซึม',
    howto: 'ตรวจสอบการรั่วซึม',
    accept: 'ไม่มีการรั่วซึม',
  },
  {
    id: 6,
    name: 'waterFilter',
    question: 'ชุดกรองน้ำเข้สปั้ม ตรวจเช็ค Filter ไม่อุดตัน',
    howto: 'ตรวจสอบกรองน้ำและเช็คการอุดตัน',
    accept: 'กรองน้ำสะอาด ไม่มีการอุดตัน',
  },
  {
    id: 7,
    name: 'gauges',
    question: 'มาตรวัดต่างๆอ่านค่าได้ และค่าปกติ',
    howto: 'ตรวจสอบมาตรวัดและอ่านค่าบนเกจ',
    accept: 'มาตรวัดอ่านค่าได้และอยู่ในช่วงที่กำหนด',
  },
  {
    id: 8,
    name: 'leakCheck',
    question: 'ตรวจเช็คการรั่วซึมตามจุดต่างๆ',
    howto: 'ใช้ฟองสบู่ทดสอบการรั่วซึม',
    accept: 'ไม่มีการรั่วซึม',
  },
  {
    id: 9,
    name: 'fluidLevels',
    question: 'ระดับน้ำหล่อเย็น, น้ำมันต่างๆเติมเต็มทุกครั้ง',
    howto: 'ตรวจสอบระดับน้ำและน้ำมัน',
    accept: 'ระดับน้ำและน้ำมันอยู่ในระดับที่ถูกต้อง',
  },
  {
    id: 10,
    name: 'waterLevel',
    question: 'ตรวจเช็คระดับน้ำ ป้องกัน Pump Run Dry',
    howto: 'ตรวจสอบระดับน้ำ',
    accept: 'ระดับน้ำอยู่ในระดับที่ป้องกัน Pump Run Dry',
  },
  {
    id: 11,
    name: 'noiseVibration',
    question: 'ไม่มีเสียงดังและการสั่นที่ผิดปกติ',
    howto: 'ตรวจสอบเสียงและสั่นสะเทือน',
    accept: 'ไม่มีเสียงดังและการสั่นสะเทือนที่ผิดปกติ',
  },
  {
    id: 12,
    name: 'fuelAdd',
    question: 'การเติมน้ำมันเชื้อเพลิง ไม่มีน้ำปะปน (ลิตร)',
    howto: 'ตรวจสอบการเติมน้ำมัน',
    accept: 'น้ำมันไม่ปะปนกับน้ำ',
  },
  {
    id: 13,
    name: 'fireExtinguisher',
    question: 'มีถังดับเพลิงวางบริเวณที่ตั้งเครื่อง',
    howto: 'ตรวจสอบตำแหน่งถังดับเพลิง',
    accept: 'ถังดับเพลิงอยู่ในตำแหน่งที่เหมาะสม',
  },
  {
    id: 14,
    name: 'coverInstallation',
    question: 'ติดตั้งที่ครอบไปเสีย มีสภาพพร้อมใช้งาน ไม่อุดตัน',
    howto: 'ตรวจสอบการติดตั้งและความพร้อมใช้งาน',
    accept: 'ที่ครอบถูกติดตั้งและพร้อมใช้งาน ไม่มีสิ่งอุดตัน',
  },
  {
    id: 15,
    name: 'fuelLevel',
    question: 'บันทึกระดับน้ำมันเชื้อเพลิง (จำนวนลิตร)',
    howto: 'ตรวจสอบและบันทึกระดับน้ำมัน',
    accept: 'บันทึกระดับน้ำมันได้ถูกต้อง',
  },
  {
    id: 16,
    name: 'hourMeter',
    question: 'บันทึกเลขชั่วโมงใช้งาน (Hour Meter) ทุกวัน',
    howto: 'ตรวจสอบและบันทึกชั่วโมงการใช้งาน',
    accept: 'บันทึกชั่วโมงใช้งานได้ถูกต้อง',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  {
    field: 'machinePlacement',
    label: '1. พื้นที่วางเครื่อง / การติดตั้งประกอบ',
  },
  { field: 'machinePlacementR', label: '' },
  { field: 'machinePlacementP', label: '' },
  { field: 'machinePlacementA', label: 'Respond to defect' },
  { field: 'machinePlacementF', label: '' },
  {
    field: 'structure',
    label: '2. โครงสร้างอุปกรณ์ ฝาปิด ประตู หูยก ตัวล็อค',
  },
  { field: 'structureR', label: '' },
  { field: 'structureP', label: '' },
  { field: 'structureA', label: 'Respond to defect' },
  { field: 'structureF', label: '' },
  {
    field: 'wiring',
    label: '3. สภาพสายไฟ ขนาดสายไฟ การกวดขันแน่น',
  },
  { field: 'wiringR', label: '' },
  { field: 'wiringP', label: '' },
  { field: 'wiringA', label: 'Respond to defect' },
  { field: 'wiringF', label: '' },
  {
    field: 'switches',
    label: '4. ปุ่มสวิซ์ต่างๆมีภาษาไทยกำกับ ไม่ชำรุด',
  },
  { field: 'switchesR', label: '' },
  { field: 'switchesP', label: '' },
  { field: 'switchesA', label: 'Respond to defect' },
  { field: 'switchesF', label: '' },
  {
    field: 'hpwjPump',
    label: '5. ปั้ม HPWJ. ไม่รั่วซึม',
  },
  { field: 'hpwjPumpR', label: '' },
  { field: 'hpwjPumpP', label: '' },
  { field: 'hpwjPumpA', label: 'Respond to defect' },
  { field: 'hpwjPumpF', label: '' },
  {
    field: 'waterFilter',
    label: '6. ชุดกรองน้ำเข้สปั้ม ตรวจเช็ค Filter ไม่อุดตัน',
  },
  { field: 'waterFilterR', label: '' },
  { field: 'waterFilterP', label: '' },
  { field: 'waterFilterA', label: 'Respond to defect' },
  { field: 'waterFilterF', label: '' },
  {
    field: 'gauges',
    label: '7. มาตรวัดต่างๆอ่านค่าได้ และค่าปกติ',
  },
  { field: 'gaugesR', label: '' },
  { field: 'gaugesP', label: '' },
  { field: 'gaugesA', label: 'Respond to defect' },
  { field: 'gaugesF', label: '' },
  {
    field: 'leakCheck',
    label: '8. ตรวจเช็คการรั่วซึมตามจุดต่างๆ',
  },
  { field: 'leakCheckR', label: '' },
  { field: 'leakCheckP', label: '' },
  { field: 'leakCheckA', label: 'Respond to defect' },
  { field: 'leakCheckF', label: '' },
  {
    field: 'fluidLevels',
    label: '9. ระดับน้ำหล่อเย็น, น้ำมันต่างๆเติมเต็มทุกครั้ง',
  },
  { field: 'fluidLevelsR', label: '' },
  { field: 'fluidLevelsP', label: '' },
  { field: 'fluidLevelsA', label: 'Respond to defect' },
  { field: 'fluidLevelsF', label: '' },
  {
    field: 'waterLevel',
    label: '10. ตรวจเช็คระดับน้ำ ป้องกัน Pump Run Dry',
  },
  { field: 'waterLevelR', label: '' },
  { field: 'waterLevelP', label: '' },
  { field: 'waterLevelA', label: 'Respond to defect' },
  { field: 'waterLevelF', label: '' },
  {
    field: 'noiseVibration',
    label: '11. ไม่มีเสียงดังและการสั่นที่ผิดปกติ',
  },
  { field: 'noiseVibrationR', label: '' },
  { field: 'noiseVibrationP', label: '' },
  { field: 'noiseVibrationA', label: 'Respond to defect' },
  { field: 'noiseVibrationF', label: '' },
  {
    field: 'fuelAdd',
    label: '12. การเติมน้ำมันเชื้อเพลิง ไม่มีน้ำปะปน (ลิตร)',
  },
  { field: 'fuelAddR', label: '' },
  { field: 'fuelAddP', label: '' },
  { field: 'fuelAddA', label: 'Respond to defect' },
  { field: 'fuelAddF', label: '' },
  {
    field: 'fireExtinguisher',
    label: '13. มีถังดับเพลิงวางบริเวณที่ตั้งเครื่อง',
  },
  { field: 'fireExtinguisherR', label: '' },
  { field: 'fireExtinguisherP', label: '' },
  { field: 'fireExtinguisherA', label: 'Respond to defect' },
  { field: 'fireExtinguisherF', label: '' },
  {
    field: 'coverInstallation',
    label: '14. ติดตั้งที่ครอบไปเสีย มีสภาพพร้อมใช้งาน ไม่อุดตัน',
  },
  { field: 'coverInstallationR', label: '' },
  { field: 'coverInstallationP', label: '' },
  { field: 'coverInstallationA', label: 'Respond to defect' },
  { field: 'coverInstallationF', label: '' },
  {
    field: 'fuelLevel',
    label: '15. บันทึกระดับน้ำมันเชื้อเพลิง (จำนวนลิตร)',
  },
  { field: 'fuelLevelR', label: '' },
  { field: 'fuelLevelP', label: '' },
  { field: 'fuelLevelA', label: 'Respond to defect' },
  { field: 'fuelLevelF', label: '' },
  {
    field: 'hourMeter',
    label: '16. บันทึกเลขชั่วโมงใช้งาน (Hour Meter) ทุกวัน',
  },
  { field: 'hourMeterR', label: '' },
  { field: 'hourMeterP', label: '' },
  { field: 'hourMeterA', label: 'Respond to defect' },
  { field: 'hourMeterF', label: '' },
  { field: 'remark', label: 'หมายเหตุ Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
