export const questions = [
  {
    id: 1,
    name: 'loader',
    question: 'บุ้งกี๋ และสลักล็อค',
    howto: 'สายตา / สัมผัส',
    accept: 'สภาพไม่ชำรุด มั่นคงแข็งแรง',
  },
  {
    id: 2,
    name: 'wheelNut',
    question: 'น็อตล้อทั้ง 4 ล้อ',
    howto: 'สายตา / สัมผัส',
    accept: 'แข็งแรง ไม่หลวม จำนวนครบถ้วน',
  },
  {
    id: 3,
    name: 'tyre',
    question: 'ยางล้อรถ',
    howto: 'สายตา',
    accept: 'มีดอกยาง ไม่บวม ไม่มีรอยปริ แตกที่แก้มยาง',
  },
  {
    id: 4,
    name: 'cabin',
    question: 'โครงสร้างห้องโดยสาร',
    howto: 'สายตา / สัมผัส',
    accept: 'ไม่ชำรุด แข็งแรง',
  },
  {
    id: 5,
    name: 'door',
    question: 'ประตูซ้าย-ขวา',
    howto: 'สายตา / สัมผัส',
    accept: 'เปิด ปิด ล็อคได้ ไม่ชำรุด กระจกเลื่อนขึ้นลงได้',
  },
  {
    id: 6,
    name: 'mirror',
    question: 'กระจกมองทุกบาน หน้า-ซ้าย-ขวา-หลัง',
    howto: 'สายตา',
    accept: 'สะอาดใส ไม่แตก ไม่ชำรุด ปรับตำแหน่งได้',
  },
  {
    id: 7,
    name: 'seat',
    question: 'เบาะนั่ง และภายในห้องโดยสาร',
    howto: 'สายตา / สัมผัส',
    accept: 'สะอาด ไม่ฉีกขาด ไม่ชำรุด ติดตั้งมั่นคง',
  },
  {
    id: 8,
    name: 'belt',
    question: 'เข็มขัดนิรภัย',
    howto: 'สายตา / สัมผัส',
    accept: 'กระชับ ปรับได้ ล็อคและปลดล็อคได้',
  },
  {
    id: 9,
    name: 'hydraulic',
    question: 'ระบบไฮดรอลิค ข้อต่อต่างๆ',
    howto: 'สายตา',
    accept: 'ไม่มีรั่วซึม',
  },
  {
    id: 10,
    name: 'breakRubber',
    question: 'แป้นเบรก/คันเร่ง',
    howto: 'สายตา',
    accept: 'มียางกันลื่น',
  },
  {
    id: 11,
    name: 'extinguisher',
    question: 'ถังดับเพลิง',
    howto: 'สายตา / สัมผัส',
    accept: 'เกจชี้ในช่องสีเขียว มีเข็มขัดรัดสลัก พร้อมใช้',
  },
  {
    id: 12,
    name: 'lub',
    question: 'ระดับน้ำมันเบรค น้ำมันเครื่อง น้ำมันพาวเวอร์ และน้ำหม้อน้ำ',
    howto: 'สายตา / สัมผัส',
    accept: 'อยู่ระหว่างขีด Max-Min และไม่รั่วซึม',
  },
  {
    id: 13,
    name: 'battery',
    question: 'ขั้วแบตเตอรี่',
    howto: 'สายตา / สัมผัส',
    accept: 'สะอาด ไม่มีคราบสกปรก มีฝาครอบ',
  },
  {
    id: 14,
    name: 'ladder',
    question: 'บันไดและราวจับ',
    howto: 'สายตา / สัมผัส',
    accept: 'ก้าวขึ้น-ลงปลอดภัย มั่นคง',
  },
  {
    id: 15,
    name: 'sign',
    question: 'ป้ายเตือนระยะปลอดภัย ขณะรถตักทำงาน',
    howto: 'สายตา',
    accept: 'ไม่ซีดจาง มองเห็นชัดเจน',
  },
  {
    id: 16,
    name: 'dashboard',
    question: 'มาตรวัดต่างๆ บนแผงหน้าปัทม์',
    howto: 'สายตา',
    accept: 'แสดงผลปกติเมื่อเปิดสวิทช์กุญแจ',
  },
  {
    id: 17,
    name: 'power',
    question: 'ระบบส่งกำลัง (ชุดคันเร่ง เกียร์)',
    howto: 'ฟังเสียง / สายตา',
    accept: 'ไม่มีควันดำ ใช้ได้ปกติ',
  },
  {
    id: 18,
    name: 'breakSystem',
    question: 'เบรกมือ เบรกเท้า ไฟเบรก',
    howto: 'สัมผัส / สายตา',
    accept: 'หยุดนิ่ง รถไม่ไหล ไฟติดพร้อมกับเบรกเท้า',
  },
  {
    id: 19,
    name: 'steeringWheel',
    question: 'พวงมาลัย',
    howto: 'สัมผัส',
    accept: 'ไม่สั่นคลอน หมุนซ้าย-ขวา บังคับล้อได้ปกติ',
  },
  {
    id: 20,
    name: 'headLight',
    question: 'ไฟหน้า ไฟท้ายซ้าย-ขวา',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง',
  },
  {
    id: 21,
    name: 'turnLight',
    question: 'ไฟเลี้ยว ซ้าย-ขวา',
    howto: 'สายตา',
    accept: 'ไฟติดชัดเจน กระพริบเป็นจังหวะทุกดวง',
  },
  {
    id: 22,
    name: 'flashLight',
    question: 'ไฟวับวาบ',
    howto: 'สายตา',
    accept: 'ไฟติด หมุนกระพริบเป็นจังหวะ ไม่ติดค้าง',
  },
  {
    id: 23,
    name: 'reverseLight',
    question: 'ไฟถอยหลัง',
    howto: 'ฟังเสียง / สายตา',
    accept: 'ไฟติดชัดเจนทุกดวง อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 24,
    name: 'reverseSound',
    question: 'สัญญาณเสียงถอยหลัง',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน อัตโนมัติขณะใช้เกียร์ถอย',
  },
  {
    id: 25,
    name: 'horn',
    question: 'สัญญาณเสียงแตร',
    howto: 'ฟังเสียง',
    accept: 'เสียงดังชัดเจน',
  },
  {
    id: 26,
    name: 'whipper',
    question: 'ใบปัดน้ำฝน',
    howto: 'สายตา',
    accept: 'ไม่เสื่อมสภาพ มีน้ำฉีดกระจก',
  },
];

export const detailFields = [
  { field: 'id', label: 'ID' },
  { field: 'date', label: 'วันที่ - Date' },
  { field: 'email', label: 'ผู้รับผิดชอบ - Responsible person' },
  { field: 'inspector', label: 'ผู้ตรวจสอบ - Inspector' },
  { field: 'responder', label: 'Responder' },
  { field: 'loader', label: '1. บุ้งกี๋ และสลักล็อค' },
  { field: 'loaderR', label: '' },
  { field: 'loaderP', label: '' },
  { field: 'loaderA', label: 'Respond to defect' },
  { field: 'loaderF', label: '' },
  { field: 'wheelNut', label: '2. น็อตล้อทั้ง 4 ล้อ' },
  { field: 'wheelNutR', label: '' },
  { field: 'wheelNutP', label: '' },
  { field: 'wheelNutA', label: 'Respond to defect' },
  { field: 'wheelNutF', label: '' },
  { field: 'tyre', label: '3. ยางล้อรถ' },
  { field: 'tyreR', label: '' },
  { field: 'tyreP', label: '' },
  { field: 'tyreA', label: 'Respond to defect' },
  { field: 'tyreF', label: '' },
  { field: 'cabin', label: '4. โครงสร้างห้องโดยสาร' },
  { field: 'cabinR', label: '' },
  { field: 'cabinP', label: '' },
  { field: 'cabinA', label: 'Respond to defect' },
  { field: 'cabinF', label: '' },
  { field: 'door', label: '5. ประตูซ้าย-ขวา' },
  { field: 'doorR', label: '' },
  { field: 'doorP', label: '' },
  { field: 'doorA', label: 'Respond to defect' },
  { field: 'doorF', label: '' },
  { field: 'mirror', label: '6. กระจกมองทุกบาน หน้า-ซ้าย-ขวา-หลัง' },
  { field: 'mirrorR', label: '' },
  { field: 'mirrorP', label: '' },
  { field: 'mirrorA', label: 'Respond to defect' },
  { field: 'mirrorF', label: '' },
  { field: 'seat', label: '7. เบาะนั่ง และภายในห้องโดยสาร' },
  { field: 'seatR', label: '' },
  { field: 'seatP', label: '' },
  { field: 'seatA', label: 'Respond to defect' },
  { field: 'seatF', label: '' },
  { field: 'belt', label: '8. เข็มขัดนิรภัย' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'hydraulic', label: '9. ระบบไฮดรอลิค ข้อต่อต่างๆ' },
  { field: 'hydraulicR', label: '' },
  { field: 'hydraulicP', label: '' },
  { field: 'hydraulicA', label: 'Respond to defect' },
  { field: 'hydraulicF', label: '' },
  { field: 'breakRubber', label: '10. แป้นเบรก/คันเร่ง' },
  { field: 'breakRubberR', label: '' },
  { field: 'breakRubberP', label: '' },
  { field: 'breakRubberA', label: 'Respond to defect' },
  { field: 'breakRubberF', label: '' },
  { field: 'extinguisher', label: '11. ถังดับเพลิง' },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'Respond to defect' },
  { field: 'extinguisherF', label: '' },
  {
    field: 'lub',
    label: '12. ระดับน้ำมันเบรค น้ำมันเครื่อง น้ำมันพาวเวอร์ และน้ำหม้อน้ำ',
  },
  { field: 'lubR', label: '' },
  { field: 'lubP', label: '' },
  { field: 'lubA', label: 'Respond to defect' },
  { field: 'lubF', label: '' },
  { field: 'battery', label: '13. ขั้วแบตเตอรี่' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'ladder', label: '14. บันไดและราวจับ' },
  { field: 'ladderR', label: '' },
  { field: 'ladderP', label: '' },
  { field: 'ladderA', label: 'Respond to defect' },
  { field: 'ladderF', label: '' },
  { field: 'sign', label: '15. ป้ายเตือนระยะปลอดภัย ขณะรถตักทำงาน' },
  { field: 'signR', label: '' },
  { field: 'signP', label: '' },
  { field: 'signA', label: 'Respond to defect' },
  { field: 'signF', label: '' },
  { field: 'dashboard', label: '16. มาตรวัดต่างๆ บนแผงหน้าปัทม์' },
  { field: 'dashboardR', label: '' },
  { field: 'dashboardP', label: '' },
  { field: 'dashboardA', label: 'Respond to defect' },
  { field: 'dashboardF', label: '' },
  { field: 'power', label: '17. ระบบส่งกำลัง (ชุดคันเร่ง เกียร์)' },
  { field: 'powerR', label: '' },
  { field: 'powerP', label: '' },
  { field: 'powerA', label: 'Respond to defect' },
  { field: 'powerF', label: '' },
  { field: 'breakSystem', label: '18. เบรกมือ เบรกเท้า ไฟเบรก' },
  { field: 'breakSystemR', label: '' },
  { field: 'breakSystemP', label: '' },
  { field: 'breakSystemA', label: 'Respond to defect' },
  { field: 'breakSystemF', label: '' },
  { field: 'steeringWheel', label: '19. พวงมาลัย' },
  { field: 'steeringWheelR', label: '' },
  { field: 'steeringWheelP', label: '' },
  { field: 'steeringWheelA', label: 'Respond to defect' },
  { field: 'steeringWheelF', label: '' },
  { field: 'headLight', label: '20. ไฟหน้า ไฟท้ายซ้าย-ขวา' },
  { field: 'headLightR', label: '' },
  { field: 'headLightP', label: '' },
  { field: 'headLightA', label: 'Respond to defect' },
  { field: 'headLightF', label: '' },
  { field: 'turnLight', label: '21. ไฟเลี้ยว ซ้าย-ขวา' },
  { field: 'turnLightR', label: '' },
  { field: 'turnLightP', label: '' },
  { field: 'turnLightA', label: 'Respond to defect' },
  { field: 'turnLightF', label: '' },
  { field: 'flashLight', label: '22. ไฟวับวาบ' },
  { field: 'flashLightR', label: '' },
  { field: 'flashLightP', label: '' },
  { field: 'flashLightA', label: 'Respond to defect' },
  { field: 'flashLightF', label: '' },
  { field: 'reverseLight', label: '23. ไฟถอยหลัง' },
  { field: 'reverseLightR', label: '' },
  { field: 'reverseLightP', label: '' },
  { field: 'reverseLightA', label: 'Respond to defect' },
  { field: 'reverseLightF', label: '' },
  { field: 'reverseSound', label: '24. สัญญาณเสียงถอยหลัง' },
  { field: 'reverseSoundR', label: '' },
  { field: 'reverseSoundP', label: '' },
  { field: 'reverseSoundA', label: 'Respond to defect' },
  { field: 'reverseSoundF', label: '' },
  { field: 'horn', label: '25. สัญญาณเสียงแตร' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'whipper', label: '26. ใบปัดน้ำฝน' },
  { field: 'whipperR', label: '' },
  { field: 'whipperP', label: '' },
  { field: 'whipperA', label: 'Respond to defect' },
  { field: 'whipperF', label: '' },
  { field: 'remark', label: 'หมายเหตุ - Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
