export const questions = [
  {
    id: 1,
    name: 'lub',
    question: 'កំរិតប្រេងម៉ាស៊ីនមិនធម្មតា',
    howto: 'ពិនិត្យកំរិតប្រេងម៉ាស៊ីន និងសភាពស្អាត',
    accept: 'កំរិតប្រេងត្រឹមត្រូវ និងស្អាត',
  },
  {
    id: 2,
    name: 'radiator',
    question: 'ធុងទឹកម៉ាស៊ីនមិនធម្មតា',
    howto: 'ពិនិត្យកំរិតទឹក និងសភាពធុងទឹក',
    accept: 'កំរិតទឹកត្រឹមត្រូវ និងស្អាត',
  },
  {
    id: 3,
    name: 'fluid',
    question: 'ប្រេងអាំប្រាយ៉ា រឺហ្រ្វាំង និងបូមចង្កូតមិនធម្មតា',
    howto: 'ពិនិត្យកំរិតប្រេង និងសភាពស្អាត',
    accept: 'កំរិតប្រេងត្រឹមត្រូវ និងគ្មានការលេចធ្លាយ',
  },
  {
    id: 4,
    name: 'battery',
    question: 'អាគុយមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងកំរិតថ្ម',
    accept: 'គ្មានស្នាមច្រេះ និងថ្មស្ថានភាពល្អ',
  },
  {
    id: 5,
    name: 'headLight',
    question: 'ភ្លើងចង្កៀងមុខមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការដំណើរការ',
    accept: 'ភ្លើងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 6,
    name: 'signalLight',
    question: 'ភ្លើងស៊ីញ៉ូមិនធម្មតា',
    howto: 'បើកភ្លើងស៊ីញ៉ូ ពិនិត្យការដំណើរការ',
    accept: 'ភ្លើងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 7,
    name: 'brakeLight',
    question: 'ភ្លើងហ្រាំងមិនធម្មតា',
    howto: 'ពិនិត្យការដំណើរការពេលសាកសួរហ្រាំង',
    accept: 'ភ្លើងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 8,
    name: 'horn',
    question: 'ស៊ីផ្លេមិនធម្មតា',
    howto: 'សាកសួរស៊ីផ្លេ',
    accept: 'ស៊ីផ្លេដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 9,
    name: 'wiper',
    question: 'ផ្លឹតទឹកជូតកញ្ចក់មិនធម្មតា',
    howto: 'ពិនិត្យការបញ្ចេញទឹក និងសម្ភារៈជូត',
    accept: 'ផ្លឹតទឹក និងការជូតដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 10,
    name: 'windshield',
    question: 'កញ្ចក់មុខ កញ្ចក់មើលក្រោយ ទ្វា និងបង្អួចមិនធម្មតា',
    howto: 'ពិនិត្យសភាពកញ្ចក់ និងបង្អួច',
    accept: 'ស្ថានភាពល្អ គ្មានការបាក់បែក',
  },
  {
    id: 11,
    name: 'belt',
    question: 'ខ្សែក្រវ៉ាត់សុវត្តិភាពមិនធម្មតា',
    howto: 'សាកសួរខ្សែក្រវ៉ាត់ និងប្រើ',
    accept: 'ខ្សែក្រវ៉ាត់ដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 12,
    name: 'dashboard',
    question: 'ពិនិត្យនាឡិកាសំម្ពាធខ្យល់ និងពត៍មានលើតាបឡូមិនធម្មតា',
    howto: 'ពិនិត្យការបង្ហាញពត៍មាន',
    accept: 'ការបង្ហាញពត៍មានត្រឹមត្រូវ',
  },
  {
    id: 13,
    name: 'wheel',
    question: 'កង់រថយន្តមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងលំនឹងកង់',
    accept: 'កង់ស្ថានភាពល្អ គ្មានស្នាមច្រេះ',
  },
  {
    id: 14,
    name: 'brakeSys',
    question: 'ប្រពន្ទហ្រ្វាំងមិនធម្មតា',
    howto: 'ពិនិត្យប្រព័ន្ធហ្រ្វាំង និងសាកសួរនៅស្ថានភាពប្រើ',
    accept: 'ប្រព័ន្ធហ្រ្វាំងដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 15,
    name: 'hose',
    question: 'ស្ថានភាពពោង ទុយោ និងវ៉ានមិនធម្មតា',
    howto: 'ពិនិត្យស្ថានភាព និងការបំពង់',
    accept: 'គ្មានការច្រេះ និងលេចធ្លាយ',
  },
  {
    id: 16,
    name: 'equipment',
    question: 'សម្ភារៈសុវត្តិភាពមិនធម្មតា',
    howto: 'ពិនិត្យសម្ភារៈសុវត្តិភាព',
    accept: 'សម្ភារៈស្ថានភាពល្អ គ្មានការខូចខាត',
  },
  {
    id: 17,
    name: 'extinguisher',
    question: 'ឧបករណ៍ពន្លត់អគ្គីភ័យមិនធម្មតា',
    howto: 'ពិនិត្យការដំណើរការ និងស្ថានភាព',
    accept: 'ឧបករណ៍ដំណើរការបានត្រឹមត្រូវ',
  },
  {
    id: 18,
    name: 'ppe',
    question: 'សម្ភារៈការពារខ្លួន (PPE)មិនធម្មតា',
    howto: 'ពិនិត្យសម្ភារៈការពារខ្លួន',
    accept: 'ស្ថានភាពល្អ គ្មានការខូចខាត',
  },
];

export const detailFields = [
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'lub', label: '1. កំរិតប្រេងម៉ាស៊ីន - Engine Oil Level' },
  { field: 'lubR', label: '' },
  { field: 'lubP', label: '' },
  { field: 'lubA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'lubF', label: '' },
  { field: 'radiator', label: '2. ធុងទឹកម៉ាស៊ីន - Radiator' },
  { field: 'radiatorR', label: '' },
  { field: 'radiatorP', label: '' },
  { field: 'radiatorA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'radiatorF', label: '' },
  {
    field: 'fluid',
    label: '3. ប្រេងអាំប្រាយ៉ា/ហ្រ្វាំង/បូមចង្កូត - Fluid Levels',
  },
  { field: 'fluidR', label: '' },
  { field: 'fluidP', label: '' },
  { field: 'fluidA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'fluidF', label: '' },
  { field: 'battery', label: '4. អាគុយ - Battery' },
  { field: 'batteryR', label: '' },
  { field: 'batteryP', label: '' },
  { field: 'batteryA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'batteryF', label: '' },
  { field: 'headLight', label: '5. ភ្លើងចង្កៀងមុខ - Headlight' },
  { field: 'headLightR', label: '' },
  { field: 'headLightP', label: '' },
  { field: 'headLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'headLightF', label: '' },
  { field: 'signalLight', label: '6. ភ្លើងស៊ីញ៉ូ - Signal Light' },
  { field: 'signalLightR', label: '' },
  { field: 'signalLightP', label: '' },
  { field: 'signalLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'signalLightF', label: '' },
  { field: 'brakeLight', label: '7. ភ្លើងហ្រាំង - Brake Light' },
  { field: 'brakeLightR', label: '' },
  { field: 'brakeLightP', label: '' },
  { field: 'brakeLightA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'brakeLightF', label: '' },
  { field: 'horn', label: '8. ស៊ីផ្លេ - Horn' },
  { field: 'hornR', label: '' },
  { field: 'hornP', label: '' },
  { field: 'hornA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hornF', label: '' },
  { field: 'wiper', label: '9. ផ្លឹតទឹកជូតកញ្ចក់ - Wipers' },
  { field: 'wiperR', label: '' },
  { field: 'wiperP', label: '' },
  { field: 'wiperA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wiperF', label: '' },
  {
    field: 'windshield',
    label: '10. កញ្ចក់មុខ/កញ្ចក់មើលក្រោយ - Windshield/Mirrors',
  },
  { field: 'windshieldR', label: '' },
  { field: 'windshieldP', label: '' },
  { field: 'windshieldA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'windshieldF', label: '' },
  { field: 'belt', label: '11. ខ្សែក្រវ៉ាត់សុវត្តិភាព - Seat Belt' },
  { field: 'beltR', label: '' },
  { field: 'beltP', label: '' },
  { field: 'beltA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'beltF', label: '' },
  { field: 'dashboard', label: '12. តាបឡូ/ម៉ាស៊ីនសំម្ពាធខ្យល់ - Dashboard' },
  { field: 'dashboardR', label: '' },
  { field: 'dashboardP', label: '' },
  { field: 'dashboardA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'dashboardF', label: '' },
  { field: 'wheel', label: '13. កង់ - Tires' },
  { field: 'wheelR', label: '' },
  { field: 'wheelP', label: '' },
  { field: 'wheelA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'wheelF', label: '' },
  { field: 'brakeSys', label: '14. ប្រព័ន្ធហ្រ្វាំង - Brake System' },
  { field: 'brakeSysR', label: '' },
  { field: 'brakeSysP', label: '' },
  { field: 'brakeSysA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'brakeSysF', label: '' },
  { field: 'hose', label: '15. ទុយោ/វ៉ាន - Hoses/Valves' },
  { field: 'hoseR', label: '' },
  { field: 'hoseP', label: '' },
  { field: 'hoseA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'hoseF', label: '' },
  { field: 'equipment', label: '16. សម្ភារៈសុវត្តិភាព - Safety Equipment' },
  { field: 'equipmentR', label: '' },
  { field: 'equipmentP', label: '' },
  { field: 'equipmentA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'equipmentF', label: '' },
  {
    field: 'extinguisher',
    label: '17. ឧបករណ៍ពន្លត់អគ្គីភ័យ - Fire Extinguisher',
  },
  { field: 'extinguisherR', label: '' },
  { field: 'extinguisherP', label: '' },
  { field: 'extinguisherA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'extinguisherF', label: '' },
  { field: 'ppe', label: '18. សម្ភារៈការពារខ្លួន (PPE) - PPE' },
  { field: 'ppeR', label: '' },
  { field: 'ppeP', label: '' },
  { field: 'ppeA', label: 'ឆ្លើយតបដល់កំហុស - Respond to defect' },
  { field: 'ppeF', label: '' },

  { field: 'remark', label: 'មតិយោបល់ - Remark' },
  { field: 'lat', label: '' },
  { field: 'url', label: '' },
];
