export const questions = [
  {
    id: 1,
    name: 'gauge',
    question: 'រង្វាស់ទ្រនិច',
    howto: 'ភ្នែក',
    accept: 'ទ្រនិចត្រូវស្ថិតចំពណ៌បៃតង ករណី CO₂ មិនមានទ្រនិច',
  },
  {
    id: 2,
    name: 'tip',
    question: 'គន្លឹះ',
    howto: 'ភ្នែក',
    accept: 'គន្លឹះត្រូវដោតជាប់ដោយមានកិបសៀល',
  },
  {
    id: 3,
    name: 'handle',
    question: 'ដៃច្របាច់',
    howto: 'ភ្នែក',
    accept: 'មិនដំណើរការឬខូចខាត',
  },
  {
    id: 4,
    name: 'nozzle',
    question: 'បំពង់ទុយោនិងក្បាលបាញ់',
    howto: 'ភ្នែក',
    accept: 'លក្ខណៈគ្មានដាច់រហែក និង ទុយោរៀបតាមលំដាប់លំដោយ',
  },
  {
    id: 5,
    name: 'label',
    question: 'ស្លាកសញ្ញាប្រភេទបំពង់និងរបៀបប្រើប្រាស់បំពង់ពន្លត់អគ្គិភ័យ',
    howto: 'ភ្នែក',
    accept: 'លក្ខណៈគ្មានដាច់រហែក និង សភាពស្អាតល្អ',
  },
  {
    id: 6,
    name: 'layout',
    question: 'ទ្រង់ទ្រាយបំពង់ពន្លត់អគ្គិភ័យ',
    howto: 'ភ្នែក',
    accept: 'លក្ខណៈគ្មានកំពិតឬខូចទ្រង់ទ្រាយនិងសភាពស្អាតល្អ',
  },
  {
    id: 7,
    name: 'hose',
    question: 'គុណភាពវត្ថុធាតុនៅក្នុងបំពង់ពន្លត់អគ្គិភ័យ',
    howto: 'ដៃ​ ត្រចៀក',
    accept: 'លើកក្រឡុកបំពង់ពន្លត់អគ្គិភ័យប្រភេទ ABC',
  },
  {
    id: 8,
    name: 'sign',
    question: 'ស្លាកត្រួតពិនិត្យបំពង់ពន្លត់អគ្គិភ័យប្រចាំខែ',
    howto: 'ដៃ​ ភ្នែក',
    accept: 'គូសធីកទៅតាមខែនិមួយៗនិងស្លាកត្រូវស្ថិតនៅជាប់បំពង់ពន្លត់អគ្គិភ័យ',
  },
  {
    id: 9,
    name: 'location',
    question: 'ទីតាំងបំពង់ពន្លត់អគ្គិភ័យ',
    howto: 'ភ្នែក',
    accept: 'មិនមានវត្ថុដាក់បាំងពីមុខបំពង់ពន្លត់អគ្គិភ័យ',
  },
  {
    id: 10,
    name: 'badge',
    question: 'ផ្លាកសញ្ញាបំពង់ពន្លត់អគ្គិភ័យ',
    howto: 'ភ្នែក',
    accept: 'មិនជ្រុះពីទីតាំងតម្លើងនិងសភាពស្អាតល្អ',
  },
];

export const detailFields = [
  { field: 'id', label: 'អត្តលេខ - ID' },
  { field: 'date', label: 'កាលបរិច្ឆេទ - Date' },
  { field: 'inspector', label: 'អ្នកត្រួតពិនិត្យ - Inspector' },
  { field: 'responder', label: 'អ្នកឆ្លើយតប - Responder' },
  { field: 'gauge', label: '1. រង្វាស់ទ្រនិច *' },
  { field: 'gaugeR', label: '' },
  { field: 'gaugeP', label: '' },
  { field: 'gaugeA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'gaugeF', label: '' },
  { field: 'tip', label: '2. គន្លឹះ *' },
  { field: 'tipR', label: '' },
  { field: 'tipP', label: '' },
  { field: 'tipA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'tipF', label: '' },
  { field: 'handle', label: '3. ដៃច្របាច់ *' },
  { field: 'handleR', label: '' },
  { field: 'handleP', label: '' },
  { field: 'handleA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'handleF', label: '' },
  { field: 'nozzle', label: '4. បំពង់ទុយោនិងក្បាលបាញ់ *' },
  { field: 'nozzleR', label: '' },
  { field: 'nozzleP', label: '' },
  { field: 'nozzleA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'nozzleF', label: '' },
  {
    field: 'label',
    label: '5. ស្លាកសញ្ញាប្រភេទបំពង់និងរបៀបប្រើប្រាស់បំពង់ពន្លត់អគ្គិភ័យ *',
  },
  { field: 'labelR', label: '' },
  { field: 'labelP', label: '' },
  { field: 'labelA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'labelF', label: '' },
  { field: 'layout', label: '6. ទ្រង់ទ្រាយបំពង់ពន្លត់អគ្គិភ័យ *' },
  { field: 'layoutR', label: '' },
  { field: 'layoutP', label: '' },
  { field: 'layoutA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'layoutF', label: '' },
  { field: 'hose', label: '7. គុណភាពវត្ថុធាតុនៅក្នុងបំពង់ពន្លត់អគ្គិភ័យ *' },
  { field: 'hoseR', label: '' },
  { field: 'hoseP', label: '' },
  { field: 'hoseA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'hoseF', label: '' },
  { field: 'sign', label: '8. ស្លាកត្រួតពិនិត្យបំពង់ពន្លត់អគ្គិភ័យប្រចាំខែ *' },
  { field: 'signR', label: '' },
  { field: 'signP', label: '' },
  { field: 'signA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'signF', label: '' },
  { field: 'location', label: '9. ទីតាំងបំពង់ពន្លត់អគ្គិភ័យ *' },
  { field: 'locationR', label: '' },
  { field: 'locationP', label: '' },
  { field: 'locationA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'locationF', label: '' },
  { field: 'badge', label: '10. ផ្លាកសញ្ញាបំពង់ពន្លត់អគ្គិភ័យ *' },
  { field: 'badgeR', label: '' },
  { field: 'badgeP', label: '' },
  { field: 'badgeA', label: 'ឆ្លើយតបដល់កំហុស Respond to defect' },
  { field: 'badgeF', label: '' },
  { field: 'remark', label: 'ចំណាំ Remark' },
  { field: 'url', label: '' },
  { field: 'lat', label: '' },
];
